/* generated by xckernel; do not edit. */
#pragma once
#include <cstdint>
#include <new>
#include "xckernel/evaluator.hpp"

namespace xckernel {
namespace detail_xck_lda_ub_o2_mo {
static constexpr double c0_0[] = {
    1.0
};
static constexpr int32_t o0_0[] = {
    0,2
};
static constexpr uint16_t f0_0[] = {
    1,0
};
static constexpr double c0_1[] = {
    1.0
};
static constexpr int32_t o0_1[] = {
    0,2
};
static constexpr uint16_t f0_1[] = {
    2,0
};
static constexpr int64_t NFLD = 1;
} // namespace detail_xck_lda_ub_o2_mo

/* Scratch (elements of T) for nx trial vectors. */
inline int64_t xck_lda_ub_o2_mo_work(int64_t npts, int64_t nocc_a, int64_t nvir_a, int64_t nocc_b, int64_t nvir_b, int64_t nx) {
    const int64_t blk = npts < grid_block ? npts : grid_block;
    const int64_t nxc = nx < 8 ? nx : 8;
    int64_t no = 0;
    if (nocc_a > no) no = nocc_a;
    if (nocc_b > no) no = nocc_b;
    return blk * (3 + nxc * (nocc_b + 2) + 0 * nocc_b + 0 * nvir_b + 2 * no) + 0 * npts + 1;
}

template <typename T, typename Txc = T>
int xck_lda_ub_o2_mo_t(int64_t npts,
        int64_t nocc_a,
        int64_t nvir_a,
        int64_t nocc_b,
        int64_t nvir_b,
        int64_t nx,
        const T* phi_o_a,
        const T* phi_v_a,
        const T* phi_o_b,
        const T* phi_v_b,
        const double* X_a,
        const double* X_b,
        const T* const* fields,
        const Txc* const* xc,
        T* out,
        T* work = nullptr) {
    const int64_t blk = npts < grid_block ? npts : grid_block;
    const int64_t nxc = nx < 8 ? nx : 8;
    int64_t no = 0;
    if (nocc_a > no) no = nocc_a;
    if (nocc_b > no) no = nocc_b;
    T* c = work;
    bool own = false;
    if (!c) {
        c = new (std::nothrow) T[xck_lda_ub_o2_mo_work(npts, nocc_a, nvir_a, nocc_b, nvir_b, nx)];
        own = true;
    }
    if (!c) return 1;
    T* A = c + blk;
    T* W = A + (int64_t)2*blk;
    T* F = W + nxc*nocc_b*blk;
    T* Xo = F + nxc*(int64_t)2*blk;
    T* Xv = Xo + (int64_t)0*nocc_b*blk;
    T* Z = Xv + (int64_t)0*nvir_b*blk;
    T* Sb = Z + (int64_t)2*no*blk;
    const T* fi[1] = {fields[0]};
    for (int64_t g0 = 0; g0 < npts; g0 += blk) {
        const int64_t bk = npts - g0 < blk ? npts - g0 : blk;
        stage_a<T, Txc>(g0, bk, 1, detail_xck_lda_ub_o2_mo::c0_0, detail_xck_lda_ub_o2_mo::o0_0, detail_xck_lda_ub_o2_mo::f0_0, detail_xck_lda_ub_o2_mo::NFLD, fi, xc, A + (int64_t)0*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_lda_ub_o2_mo::c0_1, detail_xck_lda_ub_o2_mo::o0_1, detail_xck_lda_ub_o2_mo::f0_1, detail_xck_lda_ub_o2_mo::NFLD, fi, xc, A + (int64_t)1*blk);
        for (int64_t x0 = 0; x0 < nx; x0 += nxc) {
            const int64_t nxb = nx - x0 < nxc ? nx - x0 : nxc;
            for (int64_t x = 0; x < nxb; ++x) {
                gemm_nn(nocc_a, nvir_a, bk, X_a + (x0 + x)*nocc_a*nvir_a, nvir_a, static_cast<const T*>(phi_v_a) + (int64_t)0*nvir_a*npts + g0, npts, Z + (int64_t)0*no*blk, bk);
                gemm_nn(nocc_b, nvir_b, bk, X_b + (x0 + x)*nocc_b*nvir_b, nvir_b, static_cast<const T*>(phi_v_b) + (int64_t)0*nvir_b*npts + g0, npts, Z + (int64_t)1*no*blk, bk);
                for (int64_t g = 0; g < bk; ++g) (F + ((int64_t)0*nxc + x)*blk)[g] = T(0);
                colsum_prod(nocc_a, bk, 2.0, static_cast<const T*>(phi_o_a) + (int64_t)0*nocc_a*npts + g0, npts, static_cast<const T*>(Z) + (int64_t)0*no*blk, bk, F + ((int64_t)0*nxc + x)*blk);
                for (int64_t g = 0; g < bk; ++g) (F + ((int64_t)1*nxc + x)*blk)[g] = T(0);
                colsum_prod(nocc_b, bk, 2.0, static_cast<const T*>(phi_o_b) + (int64_t)0*nocc_b*npts + g0, npts, static_cast<const T*>(Z) + (int64_t)1*no*blk, bk, F + ((int64_t)1*nxc + x)*blk);
            }
            for (int64_t x = 0; x < nxb; ++x) {
                {
                    const T* A_[] = {A + (int64_t)0*blk, A + (int64_t)1*blk};
                    const T* P_[] = {F + ((int64_t)0*nxc + x)*blk, F + ((int64_t)1*nxc + x)*blk};
                    lincomb<T>(bk, 2, A_, P_, c);
                }
                accumulate<T>(bk, nocc_b, c, phi_o_b + (int64_t)0*nocc_b*npts + g0, npts, W + x*nocc_b*bk, 1);
            }
            gemm_rect(nxb*nocc_b, nvir_b, bk, static_cast<const T*>(W), bk, phi_v_b + (int64_t)0*nvir_b*npts + g0, npts, out + x0*nocc_b*nvir_b, nvir_b);
        }
    }
    if (own) delete[] c;
    return 0;
}


/* Operands of xck_lda_ub_o2_mo_t: `fields` in the order of
 * xck_lda_ub_o2_mo_field_names, `xc` in the order of xck_lda_ub_o2_mo_xc_names (the
 * C ABI's `scal` is the two concatenated, split at n_fields). The
 * structs name them; the overload taking them packs the arrays. */
inline constexpr int xck_lda_ub_o2_mo_n_fields = 1;
inline constexpr int xck_lda_ub_o2_mo_n_xc = 2;
inline constexpr const char* xck_lda_ub_o2_mo_field_names[] = {"w"};
inline constexpr const char* xck_lda_ub_o2_mo_xc_names[] = {"v2rho2_1", "v2rho2_2"};
template <typename T>
struct xck_lda_ub_o2_mo_fields {
    const T* w;
};
template <typename Txc>
struct xck_lda_ub_o2_mo_xc {
    const Txc* v2rho2_1;
    const Txc* v2rho2_2;
};

template <typename T, typename Txc = T>
int xck_lda_ub_o2_mo_t(int64_t npts,
        int64_t nocc_a,
        int64_t nvir_a,
        int64_t nocc_b,
        int64_t nvir_b,
        int64_t nx,
        const T* phi_o_a,
        const T* phi_v_a,
        const T* phi_o_b,
        const T* phi_v_b,
        const double* X_a,
        const double* X_b,
        const xck_lda_ub_o2_mo_fields<T>& fields_,
        const xck_lda_ub_o2_mo_xc<Txc>& xc_,
        T* out,
        T* work = nullptr) {
    const T* f_[] = {fields_.w};
    const Txc* x_[] = {xc_.v2rho2_1, xc_.v2rho2_2};
    return xck_lda_ub_o2_mo_t<T, Txc>(npts, nocc_a, nvir_a, nocc_b, nvir_b, nx, phi_o_a, phi_v_a, phi_o_b, phi_v_b, X_a, X_b, f_, x_, out, work);
}

} // namespace xckernel
