/* generated by xckernel; do not edit. */
#pragma once
#include <cstdint>
#include <new>
#include "xckernel/evaluator.hpp"

namespace xckernel {
namespace detail_xck_mgga_r_o2 {
static constexpr double c0[] = {
    1.0,1.0,1.0,2.0,2.0,2.0
};
static constexpr int32_t o0[] = {
    0,3,6,9,13,17,21
};
static constexpr uint16_t f0[] = {
    7,16,0,8,11,0,9,18,0,4,1,17,0,5,2,17,0,6,3,17,0
};
static constexpr double c1[] = {
    2.0,2.0,2.0,2.0,4.0,4.0,4.0
};
static constexpr int32_t o1[] = {
    0,3,7,11,15,20,25,30
};
static constexpr uint16_t f1[] = {
    4,14,0,1,7,19,0,1,8,17,0,1,9,20,0,4,1,1,12,0,5,1,2,12,0,6,1,3,12,0
};
static constexpr double c2[] = {
    2.0,2.0,2.0,2.0,4.0,4.0,4.0
};
static constexpr int32_t o2[] = {
    0,3,7,11,15,20,25,30
};
static constexpr uint16_t f2[] = {
    5,14,0,2,7,19,0,2,8,17,0,2,9,20,0,4,1,2,12,0,5,2,2,12,0,6,2,3,12,0
};
static constexpr double c3[] = {
    2.0,2.0,2.0,2.0,4.0,4.0,4.0
};
static constexpr int32_t o3[] = {
    0,3,7,11,15,20,25,30
};
static constexpr uint16_t f3[] = {
    6,14,0,3,7,19,0,3,8,17,0,3,9,20,0,4,1,3,12,0,5,2,3,12,0,6,3,3,12,0
};
static constexpr double c4[] = {
    1.0,1.0,1.0,2.0,2.0,2.0
};
static constexpr int32_t o4[] = {
    0,3,6,9,13,17,21
};
static constexpr uint16_t f4[] = {
    7,10,0,8,16,0,9,15,0,4,1,19,0,5,2,19,0,6,3,19,0
};
static constexpr double c5[] = {
    2.0,2.0,2.0,2.0,4.0,4.0,4.0
};
static constexpr int32_t o5[] = {
    0,3,7,11,15,20,25,30
};
static constexpr uint16_t f5[] = {
    4,14,0,1,7,19,0,1,8,17,0,1,9,20,0,4,1,1,12,0,5,1,2,12,0,6,1,3,12,0
};
static constexpr double c6[] = {
    0.5,0.5,0.5,1.0,1.0,1.0,2.0,2.0,2.0,4.0,4.0,4.0
};
static constexpr int32_t o6[] = {
    0,3,6,9,13,17,21,24,27,30,34,38,42
};
static constexpr uint16_t f6[] = {
    7,15,0,8,18,0,9,13,0,4,1,20,0,5,2,20,0,6,3,20,0,7,10,0,8,16,0,9,15,0,4,1,19,0,5,2,19,0,6,3,19,0
};
static constexpr double c7[] = {
    2.0,2.0,2.0,2.0,4.0,4.0,4.0
};
static constexpr int32_t o7[] = {
    0,3,7,11,15,20,25,30
};
static constexpr uint16_t f7[] = {
    5,14,0,2,7,19,0,2,8,17,0,2,9,20,0,4,1,2,12,0,5,2,2,12,0,6,2,3,12,0
};
static constexpr double c8[] = {
    0.5,0.5,0.5,1.0,1.0,1.0,2.0,2.0,2.0,4.0,4.0,4.0
};
static constexpr int32_t o8[] = {
    0,3,6,9,13,17,21,24,27,30,34,38,42
};
static constexpr uint16_t f8[] = {
    7,15,0,8,18,0,9,13,0,4,1,20,0,5,2,20,0,6,3,20,0,7,10,0,8,16,0,9,15,0,4,1,19,0,5,2,19,0,6,3,19,0
};
static constexpr double c9[] = {
    2.0,2.0,2.0,2.0,4.0,4.0,4.0
};
static constexpr int32_t o9[] = {
    0,3,7,11,15,20,25,30
};
static constexpr uint16_t f9[] = {
    6,14,0,3,7,19,0,3,8,17,0,3,9,20,0,4,1,3,12,0,5,2,3,12,0,6,3,3,12,0
};
static constexpr double c10[] = {
    0.5,0.5,0.5,1.0,1.0,1.0,2.0,2.0,2.0,4.0,4.0,4.0
};
static constexpr int32_t o10[] = {
    0,3,6,9,13,17,21,24,27,30,34,38,42
};
static constexpr uint16_t f10[] = {
    7,15,0,8,18,0,9,13,0,4,1,20,0,5,2,20,0,6,3,20,0,7,10,0,8,16,0,9,15,0,4,1,19,0,5,2,19,0,6,3,19,0
};
static constexpr double c11[] = {
    1.0,1.0,1.0,2.0,2.0,2.0
};
static constexpr int32_t o11[] = {
    0,3,6,9,13,17,21
};
static constexpr uint16_t f11[] = {
    7,10,0,8,16,0,9,15,0,4,1,19,0,5,2,19,0,6,3,19,0
};
static constexpr int64_t NFLD = 10;
} // namespace detail_xck_mgga_r_o2

/* fields: host-computed per-point operands (type T); xc: the
 * functional-derivative arrays (type Txc; Libxc computes in double
 * regardless of T). work: caller scratch of
 * xckernel::work_size(npts, nbf) elements or nullptr
 * (heap-allocated internally; pass a buffer in device code). */
template <typename T, typename Txc = T>
int xck_mgga_r_o2_t(int64_t npts, int64_t nbf,
             const T* chi, const T* dchi, const T* lapl_chi,
             const T* hess_chi,
             const T* const* fields, const Txc* const* xc,
             T* out, T* work = nullptr) {
    const int64_t blk = npts < grid_block ? npts : grid_block;
    T* c = work;
    bool own = false;
    if (!c) {
        c = new (std::nothrow) T[work_size(npts, nbf)];
        own = true;
    }
    if (!c) return 1;
    T* W = c + blk;
    const T* Wc = W;
    for (int64_t g0 = 0; g0 < npts; g0 += blk) {
        const int64_t bk = npts - g0 < blk ? npts - g0 : blk;
        stage_a<T, Txc>(g0, bk, 6, detail_xck_mgga_r_o2::c0, detail_xck_mgga_r_o2::o0, detail_xck_mgga_r_o2::f0, detail_xck_mgga_r_o2::NFLD, fields, xc, c);
        accumulate<T>(bk, nbf, c, chi + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 7, detail_xck_mgga_r_o2::c1, detail_xck_mgga_r_o2::o1, detail_xck_mgga_r_o2::f1, detail_xck_mgga_r_o2::NFLD, fields, xc, c);
        accumulate<T>(bk, nbf, c, dchi + (int64_t)0*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 7, detail_xck_mgga_r_o2::c2, detail_xck_mgga_r_o2::o2, detail_xck_mgga_r_o2::f2, detail_xck_mgga_r_o2::NFLD, fields, xc, c);
        accumulate<T>(bk, nbf, c, dchi + (int64_t)1*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 7, detail_xck_mgga_r_o2::c3, detail_xck_mgga_r_o2::o3, detail_xck_mgga_r_o2::f3, detail_xck_mgga_r_o2::NFLD, fields, xc, c);
        accumulate<T>(bk, nbf, c, dchi + (int64_t)2*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 6, detail_xck_mgga_r_o2::c4, detail_xck_mgga_r_o2::o4, detail_xck_mgga_r_o2::f4, detail_xck_mgga_r_o2::NFLD, fields, xc, c);
        accumulate<T>(bk, nbf, c, lapl_chi + g0, npts, W, 0);
        gemm_nt(nbf, bk, chi + g0, npts, Wc, bk, out);
        stage_a<T, Txc>(g0, bk, 7, detail_xck_mgga_r_o2::c5, detail_xck_mgga_r_o2::o5, detail_xck_mgga_r_o2::f5, detail_xck_mgga_r_o2::NFLD, fields, xc, c);
        accumulate<T>(bk, nbf, c, chi + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 12, detail_xck_mgga_r_o2::c6, detail_xck_mgga_r_o2::o6, detail_xck_mgga_r_o2::f6, detail_xck_mgga_r_o2::NFLD, fields, xc, c);
        accumulate<T>(bk, nbf, c, dchi + (int64_t)0*nbf*npts + g0, npts, W, 0);
        gemm_nt(nbf, bk, dchi + (int64_t)0*nbf*npts + g0, npts, Wc, bk, out);
        stage_a<T, Txc>(g0, bk, 7, detail_xck_mgga_r_o2::c7, detail_xck_mgga_r_o2::o7, detail_xck_mgga_r_o2::f7, detail_xck_mgga_r_o2::NFLD, fields, xc, c);
        accumulate<T>(bk, nbf, c, chi + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 12, detail_xck_mgga_r_o2::c8, detail_xck_mgga_r_o2::o8, detail_xck_mgga_r_o2::f8, detail_xck_mgga_r_o2::NFLD, fields, xc, c);
        accumulate<T>(bk, nbf, c, dchi + (int64_t)1*nbf*npts + g0, npts, W, 0);
        gemm_nt(nbf, bk, dchi + (int64_t)1*nbf*npts + g0, npts, Wc, bk, out);
        stage_a<T, Txc>(g0, bk, 7, detail_xck_mgga_r_o2::c9, detail_xck_mgga_r_o2::o9, detail_xck_mgga_r_o2::f9, detail_xck_mgga_r_o2::NFLD, fields, xc, c);
        accumulate<T>(bk, nbf, c, chi + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 12, detail_xck_mgga_r_o2::c10, detail_xck_mgga_r_o2::o10, detail_xck_mgga_r_o2::f10, detail_xck_mgga_r_o2::NFLD, fields, xc, c);
        accumulate<T>(bk, nbf, c, dchi + (int64_t)2*nbf*npts + g0, npts, W, 0);
        gemm_nt(nbf, bk, dchi + (int64_t)2*nbf*npts + g0, npts, Wc, bk, out);
        stage_a<T, Txc>(g0, bk, 6, detail_xck_mgga_r_o2::c11, detail_xck_mgga_r_o2::o11, detail_xck_mgga_r_o2::f11, detail_xck_mgga_r_o2::NFLD, fields, xc, c);
        accumulate<T>(bk, nbf, c, chi + g0, npts, W, 1);
        gemm_nt(nbf, bk, lapl_chi + g0, npts, Wc, bk, out);
    }
    if (own) delete[] c;
    return 0;
}

} // namespace xckernel
