/* generated by xckernel; do not edit. */
#pragma once
#include <cstdint>
#include <new>
#include "xckernel/evaluator.hpp"

namespace xckernel {
namespace detail_xck_cmgga_tau_r_g1 {
static constexpr double c0_0[] = {
    -1.0,-0.5,-0.5,-0.5
};
static constexpr int32_t o0_0[] = {
    0,2,8,14,20
};
static constexpr uint16_t f0_0[] = {
    8,0,7,7,4,4,10,0,7,7,5,5,10,0,7,7,6,6,10,0
};
static constexpr double c0_1[] = {
    -2.0,0.5
};
static constexpr int32_t o0_1[] = {
    0,3,7
};
static constexpr uint16_t f0_1[] = {
    1,9,0,7,4,10,0
};
static constexpr double c0_2[] = {
    -2.0,0.5
};
static constexpr int32_t o0_2[] = {
    0,3,7
};
static constexpr uint16_t f0_2[] = {
    2,9,0,7,5,10,0
};
static constexpr double c0_3[] = {
    -2.0,0.5
};
static constexpr int32_t o0_3[] = {
    0,3,7
};
static constexpr uint16_t f0_3[] = {
    3,9,0,7,6,10,0
};
static constexpr double c0_4[] = {
    -1.0,-0.5,-0.5,-0.5
};
static constexpr int32_t o0_4[] = {
    0,2,8,14,20
};
static constexpr uint16_t f0_4[] = {
    8,0,7,7,4,4,10,0,7,7,5,5,10,0,7,7,6,6,10,0
};
static constexpr double c0_5[] = {
    -2.0,-0.5
};
static constexpr int32_t o0_5[] = {
    0,3,7
};
static constexpr uint16_t f0_5[] = {
    1,9,0,7,4,10,0
};
static constexpr double c0_6[] = {
    -2.0,-0.5
};
static constexpr int32_t o0_6[] = {
    0,3,7
};
static constexpr uint16_t f0_6[] = {
    2,9,0,7,5,10,0
};
static constexpr double c0_7[] = {
    -2.0,-0.5
};
static constexpr int32_t o0_7[] = {
    0,3,7
};
static constexpr uint16_t f0_7[] = {
    3,9,0,7,6,10,0
};
static constexpr double c0_8[] = {
    -2.0,-0.5
};
static constexpr int32_t o0_8[] = {
    0,3,7
};
static constexpr uint16_t f0_8[] = {
    1,9,0,7,4,10,0
};
static constexpr double c0_9[] = {
    -0.5
};
static constexpr int32_t o0_9[] = {
    0,2
};
static constexpr uint16_t f0_9[] = {
    10,0
};
static constexpr double c0_10[] = {
    -2.0,0.5
};
static constexpr int32_t o0_10[] = {
    0,3,7
};
static constexpr uint16_t f0_10[] = {
    1,9,0,7,4,10,0
};
static constexpr double c0_11[] = {
    -0.5
};
static constexpr int32_t o0_11[] = {
    0,2
};
static constexpr uint16_t f0_11[] = {
    10,0
};
static constexpr double c0_12[] = {
    -2.0,-0.5
};
static constexpr int32_t o0_12[] = {
    0,3,7
};
static constexpr uint16_t f0_12[] = {
    2,9,0,7,5,10,0
};
static constexpr double c0_13[] = {
    -0.5
};
static constexpr int32_t o0_13[] = {
    0,2
};
static constexpr uint16_t f0_13[] = {
    10,0
};
static constexpr double c0_14[] = {
    -2.0,0.5
};
static constexpr int32_t o0_14[] = {
    0,3,7
};
static constexpr uint16_t f0_14[] = {
    2,9,0,7,5,10,0
};
static constexpr double c0_15[] = {
    -0.5
};
static constexpr int32_t o0_15[] = {
    0,2
};
static constexpr uint16_t f0_15[] = {
    10,0
};
static constexpr double c0_16[] = {
    -2.0,-0.5
};
static constexpr int32_t o0_16[] = {
    0,3,7
};
static constexpr uint16_t f0_16[] = {
    3,9,0,7,6,10,0
};
static constexpr double c0_17[] = {
    -0.5
};
static constexpr int32_t o0_17[] = {
    0,2
};
static constexpr uint16_t f0_17[] = {
    10,0
};
static constexpr double c0_18[] = {
    -2.0,0.5
};
static constexpr int32_t o0_18[] = {
    0,3,7
};
static constexpr uint16_t f0_18[] = {
    3,9,0,7,6,10,0
};
static constexpr double c0_19[] = {
    -0.5
};
static constexpr int32_t o0_19[] = {
    0,2
};
static constexpr uint16_t f0_19[] = {
    10,0
};
static constexpr double c1_0[] = {
    -1.0,-0.5,-0.5,-0.5
};
static constexpr int32_t o1_0[] = {
    0,2,8,14,20
};
static constexpr uint16_t f1_0[] = {
    8,0,7,7,4,4,10,0,7,7,5,5,10,0,7,7,6,6,10,0
};
static constexpr double c1_1[] = {
    -2.0,0.5
};
static constexpr int32_t o1_1[] = {
    0,3,7
};
static constexpr uint16_t f1_1[] = {
    1,9,0,7,4,10,0
};
static constexpr double c1_2[] = {
    -2.0,0.5
};
static constexpr int32_t o1_2[] = {
    0,3,7
};
static constexpr uint16_t f1_2[] = {
    2,9,0,7,5,10,0
};
static constexpr double c1_3[] = {
    -2.0,0.5
};
static constexpr int32_t o1_3[] = {
    0,3,7
};
static constexpr uint16_t f1_3[] = {
    3,9,0,7,6,10,0
};
static constexpr double c1_4[] = {
    -1.0,-0.5,-0.5,-0.5
};
static constexpr int32_t o1_4[] = {
    0,2,8,14,20
};
static constexpr uint16_t f1_4[] = {
    8,0,7,7,4,4,10,0,7,7,5,5,10,0,7,7,6,6,10,0
};
static constexpr double c1_5[] = {
    -2.0,-0.5
};
static constexpr int32_t o1_5[] = {
    0,3,7
};
static constexpr uint16_t f1_5[] = {
    1,9,0,7,4,10,0
};
static constexpr double c1_6[] = {
    -2.0,-0.5
};
static constexpr int32_t o1_6[] = {
    0,3,7
};
static constexpr uint16_t f1_6[] = {
    2,9,0,7,5,10,0
};
static constexpr double c1_7[] = {
    -2.0,-0.5
};
static constexpr int32_t o1_7[] = {
    0,3,7
};
static constexpr uint16_t f1_7[] = {
    3,9,0,7,6,10,0
};
static constexpr double c1_8[] = {
    -2.0,-0.5
};
static constexpr int32_t o1_8[] = {
    0,3,7
};
static constexpr uint16_t f1_8[] = {
    1,9,0,7,4,10,0
};
static constexpr double c1_9[] = {
    -0.5
};
static constexpr int32_t o1_9[] = {
    0,2
};
static constexpr uint16_t f1_9[] = {
    10,0
};
static constexpr double c1_10[] = {
    -2.0,0.5
};
static constexpr int32_t o1_10[] = {
    0,3,7
};
static constexpr uint16_t f1_10[] = {
    1,9,0,7,4,10,0
};
static constexpr double c1_11[] = {
    -0.5
};
static constexpr int32_t o1_11[] = {
    0,2
};
static constexpr uint16_t f1_11[] = {
    10,0
};
static constexpr double c1_12[] = {
    -2.0,-0.5
};
static constexpr int32_t o1_12[] = {
    0,3,7
};
static constexpr uint16_t f1_12[] = {
    2,9,0,7,5,10,0
};
static constexpr double c1_13[] = {
    -0.5
};
static constexpr int32_t o1_13[] = {
    0,2
};
static constexpr uint16_t f1_13[] = {
    10,0
};
static constexpr double c1_14[] = {
    -2.0,0.5
};
static constexpr int32_t o1_14[] = {
    0,3,7
};
static constexpr uint16_t f1_14[] = {
    2,9,0,7,5,10,0
};
static constexpr double c1_15[] = {
    -0.5
};
static constexpr int32_t o1_15[] = {
    0,2
};
static constexpr uint16_t f1_15[] = {
    10,0
};
static constexpr double c1_16[] = {
    -2.0,-0.5
};
static constexpr int32_t o1_16[] = {
    0,3,7
};
static constexpr uint16_t f1_16[] = {
    3,9,0,7,6,10,0
};
static constexpr double c1_17[] = {
    -0.5
};
static constexpr int32_t o1_17[] = {
    0,2
};
static constexpr uint16_t f1_17[] = {
    10,0
};
static constexpr double c1_18[] = {
    -2.0,0.5
};
static constexpr int32_t o1_18[] = {
    0,3,7
};
static constexpr uint16_t f1_18[] = {
    3,9,0,7,6,10,0
};
static constexpr double c1_19[] = {
    -0.5
};
static constexpr int32_t o1_19[] = {
    0,2
};
static constexpr uint16_t f1_19[] = {
    10,0
};
static constexpr double c2_0[] = {
    -1.0,-0.5,-0.5,-0.5
};
static constexpr int32_t o2_0[] = {
    0,2,8,14,20
};
static constexpr uint16_t f2_0[] = {
    8,0,7,7,4,4,10,0,7,7,5,5,10,0,7,7,6,6,10,0
};
static constexpr double c2_1[] = {
    -2.0,0.5
};
static constexpr int32_t o2_1[] = {
    0,3,7
};
static constexpr uint16_t f2_1[] = {
    1,9,0,7,4,10,0
};
static constexpr double c2_2[] = {
    -2.0,0.5
};
static constexpr int32_t o2_2[] = {
    0,3,7
};
static constexpr uint16_t f2_2[] = {
    2,9,0,7,5,10,0
};
static constexpr double c2_3[] = {
    -2.0,0.5
};
static constexpr int32_t o2_3[] = {
    0,3,7
};
static constexpr uint16_t f2_3[] = {
    3,9,0,7,6,10,0
};
static constexpr double c2_4[] = {
    -1.0,-0.5,-0.5,-0.5
};
static constexpr int32_t o2_4[] = {
    0,2,8,14,20
};
static constexpr uint16_t f2_4[] = {
    8,0,7,7,4,4,10,0,7,7,5,5,10,0,7,7,6,6,10,0
};
static constexpr double c2_5[] = {
    -2.0,-0.5
};
static constexpr int32_t o2_5[] = {
    0,3,7
};
static constexpr uint16_t f2_5[] = {
    1,9,0,7,4,10,0
};
static constexpr double c2_6[] = {
    -2.0,-0.5
};
static constexpr int32_t o2_6[] = {
    0,3,7
};
static constexpr uint16_t f2_6[] = {
    2,9,0,7,5,10,0
};
static constexpr double c2_7[] = {
    -2.0,-0.5
};
static constexpr int32_t o2_7[] = {
    0,3,7
};
static constexpr uint16_t f2_7[] = {
    3,9,0,7,6,10,0
};
static constexpr double c2_8[] = {
    -2.0,-0.5
};
static constexpr int32_t o2_8[] = {
    0,3,7
};
static constexpr uint16_t f2_8[] = {
    1,9,0,7,4,10,0
};
static constexpr double c2_9[] = {
    -0.5
};
static constexpr int32_t o2_9[] = {
    0,2
};
static constexpr uint16_t f2_9[] = {
    10,0
};
static constexpr double c2_10[] = {
    -2.0,0.5
};
static constexpr int32_t o2_10[] = {
    0,3,7
};
static constexpr uint16_t f2_10[] = {
    1,9,0,7,4,10,0
};
static constexpr double c2_11[] = {
    -0.5
};
static constexpr int32_t o2_11[] = {
    0,2
};
static constexpr uint16_t f2_11[] = {
    10,0
};
static constexpr double c2_12[] = {
    -2.0,-0.5
};
static constexpr int32_t o2_12[] = {
    0,3,7
};
static constexpr uint16_t f2_12[] = {
    2,9,0,7,5,10,0
};
static constexpr double c2_13[] = {
    -0.5
};
static constexpr int32_t o2_13[] = {
    0,2
};
static constexpr uint16_t f2_13[] = {
    10,0
};
static constexpr double c2_14[] = {
    -2.0,0.5
};
static constexpr int32_t o2_14[] = {
    0,3,7
};
static constexpr uint16_t f2_14[] = {
    2,9,0,7,5,10,0
};
static constexpr double c2_15[] = {
    -0.5
};
static constexpr int32_t o2_15[] = {
    0,2
};
static constexpr uint16_t f2_15[] = {
    10,0
};
static constexpr double c2_16[] = {
    -2.0,-0.5
};
static constexpr int32_t o2_16[] = {
    0,3,7
};
static constexpr uint16_t f2_16[] = {
    3,9,0,7,6,10,0
};
static constexpr double c2_17[] = {
    -0.5
};
static constexpr int32_t o2_17[] = {
    0,2
};
static constexpr uint16_t f2_17[] = {
    10,0
};
static constexpr double c2_18[] = {
    -2.0,0.5
};
static constexpr int32_t o2_18[] = {
    0,3,7
};
static constexpr uint16_t f2_18[] = {
    3,9,0,7,6,10,0
};
static constexpr double c2_19[] = {
    -0.5
};
static constexpr int32_t o2_19[] = {
    0,2
};
static constexpr uint16_t f2_19[] = {
    10,0
};
static constexpr int64_t NFLD = 8;
} // namespace detail_xck_cmgga_tau_r_g1

/* Scratch (elements of T) the kernel needs: pass at least this
 * much as `work`, or nullptr to allocate it internally. */
inline int64_t xck_cmgga_tau_r_g1_work(int64_t npts, int64_t nbf) {
    const int64_t blk = npts < grid_block ? npts : grid_block;
    return blk * (1 + nbf * 1) + 0 * npts + 1;
}

/* fields: the per-point tower operands (type T), in the order
 * of xck_cmgga_tau_r_g1_scal_names; xc: the functional-derivative arrays
 * (type Txc; Libxc computes in double whatever T is). */
template <typename T, typename Txc = T>
int xck_cmgga_tau_r_g1_t(int64_t npts,
        int64_t nbf,
        const T* chi,
        const T* Dchi,
        const T* DTchi,
        const T* const* fields,
        const Txc* const* xc,
        T* out,
        T* work = nullptr) {
    const int64_t blk = npts < grid_block ? npts : grid_block;
    T* c = work;
    bool own = false;
    if (!c) {
        c = new (std::nothrow) T[xck_cmgga_tau_r_g1_work(npts, nbf)];
        own = true;
    }
    if (!c) return 1;
    T* W = c + blk;
    const T* Wc = W;
    const T* fi[8] = {fields[0], fields[1], fields[2], fields[3], fields[4], fields[5], fields[6], fields[7]};
    for (int64_t g0 = 0; g0 < npts; g0 += blk) {
        const int64_t bk = npts - g0 < blk ? npts - g0 : blk;
        stage_a<T, Txc>(g0, bk, 4, detail_xck_cmgga_tau_r_g1::c0_0, detail_xck_cmgga_tau_r_g1::o0_0, detail_xck_cmgga_tau_r_g1::f0_0, detail_xck_cmgga_tau_r_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_cmgga_tau_r_g1::c0_1, detail_xck_cmgga_tau_r_g1::o0_1, detail_xck_cmgga_tau_r_g1::f0_1, detail_xck_cmgga_tau_r_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)1*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_cmgga_tau_r_g1::c0_2, detail_xck_cmgga_tau_r_g1::o0_2, detail_xck_cmgga_tau_r_g1::f0_2, detail_xck_cmgga_tau_r_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)2*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_cmgga_tau_r_g1::c0_3, detail_xck_cmgga_tau_r_g1::o0_3, detail_xck_cmgga_tau_r_g1::f0_3, detail_xck_cmgga_tau_r_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)3*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 4, detail_xck_cmgga_tau_r_g1::c0_4, detail_xck_cmgga_tau_r_g1::o0_4, detail_xck_cmgga_tau_r_g1::f0_4, detail_xck_cmgga_tau_r_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, DTchi + (int64_t)0*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_cmgga_tau_r_g1::c0_5, detail_xck_cmgga_tau_r_g1::o0_5, detail_xck_cmgga_tau_r_g1::f0_5, detail_xck_cmgga_tau_r_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, DTchi + (int64_t)1*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_cmgga_tau_r_g1::c0_6, detail_xck_cmgga_tau_r_g1::o0_6, detail_xck_cmgga_tau_r_g1::f0_6, detail_xck_cmgga_tau_r_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, DTchi + (int64_t)2*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_cmgga_tau_r_g1::c0_7, detail_xck_cmgga_tau_r_g1::o0_7, detail_xck_cmgga_tau_r_g1::f0_7, detail_xck_cmgga_tau_r_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, DTchi + (int64_t)3*nbf*npts + g0, npts, W, 0);
        rowdot(nbf, bk, chi + (int64_t)1*nbf*npts + g0, npts, Wc, bk, out + (int64_t)0*nbf);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_cmgga_tau_r_g1::c0_8, detail_xck_cmgga_tau_r_g1::o0_8, detail_xck_cmgga_tau_r_g1::f0_8, detail_xck_cmgga_tau_r_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_cmgga_tau_r_g1::c0_9, detail_xck_cmgga_tau_r_g1::o0_9, detail_xck_cmgga_tau_r_g1::f0_9, detail_xck_cmgga_tau_r_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)1*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_cmgga_tau_r_g1::c0_10, detail_xck_cmgga_tau_r_g1::o0_10, detail_xck_cmgga_tau_r_g1::f0_10, detail_xck_cmgga_tau_r_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, DTchi + (int64_t)0*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_cmgga_tau_r_g1::c0_11, detail_xck_cmgga_tau_r_g1::o0_11, detail_xck_cmgga_tau_r_g1::f0_11, detail_xck_cmgga_tau_r_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, DTchi + (int64_t)1*nbf*npts + g0, npts, W, 0);
        rowdot(nbf, bk, chi + (int64_t)4*nbf*npts + g0, npts, Wc, bk, out + (int64_t)0*nbf);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_cmgga_tau_r_g1::c0_12, detail_xck_cmgga_tau_r_g1::o0_12, detail_xck_cmgga_tau_r_g1::f0_12, detail_xck_cmgga_tau_r_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_cmgga_tau_r_g1::c0_13, detail_xck_cmgga_tau_r_g1::o0_13, detail_xck_cmgga_tau_r_g1::f0_13, detail_xck_cmgga_tau_r_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)2*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_cmgga_tau_r_g1::c0_14, detail_xck_cmgga_tau_r_g1::o0_14, detail_xck_cmgga_tau_r_g1::f0_14, detail_xck_cmgga_tau_r_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, DTchi + (int64_t)0*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_cmgga_tau_r_g1::c0_15, detail_xck_cmgga_tau_r_g1::o0_15, detail_xck_cmgga_tau_r_g1::f0_15, detail_xck_cmgga_tau_r_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, DTchi + (int64_t)2*nbf*npts + g0, npts, W, 0);
        rowdot(nbf, bk, chi + (int64_t)5*nbf*npts + g0, npts, Wc, bk, out + (int64_t)0*nbf);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_cmgga_tau_r_g1::c0_16, detail_xck_cmgga_tau_r_g1::o0_16, detail_xck_cmgga_tau_r_g1::f0_16, detail_xck_cmgga_tau_r_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_cmgga_tau_r_g1::c0_17, detail_xck_cmgga_tau_r_g1::o0_17, detail_xck_cmgga_tau_r_g1::f0_17, detail_xck_cmgga_tau_r_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)3*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_cmgga_tau_r_g1::c0_18, detail_xck_cmgga_tau_r_g1::o0_18, detail_xck_cmgga_tau_r_g1::f0_18, detail_xck_cmgga_tau_r_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, DTchi + (int64_t)0*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_cmgga_tau_r_g1::c0_19, detail_xck_cmgga_tau_r_g1::o0_19, detail_xck_cmgga_tau_r_g1::f0_19, detail_xck_cmgga_tau_r_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, DTchi + (int64_t)3*nbf*npts + g0, npts, W, 0);
        rowdot(nbf, bk, chi + (int64_t)6*nbf*npts + g0, npts, Wc, bk, out + (int64_t)0*nbf);
        stage_a<T, Txc>(g0, bk, 4, detail_xck_cmgga_tau_r_g1::c1_0, detail_xck_cmgga_tau_r_g1::o1_0, detail_xck_cmgga_tau_r_g1::f1_0, detail_xck_cmgga_tau_r_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_cmgga_tau_r_g1::c1_1, detail_xck_cmgga_tau_r_g1::o1_1, detail_xck_cmgga_tau_r_g1::f1_1, detail_xck_cmgga_tau_r_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)1*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_cmgga_tau_r_g1::c1_2, detail_xck_cmgga_tau_r_g1::o1_2, detail_xck_cmgga_tau_r_g1::f1_2, detail_xck_cmgga_tau_r_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)2*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_cmgga_tau_r_g1::c1_3, detail_xck_cmgga_tau_r_g1::o1_3, detail_xck_cmgga_tau_r_g1::f1_3, detail_xck_cmgga_tau_r_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)3*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 4, detail_xck_cmgga_tau_r_g1::c1_4, detail_xck_cmgga_tau_r_g1::o1_4, detail_xck_cmgga_tau_r_g1::f1_4, detail_xck_cmgga_tau_r_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, DTchi + (int64_t)0*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_cmgga_tau_r_g1::c1_5, detail_xck_cmgga_tau_r_g1::o1_5, detail_xck_cmgga_tau_r_g1::f1_5, detail_xck_cmgga_tau_r_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, DTchi + (int64_t)1*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_cmgga_tau_r_g1::c1_6, detail_xck_cmgga_tau_r_g1::o1_6, detail_xck_cmgga_tau_r_g1::f1_6, detail_xck_cmgga_tau_r_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, DTchi + (int64_t)2*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_cmgga_tau_r_g1::c1_7, detail_xck_cmgga_tau_r_g1::o1_7, detail_xck_cmgga_tau_r_g1::f1_7, detail_xck_cmgga_tau_r_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, DTchi + (int64_t)3*nbf*npts + g0, npts, W, 0);
        rowdot(nbf, bk, chi + (int64_t)2*nbf*npts + g0, npts, Wc, bk, out + (int64_t)1*nbf);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_cmgga_tau_r_g1::c1_8, detail_xck_cmgga_tau_r_g1::o1_8, detail_xck_cmgga_tau_r_g1::f1_8, detail_xck_cmgga_tau_r_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_cmgga_tau_r_g1::c1_9, detail_xck_cmgga_tau_r_g1::o1_9, detail_xck_cmgga_tau_r_g1::f1_9, detail_xck_cmgga_tau_r_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)1*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_cmgga_tau_r_g1::c1_10, detail_xck_cmgga_tau_r_g1::o1_10, detail_xck_cmgga_tau_r_g1::f1_10, detail_xck_cmgga_tau_r_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, DTchi + (int64_t)0*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_cmgga_tau_r_g1::c1_11, detail_xck_cmgga_tau_r_g1::o1_11, detail_xck_cmgga_tau_r_g1::f1_11, detail_xck_cmgga_tau_r_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, DTchi + (int64_t)1*nbf*npts + g0, npts, W, 0);
        rowdot(nbf, bk, chi + (int64_t)5*nbf*npts + g0, npts, Wc, bk, out + (int64_t)1*nbf);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_cmgga_tau_r_g1::c1_12, detail_xck_cmgga_tau_r_g1::o1_12, detail_xck_cmgga_tau_r_g1::f1_12, detail_xck_cmgga_tau_r_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_cmgga_tau_r_g1::c1_13, detail_xck_cmgga_tau_r_g1::o1_13, detail_xck_cmgga_tau_r_g1::f1_13, detail_xck_cmgga_tau_r_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)2*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_cmgga_tau_r_g1::c1_14, detail_xck_cmgga_tau_r_g1::o1_14, detail_xck_cmgga_tau_r_g1::f1_14, detail_xck_cmgga_tau_r_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, DTchi + (int64_t)0*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_cmgga_tau_r_g1::c1_15, detail_xck_cmgga_tau_r_g1::o1_15, detail_xck_cmgga_tau_r_g1::f1_15, detail_xck_cmgga_tau_r_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, DTchi + (int64_t)2*nbf*npts + g0, npts, W, 0);
        rowdot(nbf, bk, chi + (int64_t)7*nbf*npts + g0, npts, Wc, bk, out + (int64_t)1*nbf);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_cmgga_tau_r_g1::c1_16, detail_xck_cmgga_tau_r_g1::o1_16, detail_xck_cmgga_tau_r_g1::f1_16, detail_xck_cmgga_tau_r_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_cmgga_tau_r_g1::c1_17, detail_xck_cmgga_tau_r_g1::o1_17, detail_xck_cmgga_tau_r_g1::f1_17, detail_xck_cmgga_tau_r_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)3*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_cmgga_tau_r_g1::c1_18, detail_xck_cmgga_tau_r_g1::o1_18, detail_xck_cmgga_tau_r_g1::f1_18, detail_xck_cmgga_tau_r_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, DTchi + (int64_t)0*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_cmgga_tau_r_g1::c1_19, detail_xck_cmgga_tau_r_g1::o1_19, detail_xck_cmgga_tau_r_g1::f1_19, detail_xck_cmgga_tau_r_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, DTchi + (int64_t)3*nbf*npts + g0, npts, W, 0);
        rowdot(nbf, bk, chi + (int64_t)8*nbf*npts + g0, npts, Wc, bk, out + (int64_t)1*nbf);
        stage_a<T, Txc>(g0, bk, 4, detail_xck_cmgga_tau_r_g1::c2_0, detail_xck_cmgga_tau_r_g1::o2_0, detail_xck_cmgga_tau_r_g1::f2_0, detail_xck_cmgga_tau_r_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_cmgga_tau_r_g1::c2_1, detail_xck_cmgga_tau_r_g1::o2_1, detail_xck_cmgga_tau_r_g1::f2_1, detail_xck_cmgga_tau_r_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)1*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_cmgga_tau_r_g1::c2_2, detail_xck_cmgga_tau_r_g1::o2_2, detail_xck_cmgga_tau_r_g1::f2_2, detail_xck_cmgga_tau_r_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)2*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_cmgga_tau_r_g1::c2_3, detail_xck_cmgga_tau_r_g1::o2_3, detail_xck_cmgga_tau_r_g1::f2_3, detail_xck_cmgga_tau_r_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)3*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 4, detail_xck_cmgga_tau_r_g1::c2_4, detail_xck_cmgga_tau_r_g1::o2_4, detail_xck_cmgga_tau_r_g1::f2_4, detail_xck_cmgga_tau_r_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, DTchi + (int64_t)0*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_cmgga_tau_r_g1::c2_5, detail_xck_cmgga_tau_r_g1::o2_5, detail_xck_cmgga_tau_r_g1::f2_5, detail_xck_cmgga_tau_r_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, DTchi + (int64_t)1*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_cmgga_tau_r_g1::c2_6, detail_xck_cmgga_tau_r_g1::o2_6, detail_xck_cmgga_tau_r_g1::f2_6, detail_xck_cmgga_tau_r_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, DTchi + (int64_t)2*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_cmgga_tau_r_g1::c2_7, detail_xck_cmgga_tau_r_g1::o2_7, detail_xck_cmgga_tau_r_g1::f2_7, detail_xck_cmgga_tau_r_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, DTchi + (int64_t)3*nbf*npts + g0, npts, W, 0);
        rowdot(nbf, bk, chi + (int64_t)3*nbf*npts + g0, npts, Wc, bk, out + (int64_t)2*nbf);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_cmgga_tau_r_g1::c2_8, detail_xck_cmgga_tau_r_g1::o2_8, detail_xck_cmgga_tau_r_g1::f2_8, detail_xck_cmgga_tau_r_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_cmgga_tau_r_g1::c2_9, detail_xck_cmgga_tau_r_g1::o2_9, detail_xck_cmgga_tau_r_g1::f2_9, detail_xck_cmgga_tau_r_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)1*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_cmgga_tau_r_g1::c2_10, detail_xck_cmgga_tau_r_g1::o2_10, detail_xck_cmgga_tau_r_g1::f2_10, detail_xck_cmgga_tau_r_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, DTchi + (int64_t)0*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_cmgga_tau_r_g1::c2_11, detail_xck_cmgga_tau_r_g1::o2_11, detail_xck_cmgga_tau_r_g1::f2_11, detail_xck_cmgga_tau_r_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, DTchi + (int64_t)1*nbf*npts + g0, npts, W, 0);
        rowdot(nbf, bk, chi + (int64_t)6*nbf*npts + g0, npts, Wc, bk, out + (int64_t)2*nbf);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_cmgga_tau_r_g1::c2_12, detail_xck_cmgga_tau_r_g1::o2_12, detail_xck_cmgga_tau_r_g1::f2_12, detail_xck_cmgga_tau_r_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_cmgga_tau_r_g1::c2_13, detail_xck_cmgga_tau_r_g1::o2_13, detail_xck_cmgga_tau_r_g1::f2_13, detail_xck_cmgga_tau_r_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)2*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_cmgga_tau_r_g1::c2_14, detail_xck_cmgga_tau_r_g1::o2_14, detail_xck_cmgga_tau_r_g1::f2_14, detail_xck_cmgga_tau_r_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, DTchi + (int64_t)0*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_cmgga_tau_r_g1::c2_15, detail_xck_cmgga_tau_r_g1::o2_15, detail_xck_cmgga_tau_r_g1::f2_15, detail_xck_cmgga_tau_r_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, DTchi + (int64_t)2*nbf*npts + g0, npts, W, 0);
        rowdot(nbf, bk, chi + (int64_t)8*nbf*npts + g0, npts, Wc, bk, out + (int64_t)2*nbf);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_cmgga_tau_r_g1::c2_16, detail_xck_cmgga_tau_r_g1::o2_16, detail_xck_cmgga_tau_r_g1::f2_16, detail_xck_cmgga_tau_r_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_cmgga_tau_r_g1::c2_17, detail_xck_cmgga_tau_r_g1::o2_17, detail_xck_cmgga_tau_r_g1::f2_17, detail_xck_cmgga_tau_r_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)3*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_cmgga_tau_r_g1::c2_18, detail_xck_cmgga_tau_r_g1::o2_18, detail_xck_cmgga_tau_r_g1::f2_18, detail_xck_cmgga_tau_r_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, DTchi + (int64_t)0*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_cmgga_tau_r_g1::c2_19, detail_xck_cmgga_tau_r_g1::o2_19, detail_xck_cmgga_tau_r_g1::f2_19, detail_xck_cmgga_tau_r_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, DTchi + (int64_t)3*nbf*npts + g0, npts, W, 0);
        rowdot(nbf, bk, chi + (int64_t)9*nbf*npts + g0, npts, Wc, bk, out + (int64_t)2*nbf);
    }
    if (own) delete[] c;
    return 0;
}

} // namespace xckernel
