/* generated by xckernel; do not edit. */
#pragma once
#include <cstdint>
#include <new>
#include "xckernel/evaluator.hpp"

namespace xckernel {
namespace detail_xck_mgga_lapl_ua_o2 {
static constexpr double c0[] = {
    1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0
};
static constexpr int32_t o0[] = {
    0,3,6,9,12,16,20,24,28,32,36,40,44,48,52,56,60
};
static constexpr uint16_t f0[] = {
    13,23,0,14,24,0,15,21,0,16,22,0,7,4,27,0,8,5,27,0,9,6,27,0,1,10,27,0,2,11,27,0,3,12,27,0,7,1,26,0,8,2,26,0,9,3,26,0,10,4,28,0,11,5,28,0,12,6,28,0
};
static constexpr double c1[] = {
    1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,4.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,4.0,4.0,4.0,4.0,4.0,4.0
};
static constexpr int32_t o1[] = {
    0,3,7,11,15,19,24,29,34,39,44,49,54,59,64,69,74,79,82,86,90,94,98,103,108,113,118,123,128,133,138,143,148,153
};
static constexpr uint16_t f1[] = {
    10,18,0,4,13,38,0,4,14,39,0,4,15,27,0,4,16,30,0,7,4,4,34,0,8,4,5,34,0,9,4,6,34,0,1,10,4,34,0,2,11,4,34,0,3,12,4,34,0,7,1,4,32,0,8,2,4,32,0,9,3,4,32,0,10,4,4,35,0,11,4,5,35,0,12,4,6,35,0,7,17,0,1,13,36,0,1,14,37,0,1,15,26,0,1,16,29,0,8,1,5,32,0,9,1,6,32,0,1,1,10,32,0,1,2,11,32,0,1,3,12,32,0,7,1,1,31,0,8,1,2,31,0,9,1,3,31,0,1,10,4,33,0,1,11,5,33,0,1,12,6,33,0
};
static constexpr double c2[] = {
    1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,4.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,4.0,4.0,4.0,4.0,4.0,4.0
};
static constexpr int32_t o2[] = {
    0,3,7,11,15,19,24,29,34,39,44,49,54,59,64,69,74,79,82,86,90,94,98,103,108,113,118,123,128,133,138,143,148,153
};
static constexpr uint16_t f2[] = {
    11,18,0,5,13,38,0,5,14,39,0,5,15,27,0,5,16,30,0,7,4,5,34,0,8,5,5,34,0,9,5,6,34,0,1,10,5,34,0,2,11,5,34,0,3,12,5,34,0,7,1,5,32,0,8,2,5,32,0,9,3,5,32,0,10,4,5,35,0,11,5,5,35,0,12,5,6,35,0,8,17,0,2,13,36,0,2,14,37,0,2,15,26,0,2,16,29,0,7,2,4,32,0,9,2,6,32,0,1,2,10,32,0,2,2,11,32,0,2,3,12,32,0,7,1,2,31,0,8,2,2,31,0,9,2,3,31,0,2,10,4,33,0,2,11,5,33,0,2,12,6,33,0
};
static constexpr double c3[] = {
    1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,4.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,4.0,4.0,4.0,4.0,4.0,4.0
};
static constexpr int32_t o3[] = {
    0,3,7,11,15,19,24,29,34,39,44,49,54,59,64,69,74,79,82,86,90,94,98,103,108,113,118,123,128,133,138,143,148,153
};
static constexpr uint16_t f3[] = {
    12,18,0,6,13,38,0,6,14,39,0,6,15,27,0,6,16,30,0,7,4,6,34,0,8,5,6,34,0,9,6,6,34,0,1,10,6,34,0,2,11,6,34,0,3,12,6,34,0,7,1,6,32,0,8,2,6,32,0,9,3,6,32,0,10,4,6,35,0,11,5,6,35,0,12,6,6,35,0,9,17,0,3,13,36,0,3,14,37,0,3,15,26,0,3,16,29,0,7,3,4,32,0,8,3,5,32,0,1,3,10,32,0,2,3,11,32,0,3,3,12,32,0,7,1,3,31,0,8,2,3,31,0,9,3,3,31,0,3,10,4,33,0,3,11,5,33,0,3,12,6,33,0
};
static constexpr double c4[] = {
    1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0
};
static constexpr int32_t o4[] = {
    0,3,6,9,12,16,20,24,28,32,36,40,44,48,52,56,60
};
static constexpr uint16_t f4[] = {
    13,19,0,14,20,0,15,23,0,16,25,0,7,4,38,0,8,5,38,0,9,6,38,0,1,10,38,0,2,11,38,0,3,12,38,0,7,1,36,0,8,2,36,0,9,3,36,0,10,4,40,0,11,5,40,0,12,6,40,0
};
static constexpr double c5[] = {
    1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,4.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,4.0,4.0,4.0,4.0,4.0,4.0
};
static constexpr int32_t o5[] = {
    0,3,7,11,15,19,24,29,34,39,44,49,54,59,64,69,74,79,82,86,90,94,98,103,108,113,118,123,128,133,138,143,148,153
};
static constexpr uint16_t f5[] = {
    10,18,0,4,13,38,0,4,14,39,0,4,15,27,0,4,16,30,0,7,4,4,34,0,8,4,5,34,0,9,4,6,34,0,1,10,4,34,0,2,11,4,34,0,3,12,4,34,0,7,1,4,32,0,8,2,4,32,0,9,3,4,32,0,10,4,4,35,0,11,4,5,35,0,12,4,6,35,0,7,17,0,1,13,36,0,1,14,37,0,1,15,26,0,1,16,29,0,8,1,5,32,0,9,1,6,32,0,1,1,10,32,0,1,2,11,32,0,1,3,12,32,0,7,1,1,31,0,8,1,2,31,0,9,1,3,31,0,1,10,4,33,0,1,11,5,33,0,1,12,6,33,0
};
static constexpr double c6[] = {
    2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,4.0,4.0,4.0,4.0,4.0,4.0
};
static constexpr int32_t o6[] = {
    0,3,6,9,12,16,20,24,28,32,36,40,44,48,52,56,60
};
static constexpr uint16_t f6[] = {
    13,19,0,14,20,0,15,23,0,16,25,0,7,4,38,0,8,5,38,0,9,6,38,0,1,10,38,0,2,11,38,0,3,12,38,0,7,1,36,0,8,2,36,0,9,3,36,0,10,4,40,0,11,5,40,0,12,6,40,0
};
static constexpr double c7[] = {
    1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,4.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,4.0,4.0,4.0,4.0,4.0,4.0
};
static constexpr int32_t o7[] = {
    0,3,7,11,15,19,24,29,34,39,44,49,54,59,64,69,74,79,82,86,90,94,98,103,108,113,118,123,128,133,138,143,148,153
};
static constexpr uint16_t f7[] = {
    11,18,0,5,13,38,0,5,14,39,0,5,15,27,0,5,16,30,0,7,4,5,34,0,8,5,5,34,0,9,5,6,34,0,1,10,5,34,0,2,11,5,34,0,3,12,5,34,0,7,1,5,32,0,8,2,5,32,0,9,3,5,32,0,10,4,5,35,0,11,5,5,35,0,12,5,6,35,0,8,17,0,2,13,36,0,2,14,37,0,2,15,26,0,2,16,29,0,7,2,4,32,0,9,2,6,32,0,1,2,10,32,0,2,2,11,32,0,2,3,12,32,0,7,1,2,31,0,8,2,2,31,0,9,2,3,31,0,2,10,4,33,0,2,11,5,33,0,2,12,6,33,0
};
static constexpr double c8[] = {
    2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,4.0,4.0,4.0,4.0,4.0,4.0
};
static constexpr int32_t o8[] = {
    0,3,6,9,12,16,20,24,28,32,36,40,44,48,52,56,60
};
static constexpr uint16_t f8[] = {
    13,19,0,14,20,0,15,23,0,16,25,0,7,4,38,0,8,5,38,0,9,6,38,0,1,10,38,0,2,11,38,0,3,12,38,0,7,1,36,0,8,2,36,0,9,3,36,0,10,4,40,0,11,5,40,0,12,6,40,0
};
static constexpr double c9[] = {
    1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,4.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,4.0,4.0,4.0,4.0,4.0,4.0
};
static constexpr int32_t o9[] = {
    0,3,7,11,15,19,24,29,34,39,44,49,54,59,64,69,74,79,82,86,90,94,98,103,108,113,118,123,128,133,138,143,148,153
};
static constexpr uint16_t f9[] = {
    12,18,0,6,13,38,0,6,14,39,0,6,15,27,0,6,16,30,0,7,4,6,34,0,8,5,6,34,0,9,6,6,34,0,1,10,6,34,0,2,11,6,34,0,3,12,6,34,0,7,1,6,32,0,8,2,6,32,0,9,3,6,32,0,10,4,6,35,0,11,5,6,35,0,12,6,6,35,0,9,17,0,3,13,36,0,3,14,37,0,3,15,26,0,3,16,29,0,7,3,4,32,0,8,3,5,32,0,1,3,10,32,0,2,3,11,32,0,3,3,12,32,0,7,1,3,31,0,8,2,3,31,0,9,3,3,31,0,3,10,4,33,0,3,11,5,33,0,3,12,6,33,0
};
static constexpr double c10[] = {
    2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,4.0,4.0,4.0,4.0,4.0,4.0
};
static constexpr int32_t o10[] = {
    0,3,6,9,12,16,20,24,28,32,36,40,44,48,52,56,60
};
static constexpr uint16_t f10[] = {
    13,19,0,14,20,0,15,23,0,16,25,0,7,4,38,0,8,5,38,0,9,6,38,0,1,10,38,0,2,11,38,0,3,12,38,0,7,1,36,0,8,2,36,0,9,3,36,0,10,4,40,0,11,5,40,0,12,6,40,0
};
static constexpr double c11[] = {
    1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0
};
static constexpr int32_t o11[] = {
    0,3,6,9,12,16,20,24,28,32,36,40,44,48,52,56,60
};
static constexpr uint16_t f11[] = {
    13,19,0,14,20,0,15,23,0,16,25,0,7,4,38,0,8,5,38,0,9,6,38,0,1,10,38,0,2,11,38,0,3,12,38,0,7,1,36,0,8,2,36,0,9,3,36,0,10,4,40,0,11,5,40,0,12,6,40,0
};
static constexpr int64_t NFLD = 17;
} // namespace detail_xck_mgga_lapl_ua_o2

/* fields: host-computed per-point operands (type T); xc: the
 * functional-derivative arrays (type Txc; Libxc computes in double
 * regardless of T). work: caller scratch of
 * xckernel::work_size(npts, nbf) elements or nullptr
 * (heap-allocated internally; pass a buffer in device code). */
template <typename T, typename Txc = T>
int xck_mgga_lapl_ua_o2_t(int64_t npts, int64_t nbf,
             const T* chi, const T* dchi, const T* lapl_chi,
             const T* hess_chi,
             const T* const* fields, const Txc* const* xc,
             T* out, T* work = nullptr) {
    const int64_t blk = npts < grid_block ? npts : grid_block;
    T* c = work;
    bool own = false;
    if (!c) {
        c = new (std::nothrow) T[work_size(npts, nbf)];
        own = true;
    }
    if (!c) return 1;
    T* W = c + blk;
    const T* Wc = W;
    for (int64_t g0 = 0; g0 < npts; g0 += blk) {
        const int64_t bk = npts - g0 < blk ? npts - g0 : blk;
        stage_a<T, Txc>(g0, bk, 16, detail_xck_mgga_lapl_ua_o2::c0, detail_xck_mgga_lapl_ua_o2::o0, detail_xck_mgga_lapl_ua_o2::f0, detail_xck_mgga_lapl_ua_o2::NFLD, fields, xc, c);
        accumulate<T>(bk, nbf, c, chi + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 33, detail_xck_mgga_lapl_ua_o2::c1, detail_xck_mgga_lapl_ua_o2::o1, detail_xck_mgga_lapl_ua_o2::f1, detail_xck_mgga_lapl_ua_o2::NFLD, fields, xc, c);
        accumulate<T>(bk, nbf, c, dchi + (int64_t)0*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 33, detail_xck_mgga_lapl_ua_o2::c2, detail_xck_mgga_lapl_ua_o2::o2, detail_xck_mgga_lapl_ua_o2::f2, detail_xck_mgga_lapl_ua_o2::NFLD, fields, xc, c);
        accumulate<T>(bk, nbf, c, dchi + (int64_t)1*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 33, detail_xck_mgga_lapl_ua_o2::c3, detail_xck_mgga_lapl_ua_o2::o3, detail_xck_mgga_lapl_ua_o2::f3, detail_xck_mgga_lapl_ua_o2::NFLD, fields, xc, c);
        accumulate<T>(bk, nbf, c, dchi + (int64_t)2*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 16, detail_xck_mgga_lapl_ua_o2::c4, detail_xck_mgga_lapl_ua_o2::o4, detail_xck_mgga_lapl_ua_o2::f4, detail_xck_mgga_lapl_ua_o2::NFLD, fields, xc, c);
        accumulate<T>(bk, nbf, c, lapl_chi + g0, npts, W, 0);
        gemm_nt(nbf, bk, chi + g0, npts, Wc, bk, out);
        stage_a<T, Txc>(g0, bk, 33, detail_xck_mgga_lapl_ua_o2::c5, detail_xck_mgga_lapl_ua_o2::o5, detail_xck_mgga_lapl_ua_o2::f5, detail_xck_mgga_lapl_ua_o2::NFLD, fields, xc, c);
        accumulate<T>(bk, nbf, c, chi + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 16, detail_xck_mgga_lapl_ua_o2::c6, detail_xck_mgga_lapl_ua_o2::o6, detail_xck_mgga_lapl_ua_o2::f6, detail_xck_mgga_lapl_ua_o2::NFLD, fields, xc, c);
        accumulate<T>(bk, nbf, c, dchi + (int64_t)0*nbf*npts + g0, npts, W, 0);
        gemm_nt(nbf, bk, dchi + (int64_t)0*nbf*npts + g0, npts, Wc, bk, out);
        stage_a<T, Txc>(g0, bk, 33, detail_xck_mgga_lapl_ua_o2::c7, detail_xck_mgga_lapl_ua_o2::o7, detail_xck_mgga_lapl_ua_o2::f7, detail_xck_mgga_lapl_ua_o2::NFLD, fields, xc, c);
        accumulate<T>(bk, nbf, c, chi + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 16, detail_xck_mgga_lapl_ua_o2::c8, detail_xck_mgga_lapl_ua_o2::o8, detail_xck_mgga_lapl_ua_o2::f8, detail_xck_mgga_lapl_ua_o2::NFLD, fields, xc, c);
        accumulate<T>(bk, nbf, c, dchi + (int64_t)1*nbf*npts + g0, npts, W, 0);
        gemm_nt(nbf, bk, dchi + (int64_t)1*nbf*npts + g0, npts, Wc, bk, out);
        stage_a<T, Txc>(g0, bk, 33, detail_xck_mgga_lapl_ua_o2::c9, detail_xck_mgga_lapl_ua_o2::o9, detail_xck_mgga_lapl_ua_o2::f9, detail_xck_mgga_lapl_ua_o2::NFLD, fields, xc, c);
        accumulate<T>(bk, nbf, c, chi + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 16, detail_xck_mgga_lapl_ua_o2::c10, detail_xck_mgga_lapl_ua_o2::o10, detail_xck_mgga_lapl_ua_o2::f10, detail_xck_mgga_lapl_ua_o2::NFLD, fields, xc, c);
        accumulate<T>(bk, nbf, c, dchi + (int64_t)2*nbf*npts + g0, npts, W, 0);
        gemm_nt(nbf, bk, dchi + (int64_t)2*nbf*npts + g0, npts, Wc, bk, out);
        stage_a<T, Txc>(g0, bk, 16, detail_xck_mgga_lapl_ua_o2::c11, detail_xck_mgga_lapl_ua_o2::o11, detail_xck_mgga_lapl_ua_o2::f11, detail_xck_mgga_lapl_ua_o2::NFLD, fields, xc, c);
        accumulate<T>(bk, nbf, c, chi + g0, npts, W, 1);
        gemm_nt(nbf, bk, lapl_chi + g0, npts, Wc, bk, out);
    }
    if (own) delete[] c;
    return 0;
}

} // namespace xckernel
