/* generated by xckernel; do not edit. */
#pragma once
#include <cstdint>
#include <new>
#include "xckernel/evaluator.hpp"

namespace xckernel {
namespace detail_xck_mgga_tau_ub_o2_batch {
static constexpr double c0_7[] = {
    1.0,2.0
};
static constexpr int32_t o0_7[] = {
    0,3,6
};
static constexpr uint16_t f0_7[] = {
    4,14,0,1,13,0
};
static constexpr double c0_8[] = {
    1.0,2.0
};
static constexpr int32_t o0_8[] = {
    0,3,6
};
static constexpr uint16_t f0_8[] = {
    5,14,0,2,13,0
};
static constexpr double c0_9[] = {
    1.0,2.0
};
static constexpr int32_t o0_9[] = {
    0,3,6
};
static constexpr uint16_t f0_9[] = {
    6,14,0,3,13,0
};
static constexpr double c0_10[] = {
    1.0,2.0
};
static constexpr int32_t o0_10[] = {
    0,3,6
};
static constexpr uint16_t f0_10[] = {
    1,14,0,4,15,0
};
static constexpr double c0_11[] = {
    1.0,2.0
};
static constexpr int32_t o0_11[] = {
    0,3,6
};
static constexpr uint16_t f0_11[] = {
    2,14,0,5,15,0
};
static constexpr double c0_12[] = {
    1.0,2.0
};
static constexpr int32_t o0_12[] = {
    0,3,6
};
static constexpr uint16_t f0_12[] = {
    3,14,0,6,15,0
};
static constexpr double c0_13[] = {
    1.0
};
static constexpr int32_t o0_13[] = {
    0,2
};
static constexpr uint16_t f0_13[] = {
    9,0
};
static constexpr double c0_14[] = {
    1.0
};
static constexpr int32_t o0_14[] = {
    0,2
};
static constexpr uint16_t f0_14[] = {
    10,0
};
static constexpr double c0_15[] = {
    1.0
};
static constexpr int32_t o0_15[] = {
    0,2
};
static constexpr uint16_t f0_15[] = {
    17,0
};
static constexpr double c0_16[] = {
    1.0
};
static constexpr int32_t o0_16[] = {
    0,2
};
static constexpr uint16_t f0_16[] = {
    18,0
};
static constexpr double c1_7[] = {
    1.0,1.0,2.0,2.0,4.0
};
static constexpr int32_t o1_7[] = {
    0,2,6,10,14,18
};
static constexpr uint16_t f1_7[] = {
    7,0,1,4,21,0,1,1,19,0,4,4,22,0,1,4,20,0
};
static constexpr double c1_8[] = {
    1.0,2.0,2.0,4.0
};
static constexpr int32_t o1_8[] = {
    0,4,8,12,16
};
static constexpr uint16_t f1_8[] = {
    1,5,21,0,1,2,19,0,4,5,22,0,2,4,20,0
};
static constexpr double c1_9[] = {
    1.0,2.0,2.0,4.0
};
static constexpr int32_t o1_9[] = {
    0,4,8,12,16
};
static constexpr uint16_t f1_9[] = {
    1,6,21,0,1,3,19,0,4,6,22,0,3,4,20,0
};
static constexpr double c1_10[] = {
    1.0,4.0,2.0,4.0
};
static constexpr int32_t o1_10[] = {
    0,4,8,10,14
};
static constexpr uint16_t f1_10[] = {
    1,1,21,0,1,4,22,0,8,0,4,4,23,0
};
static constexpr double c1_11[] = {
    1.0,2.0,2.0,4.0
};
static constexpr int32_t o1_11[] = {
    0,4,8,12,16
};
static constexpr uint16_t f1_11[] = {
    1,2,21,0,1,5,22,0,2,4,22,0,4,5,23,0
};
static constexpr double c1_12[] = {
    1.0,2.0,2.0,4.0
};
static constexpr int32_t o1_12[] = {
    0,4,8,12,16
};
static constexpr uint16_t f1_12[] = {
    1,3,21,0,1,6,22,0,3,4,22,0,4,6,23,0
};
static constexpr double c1_13[] = {
    1.0,2.0
};
static constexpr int32_t o1_13[] = {
    0,3,6
};
static constexpr uint16_t f1_13[] = {
    1,11,0,4,12,0
};
static constexpr double c1_14[] = {
    1.0,2.0
};
static constexpr int32_t o1_14[] = {
    0,3,6
};
static constexpr uint16_t f1_14[] = {
    1,14,0,4,15,0
};
static constexpr double c1_15[] = {
    1.0,2.0
};
static constexpr int32_t o1_15[] = {
    0,3,6
};
static constexpr uint16_t f1_15[] = {
    1,25,0,4,27,0
};
static constexpr double c1_16[] = {
    1.0,2.0
};
static constexpr int32_t o1_16[] = {
    0,3,6
};
static constexpr uint16_t f1_16[] = {
    1,26,0,4,28,0
};
static constexpr double c2_7[] = {
    1.0,2.0,2.0,4.0
};
static constexpr int32_t o2_7[] = {
    0,4,8,12,16
};
static constexpr uint16_t f2_7[] = {
    2,4,21,0,1,2,19,0,4,5,22,0,1,5,20,0
};
static constexpr double c2_8[] = {
    1.0,1.0,2.0,2.0,4.0
};
static constexpr int32_t o2_8[] = {
    0,2,6,10,14,18
};
static constexpr uint16_t f2_8[] = {
    7,0,2,5,21,0,2,2,19,0,5,5,22,0,2,5,20,0
};
static constexpr double c2_9[] = {
    1.0,2.0,2.0,4.0
};
static constexpr int32_t o2_9[] = {
    0,4,8,12,16
};
static constexpr uint16_t f2_9[] = {
    2,6,21,0,2,3,19,0,5,6,22,0,3,5,20,0
};
static constexpr double c2_10[] = {
    1.0,2.0,2.0,4.0
};
static constexpr int32_t o2_10[] = {
    0,4,8,12,16
};
static constexpr uint16_t f2_10[] = {
    1,2,21,0,2,4,22,0,1,5,22,0,4,5,23,0
};
static constexpr double c2_11[] = {
    1.0,4.0,2.0,4.0
};
static constexpr int32_t o2_11[] = {
    0,4,8,10,14
};
static constexpr uint16_t f2_11[] = {
    2,2,21,0,2,5,22,0,8,0,5,5,23,0
};
static constexpr double c2_12[] = {
    1.0,2.0,2.0,4.0
};
static constexpr int32_t o2_12[] = {
    0,4,8,12,16
};
static constexpr uint16_t f2_12[] = {
    2,3,21,0,2,6,22,0,3,5,22,0,5,6,23,0
};
static constexpr double c2_13[] = {
    1.0,2.0
};
static constexpr int32_t o2_13[] = {
    0,3,6
};
static constexpr uint16_t f2_13[] = {
    2,11,0,5,12,0
};
static constexpr double c2_14[] = {
    1.0,2.0
};
static constexpr int32_t o2_14[] = {
    0,3,6
};
static constexpr uint16_t f2_14[] = {
    2,14,0,5,15,0
};
static constexpr double c2_15[] = {
    1.0,2.0
};
static constexpr int32_t o2_15[] = {
    0,3,6
};
static constexpr uint16_t f2_15[] = {
    2,25,0,5,27,0
};
static constexpr double c2_16[] = {
    1.0,2.0
};
static constexpr int32_t o2_16[] = {
    0,3,6
};
static constexpr uint16_t f2_16[] = {
    2,26,0,5,28,0
};
static constexpr double c3_7[] = {
    1.0,2.0,2.0,4.0
};
static constexpr int32_t o3_7[] = {
    0,4,8,12,16
};
static constexpr uint16_t f3_7[] = {
    3,4,21,0,1,3,19,0,4,6,22,0,1,6,20,0
};
static constexpr double c3_8[] = {
    1.0,2.0,2.0,4.0
};
static constexpr int32_t o3_8[] = {
    0,4,8,12,16
};
static constexpr uint16_t f3_8[] = {
    3,5,21,0,2,3,19,0,5,6,22,0,2,6,20,0
};
static constexpr double c3_9[] = {
    1.0,1.0,2.0,2.0,4.0
};
static constexpr int32_t o3_9[] = {
    0,2,6,10,14,18
};
static constexpr uint16_t f3_9[] = {
    7,0,3,6,21,0,3,3,19,0,6,6,22,0,3,6,20,0
};
static constexpr double c3_10[] = {
    1.0,2.0,2.0,4.0
};
static constexpr int32_t o3_10[] = {
    0,4,8,12,16
};
static constexpr uint16_t f3_10[] = {
    1,3,21,0,3,4,22,0,1,6,22,0,4,6,23,0
};
static constexpr double c3_11[] = {
    1.0,2.0,2.0,4.0
};
static constexpr int32_t o3_11[] = {
    0,4,8,12,16
};
static constexpr uint16_t f3_11[] = {
    2,3,21,0,3,5,22,0,2,6,22,0,5,6,23,0
};
static constexpr double c3_12[] = {
    1.0,4.0,2.0,4.0
};
static constexpr int32_t o3_12[] = {
    0,4,8,10,14
};
static constexpr uint16_t f3_12[] = {
    3,3,21,0,3,6,22,0,8,0,6,6,23,0
};
static constexpr double c3_13[] = {
    1.0,2.0
};
static constexpr int32_t o3_13[] = {
    0,3,6
};
static constexpr uint16_t f3_13[] = {
    3,11,0,6,12,0
};
static constexpr double c3_14[] = {
    1.0,2.0
};
static constexpr int32_t o3_14[] = {
    0,3,6
};
static constexpr uint16_t f3_14[] = {
    3,14,0,6,15,0
};
static constexpr double c3_15[] = {
    1.0,2.0
};
static constexpr int32_t o3_15[] = {
    0,3,6
};
static constexpr uint16_t f3_15[] = {
    3,25,0,6,27,0
};
static constexpr double c3_16[] = {
    1.0,2.0
};
static constexpr int32_t o3_16[] = {
    0,3,6
};
static constexpr uint16_t f3_16[] = {
    3,26,0,6,28,0
};
static constexpr double c4_7[] = {
    1.0,1.0,2.0,2.0,4.0
};
static constexpr int32_t o4_7[] = {
    0,2,6,10,14,18
};
static constexpr uint16_t f4_7[] = {
    7,0,1,4,21,0,1,1,19,0,4,4,22,0,1,4,20,0
};
static constexpr double c4_8[] = {
    1.0,2.0,2.0,4.0
};
static constexpr int32_t o4_8[] = {
    0,4,8,12,16
};
static constexpr uint16_t f4_8[] = {
    1,5,21,0,1,2,19,0,4,5,22,0,2,4,20,0
};
static constexpr double c4_9[] = {
    1.0,2.0,2.0,4.0
};
static constexpr int32_t o4_9[] = {
    0,4,8,12,16
};
static constexpr uint16_t f4_9[] = {
    1,6,21,0,1,3,19,0,4,6,22,0,3,4,20,0
};
static constexpr double c4_10[] = {
    1.0,4.0,2.0,4.0
};
static constexpr int32_t o4_10[] = {
    0,4,8,10,14
};
static constexpr uint16_t f4_10[] = {
    1,1,21,0,1,4,22,0,8,0,4,4,23,0
};
static constexpr double c4_11[] = {
    1.0,2.0,2.0,4.0
};
static constexpr int32_t o4_11[] = {
    0,4,8,12,16
};
static constexpr uint16_t f4_11[] = {
    1,2,21,0,1,5,22,0,2,4,22,0,4,5,23,0
};
static constexpr double c4_12[] = {
    1.0,2.0,2.0,4.0
};
static constexpr int32_t o4_12[] = {
    0,4,8,12,16
};
static constexpr uint16_t f4_12[] = {
    1,3,21,0,1,6,22,0,3,4,22,0,4,6,23,0
};
static constexpr double c4_13[] = {
    1.0,2.0
};
static constexpr int32_t o4_13[] = {
    0,3,6
};
static constexpr uint16_t f4_13[] = {
    1,11,0,4,12,0
};
static constexpr double c4_14[] = {
    1.0,2.0
};
static constexpr int32_t o4_14[] = {
    0,3,6
};
static constexpr uint16_t f4_14[] = {
    1,14,0,4,15,0
};
static constexpr double c4_15[] = {
    1.0,2.0
};
static constexpr int32_t o4_15[] = {
    0,3,6
};
static constexpr uint16_t f4_15[] = {
    1,25,0,4,27,0
};
static constexpr double c4_16[] = {
    1.0,2.0
};
static constexpr int32_t o4_16[] = {
    0,3,6
};
static constexpr uint16_t f4_16[] = {
    1,26,0,4,28,0
};
static constexpr double c5_7[] = {
    0.5,1.0
};
static constexpr int32_t o5_7[] = {
    0,3,6
};
static constexpr uint16_t f5_7[] = {
    4,26,0,1,24,0
};
static constexpr double c5_8[] = {
    0.5,1.0
};
static constexpr int32_t o5_8[] = {
    0,3,6
};
static constexpr uint16_t f5_8[] = {
    5,26,0,2,24,0
};
static constexpr double c5_9[] = {
    0.5,1.0
};
static constexpr int32_t o5_9[] = {
    0,3,6
};
static constexpr uint16_t f5_9[] = {
    6,26,0,3,24,0
};
static constexpr double c5_10[] = {
    0.5,1.0
};
static constexpr int32_t o5_10[] = {
    0,3,6
};
static constexpr uint16_t f5_10[] = {
    1,26,0,4,28,0
};
static constexpr double c5_11[] = {
    0.5,1.0
};
static constexpr int32_t o5_11[] = {
    0,3,6
};
static constexpr uint16_t f5_11[] = {
    2,26,0,5,28,0
};
static constexpr double c5_12[] = {
    0.5,1.0
};
static constexpr int32_t o5_12[] = {
    0,3,6
};
static constexpr uint16_t f5_12[] = {
    3,26,0,6,28,0
};
static constexpr double c5_13[] = {
    0.5
};
static constexpr int32_t o5_13[] = {
    0,2
};
static constexpr uint16_t f5_13[] = {
    16,0
};
static constexpr double c5_14[] = {
    0.5
};
static constexpr int32_t o5_14[] = {
    0,2
};
static constexpr uint16_t f5_14[] = {
    18,0
};
static constexpr double c5_15[] = {
    0.5
};
static constexpr int32_t o5_15[] = {
    0,2
};
static constexpr uint16_t f5_15[] = {
    29,0
};
static constexpr double c5_16[] = {
    0.5
};
static constexpr int32_t o5_16[] = {
    0,2
};
static constexpr uint16_t f5_16[] = {
    30,0
};
static constexpr double c6_7[] = {
    1.0,2.0,2.0,4.0
};
static constexpr int32_t o6_7[] = {
    0,4,8,12,16
};
static constexpr uint16_t f6_7[] = {
    2,4,21,0,1,2,19,0,4,5,22,0,1,5,20,0
};
static constexpr double c6_8[] = {
    1.0,1.0,2.0,2.0,4.0
};
static constexpr int32_t o6_8[] = {
    0,2,6,10,14,18
};
static constexpr uint16_t f6_8[] = {
    7,0,2,5,21,0,2,2,19,0,5,5,22,0,2,5,20,0
};
static constexpr double c6_9[] = {
    1.0,2.0,2.0,4.0
};
static constexpr int32_t o6_9[] = {
    0,4,8,12,16
};
static constexpr uint16_t f6_9[] = {
    2,6,21,0,2,3,19,0,5,6,22,0,3,5,20,0
};
static constexpr double c6_10[] = {
    1.0,2.0,2.0,4.0
};
static constexpr int32_t o6_10[] = {
    0,4,8,12,16
};
static constexpr uint16_t f6_10[] = {
    1,2,21,0,2,4,22,0,1,5,22,0,4,5,23,0
};
static constexpr double c6_11[] = {
    1.0,4.0,2.0,4.0
};
static constexpr int32_t o6_11[] = {
    0,4,8,10,14
};
static constexpr uint16_t f6_11[] = {
    2,2,21,0,2,5,22,0,8,0,5,5,23,0
};
static constexpr double c6_12[] = {
    1.0,2.0,2.0,4.0
};
static constexpr int32_t o6_12[] = {
    0,4,8,12,16
};
static constexpr uint16_t f6_12[] = {
    2,3,21,0,2,6,22,0,3,5,22,0,5,6,23,0
};
static constexpr double c6_13[] = {
    1.0,2.0
};
static constexpr int32_t o6_13[] = {
    0,3,6
};
static constexpr uint16_t f6_13[] = {
    2,11,0,5,12,0
};
static constexpr double c6_14[] = {
    1.0,2.0
};
static constexpr int32_t o6_14[] = {
    0,3,6
};
static constexpr uint16_t f6_14[] = {
    2,14,0,5,15,0
};
static constexpr double c6_15[] = {
    1.0,2.0
};
static constexpr int32_t o6_15[] = {
    0,3,6
};
static constexpr uint16_t f6_15[] = {
    2,25,0,5,27,0
};
static constexpr double c6_16[] = {
    1.0,2.0
};
static constexpr int32_t o6_16[] = {
    0,3,6
};
static constexpr uint16_t f6_16[] = {
    2,26,0,5,28,0
};
static constexpr double c7_7[] = {
    0.5,1.0
};
static constexpr int32_t o7_7[] = {
    0,3,6
};
static constexpr uint16_t f7_7[] = {
    4,26,0,1,24,0
};
static constexpr double c7_8[] = {
    0.5,1.0
};
static constexpr int32_t o7_8[] = {
    0,3,6
};
static constexpr uint16_t f7_8[] = {
    5,26,0,2,24,0
};
static constexpr double c7_9[] = {
    0.5,1.0
};
static constexpr int32_t o7_9[] = {
    0,3,6
};
static constexpr uint16_t f7_9[] = {
    6,26,0,3,24,0
};
static constexpr double c7_10[] = {
    0.5,1.0
};
static constexpr int32_t o7_10[] = {
    0,3,6
};
static constexpr uint16_t f7_10[] = {
    1,26,0,4,28,0
};
static constexpr double c7_11[] = {
    0.5,1.0
};
static constexpr int32_t o7_11[] = {
    0,3,6
};
static constexpr uint16_t f7_11[] = {
    2,26,0,5,28,0
};
static constexpr double c7_12[] = {
    0.5,1.0
};
static constexpr int32_t o7_12[] = {
    0,3,6
};
static constexpr uint16_t f7_12[] = {
    3,26,0,6,28,0
};
static constexpr double c7_13[] = {
    0.5
};
static constexpr int32_t o7_13[] = {
    0,2
};
static constexpr uint16_t f7_13[] = {
    16,0
};
static constexpr double c7_14[] = {
    0.5
};
static constexpr int32_t o7_14[] = {
    0,2
};
static constexpr uint16_t f7_14[] = {
    18,0
};
static constexpr double c7_15[] = {
    0.5
};
static constexpr int32_t o7_15[] = {
    0,2
};
static constexpr uint16_t f7_15[] = {
    29,0
};
static constexpr double c7_16[] = {
    0.5
};
static constexpr int32_t o7_16[] = {
    0,2
};
static constexpr uint16_t f7_16[] = {
    30,0
};
static constexpr double c8_7[] = {
    1.0,2.0,2.0,4.0
};
static constexpr int32_t o8_7[] = {
    0,4,8,12,16
};
static constexpr uint16_t f8_7[] = {
    3,4,21,0,1,3,19,0,4,6,22,0,1,6,20,0
};
static constexpr double c8_8[] = {
    1.0,2.0,2.0,4.0
};
static constexpr int32_t o8_8[] = {
    0,4,8,12,16
};
static constexpr uint16_t f8_8[] = {
    3,5,21,0,2,3,19,0,5,6,22,0,2,6,20,0
};
static constexpr double c8_9[] = {
    1.0,1.0,2.0,2.0,4.0
};
static constexpr int32_t o8_9[] = {
    0,2,6,10,14,18
};
static constexpr uint16_t f8_9[] = {
    7,0,3,6,21,0,3,3,19,0,6,6,22,0,3,6,20,0
};
static constexpr double c8_10[] = {
    1.0,2.0,2.0,4.0
};
static constexpr int32_t o8_10[] = {
    0,4,8,12,16
};
static constexpr uint16_t f8_10[] = {
    1,3,21,0,3,4,22,0,1,6,22,0,4,6,23,0
};
static constexpr double c8_11[] = {
    1.0,2.0,2.0,4.0
};
static constexpr int32_t o8_11[] = {
    0,4,8,12,16
};
static constexpr uint16_t f8_11[] = {
    2,3,21,0,3,5,22,0,2,6,22,0,5,6,23,0
};
static constexpr double c8_12[] = {
    1.0,4.0,2.0,4.0
};
static constexpr int32_t o8_12[] = {
    0,4,8,10,14
};
static constexpr uint16_t f8_12[] = {
    3,3,21,0,3,6,22,0,8,0,6,6,23,0
};
static constexpr double c8_13[] = {
    1.0,2.0
};
static constexpr int32_t o8_13[] = {
    0,3,6
};
static constexpr uint16_t f8_13[] = {
    3,11,0,6,12,0
};
static constexpr double c8_14[] = {
    1.0,2.0
};
static constexpr int32_t o8_14[] = {
    0,3,6
};
static constexpr uint16_t f8_14[] = {
    3,14,0,6,15,0
};
static constexpr double c8_15[] = {
    1.0,2.0
};
static constexpr int32_t o8_15[] = {
    0,3,6
};
static constexpr uint16_t f8_15[] = {
    3,25,0,6,27,0
};
static constexpr double c8_16[] = {
    1.0,2.0
};
static constexpr int32_t o8_16[] = {
    0,3,6
};
static constexpr uint16_t f8_16[] = {
    3,26,0,6,28,0
};
static constexpr double c9_7[] = {
    0.5,1.0
};
static constexpr int32_t o9_7[] = {
    0,3,6
};
static constexpr uint16_t f9_7[] = {
    4,26,0,1,24,0
};
static constexpr double c9_8[] = {
    0.5,1.0
};
static constexpr int32_t o9_8[] = {
    0,3,6
};
static constexpr uint16_t f9_8[] = {
    5,26,0,2,24,0
};
static constexpr double c9_9[] = {
    0.5,1.0
};
static constexpr int32_t o9_9[] = {
    0,3,6
};
static constexpr uint16_t f9_9[] = {
    6,26,0,3,24,0
};
static constexpr double c9_10[] = {
    0.5,1.0
};
static constexpr int32_t o9_10[] = {
    0,3,6
};
static constexpr uint16_t f9_10[] = {
    1,26,0,4,28,0
};
static constexpr double c9_11[] = {
    0.5,1.0
};
static constexpr int32_t o9_11[] = {
    0,3,6
};
static constexpr uint16_t f9_11[] = {
    2,26,0,5,28,0
};
static constexpr double c9_12[] = {
    0.5,1.0
};
static constexpr int32_t o9_12[] = {
    0,3,6
};
static constexpr uint16_t f9_12[] = {
    3,26,0,6,28,0
};
static constexpr double c9_13[] = {
    0.5
};
static constexpr int32_t o9_13[] = {
    0,2
};
static constexpr uint16_t f9_13[] = {
    16,0
};
static constexpr double c9_14[] = {
    0.5
};
static constexpr int32_t o9_14[] = {
    0,2
};
static constexpr uint16_t f9_14[] = {
    18,0
};
static constexpr double c9_15[] = {
    0.5
};
static constexpr int32_t o9_15[] = {
    0,2
};
static constexpr uint16_t f9_15[] = {
    29,0
};
static constexpr double c9_16[] = {
    0.5
};
static constexpr int32_t o9_16[] = {
    0,2
};
static constexpr uint16_t f9_16[] = {
    30,0
};
static constexpr int64_t NFLD = 7;
} // namespace detail_xck_mgga_tau_ub_o2_batch

/* Scratch (elements of T) the kernel needs for nx perturbations. */
inline int64_t xck_mgga_tau_ub_o2_batch_work(int64_t npts, int64_t nbf, int64_t nx) {
    const int64_t blk = npts < grid_block ? npts : grid_block;
    const int64_t nxc = nx < 8 ? nx : 8;
    return blk * (101 + nbf * (nxc + 0)) + 0 * npts + 1;
}

/* fields: the per-point tower operands in the order of
 * xck_mgga_tau_ub_o2_batch_field_names, perturbed ones (_p1) (nx, npts); xc in
 * the order of xck_mgga_tau_ub_o2_batch_xc_names (both below). */
template <typename T, typename Txc = T>
int xck_mgga_tau_ub_o2_batch_t(int64_t npts, int64_t nbf, int64_t nx,
        const T* chi, const T* const* fields,
        const Txc* const* xc, T* out, T* work = nullptr) {
    const int64_t blk = npts < grid_block ? npts : grid_block;
    const int64_t nxc = nx < 8 ? nx : 8;
    T* c = work;
    bool own = false;
    if (!c) {
        c = new (std::nothrow) T[xck_mgga_tau_ub_o2_batch_work(npts, nbf, nx)];
        own = true;
    }
    if (!c) return 1;
    T* A = c + blk;
    T* W = A + (int64_t)100*blk;
    T* Sb = c + blk * (101 + nbf * (nxc + 0));
    const T* fi[7] = {fields[0], fields[1], fields[2], fields[3], fields[4], fields[5], fields[6]};
    for (int64_t g0 = 0; g0 < npts; g0 += blk) {
        const int64_t bk = npts - g0 < blk ? npts - g0 : blk;
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_tau_ub_o2_batch::c0_7, detail_xck_mgga_tau_ub_o2_batch::o0_7, detail_xck_mgga_tau_ub_o2_batch::f0_7, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)0*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_tau_ub_o2_batch::c0_8, detail_xck_mgga_tau_ub_o2_batch::o0_8, detail_xck_mgga_tau_ub_o2_batch::f0_8, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)1*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_tau_ub_o2_batch::c0_9, detail_xck_mgga_tau_ub_o2_batch::o0_9, detail_xck_mgga_tau_ub_o2_batch::f0_9, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)2*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_tau_ub_o2_batch::c0_10, detail_xck_mgga_tau_ub_o2_batch::o0_10, detail_xck_mgga_tau_ub_o2_batch::f0_10, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)3*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_tau_ub_o2_batch::c0_11, detail_xck_mgga_tau_ub_o2_batch::o0_11, detail_xck_mgga_tau_ub_o2_batch::f0_11, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)4*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_tau_ub_o2_batch::c0_12, detail_xck_mgga_tau_ub_o2_batch::o0_12, detail_xck_mgga_tau_ub_o2_batch::f0_12, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)5*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_tau_ub_o2_batch::c0_13, detail_xck_mgga_tau_ub_o2_batch::o0_13, detail_xck_mgga_tau_ub_o2_batch::f0_13, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)6*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_tau_ub_o2_batch::c0_14, detail_xck_mgga_tau_ub_o2_batch::o0_14, detail_xck_mgga_tau_ub_o2_batch::f0_14, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)7*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_tau_ub_o2_batch::c0_15, detail_xck_mgga_tau_ub_o2_batch::o0_15, detail_xck_mgga_tau_ub_o2_batch::f0_15, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)8*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_tau_ub_o2_batch::c0_16, detail_xck_mgga_tau_ub_o2_batch::o0_16, detail_xck_mgga_tau_ub_o2_batch::f0_16, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)9*blk);
        stage_a<T, Txc>(g0, bk, 5, detail_xck_mgga_tau_ub_o2_batch::c1_7, detail_xck_mgga_tau_ub_o2_batch::o1_7, detail_xck_mgga_tau_ub_o2_batch::f1_7, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)10*blk);
        stage_a<T, Txc>(g0, bk, 4, detail_xck_mgga_tau_ub_o2_batch::c1_8, detail_xck_mgga_tau_ub_o2_batch::o1_8, detail_xck_mgga_tau_ub_o2_batch::f1_8, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)11*blk);
        stage_a<T, Txc>(g0, bk, 4, detail_xck_mgga_tau_ub_o2_batch::c1_9, detail_xck_mgga_tau_ub_o2_batch::o1_9, detail_xck_mgga_tau_ub_o2_batch::f1_9, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)12*blk);
        stage_a<T, Txc>(g0, bk, 4, detail_xck_mgga_tau_ub_o2_batch::c1_10, detail_xck_mgga_tau_ub_o2_batch::o1_10, detail_xck_mgga_tau_ub_o2_batch::f1_10, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)13*blk);
        stage_a<T, Txc>(g0, bk, 4, detail_xck_mgga_tau_ub_o2_batch::c1_11, detail_xck_mgga_tau_ub_o2_batch::o1_11, detail_xck_mgga_tau_ub_o2_batch::f1_11, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)14*blk);
        stage_a<T, Txc>(g0, bk, 4, detail_xck_mgga_tau_ub_o2_batch::c1_12, detail_xck_mgga_tau_ub_o2_batch::o1_12, detail_xck_mgga_tau_ub_o2_batch::f1_12, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)15*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_tau_ub_o2_batch::c1_13, detail_xck_mgga_tau_ub_o2_batch::o1_13, detail_xck_mgga_tau_ub_o2_batch::f1_13, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)16*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_tau_ub_o2_batch::c1_14, detail_xck_mgga_tau_ub_o2_batch::o1_14, detail_xck_mgga_tau_ub_o2_batch::f1_14, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)17*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_tau_ub_o2_batch::c1_15, detail_xck_mgga_tau_ub_o2_batch::o1_15, detail_xck_mgga_tau_ub_o2_batch::f1_15, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)18*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_tau_ub_o2_batch::c1_16, detail_xck_mgga_tau_ub_o2_batch::o1_16, detail_xck_mgga_tau_ub_o2_batch::f1_16, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)19*blk);
        stage_a<T, Txc>(g0, bk, 4, detail_xck_mgga_tau_ub_o2_batch::c2_7, detail_xck_mgga_tau_ub_o2_batch::o2_7, detail_xck_mgga_tau_ub_o2_batch::f2_7, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)20*blk);
        stage_a<T, Txc>(g0, bk, 5, detail_xck_mgga_tau_ub_o2_batch::c2_8, detail_xck_mgga_tau_ub_o2_batch::o2_8, detail_xck_mgga_tau_ub_o2_batch::f2_8, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)21*blk);
        stage_a<T, Txc>(g0, bk, 4, detail_xck_mgga_tau_ub_o2_batch::c2_9, detail_xck_mgga_tau_ub_o2_batch::o2_9, detail_xck_mgga_tau_ub_o2_batch::f2_9, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)22*blk);
        stage_a<T, Txc>(g0, bk, 4, detail_xck_mgga_tau_ub_o2_batch::c2_10, detail_xck_mgga_tau_ub_o2_batch::o2_10, detail_xck_mgga_tau_ub_o2_batch::f2_10, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)23*blk);
        stage_a<T, Txc>(g0, bk, 4, detail_xck_mgga_tau_ub_o2_batch::c2_11, detail_xck_mgga_tau_ub_o2_batch::o2_11, detail_xck_mgga_tau_ub_o2_batch::f2_11, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)24*blk);
        stage_a<T, Txc>(g0, bk, 4, detail_xck_mgga_tau_ub_o2_batch::c2_12, detail_xck_mgga_tau_ub_o2_batch::o2_12, detail_xck_mgga_tau_ub_o2_batch::f2_12, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)25*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_tau_ub_o2_batch::c2_13, detail_xck_mgga_tau_ub_o2_batch::o2_13, detail_xck_mgga_tau_ub_o2_batch::f2_13, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)26*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_tau_ub_o2_batch::c2_14, detail_xck_mgga_tau_ub_o2_batch::o2_14, detail_xck_mgga_tau_ub_o2_batch::f2_14, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)27*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_tau_ub_o2_batch::c2_15, detail_xck_mgga_tau_ub_o2_batch::o2_15, detail_xck_mgga_tau_ub_o2_batch::f2_15, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)28*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_tau_ub_o2_batch::c2_16, detail_xck_mgga_tau_ub_o2_batch::o2_16, detail_xck_mgga_tau_ub_o2_batch::f2_16, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)29*blk);
        stage_a<T, Txc>(g0, bk, 4, detail_xck_mgga_tau_ub_o2_batch::c3_7, detail_xck_mgga_tau_ub_o2_batch::o3_7, detail_xck_mgga_tau_ub_o2_batch::f3_7, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)30*blk);
        stage_a<T, Txc>(g0, bk, 4, detail_xck_mgga_tau_ub_o2_batch::c3_8, detail_xck_mgga_tau_ub_o2_batch::o3_8, detail_xck_mgga_tau_ub_o2_batch::f3_8, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)31*blk);
        stage_a<T, Txc>(g0, bk, 5, detail_xck_mgga_tau_ub_o2_batch::c3_9, detail_xck_mgga_tau_ub_o2_batch::o3_9, detail_xck_mgga_tau_ub_o2_batch::f3_9, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)32*blk);
        stage_a<T, Txc>(g0, bk, 4, detail_xck_mgga_tau_ub_o2_batch::c3_10, detail_xck_mgga_tau_ub_o2_batch::o3_10, detail_xck_mgga_tau_ub_o2_batch::f3_10, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)33*blk);
        stage_a<T, Txc>(g0, bk, 4, detail_xck_mgga_tau_ub_o2_batch::c3_11, detail_xck_mgga_tau_ub_o2_batch::o3_11, detail_xck_mgga_tau_ub_o2_batch::f3_11, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)34*blk);
        stage_a<T, Txc>(g0, bk, 4, detail_xck_mgga_tau_ub_o2_batch::c3_12, detail_xck_mgga_tau_ub_o2_batch::o3_12, detail_xck_mgga_tau_ub_o2_batch::f3_12, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)35*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_tau_ub_o2_batch::c3_13, detail_xck_mgga_tau_ub_o2_batch::o3_13, detail_xck_mgga_tau_ub_o2_batch::f3_13, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)36*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_tau_ub_o2_batch::c3_14, detail_xck_mgga_tau_ub_o2_batch::o3_14, detail_xck_mgga_tau_ub_o2_batch::f3_14, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)37*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_tau_ub_o2_batch::c3_15, detail_xck_mgga_tau_ub_o2_batch::o3_15, detail_xck_mgga_tau_ub_o2_batch::f3_15, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)38*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_tau_ub_o2_batch::c3_16, detail_xck_mgga_tau_ub_o2_batch::o3_16, detail_xck_mgga_tau_ub_o2_batch::f3_16, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)39*blk);
        stage_a<T, Txc>(g0, bk, 5, detail_xck_mgga_tau_ub_o2_batch::c4_7, detail_xck_mgga_tau_ub_o2_batch::o4_7, detail_xck_mgga_tau_ub_o2_batch::f4_7, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)40*blk);
        stage_a<T, Txc>(g0, bk, 4, detail_xck_mgga_tau_ub_o2_batch::c4_8, detail_xck_mgga_tau_ub_o2_batch::o4_8, detail_xck_mgga_tau_ub_o2_batch::f4_8, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)41*blk);
        stage_a<T, Txc>(g0, bk, 4, detail_xck_mgga_tau_ub_o2_batch::c4_9, detail_xck_mgga_tau_ub_o2_batch::o4_9, detail_xck_mgga_tau_ub_o2_batch::f4_9, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)42*blk);
        stage_a<T, Txc>(g0, bk, 4, detail_xck_mgga_tau_ub_o2_batch::c4_10, detail_xck_mgga_tau_ub_o2_batch::o4_10, detail_xck_mgga_tau_ub_o2_batch::f4_10, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)43*blk);
        stage_a<T, Txc>(g0, bk, 4, detail_xck_mgga_tau_ub_o2_batch::c4_11, detail_xck_mgga_tau_ub_o2_batch::o4_11, detail_xck_mgga_tau_ub_o2_batch::f4_11, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)44*blk);
        stage_a<T, Txc>(g0, bk, 4, detail_xck_mgga_tau_ub_o2_batch::c4_12, detail_xck_mgga_tau_ub_o2_batch::o4_12, detail_xck_mgga_tau_ub_o2_batch::f4_12, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)45*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_tau_ub_o2_batch::c4_13, detail_xck_mgga_tau_ub_o2_batch::o4_13, detail_xck_mgga_tau_ub_o2_batch::f4_13, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)46*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_tau_ub_o2_batch::c4_14, detail_xck_mgga_tau_ub_o2_batch::o4_14, detail_xck_mgga_tau_ub_o2_batch::f4_14, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)47*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_tau_ub_o2_batch::c4_15, detail_xck_mgga_tau_ub_o2_batch::o4_15, detail_xck_mgga_tau_ub_o2_batch::f4_15, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)48*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_tau_ub_o2_batch::c4_16, detail_xck_mgga_tau_ub_o2_batch::o4_16, detail_xck_mgga_tau_ub_o2_batch::f4_16, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)49*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_tau_ub_o2_batch::c5_7, detail_xck_mgga_tau_ub_o2_batch::o5_7, detail_xck_mgga_tau_ub_o2_batch::f5_7, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)50*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_tau_ub_o2_batch::c5_8, detail_xck_mgga_tau_ub_o2_batch::o5_8, detail_xck_mgga_tau_ub_o2_batch::f5_8, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)51*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_tau_ub_o2_batch::c5_9, detail_xck_mgga_tau_ub_o2_batch::o5_9, detail_xck_mgga_tau_ub_o2_batch::f5_9, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)52*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_tau_ub_o2_batch::c5_10, detail_xck_mgga_tau_ub_o2_batch::o5_10, detail_xck_mgga_tau_ub_o2_batch::f5_10, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)53*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_tau_ub_o2_batch::c5_11, detail_xck_mgga_tau_ub_o2_batch::o5_11, detail_xck_mgga_tau_ub_o2_batch::f5_11, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)54*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_tau_ub_o2_batch::c5_12, detail_xck_mgga_tau_ub_o2_batch::o5_12, detail_xck_mgga_tau_ub_o2_batch::f5_12, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)55*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_tau_ub_o2_batch::c5_13, detail_xck_mgga_tau_ub_o2_batch::o5_13, detail_xck_mgga_tau_ub_o2_batch::f5_13, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)56*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_tau_ub_o2_batch::c5_14, detail_xck_mgga_tau_ub_o2_batch::o5_14, detail_xck_mgga_tau_ub_o2_batch::f5_14, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)57*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_tau_ub_o2_batch::c5_15, detail_xck_mgga_tau_ub_o2_batch::o5_15, detail_xck_mgga_tau_ub_o2_batch::f5_15, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)58*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_tau_ub_o2_batch::c5_16, detail_xck_mgga_tau_ub_o2_batch::o5_16, detail_xck_mgga_tau_ub_o2_batch::f5_16, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)59*blk);
        stage_a<T, Txc>(g0, bk, 4, detail_xck_mgga_tau_ub_o2_batch::c6_7, detail_xck_mgga_tau_ub_o2_batch::o6_7, detail_xck_mgga_tau_ub_o2_batch::f6_7, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)60*blk);
        stage_a<T, Txc>(g0, bk, 5, detail_xck_mgga_tau_ub_o2_batch::c6_8, detail_xck_mgga_tau_ub_o2_batch::o6_8, detail_xck_mgga_tau_ub_o2_batch::f6_8, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)61*blk);
        stage_a<T, Txc>(g0, bk, 4, detail_xck_mgga_tau_ub_o2_batch::c6_9, detail_xck_mgga_tau_ub_o2_batch::o6_9, detail_xck_mgga_tau_ub_o2_batch::f6_9, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)62*blk);
        stage_a<T, Txc>(g0, bk, 4, detail_xck_mgga_tau_ub_o2_batch::c6_10, detail_xck_mgga_tau_ub_o2_batch::o6_10, detail_xck_mgga_tau_ub_o2_batch::f6_10, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)63*blk);
        stage_a<T, Txc>(g0, bk, 4, detail_xck_mgga_tau_ub_o2_batch::c6_11, detail_xck_mgga_tau_ub_o2_batch::o6_11, detail_xck_mgga_tau_ub_o2_batch::f6_11, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)64*blk);
        stage_a<T, Txc>(g0, bk, 4, detail_xck_mgga_tau_ub_o2_batch::c6_12, detail_xck_mgga_tau_ub_o2_batch::o6_12, detail_xck_mgga_tau_ub_o2_batch::f6_12, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)65*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_tau_ub_o2_batch::c6_13, detail_xck_mgga_tau_ub_o2_batch::o6_13, detail_xck_mgga_tau_ub_o2_batch::f6_13, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)66*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_tau_ub_o2_batch::c6_14, detail_xck_mgga_tau_ub_o2_batch::o6_14, detail_xck_mgga_tau_ub_o2_batch::f6_14, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)67*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_tau_ub_o2_batch::c6_15, detail_xck_mgga_tau_ub_o2_batch::o6_15, detail_xck_mgga_tau_ub_o2_batch::f6_15, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)68*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_tau_ub_o2_batch::c6_16, detail_xck_mgga_tau_ub_o2_batch::o6_16, detail_xck_mgga_tau_ub_o2_batch::f6_16, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)69*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_tau_ub_o2_batch::c7_7, detail_xck_mgga_tau_ub_o2_batch::o7_7, detail_xck_mgga_tau_ub_o2_batch::f7_7, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)70*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_tau_ub_o2_batch::c7_8, detail_xck_mgga_tau_ub_o2_batch::o7_8, detail_xck_mgga_tau_ub_o2_batch::f7_8, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)71*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_tau_ub_o2_batch::c7_9, detail_xck_mgga_tau_ub_o2_batch::o7_9, detail_xck_mgga_tau_ub_o2_batch::f7_9, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)72*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_tau_ub_o2_batch::c7_10, detail_xck_mgga_tau_ub_o2_batch::o7_10, detail_xck_mgga_tau_ub_o2_batch::f7_10, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)73*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_tau_ub_o2_batch::c7_11, detail_xck_mgga_tau_ub_o2_batch::o7_11, detail_xck_mgga_tau_ub_o2_batch::f7_11, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)74*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_tau_ub_o2_batch::c7_12, detail_xck_mgga_tau_ub_o2_batch::o7_12, detail_xck_mgga_tau_ub_o2_batch::f7_12, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)75*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_tau_ub_o2_batch::c7_13, detail_xck_mgga_tau_ub_o2_batch::o7_13, detail_xck_mgga_tau_ub_o2_batch::f7_13, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)76*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_tau_ub_o2_batch::c7_14, detail_xck_mgga_tau_ub_o2_batch::o7_14, detail_xck_mgga_tau_ub_o2_batch::f7_14, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)77*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_tau_ub_o2_batch::c7_15, detail_xck_mgga_tau_ub_o2_batch::o7_15, detail_xck_mgga_tau_ub_o2_batch::f7_15, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)78*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_tau_ub_o2_batch::c7_16, detail_xck_mgga_tau_ub_o2_batch::o7_16, detail_xck_mgga_tau_ub_o2_batch::f7_16, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)79*blk);
        stage_a<T, Txc>(g0, bk, 4, detail_xck_mgga_tau_ub_o2_batch::c8_7, detail_xck_mgga_tau_ub_o2_batch::o8_7, detail_xck_mgga_tau_ub_o2_batch::f8_7, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)80*blk);
        stage_a<T, Txc>(g0, bk, 4, detail_xck_mgga_tau_ub_o2_batch::c8_8, detail_xck_mgga_tau_ub_o2_batch::o8_8, detail_xck_mgga_tau_ub_o2_batch::f8_8, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)81*blk);
        stage_a<T, Txc>(g0, bk, 5, detail_xck_mgga_tau_ub_o2_batch::c8_9, detail_xck_mgga_tau_ub_o2_batch::o8_9, detail_xck_mgga_tau_ub_o2_batch::f8_9, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)82*blk);
        stage_a<T, Txc>(g0, bk, 4, detail_xck_mgga_tau_ub_o2_batch::c8_10, detail_xck_mgga_tau_ub_o2_batch::o8_10, detail_xck_mgga_tau_ub_o2_batch::f8_10, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)83*blk);
        stage_a<T, Txc>(g0, bk, 4, detail_xck_mgga_tau_ub_o2_batch::c8_11, detail_xck_mgga_tau_ub_o2_batch::o8_11, detail_xck_mgga_tau_ub_o2_batch::f8_11, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)84*blk);
        stage_a<T, Txc>(g0, bk, 4, detail_xck_mgga_tau_ub_o2_batch::c8_12, detail_xck_mgga_tau_ub_o2_batch::o8_12, detail_xck_mgga_tau_ub_o2_batch::f8_12, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)85*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_tau_ub_o2_batch::c8_13, detail_xck_mgga_tau_ub_o2_batch::o8_13, detail_xck_mgga_tau_ub_o2_batch::f8_13, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)86*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_tau_ub_o2_batch::c8_14, detail_xck_mgga_tau_ub_o2_batch::o8_14, detail_xck_mgga_tau_ub_o2_batch::f8_14, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)87*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_tau_ub_o2_batch::c8_15, detail_xck_mgga_tau_ub_o2_batch::o8_15, detail_xck_mgga_tau_ub_o2_batch::f8_15, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)88*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_tau_ub_o2_batch::c8_16, detail_xck_mgga_tau_ub_o2_batch::o8_16, detail_xck_mgga_tau_ub_o2_batch::f8_16, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)89*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_tau_ub_o2_batch::c9_7, detail_xck_mgga_tau_ub_o2_batch::o9_7, detail_xck_mgga_tau_ub_o2_batch::f9_7, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)90*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_tau_ub_o2_batch::c9_8, detail_xck_mgga_tau_ub_o2_batch::o9_8, detail_xck_mgga_tau_ub_o2_batch::f9_8, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)91*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_tau_ub_o2_batch::c9_9, detail_xck_mgga_tau_ub_o2_batch::o9_9, detail_xck_mgga_tau_ub_o2_batch::f9_9, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)92*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_tau_ub_o2_batch::c9_10, detail_xck_mgga_tau_ub_o2_batch::o9_10, detail_xck_mgga_tau_ub_o2_batch::f9_10, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)93*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_tau_ub_o2_batch::c9_11, detail_xck_mgga_tau_ub_o2_batch::o9_11, detail_xck_mgga_tau_ub_o2_batch::f9_11, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)94*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_tau_ub_o2_batch::c9_12, detail_xck_mgga_tau_ub_o2_batch::o9_12, detail_xck_mgga_tau_ub_o2_batch::f9_12, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)95*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_tau_ub_o2_batch::c9_13, detail_xck_mgga_tau_ub_o2_batch::o9_13, detail_xck_mgga_tau_ub_o2_batch::f9_13, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)96*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_tau_ub_o2_batch::c9_14, detail_xck_mgga_tau_ub_o2_batch::o9_14, detail_xck_mgga_tau_ub_o2_batch::f9_14, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)97*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_tau_ub_o2_batch::c9_15, detail_xck_mgga_tau_ub_o2_batch::o9_15, detail_xck_mgga_tau_ub_o2_batch::f9_15, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)98*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_tau_ub_o2_batch::c9_16, detail_xck_mgga_tau_ub_o2_batch::o9_16, detail_xck_mgga_tau_ub_o2_batch::f9_16, detail_xck_mgga_tau_ub_o2_batch::NFLD, fi, xc, A + (int64_t)99*blk);
        for (int64_t x0 = 0; x0 < nx; x0 += nxc) {
            const int64_t nxb = nx - x0 < nxc ? nx - x0 : nxc;
            for (int64_t x = 0; x < nxb; ++x) {
                {
                    const T* A_[] = {A + (int64_t)0*blk, A + (int64_t)1*blk, A + (int64_t)2*blk, A + (int64_t)3*blk, A + (int64_t)4*blk, A + (int64_t)5*blk, A + (int64_t)6*blk, A + (int64_t)7*blk, A + (int64_t)8*blk, A + (int64_t)9*blk};
                    const T* P_[] = {fields[7] + (x0 + x)*npts + g0, fields[8] + (x0 + x)*npts + g0, fields[9] + (x0 + x)*npts + g0, fields[10] + (x0 + x)*npts + g0, fields[11] + (x0 + x)*npts + g0, fields[12] + (x0 + x)*npts + g0, fields[13] + (x0 + x)*npts + g0, fields[14] + (x0 + x)*npts + g0, fields[15] + (x0 + x)*npts + g0, fields[16] + (x0 + x)*npts + g0};
                    lincomb<T>(bk, 10, A_, P_, c);
                }
                accumulate<T>(bk, nbf, c, chi + (int64_t)0*nbf*npts + g0, npts, W + x*nbf*bk, 1);
                {
                    const T* A_[] = {A + (int64_t)40*blk, A + (int64_t)41*blk, A + (int64_t)42*blk, A + (int64_t)43*blk, A + (int64_t)44*blk, A + (int64_t)45*blk, A + (int64_t)46*blk, A + (int64_t)47*blk, A + (int64_t)48*blk, A + (int64_t)49*blk};
                    const T* P_[] = {fields[7] + (x0 + x)*npts + g0, fields[8] + (x0 + x)*npts + g0, fields[9] + (x0 + x)*npts + g0, fields[10] + (x0 + x)*npts + g0, fields[11] + (x0 + x)*npts + g0, fields[12] + (x0 + x)*npts + g0, fields[13] + (x0 + x)*npts + g0, fields[14] + (x0 + x)*npts + g0, fields[15] + (x0 + x)*npts + g0, fields[16] + (x0 + x)*npts + g0};
                    lincomb<T>(bk, 10, A_, P_, c);
                }
                accumulate<T>(bk, nbf, c, chi + (int64_t)1*nbf*npts + g0, npts, W + x*nbf*bk, 0);
                {
                    const T* A_[] = {A + (int64_t)60*blk, A + (int64_t)61*blk, A + (int64_t)62*blk, A + (int64_t)63*blk, A + (int64_t)64*blk, A + (int64_t)65*blk, A + (int64_t)66*blk, A + (int64_t)67*blk, A + (int64_t)68*blk, A + (int64_t)69*blk};
                    const T* P_[] = {fields[7] + (x0 + x)*npts + g0, fields[8] + (x0 + x)*npts + g0, fields[9] + (x0 + x)*npts + g0, fields[10] + (x0 + x)*npts + g0, fields[11] + (x0 + x)*npts + g0, fields[12] + (x0 + x)*npts + g0, fields[13] + (x0 + x)*npts + g0, fields[14] + (x0 + x)*npts + g0, fields[15] + (x0 + x)*npts + g0, fields[16] + (x0 + x)*npts + g0};
                    lincomb<T>(bk, 10, A_, P_, c);
                }
                accumulate<T>(bk, nbf, c, chi + (int64_t)2*nbf*npts + g0, npts, W + x*nbf*bk, 0);
                {
                    const T* A_[] = {A + (int64_t)80*blk, A + (int64_t)81*blk, A + (int64_t)82*blk, A + (int64_t)83*blk, A + (int64_t)84*blk, A + (int64_t)85*blk, A + (int64_t)86*blk, A + (int64_t)87*blk, A + (int64_t)88*blk, A + (int64_t)89*blk};
                    const T* P_[] = {fields[7] + (x0 + x)*npts + g0, fields[8] + (x0 + x)*npts + g0, fields[9] + (x0 + x)*npts + g0, fields[10] + (x0 + x)*npts + g0, fields[11] + (x0 + x)*npts + g0, fields[12] + (x0 + x)*npts + g0, fields[13] + (x0 + x)*npts + g0, fields[14] + (x0 + x)*npts + g0, fields[15] + (x0 + x)*npts + g0, fields[16] + (x0 + x)*npts + g0};
                    lincomb<T>(bk, 10, A_, P_, c);
                }
                accumulate<T>(bk, nbf, c, chi + (int64_t)3*nbf*npts + g0, npts, W + x*nbf*bk, 0);
            }
            gemm_rect(nxb*nbf, nbf, bk, static_cast<const T*>(W), bk, chi + (int64_t)0*nbf*npts + g0, npts, out + x0*nbf*nbf, nbf);
            for (int64_t x = 0; x < nxb; ++x) {
                {
                    const T* A_[] = {A + (int64_t)10*blk, A + (int64_t)11*blk, A + (int64_t)12*blk, A + (int64_t)13*blk, A + (int64_t)14*blk, A + (int64_t)15*blk, A + (int64_t)16*blk, A + (int64_t)17*blk, A + (int64_t)18*blk, A + (int64_t)19*blk};
                    const T* P_[] = {fields[7] + (x0 + x)*npts + g0, fields[8] + (x0 + x)*npts + g0, fields[9] + (x0 + x)*npts + g0, fields[10] + (x0 + x)*npts + g0, fields[11] + (x0 + x)*npts + g0, fields[12] + (x0 + x)*npts + g0, fields[13] + (x0 + x)*npts + g0, fields[14] + (x0 + x)*npts + g0, fields[15] + (x0 + x)*npts + g0, fields[16] + (x0 + x)*npts + g0};
                    lincomb<T>(bk, 10, A_, P_, c);
                }
                accumulate<T>(bk, nbf, c, chi + (int64_t)0*nbf*npts + g0, npts, W + x*nbf*bk, 1);
                {
                    const T* A_[] = {A + (int64_t)50*blk, A + (int64_t)51*blk, A + (int64_t)52*blk, A + (int64_t)53*blk, A + (int64_t)54*blk, A + (int64_t)55*blk, A + (int64_t)56*blk, A + (int64_t)57*blk, A + (int64_t)58*blk, A + (int64_t)59*blk};
                    const T* P_[] = {fields[7] + (x0 + x)*npts + g0, fields[8] + (x0 + x)*npts + g0, fields[9] + (x0 + x)*npts + g0, fields[10] + (x0 + x)*npts + g0, fields[11] + (x0 + x)*npts + g0, fields[12] + (x0 + x)*npts + g0, fields[13] + (x0 + x)*npts + g0, fields[14] + (x0 + x)*npts + g0, fields[15] + (x0 + x)*npts + g0, fields[16] + (x0 + x)*npts + g0};
                    lincomb<T>(bk, 10, A_, P_, c);
                }
                accumulate<T>(bk, nbf, c, chi + (int64_t)1*nbf*npts + g0, npts, W + x*nbf*bk, 0);
            }
            gemm_rect(nxb*nbf, nbf, bk, static_cast<const T*>(W), bk, chi + (int64_t)1*nbf*npts + g0, npts, out + x0*nbf*nbf, nbf);
            for (int64_t x = 0; x < nxb; ++x) {
                {
                    const T* A_[] = {A + (int64_t)20*blk, A + (int64_t)21*blk, A + (int64_t)22*blk, A + (int64_t)23*blk, A + (int64_t)24*blk, A + (int64_t)25*blk, A + (int64_t)26*blk, A + (int64_t)27*blk, A + (int64_t)28*blk, A + (int64_t)29*blk};
                    const T* P_[] = {fields[7] + (x0 + x)*npts + g0, fields[8] + (x0 + x)*npts + g0, fields[9] + (x0 + x)*npts + g0, fields[10] + (x0 + x)*npts + g0, fields[11] + (x0 + x)*npts + g0, fields[12] + (x0 + x)*npts + g0, fields[13] + (x0 + x)*npts + g0, fields[14] + (x0 + x)*npts + g0, fields[15] + (x0 + x)*npts + g0, fields[16] + (x0 + x)*npts + g0};
                    lincomb<T>(bk, 10, A_, P_, c);
                }
                accumulate<T>(bk, nbf, c, chi + (int64_t)0*nbf*npts + g0, npts, W + x*nbf*bk, 1);
                {
                    const T* A_[] = {A + (int64_t)70*blk, A + (int64_t)71*blk, A + (int64_t)72*blk, A + (int64_t)73*blk, A + (int64_t)74*blk, A + (int64_t)75*blk, A + (int64_t)76*blk, A + (int64_t)77*blk, A + (int64_t)78*blk, A + (int64_t)79*blk};
                    const T* P_[] = {fields[7] + (x0 + x)*npts + g0, fields[8] + (x0 + x)*npts + g0, fields[9] + (x0 + x)*npts + g0, fields[10] + (x0 + x)*npts + g0, fields[11] + (x0 + x)*npts + g0, fields[12] + (x0 + x)*npts + g0, fields[13] + (x0 + x)*npts + g0, fields[14] + (x0 + x)*npts + g0, fields[15] + (x0 + x)*npts + g0, fields[16] + (x0 + x)*npts + g0};
                    lincomb<T>(bk, 10, A_, P_, c);
                }
                accumulate<T>(bk, nbf, c, chi + (int64_t)2*nbf*npts + g0, npts, W + x*nbf*bk, 0);
            }
            gemm_rect(nxb*nbf, nbf, bk, static_cast<const T*>(W), bk, chi + (int64_t)2*nbf*npts + g0, npts, out + x0*nbf*nbf, nbf);
            for (int64_t x = 0; x < nxb; ++x) {
                {
                    const T* A_[] = {A + (int64_t)30*blk, A + (int64_t)31*blk, A + (int64_t)32*blk, A + (int64_t)33*blk, A + (int64_t)34*blk, A + (int64_t)35*blk, A + (int64_t)36*blk, A + (int64_t)37*blk, A + (int64_t)38*blk, A + (int64_t)39*blk};
                    const T* P_[] = {fields[7] + (x0 + x)*npts + g0, fields[8] + (x0 + x)*npts + g0, fields[9] + (x0 + x)*npts + g0, fields[10] + (x0 + x)*npts + g0, fields[11] + (x0 + x)*npts + g0, fields[12] + (x0 + x)*npts + g0, fields[13] + (x0 + x)*npts + g0, fields[14] + (x0 + x)*npts + g0, fields[15] + (x0 + x)*npts + g0, fields[16] + (x0 + x)*npts + g0};
                    lincomb<T>(bk, 10, A_, P_, c);
                }
                accumulate<T>(bk, nbf, c, chi + (int64_t)0*nbf*npts + g0, npts, W + x*nbf*bk, 1);
                {
                    const T* A_[] = {A + (int64_t)90*blk, A + (int64_t)91*blk, A + (int64_t)92*blk, A + (int64_t)93*blk, A + (int64_t)94*blk, A + (int64_t)95*blk, A + (int64_t)96*blk, A + (int64_t)97*blk, A + (int64_t)98*blk, A + (int64_t)99*blk};
                    const T* P_[] = {fields[7] + (x0 + x)*npts + g0, fields[8] + (x0 + x)*npts + g0, fields[9] + (x0 + x)*npts + g0, fields[10] + (x0 + x)*npts + g0, fields[11] + (x0 + x)*npts + g0, fields[12] + (x0 + x)*npts + g0, fields[13] + (x0 + x)*npts + g0, fields[14] + (x0 + x)*npts + g0, fields[15] + (x0 + x)*npts + g0, fields[16] + (x0 + x)*npts + g0};
                    lincomb<T>(bk, 10, A_, P_, c);
                }
                accumulate<T>(bk, nbf, c, chi + (int64_t)3*nbf*npts + g0, npts, W + x*nbf*bk, 0);
            }
            gemm_rect(nxb*nbf, nbf, bk, static_cast<const T*>(W), bk, chi + (int64_t)3*nbf*npts + g0, npts, out + x0*nbf*nbf, nbf);
        }
    }
    if (own) delete[] c;
    return 0;
}


/* Operands of xck_mgga_tau_ub_o2_batch_t: `fields` in the order of
 * xck_mgga_tau_ub_o2_batch_field_names, `xc` in the order of xck_mgga_tau_ub_o2_batch_xc_names (the
 * C ABI's `scal` is the two concatenated, split at n_fields). The
 * structs name them; the overload taking them packs the arrays. */
inline constexpr int xck_mgga_tau_ub_o2_batch_n_fields = 17;
inline constexpr int xck_mgga_tau_ub_o2_batch_n_xc = 24;
inline constexpr const char* xck_mgga_tau_ub_o2_batch_field_names[] = {"w", "rho_a_x", "rho_a_y", "rho_a_z", "rho_b_x", "rho_b_y", "rho_b_z", "rho_a_p1_x", "rho_a_p1_y", "rho_a_p1_z", "rho_b_p1_x", "rho_b_p1_y", "rho_b_p1_z", "rho_a_p1", "rho_b_p1", "tau_a_p1", "tau_b_p1"};
inline constexpr const char* xck_mgga_tau_ub_o2_batch_xc_names[] = {"vsigma_1", "vsigma_2", "v2rho2_1", "v2rho2_2", "v2rhosigma_1", "v2rhosigma_2", "v2rhosigma_3", "v2rhosigma_4", "v2rhosigma_5", "v2rhotau_1", "v2rhotau_2", "v2rhotau_3", "v2sigma2_1", "v2sigma2_2", "v2sigma2_3", "v2sigma2_4", "v2sigma2_5", "v2sigmatau_1", "v2sigmatau_2", "v2sigmatau_3", "v2sigmatau_4", "v2sigmatau_5", "v2tau2_1", "v2tau2_2"};
template <typename T>
struct xck_mgga_tau_ub_o2_batch_fields {
    const T* w;
    const T* rho_a_x;
    const T* rho_a_y;
    const T* rho_a_z;
    const T* rho_b_x;
    const T* rho_b_y;
    const T* rho_b_z;
    const T* rho_a_p1_x;
    const T* rho_a_p1_y;
    const T* rho_a_p1_z;
    const T* rho_b_p1_x;
    const T* rho_b_p1_y;
    const T* rho_b_p1_z;
    const T* rho_a_p1;
    const T* rho_b_p1;
    const T* tau_a_p1;
    const T* tau_b_p1;
};
template <typename Txc>
struct xck_mgga_tau_ub_o2_batch_xc {
    const Txc* vsigma_1;
    const Txc* vsigma_2;
    const Txc* v2rho2_1;
    const Txc* v2rho2_2;
    const Txc* v2rhosigma_1;
    const Txc* v2rhosigma_2;
    const Txc* v2rhosigma_3;
    const Txc* v2rhosigma_4;
    const Txc* v2rhosigma_5;
    const Txc* v2rhotau_1;
    const Txc* v2rhotau_2;
    const Txc* v2rhotau_3;
    const Txc* v2sigma2_1;
    const Txc* v2sigma2_2;
    const Txc* v2sigma2_3;
    const Txc* v2sigma2_4;
    const Txc* v2sigma2_5;
    const Txc* v2sigmatau_1;
    const Txc* v2sigmatau_2;
    const Txc* v2sigmatau_3;
    const Txc* v2sigmatau_4;
    const Txc* v2sigmatau_5;
    const Txc* v2tau2_1;
    const Txc* v2tau2_2;
};

template <typename T, typename Txc = T>
int xck_mgga_tau_ub_o2_batch_t(int64_t npts,
        int64_t nbf,
        int64_t nx,
        const T* chi,
        const xck_mgga_tau_ub_o2_batch_fields<T>& fields_,
        const xck_mgga_tau_ub_o2_batch_xc<Txc>& xc_,
        T* out,
        T* work = nullptr) {
    const T* f_[] = {fields_.w, fields_.rho_a_x, fields_.rho_a_y, fields_.rho_a_z, fields_.rho_b_x, fields_.rho_b_y, fields_.rho_b_z, fields_.rho_a_p1_x, fields_.rho_a_p1_y, fields_.rho_a_p1_z, fields_.rho_b_p1_x, fields_.rho_b_p1_y, fields_.rho_b_p1_z, fields_.rho_a_p1, fields_.rho_b_p1, fields_.tau_a_p1, fields_.tau_b_p1};
    const Txc* x_[] = {xc_.vsigma_1, xc_.vsigma_2, xc_.v2rho2_1, xc_.v2rho2_2, xc_.v2rhosigma_1, xc_.v2rhosigma_2, xc_.v2rhosigma_3, xc_.v2rhosigma_4, xc_.v2rhosigma_5, xc_.v2rhotau_1, xc_.v2rhotau_2, xc_.v2rhotau_3, xc_.v2sigma2_1, xc_.v2sigma2_2, xc_.v2sigma2_3, xc_.v2sigma2_4, xc_.v2sigma2_5, xc_.v2sigmatau_1, xc_.v2sigmatau_2, xc_.v2sigmatau_3, xc_.v2sigmatau_4, xc_.v2sigmatau_5, xc_.v2tau2_1, xc_.v2tau2_2};
    return xck_mgga_tau_ub_o2_batch_t<T, Txc>(npts, nbf, nx, chi, f_, x_, out, work);
}

} // namespace xckernel
