/* generated by xckernel; do not edit. */
#pragma once
#include <cstdint>
#include <new>
#include "xckernel/evaluator.hpp"

namespace xckernel {
namespace detail_xck_mgga_tau_st_o2_m {
static constexpr double c0[] = {
    1.0,-1.0,1.0,-1.0,2.0,2.0,2.0,-2.0,-2.0,-2.0
};
static constexpr int32_t o0[] = {
    0,3,6,9,12,16,20,24,28,32,36
};
static constexpr uint16_t f0[] = {
    7,11,0,7,12,0,8,18,0,8,19,0,4,1,13,0,5,2,13,0,6,3,13,0,4,1,15,0,5,2,15,0,6,3,15,0
};
static constexpr double c1[] = {
    -1.0,1.0,-1.0,1.0,-1.0,2.0,2.0,2.0,-2.0,-2.0,-2.0,2.0,2.0,-2.0,2.0,-2.0,4.0,4.0,4.0,-4.0,-4.0,-4.0
};
static constexpr int32_t o1[] = {
    0,3,7,11,15,19,24,29,34,39,44,49,52,56,60,64,68,73,78,83,88,93,98
};
static constexpr uint16_t f1[] = {
    4,10,0,1,7,14,0,1,7,17,0,1,8,27,0,1,8,28,0,4,1,1,22,0,5,1,2,22,0,6,1,3,22,0,4,1,1,24,0,5,1,2,24,0,6,1,3,24,0,4,9,0,1,7,13,0,1,7,16,0,1,8,25,0,1,8,26,0,4,1,1,21,0,5,1,2,21,0,6,1,3,21,0,4,1,1,23,0,5,1,2,23,0,6,1,3,23,0
};
static constexpr double c2[] = {
    -1.0,1.0,-1.0,1.0,-1.0,2.0,2.0,2.0,-2.0,-2.0,-2.0,2.0,2.0,-2.0,2.0,-2.0,4.0,4.0,4.0,-4.0,-4.0,-4.0
};
static constexpr int32_t o2[] = {
    0,3,7,11,15,19,24,29,34,39,44,49,52,56,60,64,68,73,78,83,88,93,98
};
static constexpr uint16_t f2[] = {
    5,10,0,2,7,14,0,2,7,17,0,2,8,27,0,2,8,28,0,4,1,2,22,0,5,2,2,22,0,6,2,3,22,0,4,1,2,24,0,5,2,2,24,0,6,2,3,24,0,5,9,0,2,7,13,0,2,7,16,0,2,8,25,0,2,8,26,0,4,1,2,21,0,5,2,2,21,0,6,2,3,21,0,4,1,2,23,0,5,2,2,23,0,6,2,3,23,0
};
static constexpr double c3[] = {
    -1.0,1.0,-1.0,1.0,-1.0,2.0,2.0,2.0,-2.0,-2.0,-2.0,2.0,2.0,-2.0,2.0,-2.0,4.0,4.0,4.0,-4.0,-4.0,-4.0
};
static constexpr int32_t o3[] = {
    0,3,7,11,15,19,24,29,34,39,44,49,52,56,60,64,68,73,78,83,88,93,98
};
static constexpr uint16_t f3[] = {
    6,10,0,3,7,14,0,3,7,17,0,3,8,27,0,3,8,28,0,4,1,3,22,0,5,2,3,22,0,6,3,3,22,0,4,1,3,24,0,5,2,3,24,0,6,3,3,24,0,6,9,0,3,7,13,0,3,7,16,0,3,8,25,0,3,8,26,0,4,1,3,21,0,5,2,3,21,0,6,3,3,21,0,4,1,3,23,0,5,2,3,23,0,6,3,3,23,0
};
static constexpr double c4[] = {
    -1.0,1.0,-1.0,1.0,-1.0,2.0,2.0,2.0,-2.0,-2.0,-2.0,2.0,2.0,-2.0,2.0,-2.0,4.0,4.0,4.0,-4.0,-4.0,-4.0
};
static constexpr int32_t o4[] = {
    0,3,7,11,15,19,24,29,34,39,44,49,52,56,60,64,68,73,78,83,88,93,98
};
static constexpr uint16_t f4[] = {
    4,10,0,1,7,14,0,1,7,17,0,1,8,27,0,1,8,28,0,4,1,1,22,0,5,1,2,22,0,6,1,3,22,0,4,1,1,24,0,5,1,2,24,0,6,1,3,24,0,4,9,0,1,7,13,0,1,7,16,0,1,8,25,0,1,8,26,0,4,1,1,21,0,5,1,2,21,0,6,1,3,21,0,4,1,1,23,0,5,1,2,23,0,6,1,3,23,0
};
static constexpr double c5[] = {
    0.5,-0.5,0.5,-0.5,1.0,1.0,1.0,-1.0,-1.0,-1.0
};
static constexpr int32_t o5[] = {
    0,3,6,9,12,16,20,24,28,32,36
};
static constexpr uint16_t f5[] = {
    7,18,0,7,20,0,8,30,0,8,31,0,4,1,25,0,5,2,25,0,6,3,25,0,4,1,29,0,5,2,29,0,6,3,29,0
};
static constexpr double c6[] = {
    -1.0,1.0,-1.0,1.0,-1.0,2.0,2.0,2.0,-2.0,-2.0,-2.0,2.0,2.0,-2.0,2.0,-2.0,4.0,4.0,4.0,-4.0,-4.0,-4.0
};
static constexpr int32_t o6[] = {
    0,3,7,11,15,19,24,29,34,39,44,49,52,56,60,64,68,73,78,83,88,93,98
};
static constexpr uint16_t f6[] = {
    5,10,0,2,7,14,0,2,7,17,0,2,8,27,0,2,8,28,0,4,1,2,22,0,5,2,2,22,0,6,2,3,22,0,4,1,2,24,0,5,2,2,24,0,6,2,3,24,0,5,9,0,2,7,13,0,2,7,16,0,2,8,25,0,2,8,26,0,4,1,2,21,0,5,2,2,21,0,6,2,3,21,0,4,1,2,23,0,5,2,2,23,0,6,2,3,23,0
};
static constexpr double c7[] = {
    0.5,-0.5,0.5,-0.5,1.0,1.0,1.0,-1.0,-1.0,-1.0
};
static constexpr int32_t o7[] = {
    0,3,6,9,12,16,20,24,28,32,36
};
static constexpr uint16_t f7[] = {
    7,18,0,7,20,0,8,30,0,8,31,0,4,1,25,0,5,2,25,0,6,3,25,0,4,1,29,0,5,2,29,0,6,3,29,0
};
static constexpr double c8[] = {
    -1.0,1.0,-1.0,1.0,-1.0,2.0,2.0,2.0,-2.0,-2.0,-2.0,2.0,2.0,-2.0,2.0,-2.0,4.0,4.0,4.0,-4.0,-4.0,-4.0
};
static constexpr int32_t o8[] = {
    0,3,7,11,15,19,24,29,34,39,44,49,52,56,60,64,68,73,78,83,88,93,98
};
static constexpr uint16_t f8[] = {
    6,10,0,3,7,14,0,3,7,17,0,3,8,27,0,3,8,28,0,4,1,3,22,0,5,2,3,22,0,6,3,3,22,0,4,1,3,24,0,5,2,3,24,0,6,3,3,24,0,6,9,0,3,7,13,0,3,7,16,0,3,8,25,0,3,8,26,0,4,1,3,21,0,5,2,3,21,0,6,3,3,21,0,4,1,3,23,0,5,2,3,23,0,6,3,3,23,0
};
static constexpr double c9[] = {
    0.5,-0.5,0.5,-0.5,1.0,1.0,1.0,-1.0,-1.0,-1.0
};
static constexpr int32_t o9[] = {
    0,3,6,9,12,16,20,24,28,32,36
};
static constexpr uint16_t f9[] = {
    7,18,0,7,20,0,8,30,0,8,31,0,4,1,25,0,5,2,25,0,6,3,25,0,4,1,29,0,5,2,29,0,6,3,29,0
};
static constexpr int64_t NFLD = 9;
} // namespace detail_xck_mgga_tau_st_o2_m

/* fields: host-computed per-point operands (type T); xc: the
 * functional-derivative arrays (type Txc; Libxc computes in double
 * regardless of T). work: caller scratch of
 * xckernel::work_size(npts, nbf) elements or nullptr
 * (heap-allocated internally; pass a buffer in device code). */
template <typename T, typename Txc = T>
int xck_mgga_tau_st_o2_m_t(int64_t npts, int64_t nbf,
             const T* chi, const T* dchi, const T* lapl_chi,
             const T* hess_chi,
             const T* const* fields, const Txc* const* xc,
             T* out, T* work = nullptr) {
    const int64_t blk = npts < grid_block ? npts : grid_block;
    T* c = work;
    bool own = false;
    if (!c) {
        c = new (std::nothrow) T[work_size(npts, nbf)];
        own = true;
    }
    if (!c) return 1;
    T* W = c + blk;
    const T* Wc = W;
    for (int64_t g0 = 0; g0 < npts; g0 += blk) {
        const int64_t bk = npts - g0 < blk ? npts - g0 : blk;
        stage_a<T, Txc>(g0, bk, 10, detail_xck_mgga_tau_st_o2_m::c0, detail_xck_mgga_tau_st_o2_m::o0, detail_xck_mgga_tau_st_o2_m::f0, detail_xck_mgga_tau_st_o2_m::NFLD, fields, xc, c);
        accumulate<T>(bk, nbf, c, chi + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 22, detail_xck_mgga_tau_st_o2_m::c1, detail_xck_mgga_tau_st_o2_m::o1, detail_xck_mgga_tau_st_o2_m::f1, detail_xck_mgga_tau_st_o2_m::NFLD, fields, xc, c);
        accumulate<T>(bk, nbf, c, dchi + (int64_t)0*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 22, detail_xck_mgga_tau_st_o2_m::c2, detail_xck_mgga_tau_st_o2_m::o2, detail_xck_mgga_tau_st_o2_m::f2, detail_xck_mgga_tau_st_o2_m::NFLD, fields, xc, c);
        accumulate<T>(bk, nbf, c, dchi + (int64_t)1*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 22, detail_xck_mgga_tau_st_o2_m::c3, detail_xck_mgga_tau_st_o2_m::o3, detail_xck_mgga_tau_st_o2_m::f3, detail_xck_mgga_tau_st_o2_m::NFLD, fields, xc, c);
        accumulate<T>(bk, nbf, c, dchi + (int64_t)2*nbf*npts + g0, npts, W, 0);
        gemm_nt(nbf, bk, chi + g0, npts, Wc, bk, out);
        stage_a<T, Txc>(g0, bk, 22, detail_xck_mgga_tau_st_o2_m::c4, detail_xck_mgga_tau_st_o2_m::o4, detail_xck_mgga_tau_st_o2_m::f4, detail_xck_mgga_tau_st_o2_m::NFLD, fields, xc, c);
        accumulate<T>(bk, nbf, c, chi + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 10, detail_xck_mgga_tau_st_o2_m::c5, detail_xck_mgga_tau_st_o2_m::o5, detail_xck_mgga_tau_st_o2_m::f5, detail_xck_mgga_tau_st_o2_m::NFLD, fields, xc, c);
        accumulate<T>(bk, nbf, c, dchi + (int64_t)0*nbf*npts + g0, npts, W, 0);
        gemm_nt(nbf, bk, dchi + (int64_t)0*nbf*npts + g0, npts, Wc, bk, out);
        stage_a<T, Txc>(g0, bk, 22, detail_xck_mgga_tau_st_o2_m::c6, detail_xck_mgga_tau_st_o2_m::o6, detail_xck_mgga_tau_st_o2_m::f6, detail_xck_mgga_tau_st_o2_m::NFLD, fields, xc, c);
        accumulate<T>(bk, nbf, c, chi + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 10, detail_xck_mgga_tau_st_o2_m::c7, detail_xck_mgga_tau_st_o2_m::o7, detail_xck_mgga_tau_st_o2_m::f7, detail_xck_mgga_tau_st_o2_m::NFLD, fields, xc, c);
        accumulate<T>(bk, nbf, c, dchi + (int64_t)1*nbf*npts + g0, npts, W, 0);
        gemm_nt(nbf, bk, dchi + (int64_t)1*nbf*npts + g0, npts, Wc, bk, out);
        stage_a<T, Txc>(g0, bk, 22, detail_xck_mgga_tau_st_o2_m::c8, detail_xck_mgga_tau_st_o2_m::o8, detail_xck_mgga_tau_st_o2_m::f8, detail_xck_mgga_tau_st_o2_m::NFLD, fields, xc, c);
        accumulate<T>(bk, nbf, c, chi + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 10, detail_xck_mgga_tau_st_o2_m::c9, detail_xck_mgga_tau_st_o2_m::o9, detail_xck_mgga_tau_st_o2_m::f9, detail_xck_mgga_tau_st_o2_m::NFLD, fields, xc, c);
        accumulate<T>(bk, nbf, c, dchi + (int64_t)2*nbf*npts + g0, npts, W, 0);
        gemm_nt(nbf, bk, dchi + (int64_t)2*nbf*npts + g0, npts, Wc, bk, out);
    }
    if (own) delete[] c;
    return 0;
}

} // namespace xckernel
