/* generated by xckernel; do not edit. */
#pragma once
#include <cstdint>
#include <new>
#include "xckernel/evaluator.hpp"

namespace xckernel {
namespace detail_xck_cmgga_tau_st_o2_p_batch {
static constexpr double c0_8[] = {
    2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
};
static constexpr int32_t o0_8[] = {
    0,3,6,9,16,23,30,37,44,51,58,65,72
};
static constexpr uint16_t f0_8[] = {
    1,14,0,1,13,0,1,15,0,1,7,7,4,4,28,0,1,7,7,4,4,26,0,1,7,7,4,4,30,0,1,7,7,5,5,28,0,1,7,7,5,5,26,0,1,7,7,5,5,30,0,1,7,7,6,6,28,0,1,7,7,6,6,26,0,1,7,7,6,6,30,0
};
static constexpr double c0_9[] = {
    2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
};
static constexpr int32_t o0_9[] = {
    0,3,6,9,16,23,30,37,44,51,58,65,72
};
static constexpr uint16_t f0_9[] = {
    2,14,0,2,13,0,2,15,0,2,7,7,4,4,28,0,2,7,7,4,4,26,0,2,7,7,4,4,30,0,2,7,7,5,5,28,0,2,7,7,5,5,26,0,2,7,7,5,5,30,0,2,7,7,6,6,28,0,2,7,7,6,6,26,0,2,7,7,6,6,30,0
};
static constexpr double c0_10[] = {
    2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
};
static constexpr int32_t o0_10[] = {
    0,3,6,9,16,23,30,37,44,51,58,65,72
};
static constexpr uint16_t f0_10[] = {
    3,14,0,3,13,0,3,15,0,3,7,7,4,4,28,0,3,7,7,4,4,26,0,3,7,7,4,4,30,0,3,7,7,5,5,28,0,3,7,7,5,5,26,0,3,7,7,5,5,30,0,3,7,7,6,6,28,0,3,7,7,6,6,26,0,3,7,7,6,6,30,0
};
static constexpr double c0_11[] = {
    -1.0,-1.0,1.0,-0.5,-0.5,-0.5,-0.5,-0.5,-0.5
};
static constexpr int32_t o0_11[] = {
    0,4,8,13,21,29,37,45,53,61
};
static constexpr uint16_t f0_11[] = {
    7,4,18,0,7,4,19,0,7,7,4,10,0,7,7,7,4,4,4,31,0,7,7,7,4,4,4,32,0,7,7,7,4,5,5,31,0,7,7,7,4,5,5,32,0,7,7,7,4,6,6,31,0,7,7,7,4,6,6,32,0
};
static constexpr double c0_12[] = {
    -1.0,-1.0,-0.5,-0.5,1.0,-0.5,-0.5,-0.5,-0.5
};
static constexpr int32_t o0_12[] = {
    0,4,8,16,24,29,37,45,53,61
};
static constexpr uint16_t f0_12[] = {
    7,5,18,0,7,5,19,0,7,7,7,4,4,5,31,0,7,7,7,4,4,5,32,0,7,7,5,10,0,7,7,7,5,5,5,31,0,7,7,7,5,5,5,32,0,7,7,7,5,6,6,31,0,7,7,7,5,6,6,32,0
};
static constexpr double c0_13[] = {
    -1.0,-1.0,-0.5,-0.5,-0.5,-0.5,1.0,-0.5,-0.5
};
static constexpr int32_t o0_13[] = {
    0,4,8,16,24,32,40,45,53,61
};
static constexpr uint16_t f0_13[] = {
    7,6,18,0,7,6,19,0,7,7,7,4,4,6,31,0,7,7,7,4,4,6,32,0,7,7,7,5,5,6,31,0,7,7,7,5,5,6,32,0,7,7,6,10,0,7,7,7,6,6,6,31,0,7,7,7,6,6,6,32,0
};
static constexpr double c0_14[] = {
    1.0,1.0,1.0,1.0,1.0,0.5,0.5,0.5,-1.0,0.5,0.25,0.5,0.5,0.25,0.5,0.5,-1.0,0.5,0.25,0.5,0.25,0.5,-1.0,0.5,0.25,0.25
};
static constexpr int32_t o0_14[] = {
    0,2,4,10,16,22,28,34,40,47,53,63,73,83,93,103,113,120,126,136,146,156,166,173,179,189,199
};
static constexpr uint16_t f0_14[] = {
    11,0,12,0,7,7,4,4,18,0,7,7,5,5,18,0,7,7,6,6,18,0,7,7,4,4,19,0,7,7,5,5,19,0,7,7,6,6,19,0,7,7,7,4,4,10,0,7,7,4,4,20,0,7,7,7,7,4,4,4,4,31,0,7,7,7,7,4,4,5,5,31,0,7,7,7,7,4,4,6,6,31,0,7,7,7,7,4,4,4,4,32,0,7,7,7,7,4,4,5,5,32,0,7,7,7,7,4,4,6,6,32,0,7,7,7,5,5,10,0,7,7,5,5,20,0,7,7,7,7,5,5,5,5,31,0,7,7,7,7,5,5,6,6,31,0,7,7,7,7,5,5,5,5,32,0,7,7,7,7,5,5,6,6,32,0,7,7,7,6,6,10,0,7,7,6,6,20,0,7,7,7,7,6,6,6,6,31,0,7,7,7,7,6,6,6,6,32,0
};
static constexpr double c0_15[] = {
    1.0,1.0,0.5,0.5,0.5,0.5,0.5,0.5
};
static constexpr int32_t o0_15[] = {
    0,2,4,10,16,22,28,34,40
};
static constexpr uint16_t f0_15[] = {
    18,0,19,0,7,7,4,4,31,0,7,7,4,4,32,0,7,7,5,5,31,0,7,7,5,5,32,0,7,7,6,6,31,0,7,7,6,6,32,0
};
static constexpr double c1_8[] = {
    1.0,2.0,6.0,2.0,2.0,4.0,4.0,-1.0,-1.0,-1.0
};
static constexpr int32_t o1_8[] = {
    0,2,6,10,14,16,20,24,29,34,39
};
static constexpr uint16_t f1_8[] = {
    9,0,1,1,24,0,1,1,22,0,1,1,25,0,8,0,1,1,21,0,1,1,23,0,1,7,4,28,0,1,7,4,26,0,1,7,4,30,0
};
static constexpr double c1_9[] = {
    2.0,6.0,2.0,4.0,4.0,-1.0,-1.0,-1.0
};
static constexpr int32_t o1_9[] = {
    0,4,8,12,16,20,25,30,35
};
static constexpr uint16_t f1_9[] = {
    1,2,24,0,1,2,22,0,1,2,25,0,1,2,21,0,1,2,23,0,2,7,4,28,0,2,7,4,26,0,2,7,4,30,0
};
static constexpr double c1_10[] = {
    2.0,6.0,2.0,4.0,4.0,-1.0,-1.0,-1.0
};
static constexpr int32_t o1_10[] = {
    0,4,8,12,16,20,25,30,35
};
static constexpr uint16_t f1_10[] = {
    1,3,24,0,1,3,22,0,1,3,25,0,1,3,21,0,1,3,23,0,3,7,4,28,0,3,7,4,26,0,3,7,4,30,0
};
static constexpr double c1_11[] = {
    -1.0,-1.0,-2.0,-2.0,-0.5,0.5,0.5
};
static constexpr int32_t o1_11[] = {
    0,5,10,15,20,23,29,35
};
static constexpr uint16_t f1_11[] = {
    1,7,4,28,0,1,7,4,29,0,1,7,4,26,0,1,7,4,27,0,7,10,0,7,7,4,4,31,0,7,7,4,4,32,0
};
static constexpr double c1_12[] = {
    -1.0,-1.0,-2.0,-2.0,0.5,0.5
};
static constexpr int32_t o1_12[] = {
    0,5,10,15,20,26,32
};
static constexpr uint16_t f1_12[] = {
    1,7,5,28,0,1,7,5,29,0,1,7,5,26,0,1,7,5,27,0,7,7,4,5,31,0,7,7,4,5,32,0
};
static constexpr double c1_13[] = {
    -1.0,-1.0,-2.0,-2.0,0.5,0.5
};
static constexpr int32_t o1_13[] = {
    0,5,10,15,20,26,32
};
static constexpr uint16_t f1_13[] = {
    1,7,6,28,0,1,7,6,29,0,1,7,6,26,0,1,7,6,27,0,7,7,4,6,31,0,7,7,4,6,32,0
};
static constexpr double c1_14[] = {
    1.0,1.0,0.5,0.5,0.5,0.5,0.5,0.5,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5,-0.5,-0.5,-0.25,-0.25,-0.25,-0.25,-0.25,-0.25
};
static constexpr int32_t o1_14[] = {
    0,3,6,13,20,27,34,41,48,51,54,61,68,75,82,89,96,101,105,109,117,125,133,141,149,157
};
static constexpr uint16_t f1_14[] = {
    1,14,0,1,17,0,1,7,7,4,4,28,0,1,7,7,5,5,28,0,1,7,7,6,6,28,0,1,7,7,4,4,29,0,1,7,7,5,5,29,0,1,7,7,6,6,29,0,1,13,0,1,16,0,1,7,7,4,4,26,0,1,7,7,5,5,26,0,1,7,7,6,6,26,0,1,7,7,4,4,27,0,1,7,7,5,5,27,0,1,7,7,6,6,27,0,7,7,4,10,0,7,4,18,0,7,4,20,0,7,7,7,4,4,4,31,0,7,7,7,4,5,5,31,0,7,7,7,4,6,6,31,0,7,7,7,4,4,4,32,0,7,7,7,4,5,5,32,0,7,7,7,4,6,6,32,0
};
static constexpr double c1_15[] = {
    1.0,1.0,2.0,2.0,-0.5,-0.5
};
static constexpr int32_t o1_15[] = {
    0,3,6,9,12,16,20
};
static constexpr uint16_t f1_15[] = {
    1,28,0,1,29,0,1,26,0,1,27,0,7,4,31,0,7,4,32,0
};
static constexpr double c2_8[] = {
    2.0,6.0,2.0,4.0,4.0,-1.0,-1.0,-1.0
};
static constexpr int32_t o2_8[] = {
    0,4,8,12,16,20,25,30,35
};
static constexpr uint16_t f2_8[] = {
    1,2,24,0,1,2,22,0,1,2,25,0,1,2,21,0,1,2,23,0,1,7,5,28,0,1,7,5,26,0,1,7,5,30,0
};
static constexpr double c2_9[] = {
    1.0,2.0,6.0,2.0,2.0,4.0,4.0,-1.0,-1.0,-1.0
};
static constexpr int32_t o2_9[] = {
    0,2,6,10,14,16,20,24,29,34,39
};
static constexpr uint16_t f2_9[] = {
    9,0,2,2,24,0,2,2,22,0,2,2,25,0,8,0,2,2,21,0,2,2,23,0,2,7,5,28,0,2,7,5,26,0,2,7,5,30,0
};
static constexpr double c2_10[] = {
    2.0,6.0,2.0,4.0,4.0,-1.0,-1.0,-1.0
};
static constexpr int32_t o2_10[] = {
    0,4,8,12,16,20,25,30,35
};
static constexpr uint16_t f2_10[] = {
    2,3,24,0,2,3,22,0,2,3,25,0,2,3,21,0,2,3,23,0,3,7,5,28,0,3,7,5,26,0,3,7,5,30,0
};
static constexpr double c2_11[] = {
    -1.0,-1.0,-2.0,-2.0,0.5,0.5
};
static constexpr int32_t o2_11[] = {
    0,5,10,15,20,26,32
};
static constexpr uint16_t f2_11[] = {
    2,7,4,28,0,2,7,4,29,0,2,7,4,26,0,2,7,4,27,0,7,7,4,5,31,0,7,7,4,5,32,0
};
static constexpr double c2_12[] = {
    -1.0,-1.0,-2.0,-2.0,-0.5,0.5,0.5
};
static constexpr int32_t o2_12[] = {
    0,5,10,15,20,23,29,35
};
static constexpr uint16_t f2_12[] = {
    2,7,5,28,0,2,7,5,29,0,2,7,5,26,0,2,7,5,27,0,7,10,0,7,7,5,5,31,0,7,7,5,5,32,0
};
static constexpr double c2_13[] = {
    -1.0,-1.0,-2.0,-2.0,0.5,0.5
};
static constexpr int32_t o2_13[] = {
    0,5,10,15,20,26,32
};
static constexpr uint16_t f2_13[] = {
    2,7,6,28,0,2,7,6,29,0,2,7,6,26,0,2,7,6,27,0,7,7,5,6,31,0,7,7,5,6,32,0
};
static constexpr double c2_14[] = {
    1.0,1.0,0.5,0.5,0.5,0.5,0.5,0.5,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5,-0.5,-0.5,-0.25,-0.25,-0.25,-0.25,-0.25,-0.25
};
static constexpr int32_t o2_14[] = {
    0,3,6,13,20,27,34,41,48,51,54,61,68,75,82,89,96,101,105,109,117,125,133,141,149,157
};
static constexpr uint16_t f2_14[] = {
    2,14,0,2,17,0,2,7,7,4,4,28,0,2,7,7,5,5,28,0,2,7,7,6,6,28,0,2,7,7,4,4,29,0,2,7,7,5,5,29,0,2,7,7,6,6,29,0,2,13,0,2,16,0,2,7,7,4,4,26,0,2,7,7,5,5,26,0,2,7,7,6,6,26,0,2,7,7,4,4,27,0,2,7,7,5,5,27,0,2,7,7,6,6,27,0,7,7,5,10,0,7,5,18,0,7,5,20,0,7,7,7,4,4,5,31,0,7,7,7,5,5,5,31,0,7,7,7,5,6,6,31,0,7,7,7,4,4,5,32,0,7,7,7,5,5,5,32,0,7,7,7,5,6,6,32,0
};
static constexpr double c2_15[] = {
    1.0,1.0,2.0,2.0,-0.5,-0.5
};
static constexpr int32_t o2_15[] = {
    0,3,6,9,12,16,20
};
static constexpr uint16_t f2_15[] = {
    2,28,0,2,29,0,2,26,0,2,27,0,7,5,31,0,7,5,32,0
};
static constexpr double c3_8[] = {
    2.0,6.0,2.0,4.0,4.0,-1.0,-1.0,-1.0
};
static constexpr int32_t o3_8[] = {
    0,4,8,12,16,20,25,30,35
};
static constexpr uint16_t f3_8[] = {
    1,3,24,0,1,3,22,0,1,3,25,0,1,3,21,0,1,3,23,0,1,7,6,28,0,1,7,6,26,0,1,7,6,30,0
};
static constexpr double c3_9[] = {
    2.0,6.0,2.0,4.0,4.0,-1.0,-1.0,-1.0
};
static constexpr int32_t o3_9[] = {
    0,4,8,12,16,20,25,30,35
};
static constexpr uint16_t f3_9[] = {
    2,3,24,0,2,3,22,0,2,3,25,0,2,3,21,0,2,3,23,0,2,7,6,28,0,2,7,6,26,0,2,7,6,30,0
};
static constexpr double c3_10[] = {
    1.0,2.0,6.0,2.0,2.0,4.0,4.0,-1.0,-1.0,-1.0
};
static constexpr int32_t o3_10[] = {
    0,2,6,10,14,16,20,24,29,34,39
};
static constexpr uint16_t f3_10[] = {
    9,0,3,3,24,0,3,3,22,0,3,3,25,0,8,0,3,3,21,0,3,3,23,0,3,7,6,28,0,3,7,6,26,0,3,7,6,30,0
};
static constexpr double c3_11[] = {
    -1.0,-1.0,-2.0,-2.0,0.5,0.5
};
static constexpr int32_t o3_11[] = {
    0,5,10,15,20,26,32
};
static constexpr uint16_t f3_11[] = {
    3,7,4,28,0,3,7,4,29,0,3,7,4,26,0,3,7,4,27,0,7,7,4,6,31,0,7,7,4,6,32,0
};
static constexpr double c3_12[] = {
    -1.0,-1.0,-2.0,-2.0,0.5,0.5
};
static constexpr int32_t o3_12[] = {
    0,5,10,15,20,26,32
};
static constexpr uint16_t f3_12[] = {
    3,7,5,28,0,3,7,5,29,0,3,7,5,26,0,3,7,5,27,0,7,7,5,6,31,0,7,7,5,6,32,0
};
static constexpr double c3_13[] = {
    -1.0,-1.0,-2.0,-2.0,-0.5,0.5,0.5
};
static constexpr int32_t o3_13[] = {
    0,5,10,15,20,23,29,35
};
static constexpr uint16_t f3_13[] = {
    3,7,6,28,0,3,7,6,29,0,3,7,6,26,0,3,7,6,27,0,7,10,0,7,7,6,6,31,0,7,7,6,6,32,0
};
static constexpr double c3_14[] = {
    1.0,1.0,0.5,0.5,0.5,0.5,0.5,0.5,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5,-0.5,-0.5,-0.25,-0.25,-0.25,-0.25,-0.25,-0.25
};
static constexpr int32_t o3_14[] = {
    0,3,6,13,20,27,34,41,48,51,54,61,68,75,82,89,96,101,105,109,117,125,133,141,149,157
};
static constexpr uint16_t f3_14[] = {
    3,14,0,3,17,0,3,7,7,4,4,28,0,3,7,7,5,5,28,0,3,7,7,6,6,28,0,3,7,7,4,4,29,0,3,7,7,5,5,29,0,3,7,7,6,6,29,0,3,13,0,3,16,0,3,7,7,4,4,26,0,3,7,7,5,5,26,0,3,7,7,6,6,26,0,3,7,7,4,4,27,0,3,7,7,5,5,27,0,3,7,7,6,6,27,0,7,7,6,10,0,7,6,18,0,7,6,20,0,7,7,7,4,4,6,31,0,7,7,7,5,5,6,31,0,7,7,7,6,6,6,31,0,7,7,7,4,4,6,32,0,7,7,7,5,5,6,32,0,7,7,7,6,6,6,32,0
};
static constexpr double c3_15[] = {
    1.0,1.0,2.0,2.0,-0.5,-0.5
};
static constexpr int32_t o3_15[] = {
    0,3,6,9,12,16,20
};
static constexpr uint16_t f3_15[] = {
    3,28,0,3,29,0,3,26,0,3,27,0,7,6,31,0,7,6,32,0
};
static constexpr double c4_8[] = {
    1.0,2.0,6.0,2.0,2.0,4.0,4.0,1.0,1.0,1.0
};
static constexpr int32_t o4_8[] = {
    0,2,6,10,14,16,20,24,29,34,39
};
static constexpr uint16_t f4_8[] = {
    9,0,1,1,24,0,1,1,22,0,1,1,25,0,8,0,1,1,21,0,1,1,23,0,1,7,4,28,0,1,7,4,26,0,1,7,4,30,0
};
static constexpr double c4_9[] = {
    2.0,6.0,2.0,4.0,4.0,1.0,1.0,1.0
};
static constexpr int32_t o4_9[] = {
    0,4,8,12,16,20,25,30,35
};
static constexpr uint16_t f4_9[] = {
    1,2,24,0,1,2,22,0,1,2,25,0,1,2,21,0,1,2,23,0,2,7,4,28,0,2,7,4,26,0,2,7,4,30,0
};
static constexpr double c4_10[] = {
    2.0,6.0,2.0,4.0,4.0,1.0,1.0,1.0
};
static constexpr int32_t o4_10[] = {
    0,4,8,12,16,20,25,30,35
};
static constexpr uint16_t f4_10[] = {
    1,3,24,0,1,3,22,0,1,3,25,0,1,3,21,0,1,3,23,0,3,7,4,28,0,3,7,4,26,0,3,7,4,30,0
};
static constexpr double c4_11[] = {
    -1.0,-1.0,-2.0,-2.0,0.5,-0.5,-0.5
};
static constexpr int32_t o4_11[] = {
    0,5,10,15,20,23,29,35
};
static constexpr uint16_t f4_11[] = {
    1,7,4,28,0,1,7,4,29,0,1,7,4,26,0,1,7,4,27,0,7,10,0,7,7,4,4,31,0,7,7,4,4,32,0
};
static constexpr double c4_12[] = {
    -1.0,-1.0,-2.0,-2.0,-0.5,-0.5
};
static constexpr int32_t o4_12[] = {
    0,5,10,15,20,26,32
};
static constexpr uint16_t f4_12[] = {
    1,7,5,28,0,1,7,5,29,0,1,7,5,26,0,1,7,5,27,0,7,7,4,5,31,0,7,7,4,5,32,0
};
static constexpr double c4_13[] = {
    -1.0,-1.0,-2.0,-2.0,-0.5,-0.5
};
static constexpr int32_t o4_13[] = {
    0,5,10,15,20,26,32
};
static constexpr uint16_t f4_13[] = {
    1,7,6,28,0,1,7,6,29,0,1,7,6,26,0,1,7,6,27,0,7,7,4,6,31,0,7,7,4,6,32,0
};
static constexpr double c4_14[] = {
    1.0,1.0,0.5,0.5,0.5,0.5,0.5,0.5,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,-0.5,0.5,0.5,0.25,0.25,0.25,0.25,0.25,0.25
};
static constexpr int32_t o4_14[] = {
    0,3,6,13,20,27,34,41,48,51,54,61,68,75,82,89,96,101,105,109,117,125,133,141,149,157
};
static constexpr uint16_t f4_14[] = {
    1,14,0,1,17,0,1,7,7,4,4,28,0,1,7,7,5,5,28,0,1,7,7,6,6,28,0,1,7,7,4,4,29,0,1,7,7,5,5,29,0,1,7,7,6,6,29,0,1,13,0,1,16,0,1,7,7,4,4,26,0,1,7,7,5,5,26,0,1,7,7,6,6,26,0,1,7,7,4,4,27,0,1,7,7,5,5,27,0,1,7,7,6,6,27,0,7,7,4,10,0,7,4,18,0,7,4,20,0,7,7,7,4,4,4,31,0,7,7,7,4,5,5,31,0,7,7,7,4,6,6,31,0,7,7,7,4,4,4,32,0,7,7,7,4,5,5,32,0,7,7,7,4,6,6,32,0
};
static constexpr double c4_15[] = {
    1.0,1.0,2.0,2.0,0.5,0.5
};
static constexpr int32_t o4_15[] = {
    0,3,6,9,12,16,20
};
static constexpr uint16_t f4_15[] = {
    1,28,0,1,29,0,1,26,0,1,27,0,7,4,31,0,7,4,32,0
};
static constexpr double c5_8[] = {
    1.0,1.0,1.0
};
static constexpr int32_t o5_8[] = {
    0,3,6,9
};
static constexpr uint16_t f5_8[] = {
    1,28,0,1,26,0,1,30,0
};
static constexpr double c5_9[] = {
    1.0,1.0,1.0
};
static constexpr int32_t o5_9[] = {
    0,3,6,9
};
static constexpr uint16_t f5_9[] = {
    2,28,0,2,26,0,2,30,0
};
static constexpr double c5_10[] = {
    1.0,1.0,1.0
};
static constexpr int32_t o5_10[] = {
    0,3,6,9
};
static constexpr uint16_t f5_10[] = {
    3,28,0,3,26,0,3,30,0
};
static constexpr double c5_11[] = {
    -0.5,-0.5
};
static constexpr int32_t o5_11[] = {
    0,4,8
};
static constexpr uint16_t f5_11[] = {
    7,4,31,0,7,4,32,0
};
static constexpr double c5_12[] = {
    -0.5,-0.5
};
static constexpr int32_t o5_12[] = {
    0,4,8
};
static constexpr uint16_t f5_12[] = {
    7,5,31,0,7,5,32,0
};
static constexpr double c5_13[] = {
    -0.5,-0.5
};
static constexpr int32_t o5_13[] = {
    0,4,8
};
static constexpr uint16_t f5_13[] = {
    7,6,31,0,7,6,32,0
};
static constexpr double c5_14[] = {
    0.5,0.5,0.25,0.25,0.25,0.25,0.25,0.25
};
static constexpr int32_t o5_14[] = {
    0,2,4,10,16,22,28,34,40
};
static constexpr uint16_t f5_14[] = {
    18,0,20,0,7,7,4,4,31,0,7,7,5,5,31,0,7,7,6,6,31,0,7,7,4,4,32,0,7,7,5,5,32,0,7,7,6,6,32,0
};
static constexpr double c5_15[] = {
    0.5,0.5
};
static constexpr int32_t o5_15[] = {
    0,2,4
};
static constexpr uint16_t f5_15[] = {
    31,0,32,0
};
static constexpr double c6_8[] = {
    2.0,6.0,2.0,4.0,4.0,1.0,1.0,1.0
};
static constexpr int32_t o6_8[] = {
    0,4,8,12,16,20,25,30,35
};
static constexpr uint16_t f6_8[] = {
    1,2,24,0,1,2,22,0,1,2,25,0,1,2,21,0,1,2,23,0,1,7,5,28,0,1,7,5,26,0,1,7,5,30,0
};
static constexpr double c6_9[] = {
    1.0,2.0,6.0,2.0,2.0,4.0,4.0,1.0,1.0,1.0
};
static constexpr int32_t o6_9[] = {
    0,2,6,10,14,16,20,24,29,34,39
};
static constexpr uint16_t f6_9[] = {
    9,0,2,2,24,0,2,2,22,0,2,2,25,0,8,0,2,2,21,0,2,2,23,0,2,7,5,28,0,2,7,5,26,0,2,7,5,30,0
};
static constexpr double c6_10[] = {
    2.0,6.0,2.0,4.0,4.0,1.0,1.0,1.0
};
static constexpr int32_t o6_10[] = {
    0,4,8,12,16,20,25,30,35
};
static constexpr uint16_t f6_10[] = {
    2,3,24,0,2,3,22,0,2,3,25,0,2,3,21,0,2,3,23,0,3,7,5,28,0,3,7,5,26,0,3,7,5,30,0
};
static constexpr double c6_11[] = {
    -1.0,-1.0,-2.0,-2.0,-0.5,-0.5
};
static constexpr int32_t o6_11[] = {
    0,5,10,15,20,26,32
};
static constexpr uint16_t f6_11[] = {
    2,7,4,28,0,2,7,4,29,0,2,7,4,26,0,2,7,4,27,0,7,7,4,5,31,0,7,7,4,5,32,0
};
static constexpr double c6_12[] = {
    -1.0,-1.0,-2.0,-2.0,0.5,-0.5,-0.5
};
static constexpr int32_t o6_12[] = {
    0,5,10,15,20,23,29,35
};
static constexpr uint16_t f6_12[] = {
    2,7,5,28,0,2,7,5,29,0,2,7,5,26,0,2,7,5,27,0,7,10,0,7,7,5,5,31,0,7,7,5,5,32,0
};
static constexpr double c6_13[] = {
    -1.0,-1.0,-2.0,-2.0,-0.5,-0.5
};
static constexpr int32_t o6_13[] = {
    0,5,10,15,20,26,32
};
static constexpr uint16_t f6_13[] = {
    2,7,6,28,0,2,7,6,29,0,2,7,6,26,0,2,7,6,27,0,7,7,5,6,31,0,7,7,5,6,32,0
};
static constexpr double c6_14[] = {
    1.0,1.0,0.5,0.5,0.5,0.5,0.5,0.5,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,-0.5,0.5,0.5,0.25,0.25,0.25,0.25,0.25,0.25
};
static constexpr int32_t o6_14[] = {
    0,3,6,13,20,27,34,41,48,51,54,61,68,75,82,89,96,101,105,109,117,125,133,141,149,157
};
static constexpr uint16_t f6_14[] = {
    2,14,0,2,17,0,2,7,7,4,4,28,0,2,7,7,5,5,28,0,2,7,7,6,6,28,0,2,7,7,4,4,29,0,2,7,7,5,5,29,0,2,7,7,6,6,29,0,2,13,0,2,16,0,2,7,7,4,4,26,0,2,7,7,5,5,26,0,2,7,7,6,6,26,0,2,7,7,4,4,27,0,2,7,7,5,5,27,0,2,7,7,6,6,27,0,7,7,5,10,0,7,5,18,0,7,5,20,0,7,7,7,4,4,5,31,0,7,7,7,5,5,5,31,0,7,7,7,5,6,6,31,0,7,7,7,4,4,5,32,0,7,7,7,5,5,5,32,0,7,7,7,5,6,6,32,0
};
static constexpr double c6_15[] = {
    1.0,1.0,2.0,2.0,0.5,0.5
};
static constexpr int32_t o6_15[] = {
    0,3,6,9,12,16,20
};
static constexpr uint16_t f6_15[] = {
    2,28,0,2,29,0,2,26,0,2,27,0,7,5,31,0,7,5,32,0
};
static constexpr double c7_8[] = {
    1.0,1.0,1.0
};
static constexpr int32_t o7_8[] = {
    0,3,6,9
};
static constexpr uint16_t f7_8[] = {
    1,28,0,1,26,0,1,30,0
};
static constexpr double c7_9[] = {
    1.0,1.0,1.0
};
static constexpr int32_t o7_9[] = {
    0,3,6,9
};
static constexpr uint16_t f7_9[] = {
    2,28,0,2,26,0,2,30,0
};
static constexpr double c7_10[] = {
    1.0,1.0,1.0
};
static constexpr int32_t o7_10[] = {
    0,3,6,9
};
static constexpr uint16_t f7_10[] = {
    3,28,0,3,26,0,3,30,0
};
static constexpr double c7_11[] = {
    -0.5,-0.5
};
static constexpr int32_t o7_11[] = {
    0,4,8
};
static constexpr uint16_t f7_11[] = {
    7,4,31,0,7,4,32,0
};
static constexpr double c7_12[] = {
    -0.5,-0.5
};
static constexpr int32_t o7_12[] = {
    0,4,8
};
static constexpr uint16_t f7_12[] = {
    7,5,31,0,7,5,32,0
};
static constexpr double c7_13[] = {
    -0.5,-0.5
};
static constexpr int32_t o7_13[] = {
    0,4,8
};
static constexpr uint16_t f7_13[] = {
    7,6,31,0,7,6,32,0
};
static constexpr double c7_14[] = {
    0.5,0.5,0.25,0.25,0.25,0.25,0.25,0.25
};
static constexpr int32_t o7_14[] = {
    0,2,4,10,16,22,28,34,40
};
static constexpr uint16_t f7_14[] = {
    18,0,20,0,7,7,4,4,31,0,7,7,5,5,31,0,7,7,6,6,31,0,7,7,4,4,32,0,7,7,5,5,32,0,7,7,6,6,32,0
};
static constexpr double c7_15[] = {
    0.5,0.5
};
static constexpr int32_t o7_15[] = {
    0,2,4
};
static constexpr uint16_t f7_15[] = {
    31,0,32,0
};
static constexpr double c8_8[] = {
    2.0,6.0,2.0,4.0,4.0,1.0,1.0,1.0
};
static constexpr int32_t o8_8[] = {
    0,4,8,12,16,20,25,30,35
};
static constexpr uint16_t f8_8[] = {
    1,3,24,0,1,3,22,0,1,3,25,0,1,3,21,0,1,3,23,0,1,7,6,28,0,1,7,6,26,0,1,7,6,30,0
};
static constexpr double c8_9[] = {
    2.0,6.0,2.0,4.0,4.0,1.0,1.0,1.0
};
static constexpr int32_t o8_9[] = {
    0,4,8,12,16,20,25,30,35
};
static constexpr uint16_t f8_9[] = {
    2,3,24,0,2,3,22,0,2,3,25,0,2,3,21,0,2,3,23,0,2,7,6,28,0,2,7,6,26,0,2,7,6,30,0
};
static constexpr double c8_10[] = {
    1.0,2.0,6.0,2.0,2.0,4.0,4.0,1.0,1.0,1.0
};
static constexpr int32_t o8_10[] = {
    0,2,6,10,14,16,20,24,29,34,39
};
static constexpr uint16_t f8_10[] = {
    9,0,3,3,24,0,3,3,22,0,3,3,25,0,8,0,3,3,21,0,3,3,23,0,3,7,6,28,0,3,7,6,26,0,3,7,6,30,0
};
static constexpr double c8_11[] = {
    -1.0,-1.0,-2.0,-2.0,-0.5,-0.5
};
static constexpr int32_t o8_11[] = {
    0,5,10,15,20,26,32
};
static constexpr uint16_t f8_11[] = {
    3,7,4,28,0,3,7,4,29,0,3,7,4,26,0,3,7,4,27,0,7,7,4,6,31,0,7,7,4,6,32,0
};
static constexpr double c8_12[] = {
    -1.0,-1.0,-2.0,-2.0,-0.5,-0.5
};
static constexpr int32_t o8_12[] = {
    0,5,10,15,20,26,32
};
static constexpr uint16_t f8_12[] = {
    3,7,5,28,0,3,7,5,29,0,3,7,5,26,0,3,7,5,27,0,7,7,5,6,31,0,7,7,5,6,32,0
};
static constexpr double c8_13[] = {
    -1.0,-1.0,-2.0,-2.0,0.5,-0.5,-0.5
};
static constexpr int32_t o8_13[] = {
    0,5,10,15,20,23,29,35
};
static constexpr uint16_t f8_13[] = {
    3,7,6,28,0,3,7,6,29,0,3,7,6,26,0,3,7,6,27,0,7,10,0,7,7,6,6,31,0,7,7,6,6,32,0
};
static constexpr double c8_14[] = {
    1.0,1.0,0.5,0.5,0.5,0.5,0.5,0.5,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,-0.5,0.5,0.5,0.25,0.25,0.25,0.25,0.25,0.25
};
static constexpr int32_t o8_14[] = {
    0,3,6,13,20,27,34,41,48,51,54,61,68,75,82,89,96,101,105,109,117,125,133,141,149,157
};
static constexpr uint16_t f8_14[] = {
    3,14,0,3,17,0,3,7,7,4,4,28,0,3,7,7,5,5,28,0,3,7,7,6,6,28,0,3,7,7,4,4,29,0,3,7,7,5,5,29,0,3,7,7,6,6,29,0,3,13,0,3,16,0,3,7,7,4,4,26,0,3,7,7,5,5,26,0,3,7,7,6,6,26,0,3,7,7,4,4,27,0,3,7,7,5,5,27,0,3,7,7,6,6,27,0,7,7,6,10,0,7,6,18,0,7,6,20,0,7,7,7,4,4,6,31,0,7,7,7,5,5,6,31,0,7,7,7,6,6,6,31,0,7,7,7,4,4,6,32,0,7,7,7,5,5,6,32,0,7,7,7,6,6,6,32,0
};
static constexpr double c8_15[] = {
    1.0,1.0,2.0,2.0,0.5,0.5
};
static constexpr int32_t o8_15[] = {
    0,3,6,9,12,16,20
};
static constexpr uint16_t f8_15[] = {
    3,28,0,3,29,0,3,26,0,3,27,0,7,6,31,0,7,6,32,0
};
static constexpr double c9_8[] = {
    1.0,1.0,1.0
};
static constexpr int32_t o9_8[] = {
    0,3,6,9
};
static constexpr uint16_t f9_8[] = {
    1,28,0,1,26,0,1,30,0
};
static constexpr double c9_9[] = {
    1.0,1.0,1.0
};
static constexpr int32_t o9_9[] = {
    0,3,6,9
};
static constexpr uint16_t f9_9[] = {
    2,28,0,2,26,0,2,30,0
};
static constexpr double c9_10[] = {
    1.0,1.0,1.0
};
static constexpr int32_t o9_10[] = {
    0,3,6,9
};
static constexpr uint16_t f9_10[] = {
    3,28,0,3,26,0,3,30,0
};
static constexpr double c9_11[] = {
    -0.5,-0.5
};
static constexpr int32_t o9_11[] = {
    0,4,8
};
static constexpr uint16_t f9_11[] = {
    7,4,31,0,7,4,32,0
};
static constexpr double c9_12[] = {
    -0.5,-0.5
};
static constexpr int32_t o9_12[] = {
    0,4,8
};
static constexpr uint16_t f9_12[] = {
    7,5,31,0,7,5,32,0
};
static constexpr double c9_13[] = {
    -0.5,-0.5
};
static constexpr int32_t o9_13[] = {
    0,4,8
};
static constexpr uint16_t f9_13[] = {
    7,6,31,0,7,6,32,0
};
static constexpr double c9_14[] = {
    0.5,0.5,0.25,0.25,0.25,0.25,0.25,0.25
};
static constexpr int32_t o9_14[] = {
    0,2,4,10,16,22,28,34,40
};
static constexpr uint16_t f9_14[] = {
    18,0,20,0,7,7,4,4,31,0,7,7,5,5,31,0,7,7,6,6,31,0,7,7,4,4,32,0,7,7,5,5,32,0,7,7,6,6,32,0
};
static constexpr double c9_15[] = {
    0.5,0.5
};
static constexpr int32_t o9_15[] = {
    0,2,4
};
static constexpr uint16_t f9_15[] = {
    31,0,32,0
};
static constexpr int64_t NFLD = 8;
} // namespace detail_xck_cmgga_tau_st_o2_p_batch

/* Scratch (elements of T) the kernel needs for nx perturbations. */
inline int64_t xck_cmgga_tau_st_o2_p_batch_work(int64_t npts, int64_t nbf, int64_t nx) {
    const int64_t blk = npts < grid_block ? npts : grid_block;
    const int64_t nxc = nx < 8 ? nx : 8;
    return blk * (81 + nbf * (nxc + 0)) + 0 * npts + 1;
}

/* fields: the per-point tower operands in the order of
 * xck_cmgga_tau_st_o2_p_batch_field_names, perturbed ones (_p1) (nx, npts); xc in
 * the order of xck_cmgga_tau_st_o2_p_batch_xc_names (both below). */
template <typename T, typename Txc = T>
int xck_cmgga_tau_st_o2_p_batch_t(int64_t npts, int64_t nbf, int64_t nx,
        const T* chi, const T* const* fields,
        const Txc* const* xc, T* out, T* work = nullptr) {
    const int64_t blk = npts < grid_block ? npts : grid_block;
    const int64_t nxc = nx < 8 ? nx : 8;
    T* c = work;
    bool own = false;
    if (!c) {
        c = new (std::nothrow) T[xck_cmgga_tau_st_o2_p_batch_work(npts, nbf, nx)];
        own = true;
    }
    if (!c) return 1;
    T* A = c + blk;
    T* W = A + (int64_t)80*blk;
    T* Sb = c + blk * (81 + nbf * (nxc + 0));
    const T* fi[8] = {fields[0], fields[1], fields[2], fields[3], fields[4], fields[5], fields[6], fields[7]};
    for (int64_t g0 = 0; g0 < npts; g0 += blk) {
        const int64_t bk = npts - g0 < blk ? npts - g0 : blk;
        stage_a<T, Txc>(g0, bk, 12, detail_xck_cmgga_tau_st_o2_p_batch::c0_8, detail_xck_cmgga_tau_st_o2_p_batch::o0_8, detail_xck_cmgga_tau_st_o2_p_batch::f0_8, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)0*blk);
        stage_a<T, Txc>(g0, bk, 12, detail_xck_cmgga_tau_st_o2_p_batch::c0_9, detail_xck_cmgga_tau_st_o2_p_batch::o0_9, detail_xck_cmgga_tau_st_o2_p_batch::f0_9, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)1*blk);
        stage_a<T, Txc>(g0, bk, 12, detail_xck_cmgga_tau_st_o2_p_batch::c0_10, detail_xck_cmgga_tau_st_o2_p_batch::o0_10, detail_xck_cmgga_tau_st_o2_p_batch::f0_10, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)2*blk);
        stage_a<T, Txc>(g0, bk, 9, detail_xck_cmgga_tau_st_o2_p_batch::c0_11, detail_xck_cmgga_tau_st_o2_p_batch::o0_11, detail_xck_cmgga_tau_st_o2_p_batch::f0_11, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)3*blk);
        stage_a<T, Txc>(g0, bk, 9, detail_xck_cmgga_tau_st_o2_p_batch::c0_12, detail_xck_cmgga_tau_st_o2_p_batch::o0_12, detail_xck_cmgga_tau_st_o2_p_batch::f0_12, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)4*blk);
        stage_a<T, Txc>(g0, bk, 9, detail_xck_cmgga_tau_st_o2_p_batch::c0_13, detail_xck_cmgga_tau_st_o2_p_batch::o0_13, detail_xck_cmgga_tau_st_o2_p_batch::f0_13, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)5*blk);
        stage_a<T, Txc>(g0, bk, 26, detail_xck_cmgga_tau_st_o2_p_batch::c0_14, detail_xck_cmgga_tau_st_o2_p_batch::o0_14, detail_xck_cmgga_tau_st_o2_p_batch::f0_14, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)6*blk);
        stage_a<T, Txc>(g0, bk, 8, detail_xck_cmgga_tau_st_o2_p_batch::c0_15, detail_xck_cmgga_tau_st_o2_p_batch::o0_15, detail_xck_cmgga_tau_st_o2_p_batch::f0_15, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)7*blk);
        stage_a<T, Txc>(g0, bk, 10, detail_xck_cmgga_tau_st_o2_p_batch::c1_8, detail_xck_cmgga_tau_st_o2_p_batch::o1_8, detail_xck_cmgga_tau_st_o2_p_batch::f1_8, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)8*blk);
        stage_a<T, Txc>(g0, bk, 8, detail_xck_cmgga_tau_st_o2_p_batch::c1_9, detail_xck_cmgga_tau_st_o2_p_batch::o1_9, detail_xck_cmgga_tau_st_o2_p_batch::f1_9, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)9*blk);
        stage_a<T, Txc>(g0, bk, 8, detail_xck_cmgga_tau_st_o2_p_batch::c1_10, detail_xck_cmgga_tau_st_o2_p_batch::o1_10, detail_xck_cmgga_tau_st_o2_p_batch::f1_10, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)10*blk);
        stage_a<T, Txc>(g0, bk, 7, detail_xck_cmgga_tau_st_o2_p_batch::c1_11, detail_xck_cmgga_tau_st_o2_p_batch::o1_11, detail_xck_cmgga_tau_st_o2_p_batch::f1_11, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)11*blk);
        stage_a<T, Txc>(g0, bk, 6, detail_xck_cmgga_tau_st_o2_p_batch::c1_12, detail_xck_cmgga_tau_st_o2_p_batch::o1_12, detail_xck_cmgga_tau_st_o2_p_batch::f1_12, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)12*blk);
        stage_a<T, Txc>(g0, bk, 6, detail_xck_cmgga_tau_st_o2_p_batch::c1_13, detail_xck_cmgga_tau_st_o2_p_batch::o1_13, detail_xck_cmgga_tau_st_o2_p_batch::f1_13, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)13*blk);
        stage_a<T, Txc>(g0, bk, 25, detail_xck_cmgga_tau_st_o2_p_batch::c1_14, detail_xck_cmgga_tau_st_o2_p_batch::o1_14, detail_xck_cmgga_tau_st_o2_p_batch::f1_14, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)14*blk);
        stage_a<T, Txc>(g0, bk, 6, detail_xck_cmgga_tau_st_o2_p_batch::c1_15, detail_xck_cmgga_tau_st_o2_p_batch::o1_15, detail_xck_cmgga_tau_st_o2_p_batch::f1_15, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)15*blk);
        stage_a<T, Txc>(g0, bk, 8, detail_xck_cmgga_tau_st_o2_p_batch::c2_8, detail_xck_cmgga_tau_st_o2_p_batch::o2_8, detail_xck_cmgga_tau_st_o2_p_batch::f2_8, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)16*blk);
        stage_a<T, Txc>(g0, bk, 10, detail_xck_cmgga_tau_st_o2_p_batch::c2_9, detail_xck_cmgga_tau_st_o2_p_batch::o2_9, detail_xck_cmgga_tau_st_o2_p_batch::f2_9, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)17*blk);
        stage_a<T, Txc>(g0, bk, 8, detail_xck_cmgga_tau_st_o2_p_batch::c2_10, detail_xck_cmgga_tau_st_o2_p_batch::o2_10, detail_xck_cmgga_tau_st_o2_p_batch::f2_10, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)18*blk);
        stage_a<T, Txc>(g0, bk, 6, detail_xck_cmgga_tau_st_o2_p_batch::c2_11, detail_xck_cmgga_tau_st_o2_p_batch::o2_11, detail_xck_cmgga_tau_st_o2_p_batch::f2_11, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)19*blk);
        stage_a<T, Txc>(g0, bk, 7, detail_xck_cmgga_tau_st_o2_p_batch::c2_12, detail_xck_cmgga_tau_st_o2_p_batch::o2_12, detail_xck_cmgga_tau_st_o2_p_batch::f2_12, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)20*blk);
        stage_a<T, Txc>(g0, bk, 6, detail_xck_cmgga_tau_st_o2_p_batch::c2_13, detail_xck_cmgga_tau_st_o2_p_batch::o2_13, detail_xck_cmgga_tau_st_o2_p_batch::f2_13, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)21*blk);
        stage_a<T, Txc>(g0, bk, 25, detail_xck_cmgga_tau_st_o2_p_batch::c2_14, detail_xck_cmgga_tau_st_o2_p_batch::o2_14, detail_xck_cmgga_tau_st_o2_p_batch::f2_14, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)22*blk);
        stage_a<T, Txc>(g0, bk, 6, detail_xck_cmgga_tau_st_o2_p_batch::c2_15, detail_xck_cmgga_tau_st_o2_p_batch::o2_15, detail_xck_cmgga_tau_st_o2_p_batch::f2_15, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)23*blk);
        stage_a<T, Txc>(g0, bk, 8, detail_xck_cmgga_tau_st_o2_p_batch::c3_8, detail_xck_cmgga_tau_st_o2_p_batch::o3_8, detail_xck_cmgga_tau_st_o2_p_batch::f3_8, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)24*blk);
        stage_a<T, Txc>(g0, bk, 8, detail_xck_cmgga_tau_st_o2_p_batch::c3_9, detail_xck_cmgga_tau_st_o2_p_batch::o3_9, detail_xck_cmgga_tau_st_o2_p_batch::f3_9, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)25*blk);
        stage_a<T, Txc>(g0, bk, 10, detail_xck_cmgga_tau_st_o2_p_batch::c3_10, detail_xck_cmgga_tau_st_o2_p_batch::o3_10, detail_xck_cmgga_tau_st_o2_p_batch::f3_10, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)26*blk);
        stage_a<T, Txc>(g0, bk, 6, detail_xck_cmgga_tau_st_o2_p_batch::c3_11, detail_xck_cmgga_tau_st_o2_p_batch::o3_11, detail_xck_cmgga_tau_st_o2_p_batch::f3_11, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)27*blk);
        stage_a<T, Txc>(g0, bk, 6, detail_xck_cmgga_tau_st_o2_p_batch::c3_12, detail_xck_cmgga_tau_st_o2_p_batch::o3_12, detail_xck_cmgga_tau_st_o2_p_batch::f3_12, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)28*blk);
        stage_a<T, Txc>(g0, bk, 7, detail_xck_cmgga_tau_st_o2_p_batch::c3_13, detail_xck_cmgga_tau_st_o2_p_batch::o3_13, detail_xck_cmgga_tau_st_o2_p_batch::f3_13, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)29*blk);
        stage_a<T, Txc>(g0, bk, 25, detail_xck_cmgga_tau_st_o2_p_batch::c3_14, detail_xck_cmgga_tau_st_o2_p_batch::o3_14, detail_xck_cmgga_tau_st_o2_p_batch::f3_14, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)30*blk);
        stage_a<T, Txc>(g0, bk, 6, detail_xck_cmgga_tau_st_o2_p_batch::c3_15, detail_xck_cmgga_tau_st_o2_p_batch::o3_15, detail_xck_cmgga_tau_st_o2_p_batch::f3_15, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)31*blk);
        stage_a<T, Txc>(g0, bk, 10, detail_xck_cmgga_tau_st_o2_p_batch::c4_8, detail_xck_cmgga_tau_st_o2_p_batch::o4_8, detail_xck_cmgga_tau_st_o2_p_batch::f4_8, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)32*blk);
        stage_a<T, Txc>(g0, bk, 8, detail_xck_cmgga_tau_st_o2_p_batch::c4_9, detail_xck_cmgga_tau_st_o2_p_batch::o4_9, detail_xck_cmgga_tau_st_o2_p_batch::f4_9, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)33*blk);
        stage_a<T, Txc>(g0, bk, 8, detail_xck_cmgga_tau_st_o2_p_batch::c4_10, detail_xck_cmgga_tau_st_o2_p_batch::o4_10, detail_xck_cmgga_tau_st_o2_p_batch::f4_10, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)34*blk);
        stage_a<T, Txc>(g0, bk, 7, detail_xck_cmgga_tau_st_o2_p_batch::c4_11, detail_xck_cmgga_tau_st_o2_p_batch::o4_11, detail_xck_cmgga_tau_st_o2_p_batch::f4_11, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)35*blk);
        stage_a<T, Txc>(g0, bk, 6, detail_xck_cmgga_tau_st_o2_p_batch::c4_12, detail_xck_cmgga_tau_st_o2_p_batch::o4_12, detail_xck_cmgga_tau_st_o2_p_batch::f4_12, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)36*blk);
        stage_a<T, Txc>(g0, bk, 6, detail_xck_cmgga_tau_st_o2_p_batch::c4_13, detail_xck_cmgga_tau_st_o2_p_batch::o4_13, detail_xck_cmgga_tau_st_o2_p_batch::f4_13, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)37*blk);
        stage_a<T, Txc>(g0, bk, 25, detail_xck_cmgga_tau_st_o2_p_batch::c4_14, detail_xck_cmgga_tau_st_o2_p_batch::o4_14, detail_xck_cmgga_tau_st_o2_p_batch::f4_14, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)38*blk);
        stage_a<T, Txc>(g0, bk, 6, detail_xck_cmgga_tau_st_o2_p_batch::c4_15, detail_xck_cmgga_tau_st_o2_p_batch::o4_15, detail_xck_cmgga_tau_st_o2_p_batch::f4_15, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)39*blk);
        stage_a<T, Txc>(g0, bk, 3, detail_xck_cmgga_tau_st_o2_p_batch::c5_8, detail_xck_cmgga_tau_st_o2_p_batch::o5_8, detail_xck_cmgga_tau_st_o2_p_batch::f5_8, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)40*blk);
        stage_a<T, Txc>(g0, bk, 3, detail_xck_cmgga_tau_st_o2_p_batch::c5_9, detail_xck_cmgga_tau_st_o2_p_batch::o5_9, detail_xck_cmgga_tau_st_o2_p_batch::f5_9, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)41*blk);
        stage_a<T, Txc>(g0, bk, 3, detail_xck_cmgga_tau_st_o2_p_batch::c5_10, detail_xck_cmgga_tau_st_o2_p_batch::o5_10, detail_xck_cmgga_tau_st_o2_p_batch::f5_10, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)42*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_cmgga_tau_st_o2_p_batch::c5_11, detail_xck_cmgga_tau_st_o2_p_batch::o5_11, detail_xck_cmgga_tau_st_o2_p_batch::f5_11, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)43*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_cmgga_tau_st_o2_p_batch::c5_12, detail_xck_cmgga_tau_st_o2_p_batch::o5_12, detail_xck_cmgga_tau_st_o2_p_batch::f5_12, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)44*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_cmgga_tau_st_o2_p_batch::c5_13, detail_xck_cmgga_tau_st_o2_p_batch::o5_13, detail_xck_cmgga_tau_st_o2_p_batch::f5_13, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)45*blk);
        stage_a<T, Txc>(g0, bk, 8, detail_xck_cmgga_tau_st_o2_p_batch::c5_14, detail_xck_cmgga_tau_st_o2_p_batch::o5_14, detail_xck_cmgga_tau_st_o2_p_batch::f5_14, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)46*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_cmgga_tau_st_o2_p_batch::c5_15, detail_xck_cmgga_tau_st_o2_p_batch::o5_15, detail_xck_cmgga_tau_st_o2_p_batch::f5_15, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)47*blk);
        stage_a<T, Txc>(g0, bk, 8, detail_xck_cmgga_tau_st_o2_p_batch::c6_8, detail_xck_cmgga_tau_st_o2_p_batch::o6_8, detail_xck_cmgga_tau_st_o2_p_batch::f6_8, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)48*blk);
        stage_a<T, Txc>(g0, bk, 10, detail_xck_cmgga_tau_st_o2_p_batch::c6_9, detail_xck_cmgga_tau_st_o2_p_batch::o6_9, detail_xck_cmgga_tau_st_o2_p_batch::f6_9, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)49*blk);
        stage_a<T, Txc>(g0, bk, 8, detail_xck_cmgga_tau_st_o2_p_batch::c6_10, detail_xck_cmgga_tau_st_o2_p_batch::o6_10, detail_xck_cmgga_tau_st_o2_p_batch::f6_10, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)50*blk);
        stage_a<T, Txc>(g0, bk, 6, detail_xck_cmgga_tau_st_o2_p_batch::c6_11, detail_xck_cmgga_tau_st_o2_p_batch::o6_11, detail_xck_cmgga_tau_st_o2_p_batch::f6_11, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)51*blk);
        stage_a<T, Txc>(g0, bk, 7, detail_xck_cmgga_tau_st_o2_p_batch::c6_12, detail_xck_cmgga_tau_st_o2_p_batch::o6_12, detail_xck_cmgga_tau_st_o2_p_batch::f6_12, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)52*blk);
        stage_a<T, Txc>(g0, bk, 6, detail_xck_cmgga_tau_st_o2_p_batch::c6_13, detail_xck_cmgga_tau_st_o2_p_batch::o6_13, detail_xck_cmgga_tau_st_o2_p_batch::f6_13, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)53*blk);
        stage_a<T, Txc>(g0, bk, 25, detail_xck_cmgga_tau_st_o2_p_batch::c6_14, detail_xck_cmgga_tau_st_o2_p_batch::o6_14, detail_xck_cmgga_tau_st_o2_p_batch::f6_14, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)54*blk);
        stage_a<T, Txc>(g0, bk, 6, detail_xck_cmgga_tau_st_o2_p_batch::c6_15, detail_xck_cmgga_tau_st_o2_p_batch::o6_15, detail_xck_cmgga_tau_st_o2_p_batch::f6_15, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)55*blk);
        stage_a<T, Txc>(g0, bk, 3, detail_xck_cmgga_tau_st_o2_p_batch::c7_8, detail_xck_cmgga_tau_st_o2_p_batch::o7_8, detail_xck_cmgga_tau_st_o2_p_batch::f7_8, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)56*blk);
        stage_a<T, Txc>(g0, bk, 3, detail_xck_cmgga_tau_st_o2_p_batch::c7_9, detail_xck_cmgga_tau_st_o2_p_batch::o7_9, detail_xck_cmgga_tau_st_o2_p_batch::f7_9, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)57*blk);
        stage_a<T, Txc>(g0, bk, 3, detail_xck_cmgga_tau_st_o2_p_batch::c7_10, detail_xck_cmgga_tau_st_o2_p_batch::o7_10, detail_xck_cmgga_tau_st_o2_p_batch::f7_10, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)58*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_cmgga_tau_st_o2_p_batch::c7_11, detail_xck_cmgga_tau_st_o2_p_batch::o7_11, detail_xck_cmgga_tau_st_o2_p_batch::f7_11, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)59*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_cmgga_tau_st_o2_p_batch::c7_12, detail_xck_cmgga_tau_st_o2_p_batch::o7_12, detail_xck_cmgga_tau_st_o2_p_batch::f7_12, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)60*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_cmgga_tau_st_o2_p_batch::c7_13, detail_xck_cmgga_tau_st_o2_p_batch::o7_13, detail_xck_cmgga_tau_st_o2_p_batch::f7_13, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)61*blk);
        stage_a<T, Txc>(g0, bk, 8, detail_xck_cmgga_tau_st_o2_p_batch::c7_14, detail_xck_cmgga_tau_st_o2_p_batch::o7_14, detail_xck_cmgga_tau_st_o2_p_batch::f7_14, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)62*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_cmgga_tau_st_o2_p_batch::c7_15, detail_xck_cmgga_tau_st_o2_p_batch::o7_15, detail_xck_cmgga_tau_st_o2_p_batch::f7_15, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)63*blk);
        stage_a<T, Txc>(g0, bk, 8, detail_xck_cmgga_tau_st_o2_p_batch::c8_8, detail_xck_cmgga_tau_st_o2_p_batch::o8_8, detail_xck_cmgga_tau_st_o2_p_batch::f8_8, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)64*blk);
        stage_a<T, Txc>(g0, bk, 8, detail_xck_cmgga_tau_st_o2_p_batch::c8_9, detail_xck_cmgga_tau_st_o2_p_batch::o8_9, detail_xck_cmgga_tau_st_o2_p_batch::f8_9, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)65*blk);
        stage_a<T, Txc>(g0, bk, 10, detail_xck_cmgga_tau_st_o2_p_batch::c8_10, detail_xck_cmgga_tau_st_o2_p_batch::o8_10, detail_xck_cmgga_tau_st_o2_p_batch::f8_10, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)66*blk);
        stage_a<T, Txc>(g0, bk, 6, detail_xck_cmgga_tau_st_o2_p_batch::c8_11, detail_xck_cmgga_tau_st_o2_p_batch::o8_11, detail_xck_cmgga_tau_st_o2_p_batch::f8_11, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)67*blk);
        stage_a<T, Txc>(g0, bk, 6, detail_xck_cmgga_tau_st_o2_p_batch::c8_12, detail_xck_cmgga_tau_st_o2_p_batch::o8_12, detail_xck_cmgga_tau_st_o2_p_batch::f8_12, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)68*blk);
        stage_a<T, Txc>(g0, bk, 7, detail_xck_cmgga_tau_st_o2_p_batch::c8_13, detail_xck_cmgga_tau_st_o2_p_batch::o8_13, detail_xck_cmgga_tau_st_o2_p_batch::f8_13, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)69*blk);
        stage_a<T, Txc>(g0, bk, 25, detail_xck_cmgga_tau_st_o2_p_batch::c8_14, detail_xck_cmgga_tau_st_o2_p_batch::o8_14, detail_xck_cmgga_tau_st_o2_p_batch::f8_14, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)70*blk);
        stage_a<T, Txc>(g0, bk, 6, detail_xck_cmgga_tau_st_o2_p_batch::c8_15, detail_xck_cmgga_tau_st_o2_p_batch::o8_15, detail_xck_cmgga_tau_st_o2_p_batch::f8_15, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)71*blk);
        stage_a<T, Txc>(g0, bk, 3, detail_xck_cmgga_tau_st_o2_p_batch::c9_8, detail_xck_cmgga_tau_st_o2_p_batch::o9_8, detail_xck_cmgga_tau_st_o2_p_batch::f9_8, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)72*blk);
        stage_a<T, Txc>(g0, bk, 3, detail_xck_cmgga_tau_st_o2_p_batch::c9_9, detail_xck_cmgga_tau_st_o2_p_batch::o9_9, detail_xck_cmgga_tau_st_o2_p_batch::f9_9, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)73*blk);
        stage_a<T, Txc>(g0, bk, 3, detail_xck_cmgga_tau_st_o2_p_batch::c9_10, detail_xck_cmgga_tau_st_o2_p_batch::o9_10, detail_xck_cmgga_tau_st_o2_p_batch::f9_10, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)74*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_cmgga_tau_st_o2_p_batch::c9_11, detail_xck_cmgga_tau_st_o2_p_batch::o9_11, detail_xck_cmgga_tau_st_o2_p_batch::f9_11, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)75*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_cmgga_tau_st_o2_p_batch::c9_12, detail_xck_cmgga_tau_st_o2_p_batch::o9_12, detail_xck_cmgga_tau_st_o2_p_batch::f9_12, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)76*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_cmgga_tau_st_o2_p_batch::c9_13, detail_xck_cmgga_tau_st_o2_p_batch::o9_13, detail_xck_cmgga_tau_st_o2_p_batch::f9_13, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)77*blk);
        stage_a<T, Txc>(g0, bk, 8, detail_xck_cmgga_tau_st_o2_p_batch::c9_14, detail_xck_cmgga_tau_st_o2_p_batch::o9_14, detail_xck_cmgga_tau_st_o2_p_batch::f9_14, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)78*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_cmgga_tau_st_o2_p_batch::c9_15, detail_xck_cmgga_tau_st_o2_p_batch::o9_15, detail_xck_cmgga_tau_st_o2_p_batch::f9_15, detail_xck_cmgga_tau_st_o2_p_batch::NFLD, fi, xc, A + (int64_t)79*blk);
        for (int64_t x0 = 0; x0 < nx; x0 += nxc) {
            const int64_t nxb = nx - x0 < nxc ? nx - x0 : nxc;
            for (int64_t x = 0; x < nxb; ++x) {
                {
                    const T* A_[] = {A + (int64_t)0*blk, A + (int64_t)1*blk, A + (int64_t)2*blk, A + (int64_t)3*blk, A + (int64_t)4*blk, A + (int64_t)5*blk, A + (int64_t)6*blk, A + (int64_t)7*blk};
                    const T* P_[] = {fields[8] + (x0 + x)*npts + g0, fields[9] + (x0 + x)*npts + g0, fields[10] + (x0 + x)*npts + g0, fields[11] + (x0 + x)*npts + g0, fields[12] + (x0 + x)*npts + g0, fields[13] + (x0 + x)*npts + g0, fields[14] + (x0 + x)*npts + g0, fields[15] + (x0 + x)*npts + g0};
                    lincomb<T>(bk, 8, A_, P_, c);
                }
                accumulate<T>(bk, nbf, c, chi + (int64_t)0*nbf*npts + g0, npts, W + x*nbf*bk, 1);
                {
                    const T* A_[] = {A + (int64_t)32*blk, A + (int64_t)33*blk, A + (int64_t)34*blk, A + (int64_t)35*blk, A + (int64_t)36*blk, A + (int64_t)37*blk, A + (int64_t)38*blk, A + (int64_t)39*blk};
                    const T* P_[] = {fields[8] + (x0 + x)*npts + g0, fields[9] + (x0 + x)*npts + g0, fields[10] + (x0 + x)*npts + g0, fields[11] + (x0 + x)*npts + g0, fields[12] + (x0 + x)*npts + g0, fields[13] + (x0 + x)*npts + g0, fields[14] + (x0 + x)*npts + g0, fields[15] + (x0 + x)*npts + g0};
                    lincomb<T>(bk, 8, A_, P_, c);
                }
                accumulate<T>(bk, nbf, c, chi + (int64_t)1*nbf*npts + g0, npts, W + x*nbf*bk, 0);
                {
                    const T* A_[] = {A + (int64_t)48*blk, A + (int64_t)49*blk, A + (int64_t)50*blk, A + (int64_t)51*blk, A + (int64_t)52*blk, A + (int64_t)53*blk, A + (int64_t)54*blk, A + (int64_t)55*blk};
                    const T* P_[] = {fields[8] + (x0 + x)*npts + g0, fields[9] + (x0 + x)*npts + g0, fields[10] + (x0 + x)*npts + g0, fields[11] + (x0 + x)*npts + g0, fields[12] + (x0 + x)*npts + g0, fields[13] + (x0 + x)*npts + g0, fields[14] + (x0 + x)*npts + g0, fields[15] + (x0 + x)*npts + g0};
                    lincomb<T>(bk, 8, A_, P_, c);
                }
                accumulate<T>(bk, nbf, c, chi + (int64_t)2*nbf*npts + g0, npts, W + x*nbf*bk, 0);
                {
                    const T* A_[] = {A + (int64_t)64*blk, A + (int64_t)65*blk, A + (int64_t)66*blk, A + (int64_t)67*blk, A + (int64_t)68*blk, A + (int64_t)69*blk, A + (int64_t)70*blk, A + (int64_t)71*blk};
                    const T* P_[] = {fields[8] + (x0 + x)*npts + g0, fields[9] + (x0 + x)*npts + g0, fields[10] + (x0 + x)*npts + g0, fields[11] + (x0 + x)*npts + g0, fields[12] + (x0 + x)*npts + g0, fields[13] + (x0 + x)*npts + g0, fields[14] + (x0 + x)*npts + g0, fields[15] + (x0 + x)*npts + g0};
                    lincomb<T>(bk, 8, A_, P_, c);
                }
                accumulate<T>(bk, nbf, c, chi + (int64_t)3*nbf*npts + g0, npts, W + x*nbf*bk, 0);
            }
            gemm_rect(nxb*nbf, nbf, bk, static_cast<const T*>(W), bk, chi + (int64_t)0*nbf*npts + g0, npts, out + x0*nbf*nbf, nbf);
            for (int64_t x = 0; x < nxb; ++x) {
                {
                    const T* A_[] = {A + (int64_t)8*blk, A + (int64_t)9*blk, A + (int64_t)10*blk, A + (int64_t)11*blk, A + (int64_t)12*blk, A + (int64_t)13*blk, A + (int64_t)14*blk, A + (int64_t)15*blk};
                    const T* P_[] = {fields[8] + (x0 + x)*npts + g0, fields[9] + (x0 + x)*npts + g0, fields[10] + (x0 + x)*npts + g0, fields[11] + (x0 + x)*npts + g0, fields[12] + (x0 + x)*npts + g0, fields[13] + (x0 + x)*npts + g0, fields[14] + (x0 + x)*npts + g0, fields[15] + (x0 + x)*npts + g0};
                    lincomb<T>(bk, 8, A_, P_, c);
                }
                accumulate<T>(bk, nbf, c, chi + (int64_t)0*nbf*npts + g0, npts, W + x*nbf*bk, 1);
                {
                    const T* A_[] = {A + (int64_t)40*blk, A + (int64_t)41*blk, A + (int64_t)42*blk, A + (int64_t)43*blk, A + (int64_t)44*blk, A + (int64_t)45*blk, A + (int64_t)46*blk, A + (int64_t)47*blk};
                    const T* P_[] = {fields[8] + (x0 + x)*npts + g0, fields[9] + (x0 + x)*npts + g0, fields[10] + (x0 + x)*npts + g0, fields[11] + (x0 + x)*npts + g0, fields[12] + (x0 + x)*npts + g0, fields[13] + (x0 + x)*npts + g0, fields[14] + (x0 + x)*npts + g0, fields[15] + (x0 + x)*npts + g0};
                    lincomb<T>(bk, 8, A_, P_, c);
                }
                accumulate<T>(bk, nbf, c, chi + (int64_t)1*nbf*npts + g0, npts, W + x*nbf*bk, 0);
            }
            gemm_rect(nxb*nbf, nbf, bk, static_cast<const T*>(W), bk, chi + (int64_t)1*nbf*npts + g0, npts, out + x0*nbf*nbf, nbf);
            for (int64_t x = 0; x < nxb; ++x) {
                {
                    const T* A_[] = {A + (int64_t)16*blk, A + (int64_t)17*blk, A + (int64_t)18*blk, A + (int64_t)19*blk, A + (int64_t)20*blk, A + (int64_t)21*blk, A + (int64_t)22*blk, A + (int64_t)23*blk};
                    const T* P_[] = {fields[8] + (x0 + x)*npts + g0, fields[9] + (x0 + x)*npts + g0, fields[10] + (x0 + x)*npts + g0, fields[11] + (x0 + x)*npts + g0, fields[12] + (x0 + x)*npts + g0, fields[13] + (x0 + x)*npts + g0, fields[14] + (x0 + x)*npts + g0, fields[15] + (x0 + x)*npts + g0};
                    lincomb<T>(bk, 8, A_, P_, c);
                }
                accumulate<T>(bk, nbf, c, chi + (int64_t)0*nbf*npts + g0, npts, W + x*nbf*bk, 1);
                {
                    const T* A_[] = {A + (int64_t)56*blk, A + (int64_t)57*blk, A + (int64_t)58*blk, A + (int64_t)59*blk, A + (int64_t)60*blk, A + (int64_t)61*blk, A + (int64_t)62*blk, A + (int64_t)63*blk};
                    const T* P_[] = {fields[8] + (x0 + x)*npts + g0, fields[9] + (x0 + x)*npts + g0, fields[10] + (x0 + x)*npts + g0, fields[11] + (x0 + x)*npts + g0, fields[12] + (x0 + x)*npts + g0, fields[13] + (x0 + x)*npts + g0, fields[14] + (x0 + x)*npts + g0, fields[15] + (x0 + x)*npts + g0};
                    lincomb<T>(bk, 8, A_, P_, c);
                }
                accumulate<T>(bk, nbf, c, chi + (int64_t)2*nbf*npts + g0, npts, W + x*nbf*bk, 0);
            }
            gemm_rect(nxb*nbf, nbf, bk, static_cast<const T*>(W), bk, chi + (int64_t)2*nbf*npts + g0, npts, out + x0*nbf*nbf, nbf);
            for (int64_t x = 0; x < nxb; ++x) {
                {
                    const T* A_[] = {A + (int64_t)24*blk, A + (int64_t)25*blk, A + (int64_t)26*blk, A + (int64_t)27*blk, A + (int64_t)28*blk, A + (int64_t)29*blk, A + (int64_t)30*blk, A + (int64_t)31*blk};
                    const T* P_[] = {fields[8] + (x0 + x)*npts + g0, fields[9] + (x0 + x)*npts + g0, fields[10] + (x0 + x)*npts + g0, fields[11] + (x0 + x)*npts + g0, fields[12] + (x0 + x)*npts + g0, fields[13] + (x0 + x)*npts + g0, fields[14] + (x0 + x)*npts + g0, fields[15] + (x0 + x)*npts + g0};
                    lincomb<T>(bk, 8, A_, P_, c);
                }
                accumulate<T>(bk, nbf, c, chi + (int64_t)0*nbf*npts + g0, npts, W + x*nbf*bk, 1);
                {
                    const T* A_[] = {A + (int64_t)72*blk, A + (int64_t)73*blk, A + (int64_t)74*blk, A + (int64_t)75*blk, A + (int64_t)76*blk, A + (int64_t)77*blk, A + (int64_t)78*blk, A + (int64_t)79*blk};
                    const T* P_[] = {fields[8] + (x0 + x)*npts + g0, fields[9] + (x0 + x)*npts + g0, fields[10] + (x0 + x)*npts + g0, fields[11] + (x0 + x)*npts + g0, fields[12] + (x0 + x)*npts + g0, fields[13] + (x0 + x)*npts + g0, fields[14] + (x0 + x)*npts + g0, fields[15] + (x0 + x)*npts + g0};
                    lincomb<T>(bk, 8, A_, P_, c);
                }
                accumulate<T>(bk, nbf, c, chi + (int64_t)3*nbf*npts + g0, npts, W + x*nbf*bk, 0);
            }
            gemm_rect(nxb*nbf, nbf, bk, static_cast<const T*>(W), bk, chi + (int64_t)3*nbf*npts + g0, npts, out + x0*nbf*nbf, nbf);
        }
    }
    if (own) delete[] c;
    return 0;
}


/* Operands of xck_cmgga_tau_st_o2_p_batch_t: `fields` in the order of
 * xck_cmgga_tau_st_o2_p_batch_field_names, `xc` in the order of xck_cmgga_tau_st_o2_p_batch_xc_names (the
 * C ABI's `scal` is the two concatenated, split at n_fields). The
 * structs name them; the overload taking them packs the arrays. */
inline constexpr int xck_cmgga_tau_st_o2_p_batch_n_fields = 16;
inline constexpr int xck_cmgga_tau_st_o2_p_batch_n_xc = 25;
inline constexpr const char* xck_cmgga_tau_st_o2_p_batch_field_names[] = {"w", "rho_a_x", "rho_a_y", "rho_a_z", "jpx_a", "jpy_a", "jpz_a", "inv_rho_a", "rho_a_p1_x", "rho_a_p1_y", "rho_a_p1_z", "jpx_a_p1", "jpy_a_p1", "jpz_a_p1", "rho_a_p1", "tau_a_p1"};
inline constexpr const char* xck_cmgga_tau_st_o2_p_batch_xc_names[] = {"vsigma_0", "vsigma_1", "vtau_0", "v2rho2_0", "v2rho2_1", "v2rhosigma_0", "v2rhosigma_1", "v2rhosigma_2", "v2rhosigma_3", "v2rhosigma_4", "v2rhotau_0", "v2rhotau_1", "v2rhotau_2", "v2sigma2_0", "v2sigma2_1", "v2sigma2_2", "v2sigma2_3", "v2sigma2_4", "v2sigmatau_0", "v2sigmatau_1", "v2sigmatau_2", "v2sigmatau_3", "v2sigmatau_4", "v2tau2_0", "v2tau2_1"};
template <typename T>
struct xck_cmgga_tau_st_o2_p_batch_fields {
    const T* w;
    const T* rho_a_x;
    const T* rho_a_y;
    const T* rho_a_z;
    const T* jpx_a;
    const T* jpy_a;
    const T* jpz_a;
    const T* inv_rho_a;
    const T* rho_a_p1_x;
    const T* rho_a_p1_y;
    const T* rho_a_p1_z;
    const T* jpx_a_p1;
    const T* jpy_a_p1;
    const T* jpz_a_p1;
    const T* rho_a_p1;
    const T* tau_a_p1;
};
template <typename Txc>
struct xck_cmgga_tau_st_o2_p_batch_xc {
    const Txc* vsigma_0;
    const Txc* vsigma_1;
    const Txc* vtau_0;
    const Txc* v2rho2_0;
    const Txc* v2rho2_1;
    const Txc* v2rhosigma_0;
    const Txc* v2rhosigma_1;
    const Txc* v2rhosigma_2;
    const Txc* v2rhosigma_3;
    const Txc* v2rhosigma_4;
    const Txc* v2rhotau_0;
    const Txc* v2rhotau_1;
    const Txc* v2rhotau_2;
    const Txc* v2sigma2_0;
    const Txc* v2sigma2_1;
    const Txc* v2sigma2_2;
    const Txc* v2sigma2_3;
    const Txc* v2sigma2_4;
    const Txc* v2sigmatau_0;
    const Txc* v2sigmatau_1;
    const Txc* v2sigmatau_2;
    const Txc* v2sigmatau_3;
    const Txc* v2sigmatau_4;
    const Txc* v2tau2_0;
    const Txc* v2tau2_1;
};

template <typename T, typename Txc = T>
int xck_cmgga_tau_st_o2_p_batch_t(int64_t npts,
        int64_t nbf,
        int64_t nx,
        const T* chi,
        const xck_cmgga_tau_st_o2_p_batch_fields<T>& fields_,
        const xck_cmgga_tau_st_o2_p_batch_xc<Txc>& xc_,
        T* out,
        T* work = nullptr) {
    const T* f_[] = {fields_.w, fields_.rho_a_x, fields_.rho_a_y, fields_.rho_a_z, fields_.jpx_a, fields_.jpy_a, fields_.jpz_a, fields_.inv_rho_a, fields_.rho_a_p1_x, fields_.rho_a_p1_y, fields_.rho_a_p1_z, fields_.jpx_a_p1, fields_.jpy_a_p1, fields_.jpz_a_p1, fields_.rho_a_p1, fields_.tau_a_p1};
    const Txc* x_[] = {xc_.vsigma_0, xc_.vsigma_1, xc_.vtau_0, xc_.v2rho2_0, xc_.v2rho2_1, xc_.v2rhosigma_0, xc_.v2rhosigma_1, xc_.v2rhosigma_2, xc_.v2rhosigma_3, xc_.v2rhosigma_4, xc_.v2rhotau_0, xc_.v2rhotau_1, xc_.v2rhotau_2, xc_.v2sigma2_0, xc_.v2sigma2_1, xc_.v2sigma2_2, xc_.v2sigma2_3, xc_.v2sigma2_4, xc_.v2sigmatau_0, xc_.v2sigmatau_1, xc_.v2sigmatau_2, xc_.v2sigmatau_3, xc_.v2sigmatau_4, xc_.v2tau2_0, xc_.v2tau2_1};
    return xck_cmgga_tau_st_o2_p_batch_t<T, Txc>(npts, nbf, nx, chi, f_, x_, out, work);
}

} // namespace xckernel
