/* generated by xckernel; do not edit. */
#pragma once
#include <cstdint>
#include <new>
#include "xckernel/evaluator.hpp"

namespace xckernel {
namespace detail_xck_mgga_lapl_ub_fg {
static constexpr double c0_0[] = {
    1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0
};
static constexpr int32_t o0_0[] = {
    0,3,6,9,12,16,20,24,28,32,36,40,44,48,52,56,60
};
static constexpr uint16_t f0_0[] = {
    19,34,0,22,35,0,1,31,0,4,32,0,1,13,39,0,2,14,39,0,3,15,39,0,4,7,39,0,5,8,39,0,6,9,39,0,1,7,38,0,2,8,38,0,3,9,38,0,4,13,40,0,5,14,40,0,6,15,40,0
};
static constexpr double c0_1[] = {
    1.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,4.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,4.0,4.0,4.0,4.0,4.0,4.0
};
static constexpr int32_t o0_1[] = {
    0,2,5,9,12,16,20,24,28,33,37,41,45,50,55,60,65,70,75,80,85,90,95,100,105,110,115,120,125,130,135,140,145,150,155
};
static constexpr uint16_t f0_1[] = {
    26,0,7,27,0,1,1,36,0,13,28,0,4,4,40,0,19,1,47,0,22,1,48,0,1,4,39,0,1,1,13,43,0,19,4,49,0,22,4,50,0,1,4,37,0,1,1,7,41,0,4,4,7,44,0,4,4,13,45,0,1,2,14,43,0,1,3,15,43,0,1,4,7,43,0,1,5,8,43,0,1,6,9,43,0,1,2,8,41,0,1,3,9,41,0,1,5,14,44,0,1,6,15,44,0,2,4,14,44,0,3,4,15,44,0,4,5,8,44,0,4,6,9,44,0,1,4,7,42,0,1,4,13,44,0,2,4,8,42,0,3,4,9,42,0,4,5,14,45,0,4,6,15,45,0
};
static constexpr double c0_2[] = {
    1.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,4.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,4.0,4.0,4.0,4.0,4.0,4.0
};
static constexpr int32_t o0_2[] = {
    0,3,6,10,14,18,22,27,31,35,39,43,48,53,58,63,68,73,78,83,88,93,98,103,108,113,118,123,128,133,138,143,148,153
};
static constexpr uint16_t f0_2[] = {
    8,27,0,14,28,0,19,2,47,0,22,2,48,0,1,2,36,0,2,4,39,0,2,2,14,43,0,19,5,49,0,22,5,50,0,1,5,37,0,4,5,40,0,2,2,8,41,0,5,5,8,44,0,5,5,14,45,0,1,2,13,43,0,2,3,15,43,0,2,4,7,43,0,2,5,8,43,0,2,6,9,43,0,1,2,7,41,0,1,5,13,44,0,2,3,9,41,0,2,4,13,44,0,2,6,15,44,0,3,5,15,44,0,4,5,7,44,0,5,6,9,44,0,1,5,7,42,0,2,5,8,42,0,2,5,14,44,0,3,5,9,42,0,4,5,13,45,0,5,6,15,45,0
};
static constexpr double c0_3[] = {
    1.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,4.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,4.0,4.0,4.0,4.0,4.0,4.0
};
static constexpr int32_t o0_3[] = {
    0,3,6,10,14,18,22,27,31,35,39,43,48,53,58,63,68,73,78,83,88,93,98,103,108,113,118,123,128,133,138,143,148,153
};
static constexpr uint16_t f0_3[] = {
    9,27,0,15,28,0,19,3,47,0,22,3,48,0,1,3,36,0,3,4,39,0,3,3,15,43,0,19,6,49,0,22,6,50,0,1,6,37,0,4,6,40,0,3,3,9,41,0,6,6,9,44,0,6,6,15,45,0,1,3,13,43,0,2,3,14,43,0,3,4,7,43,0,3,5,8,43,0,3,6,9,43,0,1,3,7,41,0,1,6,13,44,0,2,3,8,41,0,2,6,14,44,0,3,4,13,44,0,3,5,14,44,0,4,6,7,44,0,5,6,8,44,0,1,6,7,42,0,2,6,8,42,0,3,6,9,42,0,3,6,15,44,0,4,6,13,45,0,5,6,14,45,0
};
static constexpr double c0_4[] = {
    1.0
};
static constexpr int32_t o0_4[] = {
    0,2
};
static constexpr uint16_t f0_4[] = {
    25,0
};
static constexpr double c0_5[] = {
    1.0,2.0
};
static constexpr int32_t o0_5[] = {
    0,3,6
};
static constexpr uint16_t f0_5[] = {
    1,27,0,4,28,0
};
static constexpr double c0_6[] = {
    1.0,2.0
};
static constexpr int32_t o0_6[] = {
    0,3,6
};
static constexpr uint16_t f0_6[] = {
    2,27,0,5,28,0
};
static constexpr double c0_7[] = {
    1.0,2.0
};
static constexpr int32_t o0_7[] = {
    0,3,6
};
static constexpr uint16_t f0_7[] = {
    3,27,0,6,28,0
};
static constexpr double c0_8[] = {
    1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0
};
static constexpr int32_t o0_8[] = {
    0,3,6,9,12,16,20,24,28,32,36,40,44,48,52,56,60
};
static constexpr uint16_t f0_8[] = {
    19,29,0,22,30,0,1,33,0,4,35,0,1,13,48,0,2,14,48,0,3,15,48,0,4,7,48,0,5,8,48,0,6,9,48,0,1,7,46,0,2,8,46,0,3,9,46,0,4,13,50,0,5,14,50,0,6,15,50,0
};
static constexpr double c0_9[] = {
    1.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,4.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,4.0,4.0,4.0,4.0,4.0,4.0
};
static constexpr int32_t o0_9[] = {
    0,2,5,9,12,16,20,24,28,33,37,41,45,50,55,60,65,70,75,80,85,90,95,100,105,110,115,120,125,130,135,140,145,150,155
};
static constexpr uint16_t f0_9[] = {
    26,0,7,27,0,1,1,36,0,13,28,0,4,4,40,0,19,1,47,0,22,1,48,0,1,4,39,0,1,1,13,43,0,19,4,49,0,22,4,50,0,1,4,37,0,1,1,7,41,0,4,4,7,44,0,4,4,13,45,0,1,2,14,43,0,1,3,15,43,0,1,4,7,43,0,1,5,8,43,0,1,6,9,43,0,1,2,8,41,0,1,3,9,41,0,1,5,14,44,0,1,6,15,44,0,2,4,14,44,0,3,4,15,44,0,4,5,8,44,0,4,6,9,44,0,1,4,7,42,0,1,4,13,44,0,2,4,8,42,0,3,4,9,42,0,4,5,14,45,0,4,6,15,45,0
};
static constexpr double c0_10[] = {
    2.0,2.0,2.0,2.0,2.0,4.0,2.0,2.0,2.0,2.0,2.0,2.0,4.0,4.0,4.0,4.0,4.0,4.0
};
static constexpr int32_t o0_10[] = {
    0,3,6,9,12,15,18,22,26,30,34,38,42,46,50,54,58,62,66
};
static constexpr uint16_t f0_10[] = {
    19,29,0,22,30,0,1,33,0,1,27,0,4,35,0,4,28,0,1,13,48,0,2,14,48,0,3,15,48,0,4,7,48,0,5,8,48,0,6,9,48,0,1,7,46,0,2,8,46,0,3,9,46,0,4,13,50,0,5,14,50,0,6,15,50,0
};
static constexpr double c0_11[] = {
    1.0,2.0
};
static constexpr int32_t o0_11[] = {
    0,3,6
};
static constexpr uint16_t f0_11[] = {
    2,27,0,5,28,0
};
static constexpr double c0_12[] = {
    1.0,2.0
};
static constexpr int32_t o0_12[] = {
    0,3,6
};
static constexpr uint16_t f0_12[] = {
    3,27,0,6,28,0
};
static constexpr double c0_13[] = {
    2.0
};
static constexpr int32_t o0_13[] = {
    0,2
};
static constexpr uint16_t f0_13[] = {
    25,0
};
static constexpr double c0_14[] = {
    1.0
};
static constexpr int32_t o0_14[] = {
    0,2
};
static constexpr uint16_t f0_14[] = {
    25,0
};
static constexpr double c0_15[] = {
    1.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,4.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,4.0,4.0,4.0,4.0,4.0,4.0
};
static constexpr int32_t o0_15[] = {
    0,3,6,10,14,18,22,27,31,35,39,43,48,53,58,63,68,73,78,83,88,93,98,103,108,113,118,123,128,133,138,143,148,153
};
static constexpr uint16_t f0_15[] = {
    8,27,0,14,28,0,19,2,47,0,22,2,48,0,1,2,36,0,2,4,39,0,2,2,14,43,0,19,5,49,0,22,5,50,0,1,5,37,0,4,5,40,0,2,2,8,41,0,5,5,8,44,0,5,5,14,45,0,1,2,13,43,0,2,3,15,43,0,2,4,7,43,0,2,5,8,43,0,2,6,9,43,0,1,2,7,41,0,1,5,13,44,0,2,3,9,41,0,2,4,13,44,0,2,6,15,44,0,3,5,15,44,0,4,5,7,44,0,5,6,9,44,0,1,5,7,42,0,2,5,8,42,0,2,5,14,44,0,3,5,9,42,0,4,5,13,45,0,5,6,15,45,0
};
static constexpr double c0_16[] = {
    1.0,2.0
};
static constexpr int32_t o0_16[] = {
    0,3,6
};
static constexpr uint16_t f0_16[] = {
    2,27,0,5,28,0
};
static constexpr double c0_17[] = {
    2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,4.0,4.0,4.0,4.0,4.0,4.0
};
static constexpr int32_t o0_17[] = {
    0,3,6,9,12,16,20,24,28,32,36,40,44,48,52,56,60
};
static constexpr uint16_t f0_17[] = {
    19,29,0,22,30,0,1,33,0,4,35,0,1,13,48,0,2,14,48,0,3,15,48,0,4,7,48,0,5,8,48,0,6,9,48,0,1,7,46,0,2,8,46,0,3,9,46,0,4,13,50,0,5,14,50,0,6,15,50,0
};
static constexpr double c0_18[] = {
    2.0
};
static constexpr int32_t o0_18[] = {
    0,2
};
static constexpr uint16_t f0_18[] = {
    25,0
};
static constexpr double c0_19[] = {
    1.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,4.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,4.0,4.0,4.0,4.0,4.0,4.0
};
static constexpr int32_t o0_19[] = {
    0,3,6,10,14,18,22,27,31,35,39,43,48,53,58,63,68,73,78,83,88,93,98,103,108,113,118,123,128,133,138,143,148,153
};
static constexpr uint16_t f0_19[] = {
    9,27,0,15,28,0,19,3,47,0,22,3,48,0,1,3,36,0,3,4,39,0,3,3,15,43,0,19,6,49,0,22,6,50,0,1,6,37,0,4,6,40,0,3,3,9,41,0,6,6,9,44,0,6,6,15,45,0,1,3,13,43,0,2,3,14,43,0,3,4,7,43,0,3,5,8,43,0,3,6,9,43,0,1,3,7,41,0,1,6,13,44,0,2,3,8,41,0,2,6,14,44,0,3,4,13,44,0,3,5,14,44,0,4,6,7,44,0,5,6,8,44,0,1,6,7,42,0,2,6,8,42,0,3,6,9,42,0,3,6,15,44,0,4,6,13,45,0,5,6,14,45,0
};
static constexpr double c0_20[] = {
    1.0,2.0
};
static constexpr int32_t o0_20[] = {
    0,3,6
};
static constexpr uint16_t f0_20[] = {
    3,27,0,6,28,0
};
static constexpr double c0_21[] = {
    2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,4.0,4.0,4.0,4.0,4.0,4.0
};
static constexpr int32_t o0_21[] = {
    0,3,6,9,12,16,20,24,28,32,36,40,44,48,52,56,60
};
static constexpr uint16_t f0_21[] = {
    19,29,0,22,30,0,1,33,0,4,35,0,1,13,48,0,2,14,48,0,3,15,48,0,4,7,48,0,5,8,48,0,6,9,48,0,1,7,46,0,2,8,46,0,3,9,46,0,4,13,50,0,5,14,50,0,6,15,50,0
};
static constexpr double c0_22[] = {
    2.0
};
static constexpr int32_t o0_22[] = {
    0,2
};
static constexpr uint16_t f0_22[] = {
    25,0
};
static constexpr double c0_23[] = {
    1.0
};
static constexpr int32_t o0_23[] = {
    0,2
};
static constexpr uint16_t f0_23[] = {
    25,0
};
static constexpr double c0_24[] = {
    1.0,2.0
};
static constexpr int32_t o0_24[] = {
    0,3,6
};
static constexpr uint16_t f0_24[] = {
    1,27,0,4,28,0
};
static constexpr double c0_25[] = {
    2.0
};
static constexpr int32_t o0_25[] = {
    0,2
};
static constexpr uint16_t f0_25[] = {
    25,0
};
static constexpr double c0_26[] = {
    1.0,2.0
};
static constexpr int32_t o0_26[] = {
    0,3,6
};
static constexpr uint16_t f0_26[] = {
    2,27,0,5,28,0
};
static constexpr double c0_27[] = {
    2.0
};
static constexpr int32_t o0_27[] = {
    0,2
};
static constexpr uint16_t f0_27[] = {
    25,0
};
static constexpr double c0_28[] = {
    1.0,2.0
};
static constexpr int32_t o0_28[] = {
    0,3,6
};
static constexpr uint16_t f0_28[] = {
    3,27,0,6,28,0
};
static constexpr double c0_29[] = {
    2.0
};
static constexpr int32_t o0_29[] = {
    0,2
};
static constexpr uint16_t f0_29[] = {
    25,0
};
static constexpr double c0_30[] = {
    1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0
};
static constexpr int32_t o0_30[] = {
    0,3,6,9,12,16,20,24,28,32,36,40,44,48,52,56,60
};
static constexpr uint16_t f0_30[] = {
    19,29,0,22,30,0,1,33,0,4,35,0,1,13,48,0,2,14,48,0,3,15,48,0,4,7,48,0,5,8,48,0,6,9,48,0,1,7,46,0,2,8,46,0,3,9,46,0,4,13,50,0,5,14,50,0,6,15,50,0
};
static constexpr double c0_31[] = {
    1.0
};
static constexpr int32_t o0_31[] = {
    0,2
};
static constexpr uint16_t f0_31[] = {
    25,0
};
static constexpr double c1_0[] = {
    1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0
};
static constexpr int32_t o1_0[] = {
    0,3,6,9,12,16,20,24,28,32,36,40,44,48,52,56,60
};
static constexpr uint16_t f1_0[] = {
    20,34,0,23,35,0,2,31,0,5,32,0,1,14,39,0,2,16,39,0,3,17,39,0,4,8,39,0,5,10,39,0,6,11,39,0,1,8,38,0,2,10,38,0,3,11,38,0,4,14,40,0,5,16,40,0,6,17,40,0
};
static constexpr double c1_1[] = {
    1.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,4.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,4.0,4.0,4.0,4.0,4.0,4.0
};
static constexpr int32_t o1_1[] = {
    0,3,6,10,14,18,22,27,31,35,39,43,48,53,58,63,68,73,78,83,88,93,98,103,108,113,118,123,128,133,138,143,148,153
};
static constexpr uint16_t f1_1[] = {
    8,27,0,14,28,0,20,1,47,0,23,1,48,0,1,2,36,0,1,5,39,0,1,1,14,43,0,20,4,49,0,23,4,50,0,2,4,37,0,4,5,40,0,1,1,8,41,0,4,4,8,44,0,4,4,14,45,0,1,2,16,43,0,1,3,17,43,0,1,4,8,43,0,1,5,10,43,0,1,6,11,43,0,1,2,10,41,0,1,3,11,41,0,1,5,16,44,0,1,6,17,44,0,2,4,16,44,0,3,4,17,44,0,4,5,10,44,0,4,6,11,44,0,1,4,8,42,0,1,4,14,44,0,2,4,10,42,0,3,4,11,42,0,4,5,16,45,0,4,6,17,45,0
};
static constexpr double c1_2[] = {
    1.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,4.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,4.0,4.0,4.0,4.0,4.0,4.0
};
static constexpr int32_t o1_2[] = {
    0,2,5,9,12,16,20,24,28,33,37,41,45,50,55,60,65,70,75,80,85,90,95,100,105,110,115,120,125,130,135,140,145,150,155
};
static constexpr uint16_t f1_2[] = {
    26,0,10,27,0,2,2,36,0,16,28,0,5,5,40,0,20,2,47,0,23,2,48,0,2,5,39,0,2,2,16,43,0,20,5,49,0,23,5,50,0,2,5,37,0,2,2,10,41,0,5,5,10,44,0,5,5,16,45,0,1,2,14,43,0,2,3,17,43,0,2,4,8,43,0,2,5,10,43,0,2,6,11,43,0,1,2,8,41,0,1,5,14,44,0,2,3,11,41,0,2,4,14,44,0,2,6,17,44,0,3,5,17,44,0,4,5,8,44,0,5,6,11,44,0,1,5,8,42,0,2,5,10,42,0,2,5,16,44,0,3,5,11,42,0,4,5,14,45,0,5,6,17,45,0
};
static constexpr double c1_3[] = {
    1.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,4.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,4.0,4.0,4.0,4.0,4.0,4.0
};
static constexpr int32_t o1_3[] = {
    0,3,6,10,14,18,22,27,31,35,39,43,48,53,58,63,68,73,78,83,88,93,98,103,108,113,118,123,128,133,138,143,148,153
};
static constexpr uint16_t f1_3[] = {
    11,27,0,17,28,0,20,3,47,0,23,3,48,0,2,3,36,0,3,5,39,0,3,3,17,43,0,20,6,49,0,23,6,50,0,2,6,37,0,5,6,40,0,3,3,11,41,0,6,6,11,44,0,6,6,17,45,0,1,3,14,43,0,2,3,16,43,0,3,4,8,43,0,3,5,10,43,0,3,6,11,43,0,1,3,8,41,0,1,6,14,44,0,2,3,10,41,0,2,6,16,44,0,3,4,14,44,0,3,5,16,44,0,4,6,8,44,0,5,6,10,44,0,1,6,8,42,0,2,6,10,42,0,3,6,11,42,0,3,6,17,44,0,4,6,14,45,0,5,6,16,45,0
};
static constexpr double c1_4[] = {
    1.0
};
static constexpr int32_t o1_4[] = {
    0,2
};
static constexpr uint16_t f1_4[] = {
    25,0
};
static constexpr double c1_5[] = {
    1.0,2.0
};
static constexpr int32_t o1_5[] = {
    0,3,6
};
static constexpr uint16_t f1_5[] = {
    1,27,0,4,28,0
};
static constexpr double c1_6[] = {
    1.0,2.0
};
static constexpr int32_t o1_6[] = {
    0,3,6
};
static constexpr uint16_t f1_6[] = {
    2,27,0,5,28,0
};
static constexpr double c1_7[] = {
    1.0,2.0
};
static constexpr int32_t o1_7[] = {
    0,3,6
};
static constexpr uint16_t f1_7[] = {
    3,27,0,6,28,0
};
static constexpr double c1_8[] = {
    1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0
};
static constexpr int32_t o1_8[] = {
    0,3,6,9,12,16,20,24,28,32,36,40,44,48,52,56,60
};
static constexpr uint16_t f1_8[] = {
    20,29,0,23,30,0,2,33,0,5,35,0,1,14,48,0,2,16,48,0,3,17,48,0,4,8,48,0,5,10,48,0,6,11,48,0,1,8,46,0,2,10,46,0,3,11,46,0,4,14,50,0,5,16,50,0,6,17,50,0
};
static constexpr double c1_9[] = {
    1.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,4.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,4.0,4.0,4.0,4.0,4.0,4.0
};
static constexpr int32_t o1_9[] = {
    0,3,6,10,14,18,22,27,31,35,39,43,48,53,58,63,68,73,78,83,88,93,98,103,108,113,118,123,128,133,138,143,148,153
};
static constexpr uint16_t f1_9[] = {
    8,27,0,14,28,0,20,1,47,0,23,1,48,0,1,2,36,0,1,5,39,0,1,1,14,43,0,20,4,49,0,23,4,50,0,2,4,37,0,4,5,40,0,1,1,8,41,0,4,4,8,44,0,4,4,14,45,0,1,2,16,43,0,1,3,17,43,0,1,4,8,43,0,1,5,10,43,0,1,6,11,43,0,1,2,10,41,0,1,3,11,41,0,1,5,16,44,0,1,6,17,44,0,2,4,16,44,0,3,4,17,44,0,4,5,10,44,0,4,6,11,44,0,1,4,8,42,0,1,4,14,44,0,2,4,10,42,0,3,4,11,42,0,4,5,16,45,0,4,6,17,45,0
};
static constexpr double c1_10[] = {
    2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,4.0,4.0,4.0,4.0,4.0,4.0
};
static constexpr int32_t o1_10[] = {
    0,3,6,9,12,16,20,24,28,32,36,40,44,48,52,56,60
};
static constexpr uint16_t f1_10[] = {
    20,29,0,23,30,0,2,33,0,5,35,0,1,14,48,0,2,16,48,0,3,17,48,0,4,8,48,0,5,10,48,0,6,11,48,0,1,8,46,0,2,10,46,0,3,11,46,0,4,14,50,0,5,16,50,0,6,17,50,0
};
static constexpr double c1_11[] = {
    1.0,2.0
};
static constexpr int32_t o1_11[] = {
    0,3,6
};
static constexpr uint16_t f1_11[] = {
    1,27,0,4,28,0
};
static constexpr double c1_12[] = {
    2.0
};
static constexpr int32_t o1_12[] = {
    0,2
};
static constexpr uint16_t f1_12[] = {
    25,0
};
static constexpr double c1_13[] = {
    1.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,4.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,4.0,4.0,4.0,4.0,4.0,4.0
};
static constexpr int32_t o1_13[] = {
    0,2,5,9,12,16,20,24,28,33,37,41,45,50,55,60,65,70,75,80,85,90,95,100,105,110,115,120,125,130,135,140,145,150,155
};
static constexpr uint16_t f1_13[] = {
    26,0,10,27,0,2,2,36,0,16,28,0,5,5,40,0,20,2,47,0,23,2,48,0,2,5,39,0,2,2,16,43,0,20,5,49,0,23,5,50,0,2,5,37,0,2,2,10,41,0,5,5,10,44,0,5,5,16,45,0,1,2,14,43,0,2,3,17,43,0,2,4,8,43,0,2,5,10,43,0,2,6,11,43,0,1,2,8,41,0,1,5,14,44,0,2,3,11,41,0,2,4,14,44,0,2,6,17,44,0,3,5,17,44,0,4,5,8,44,0,5,6,11,44,0,1,5,8,42,0,2,5,10,42,0,2,5,16,44,0,3,5,11,42,0,4,5,14,45,0,5,6,17,45,0
};
static constexpr double c1_14[] = {
    1.0,2.0
};
static constexpr int32_t o1_14[] = {
    0,3,6
};
static constexpr uint16_t f1_14[] = {
    1,27,0,4,28,0
};
static constexpr double c1_15[] = {
    2.0,2.0,2.0,2.0,2.0,4.0,2.0,2.0,2.0,2.0,2.0,2.0,4.0,4.0,4.0,4.0,4.0,4.0
};
static constexpr int32_t o1_15[] = {
    0,3,6,9,12,15,18,22,26,30,34,38,42,46,50,54,58,62,66
};
static constexpr uint16_t f1_15[] = {
    20,29,0,23,30,0,2,33,0,2,27,0,5,35,0,5,28,0,1,14,48,0,2,16,48,0,3,17,48,0,4,8,48,0,5,10,48,0,6,11,48,0,1,8,46,0,2,10,46,0,3,11,46,0,4,14,50,0,5,16,50,0,6,17,50,0
};
static constexpr double c1_16[] = {
    1.0,2.0
};
static constexpr int32_t o1_16[] = {
    0,3,6
};
static constexpr uint16_t f1_16[] = {
    3,27,0,6,28,0
};
static constexpr double c1_17[] = {
    2.0
};
static constexpr int32_t o1_17[] = {
    0,2
};
static constexpr uint16_t f1_17[] = {
    25,0
};
static constexpr double c1_18[] = {
    1.0
};
static constexpr int32_t o1_18[] = {
    0,2
};
static constexpr uint16_t f1_18[] = {
    25,0
};
static constexpr double c1_19[] = {
    1.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,4.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,4.0,4.0,4.0,4.0,4.0,4.0
};
static constexpr int32_t o1_19[] = {
    0,3,6,10,14,18,22,27,31,35,39,43,48,53,58,63,68,73,78,83,88,93,98,103,108,113,118,123,128,133,138,143,148,153
};
static constexpr uint16_t f1_19[] = {
    11,27,0,17,28,0,20,3,47,0,23,3,48,0,2,3,36,0,3,5,39,0,3,3,17,43,0,20,6,49,0,23,6,50,0,2,6,37,0,5,6,40,0,3,3,11,41,0,6,6,11,44,0,6,6,17,45,0,1,3,14,43,0,2,3,16,43,0,3,4,8,43,0,3,5,10,43,0,3,6,11,43,0,1,3,8,41,0,1,6,14,44,0,2,3,10,41,0,2,6,16,44,0,3,4,14,44,0,3,5,16,44,0,4,6,8,44,0,5,6,10,44,0,1,6,8,42,0,2,6,10,42,0,3,6,11,42,0,3,6,17,44,0,4,6,14,45,0,5,6,16,45,0
};
static constexpr double c1_20[] = {
    1.0,2.0
};
static constexpr int32_t o1_20[] = {
    0,3,6
};
static constexpr uint16_t f1_20[] = {
    3,27,0,6,28,0
};
static constexpr double c1_21[] = {
    2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,4.0,4.0,4.0,4.0,4.0,4.0
};
static constexpr int32_t o1_21[] = {
    0,3,6,9,12,16,20,24,28,32,36,40,44,48,52,56,60
};
static constexpr uint16_t f1_21[] = {
    20,29,0,23,30,0,2,33,0,5,35,0,1,14,48,0,2,16,48,0,3,17,48,0,4,8,48,0,5,10,48,0,6,11,48,0,1,8,46,0,2,10,46,0,3,11,46,0,4,14,50,0,5,16,50,0,6,17,50,0
};
static constexpr double c1_22[] = {
    2.0
};
static constexpr int32_t o1_22[] = {
    0,2
};
static constexpr uint16_t f1_22[] = {
    25,0
};
static constexpr double c1_23[] = {
    1.0
};
static constexpr int32_t o1_23[] = {
    0,2
};
static constexpr uint16_t f1_23[] = {
    25,0
};
static constexpr double c1_24[] = {
    1.0,2.0
};
static constexpr int32_t o1_24[] = {
    0,3,6
};
static constexpr uint16_t f1_24[] = {
    1,27,0,4,28,0
};
static constexpr double c1_25[] = {
    2.0
};
static constexpr int32_t o1_25[] = {
    0,2
};
static constexpr uint16_t f1_25[] = {
    25,0
};
static constexpr double c1_26[] = {
    1.0,2.0
};
static constexpr int32_t o1_26[] = {
    0,3,6
};
static constexpr uint16_t f1_26[] = {
    2,27,0,5,28,0
};
static constexpr double c1_27[] = {
    2.0
};
static constexpr int32_t o1_27[] = {
    0,2
};
static constexpr uint16_t f1_27[] = {
    25,0
};
static constexpr double c1_28[] = {
    1.0,2.0
};
static constexpr int32_t o1_28[] = {
    0,3,6
};
static constexpr uint16_t f1_28[] = {
    3,27,0,6,28,0
};
static constexpr double c1_29[] = {
    2.0
};
static constexpr int32_t o1_29[] = {
    0,2
};
static constexpr uint16_t f1_29[] = {
    25,0
};
static constexpr double c1_30[] = {
    1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0
};
static constexpr int32_t o1_30[] = {
    0,3,6,9,12,16,20,24,28,32,36,40,44,48,52,56,60
};
static constexpr uint16_t f1_30[] = {
    20,29,0,23,30,0,2,33,0,5,35,0,1,14,48,0,2,16,48,0,3,17,48,0,4,8,48,0,5,10,48,0,6,11,48,0,1,8,46,0,2,10,46,0,3,11,46,0,4,14,50,0,5,16,50,0,6,17,50,0
};
static constexpr double c1_31[] = {
    1.0
};
static constexpr int32_t o1_31[] = {
    0,2
};
static constexpr uint16_t f1_31[] = {
    25,0
};
static constexpr double c2_0[] = {
    1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0
};
static constexpr int32_t o2_0[] = {
    0,3,6,9,12,16,20,24,28,32,36,40,44,48,52,56,60
};
static constexpr uint16_t f2_0[] = {
    21,34,0,24,35,0,3,31,0,6,32,0,1,15,39,0,2,17,39,0,3,18,39,0,4,9,39,0,5,11,39,0,6,12,39,0,1,9,38,0,2,11,38,0,3,12,38,0,4,15,40,0,5,17,40,0,6,18,40,0
};
static constexpr double c2_1[] = {
    1.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,4.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,4.0,4.0,4.0,4.0,4.0,4.0
};
static constexpr int32_t o2_1[] = {
    0,3,6,10,14,18,22,27,31,35,39,43,48,53,58,63,68,73,78,83,88,93,98,103,108,113,118,123,128,133,138,143,148,153
};
static constexpr uint16_t f2_1[] = {
    9,27,0,15,28,0,21,1,47,0,24,1,48,0,1,3,36,0,1,6,39,0,1,1,15,43,0,21,4,49,0,24,4,50,0,3,4,37,0,4,6,40,0,1,1,9,41,0,4,4,9,44,0,4,4,15,45,0,1,2,17,43,0,1,3,18,43,0,1,4,9,43,0,1,5,11,43,0,1,6,12,43,0,1,2,11,41,0,1,3,12,41,0,1,5,17,44,0,1,6,18,44,0,2,4,17,44,0,3,4,18,44,0,4,5,11,44,0,4,6,12,44,0,1,4,9,42,0,1,4,15,44,0,2,4,11,42,0,3,4,12,42,0,4,5,17,45,0,4,6,18,45,0
};
static constexpr double c2_2[] = {
    1.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,4.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,4.0,4.0,4.0,4.0,4.0,4.0
};
static constexpr int32_t o2_2[] = {
    0,3,6,10,14,18,22,27,31,35,39,43,48,53,58,63,68,73,78,83,88,93,98,103,108,113,118,123,128,133,138,143,148,153
};
static constexpr uint16_t f2_2[] = {
    11,27,0,17,28,0,21,2,47,0,24,2,48,0,2,3,36,0,2,6,39,0,2,2,17,43,0,21,5,49,0,24,5,50,0,3,5,37,0,5,6,40,0,2,2,11,41,0,5,5,11,44,0,5,5,17,45,0,1,2,15,43,0,2,3,18,43,0,2,4,9,43,0,2,5,11,43,0,2,6,12,43,0,1,2,9,41,0,1,5,15,44,0,2,3,12,41,0,2,4,15,44,0,2,6,18,44,0,3,5,18,44,0,4,5,9,44,0,5,6,12,44,0,1,5,9,42,0,2,5,11,42,0,2,5,17,44,0,3,5,12,42,0,4,5,15,45,0,5,6,18,45,0
};
static constexpr double c2_3[] = {
    1.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,4.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,4.0,4.0,4.0,4.0,4.0,4.0
};
static constexpr int32_t o2_3[] = {
    0,2,5,9,12,16,20,24,28,33,37,41,45,50,55,60,65,70,75,80,85,90,95,100,105,110,115,120,125,130,135,140,145,150,155
};
static constexpr uint16_t f2_3[] = {
    26,0,12,27,0,3,3,36,0,18,28,0,6,6,40,0,21,3,47,0,24,3,48,0,3,6,39,0,3,3,18,43,0,21,6,49,0,24,6,50,0,3,6,37,0,3,3,12,41,0,6,6,12,44,0,6,6,18,45,0,1,3,15,43,0,2,3,17,43,0,3,4,9,43,0,3,5,11,43,0,3,6,12,43,0,1,3,9,41,0,1,6,15,44,0,2,3,11,41,0,2,6,17,44,0,3,4,15,44,0,3,5,17,44,0,4,6,9,44,0,5,6,11,44,0,1,6,9,42,0,2,6,11,42,0,3,6,12,42,0,3,6,18,44,0,4,6,15,45,0,5,6,17,45,0
};
static constexpr double c2_4[] = {
    1.0
};
static constexpr int32_t o2_4[] = {
    0,2
};
static constexpr uint16_t f2_4[] = {
    25,0
};
static constexpr double c2_5[] = {
    1.0,2.0
};
static constexpr int32_t o2_5[] = {
    0,3,6
};
static constexpr uint16_t f2_5[] = {
    1,27,0,4,28,0
};
static constexpr double c2_6[] = {
    1.0,2.0
};
static constexpr int32_t o2_6[] = {
    0,3,6
};
static constexpr uint16_t f2_6[] = {
    2,27,0,5,28,0
};
static constexpr double c2_7[] = {
    1.0,2.0
};
static constexpr int32_t o2_7[] = {
    0,3,6
};
static constexpr uint16_t f2_7[] = {
    3,27,0,6,28,0
};
static constexpr double c2_8[] = {
    1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0
};
static constexpr int32_t o2_8[] = {
    0,3,6,9,12,16,20,24,28,32,36,40,44,48,52,56,60
};
static constexpr uint16_t f2_8[] = {
    21,29,0,24,30,0,3,33,0,6,35,0,1,15,48,0,2,17,48,0,3,18,48,0,4,9,48,0,5,11,48,0,6,12,48,0,1,9,46,0,2,11,46,0,3,12,46,0,4,15,50,0,5,17,50,0,6,18,50,0
};
static constexpr double c2_9[] = {
    1.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,4.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,4.0,4.0,4.0,4.0,4.0,4.0
};
static constexpr int32_t o2_9[] = {
    0,3,6,10,14,18,22,27,31,35,39,43,48,53,58,63,68,73,78,83,88,93,98,103,108,113,118,123,128,133,138,143,148,153
};
static constexpr uint16_t f2_9[] = {
    9,27,0,15,28,0,21,1,47,0,24,1,48,0,1,3,36,0,1,6,39,0,1,1,15,43,0,21,4,49,0,24,4,50,0,3,4,37,0,4,6,40,0,1,1,9,41,0,4,4,9,44,0,4,4,15,45,0,1,2,17,43,0,1,3,18,43,0,1,4,9,43,0,1,5,11,43,0,1,6,12,43,0,1,2,11,41,0,1,3,12,41,0,1,5,17,44,0,1,6,18,44,0,2,4,17,44,0,3,4,18,44,0,4,5,11,44,0,4,6,12,44,0,1,4,9,42,0,1,4,15,44,0,2,4,11,42,0,3,4,12,42,0,4,5,17,45,0,4,6,18,45,0
};
static constexpr double c2_10[] = {
    2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,4.0,4.0,4.0,4.0,4.0,4.0
};
static constexpr int32_t o2_10[] = {
    0,3,6,9,12,16,20,24,28,32,36,40,44,48,52,56,60
};
static constexpr uint16_t f2_10[] = {
    21,29,0,24,30,0,3,33,0,6,35,0,1,15,48,0,2,17,48,0,3,18,48,0,4,9,48,0,5,11,48,0,6,12,48,0,1,9,46,0,2,11,46,0,3,12,46,0,4,15,50,0,5,17,50,0,6,18,50,0
};
static constexpr double c2_11[] = {
    1.0,2.0
};
static constexpr int32_t o2_11[] = {
    0,3,6
};
static constexpr uint16_t f2_11[] = {
    1,27,0,4,28,0
};
static constexpr double c2_12[] = {
    2.0
};
static constexpr int32_t o2_12[] = {
    0,2
};
static constexpr uint16_t f2_12[] = {
    25,0
};
static constexpr double c2_13[] = {
    1.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,4.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,4.0,4.0,4.0,4.0,4.0,4.0
};
static constexpr int32_t o2_13[] = {
    0,3,6,10,14,18,22,27,31,35,39,43,48,53,58,63,68,73,78,83,88,93,98,103,108,113,118,123,128,133,138,143,148,153
};
static constexpr uint16_t f2_13[] = {
    11,27,0,17,28,0,21,2,47,0,24,2,48,0,2,3,36,0,2,6,39,0,2,2,17,43,0,21,5,49,0,24,5,50,0,3,5,37,0,5,6,40,0,2,2,11,41,0,5,5,11,44,0,5,5,17,45,0,1,2,15,43,0,2,3,18,43,0,2,4,9,43,0,2,5,11,43,0,2,6,12,43,0,1,2,9,41,0,1,5,15,44,0,2,3,12,41,0,2,4,15,44,0,2,6,18,44,0,3,5,18,44,0,4,5,9,44,0,5,6,12,44,0,1,5,9,42,0,2,5,11,42,0,2,5,17,44,0,3,5,12,42,0,4,5,15,45,0,5,6,18,45,0
};
static constexpr double c2_14[] = {
    2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,4.0,4.0,4.0,4.0,4.0,4.0
};
static constexpr int32_t o2_14[] = {
    0,3,6,9,12,16,20,24,28,32,36,40,44,48,52,56,60
};
static constexpr uint16_t f2_14[] = {
    21,29,0,24,30,0,3,33,0,6,35,0,1,15,48,0,2,17,48,0,3,18,48,0,4,9,48,0,5,11,48,0,6,12,48,0,1,9,46,0,2,11,46,0,3,12,46,0,4,15,50,0,5,17,50,0,6,18,50,0
};
static constexpr double c2_15[] = {
    1.0,2.0
};
static constexpr int32_t o2_15[] = {
    0,3,6
};
static constexpr uint16_t f2_15[] = {
    2,27,0,5,28,0
};
static constexpr double c2_16[] = {
    2.0
};
static constexpr int32_t o2_16[] = {
    0,2
};
static constexpr uint16_t f2_16[] = {
    25,0
};
static constexpr double c2_17[] = {
    1.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,4.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,4.0,4.0,4.0,4.0,4.0,4.0
};
static constexpr int32_t o2_17[] = {
    0,2,5,9,12,16,20,24,28,33,37,41,45,50,55,60,65,70,75,80,85,90,95,100,105,110,115,120,125,130,135,140,145,150,155
};
static constexpr uint16_t f2_17[] = {
    26,0,12,27,0,3,3,36,0,18,28,0,6,6,40,0,21,3,47,0,24,3,48,0,3,6,39,0,3,3,18,43,0,21,6,49,0,24,6,50,0,3,6,37,0,3,3,12,41,0,6,6,12,44,0,6,6,18,45,0,1,3,15,43,0,2,3,17,43,0,3,4,9,43,0,3,5,11,43,0,3,6,12,43,0,1,3,9,41,0,1,6,15,44,0,2,3,11,41,0,2,6,17,44,0,3,4,15,44,0,3,5,17,44,0,4,6,9,44,0,5,6,11,44,0,1,6,9,42,0,2,6,11,42,0,3,6,12,42,0,3,6,18,44,0,4,6,15,45,0,5,6,17,45,0
};
static constexpr double c2_18[] = {
    1.0,2.0
};
static constexpr int32_t o2_18[] = {
    0,3,6
};
static constexpr uint16_t f2_18[] = {
    1,27,0,4,28,0
};
static constexpr double c2_19[] = {
    1.0,2.0
};
static constexpr int32_t o2_19[] = {
    0,3,6
};
static constexpr uint16_t f2_19[] = {
    2,27,0,5,28,0
};
static constexpr double c2_20[] = {
    2.0,2.0,2.0,2.0,2.0,4.0,2.0,2.0,2.0,2.0,2.0,2.0,4.0,4.0,4.0,4.0,4.0,4.0
};
static constexpr int32_t o2_20[] = {
    0,3,6,9,12,15,18,22,26,30,34,38,42,46,50,54,58,62,66
};
static constexpr uint16_t f2_20[] = {
    21,29,0,24,30,0,3,33,0,3,27,0,6,35,0,6,28,0,1,15,48,0,2,17,48,0,3,18,48,0,4,9,48,0,5,11,48,0,6,12,48,0,1,9,46,0,2,11,46,0,3,12,46,0,4,15,50,0,5,17,50,0,6,18,50,0
};
static constexpr double c2_21[] = {
    2.0
};
static constexpr int32_t o2_21[] = {
    0,2
};
static constexpr uint16_t f2_21[] = {
    25,0
};
static constexpr double c2_22[] = {
    1.0
};
static constexpr int32_t o2_22[] = {
    0,2
};
static constexpr uint16_t f2_22[] = {
    25,0
};
static constexpr double c2_23[] = {
    1.0
};
static constexpr int32_t o2_23[] = {
    0,2
};
static constexpr uint16_t f2_23[] = {
    25,0
};
static constexpr double c2_24[] = {
    1.0,2.0
};
static constexpr int32_t o2_24[] = {
    0,3,6
};
static constexpr uint16_t f2_24[] = {
    1,27,0,4,28,0
};
static constexpr double c2_25[] = {
    2.0
};
static constexpr int32_t o2_25[] = {
    0,2
};
static constexpr uint16_t f2_25[] = {
    25,0
};
static constexpr double c2_26[] = {
    1.0,2.0
};
static constexpr int32_t o2_26[] = {
    0,3,6
};
static constexpr uint16_t f2_26[] = {
    2,27,0,5,28,0
};
static constexpr double c2_27[] = {
    2.0
};
static constexpr int32_t o2_27[] = {
    0,2
};
static constexpr uint16_t f2_27[] = {
    25,0
};
static constexpr double c2_28[] = {
    1.0,2.0
};
static constexpr int32_t o2_28[] = {
    0,3,6
};
static constexpr uint16_t f2_28[] = {
    3,27,0,6,28,0
};
static constexpr double c2_29[] = {
    2.0
};
static constexpr int32_t o2_29[] = {
    0,2
};
static constexpr uint16_t f2_29[] = {
    25,0
};
static constexpr double c2_30[] = {
    1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0
};
static constexpr int32_t o2_30[] = {
    0,3,6,9,12,16,20,24,28,32,36,40,44,48,52,56,60
};
static constexpr uint16_t f2_30[] = {
    21,29,0,24,30,0,3,33,0,6,35,0,1,15,48,0,2,17,48,0,3,18,48,0,4,9,48,0,5,11,48,0,6,12,48,0,1,9,46,0,2,11,46,0,3,12,46,0,4,15,50,0,5,17,50,0,6,18,50,0
};
static constexpr double c2_31[] = {
    1.0
};
static constexpr int32_t o2_31[] = {
    0,2
};
static constexpr uint16_t f2_31[] = {
    25,0
};
static constexpr int64_t NFLD = 25;
} // namespace detail_xck_mgga_lapl_ub_fg

/* Scratch (elements of T) the kernel needs: pass at least this
 * much as `work`, or nullptr to allocate it internally. */
inline int64_t xck_mgga_lapl_ub_fg_work(int64_t npts, int64_t nbf) {
    const int64_t blk = npts < grid_block ? npts : grid_block;
    return blk * (1 + nbf * 5) + 6 * npts + 1;
}

/* fields: the per-point tower operands (type T), in the order
 * of xck_mgga_lapl_ub_fg_scal_names; xc: the functional-derivative arrays
 * (type Txc; Libxc computes in double whatever T is). */
template <typename T, typename Txc = T>
int xck_mgga_lapl_ub_fg_t(int64_t npts,
        int64_t nbf,
        const T* chi,
        const T* const* fields,
        const Txc* const* xc,
        T* out,
        T* work = nullptr) {
    const int64_t blk = npts < grid_block ? npts : grid_block;
    T* c = work;
    bool own = false;
    if (!c) {
        c = new (std::nothrow) T[xck_mgga_lapl_ub_fg_work(npts, nbf)];
        own = true;
    }
    if (!c) return 1;
    T* W = c + blk;
    const T* Wc = W;
    T* X0 = W + (int64_t)1*nbf*blk;
    T* X1 = W + (int64_t)2*nbf*blk;
    T* X2 = W + (int64_t)3*nbf*blk;
    T* X3 = W + (int64_t)4*nbf*blk;
    T* S0 = c + blk * (1 + nbf * 5) + (int64_t)0*npts;
    {
        const T* s_[] = {fields[19], fields[20], fields[21]};
        static constexpr double w_[] = {1.0, 1.0, 1.0};
        combine<T>(npts, 1, 3, s_, w_, 0, S0);
    }
    T* S1 = c + blk * (1 + nbf * 5) + (int64_t)1*npts;
    {
        const T* s_[] = {fields[22], fields[23], fields[24]};
        static constexpr double w_[] = {1.0, 1.0, 1.0};
        combine<T>(npts, 1, 3, s_, w_, 0, S1);
    }
    T* S2 = c + blk * (1 + nbf * 5) + (int64_t)2*npts;
    {
        const T* s_[] = {fields[25], fields[26], fields[27]};
        static constexpr double w_[] = {1.0, 1.0, 1.0};
        combine<T>(npts, 1, 3, s_, w_, 0, S2);
    }
    T* S3 = c + blk * (1 + nbf * 5) + (int64_t)3*npts;
    {
        const T* s_[] = {fields[28], fields[29], fields[30]};
        static constexpr double w_[] = {1.0, 1.0, 1.0};
        combine<T>(npts, 1, 3, s_, w_, 0, S3);
    }
    T* S4 = c + blk * (1 + nbf * 5) + (int64_t)4*npts;
    {
        const T* s_[] = {fields[31], fields[32], fields[33]};
        static constexpr double w_[] = {1.0, 1.0, 1.0};
        combine<T>(npts, 1, 3, s_, w_, 0, S4);
    }
    T* S5 = c + blk * (1 + nbf * 5) + (int64_t)5*npts;
    {
        const T* s_[] = {fields[34], fields[35], fields[36]};
        static constexpr double w_[] = {1.0, 1.0, 1.0};
        combine<T>(npts, 1, 3, s_, w_, 0, S5);
    }
    const T* fi[25] = {fields[0], fields[1], fields[2], fields[3], fields[4], fields[5], fields[6], fields[7], fields[8], fields[9], fields[10], fields[11], fields[12], fields[13], fields[14], fields[15], fields[16], fields[17], fields[18], S0, S1, S2, S3, S4, S5};
    for (int64_t g0 = 0; g0 < npts; g0 += blk) {
        const int64_t bk = npts - g0 < blk ? npts - g0 : blk;
        {
            const T* s_[] = {chi + (int64_t)10*nbf*npts + g0, chi + (int64_t)13*nbf*npts + g0, chi + (int64_t)15*nbf*npts + g0};
            static constexpr double w_[] = {1.0, 1.0, 1.0};
            combine<T>(bk, nbf, 3, s_, w_, npts, X0);
        }
        {
            const T* s_[] = {chi + (int64_t)11*nbf*npts + g0, chi + (int64_t)16*nbf*npts + g0, chi + (int64_t)18*nbf*npts + g0};
            static constexpr double w_[] = {1.0, 1.0, 1.0};
            combine<T>(bk, nbf, 3, s_, w_, npts, X1);
        }
        {
            const T* s_[] = {chi + (int64_t)12*nbf*npts + g0, chi + (int64_t)17*nbf*npts + g0, chi + (int64_t)19*nbf*npts + g0};
            static constexpr double w_[] = {1.0, 1.0, 1.0};
            combine<T>(bk, nbf, 3, s_, w_, npts, X2);
        }
        {
            const T* s_[] = {chi + (int64_t)4*nbf*npts + g0, chi + (int64_t)7*nbf*npts + g0, chi + (int64_t)9*nbf*npts + g0};
            static constexpr double w_[] = {1.0, 1.0, 1.0};
            combine<T>(bk, nbf, 3, s_, w_, npts, X3);
        }
        stage_a<T, Txc>(g0, bk, 16, detail_xck_mgga_lapl_ub_fg::c0_0, detail_xck_mgga_lapl_ub_fg::o0_0, detail_xck_mgga_lapl_ub_fg::f0_0, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 34, detail_xck_mgga_lapl_ub_fg::c0_1, detail_xck_mgga_lapl_ub_fg::o0_1, detail_xck_mgga_lapl_ub_fg::f0_1, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)1*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 33, detail_xck_mgga_lapl_ub_fg::c0_2, detail_xck_mgga_lapl_ub_fg::o0_2, detail_xck_mgga_lapl_ub_fg::f0_2, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)2*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 33, detail_xck_mgga_lapl_ub_fg::c0_3, detail_xck_mgga_lapl_ub_fg::o0_3, detail_xck_mgga_lapl_ub_fg::f0_3, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)3*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_lapl_ub_fg::c0_4, detail_xck_mgga_lapl_ub_fg::o0_4, detail_xck_mgga_lapl_ub_fg::f0_4, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, X0, bk, W, 0);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_lapl_ub_fg::c0_5, detail_xck_mgga_lapl_ub_fg::o0_5, detail_xck_mgga_lapl_ub_fg::f0_5, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)4*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_lapl_ub_fg::c0_6, detail_xck_mgga_lapl_ub_fg::o0_6, detail_xck_mgga_lapl_ub_fg::f0_6, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)5*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_lapl_ub_fg::c0_7, detail_xck_mgga_lapl_ub_fg::o0_7, detail_xck_mgga_lapl_ub_fg::f0_7, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)6*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 16, detail_xck_mgga_lapl_ub_fg::c0_8, detail_xck_mgga_lapl_ub_fg::o0_8, detail_xck_mgga_lapl_ub_fg::f0_8, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, X3, bk, W, 0);
        gemm_nt(nbf, bk, chi + (int64_t)0*nbf*npts + g0, npts, Wc, bk, out + (int64_t)0*nbf*nbf);
        stage_a<T, Txc>(g0, bk, 34, detail_xck_mgga_lapl_ub_fg::c0_9, detail_xck_mgga_lapl_ub_fg::o0_9, detail_xck_mgga_lapl_ub_fg::f0_9, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 18, detail_xck_mgga_lapl_ub_fg::c0_10, detail_xck_mgga_lapl_ub_fg::o0_10, detail_xck_mgga_lapl_ub_fg::f0_10, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)1*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_lapl_ub_fg::c0_11, detail_xck_mgga_lapl_ub_fg::o0_11, detail_xck_mgga_lapl_ub_fg::f0_11, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)2*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_lapl_ub_fg::c0_12, detail_xck_mgga_lapl_ub_fg::o0_12, detail_xck_mgga_lapl_ub_fg::f0_12, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)3*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_lapl_ub_fg::c0_13, detail_xck_mgga_lapl_ub_fg::o0_13, detail_xck_mgga_lapl_ub_fg::f0_13, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)4*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_lapl_ub_fg::c0_14, detail_xck_mgga_lapl_ub_fg::o0_14, detail_xck_mgga_lapl_ub_fg::f0_14, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, X3, bk, W, 0);
        gemm_nt(nbf, bk, chi + (int64_t)1*nbf*npts + g0, npts, Wc, bk, out + (int64_t)0*nbf*nbf);
        stage_a<T, Txc>(g0, bk, 33, detail_xck_mgga_lapl_ub_fg::c0_15, detail_xck_mgga_lapl_ub_fg::o0_15, detail_xck_mgga_lapl_ub_fg::f0_15, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_lapl_ub_fg::c0_16, detail_xck_mgga_lapl_ub_fg::o0_16, detail_xck_mgga_lapl_ub_fg::f0_16, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)1*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 16, detail_xck_mgga_lapl_ub_fg::c0_17, detail_xck_mgga_lapl_ub_fg::o0_17, detail_xck_mgga_lapl_ub_fg::f0_17, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)2*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_lapl_ub_fg::c0_18, detail_xck_mgga_lapl_ub_fg::o0_18, detail_xck_mgga_lapl_ub_fg::f0_18, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)5*nbf*npts + g0, npts, W, 0);
        gemm_nt(nbf, bk, chi + (int64_t)2*nbf*npts + g0, npts, Wc, bk, out + (int64_t)0*nbf*nbf);
        stage_a<T, Txc>(g0, bk, 33, detail_xck_mgga_lapl_ub_fg::c0_19, detail_xck_mgga_lapl_ub_fg::o0_19, detail_xck_mgga_lapl_ub_fg::f0_19, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_lapl_ub_fg::c0_20, detail_xck_mgga_lapl_ub_fg::o0_20, detail_xck_mgga_lapl_ub_fg::f0_20, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)1*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 16, detail_xck_mgga_lapl_ub_fg::c0_21, detail_xck_mgga_lapl_ub_fg::o0_21, detail_xck_mgga_lapl_ub_fg::f0_21, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)3*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_lapl_ub_fg::c0_22, detail_xck_mgga_lapl_ub_fg::o0_22, detail_xck_mgga_lapl_ub_fg::f0_22, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)6*nbf*npts + g0, npts, W, 0);
        gemm_nt(nbf, bk, chi + (int64_t)3*nbf*npts + g0, npts, Wc, bk, out + (int64_t)0*nbf*nbf);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_lapl_ub_fg::c0_23, detail_xck_mgga_lapl_ub_fg::o0_23, detail_xck_mgga_lapl_ub_fg::f0_23, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        gemm_nt(nbf, bk, X0, bk, Wc, bk, out + (int64_t)0*nbf*nbf);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_lapl_ub_fg::c0_24, detail_xck_mgga_lapl_ub_fg::o0_24, detail_xck_mgga_lapl_ub_fg::f0_24, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_lapl_ub_fg::c0_25, detail_xck_mgga_lapl_ub_fg::o0_25, detail_xck_mgga_lapl_ub_fg::f0_25, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)1*nbf*npts + g0, npts, W, 0);
        gemm_nt(nbf, bk, chi + (int64_t)4*nbf*npts + g0, npts, Wc, bk, out + (int64_t)0*nbf*nbf);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_lapl_ub_fg::c0_26, detail_xck_mgga_lapl_ub_fg::o0_26, detail_xck_mgga_lapl_ub_fg::f0_26, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_lapl_ub_fg::c0_27, detail_xck_mgga_lapl_ub_fg::o0_27, detail_xck_mgga_lapl_ub_fg::f0_27, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)2*nbf*npts + g0, npts, W, 0);
        gemm_nt(nbf, bk, chi + (int64_t)5*nbf*npts + g0, npts, Wc, bk, out + (int64_t)0*nbf*nbf);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_lapl_ub_fg::c0_28, detail_xck_mgga_lapl_ub_fg::o0_28, detail_xck_mgga_lapl_ub_fg::f0_28, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_lapl_ub_fg::c0_29, detail_xck_mgga_lapl_ub_fg::o0_29, detail_xck_mgga_lapl_ub_fg::f0_29, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)3*nbf*npts + g0, npts, W, 0);
        gemm_nt(nbf, bk, chi + (int64_t)6*nbf*npts + g0, npts, Wc, bk, out + (int64_t)0*nbf*nbf);
        stage_a<T, Txc>(g0, bk, 16, detail_xck_mgga_lapl_ub_fg::c0_30, detail_xck_mgga_lapl_ub_fg::o0_30, detail_xck_mgga_lapl_ub_fg::f0_30, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_lapl_ub_fg::c0_31, detail_xck_mgga_lapl_ub_fg::o0_31, detail_xck_mgga_lapl_ub_fg::f0_31, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)1*nbf*npts + g0, npts, W, 0);
        gemm_nt(nbf, bk, X3, bk, Wc, bk, out + (int64_t)0*nbf*nbf);
        stage_a<T, Txc>(g0, bk, 16, detail_xck_mgga_lapl_ub_fg::c1_0, detail_xck_mgga_lapl_ub_fg::o1_0, detail_xck_mgga_lapl_ub_fg::f1_0, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 33, detail_xck_mgga_lapl_ub_fg::c1_1, detail_xck_mgga_lapl_ub_fg::o1_1, detail_xck_mgga_lapl_ub_fg::f1_1, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)1*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 34, detail_xck_mgga_lapl_ub_fg::c1_2, detail_xck_mgga_lapl_ub_fg::o1_2, detail_xck_mgga_lapl_ub_fg::f1_2, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)2*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 33, detail_xck_mgga_lapl_ub_fg::c1_3, detail_xck_mgga_lapl_ub_fg::o1_3, detail_xck_mgga_lapl_ub_fg::f1_3, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)3*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_lapl_ub_fg::c1_4, detail_xck_mgga_lapl_ub_fg::o1_4, detail_xck_mgga_lapl_ub_fg::f1_4, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, X1, bk, W, 0);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_lapl_ub_fg::c1_5, detail_xck_mgga_lapl_ub_fg::o1_5, detail_xck_mgga_lapl_ub_fg::f1_5, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)5*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_lapl_ub_fg::c1_6, detail_xck_mgga_lapl_ub_fg::o1_6, detail_xck_mgga_lapl_ub_fg::f1_6, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)7*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_lapl_ub_fg::c1_7, detail_xck_mgga_lapl_ub_fg::o1_7, detail_xck_mgga_lapl_ub_fg::f1_7, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)8*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 16, detail_xck_mgga_lapl_ub_fg::c1_8, detail_xck_mgga_lapl_ub_fg::o1_8, detail_xck_mgga_lapl_ub_fg::f1_8, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, X3, bk, W, 0);
        gemm_nt(nbf, bk, chi + (int64_t)0*nbf*npts + g0, npts, Wc, bk, out + (int64_t)1*nbf*nbf);
        stage_a<T, Txc>(g0, bk, 33, detail_xck_mgga_lapl_ub_fg::c1_9, detail_xck_mgga_lapl_ub_fg::o1_9, detail_xck_mgga_lapl_ub_fg::f1_9, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 16, detail_xck_mgga_lapl_ub_fg::c1_10, detail_xck_mgga_lapl_ub_fg::o1_10, detail_xck_mgga_lapl_ub_fg::f1_10, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)1*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_lapl_ub_fg::c1_11, detail_xck_mgga_lapl_ub_fg::o1_11, detail_xck_mgga_lapl_ub_fg::f1_11, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)2*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_lapl_ub_fg::c1_12, detail_xck_mgga_lapl_ub_fg::o1_12, detail_xck_mgga_lapl_ub_fg::f1_12, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)5*nbf*npts + g0, npts, W, 0);
        gemm_nt(nbf, bk, chi + (int64_t)1*nbf*npts + g0, npts, Wc, bk, out + (int64_t)1*nbf*nbf);
        stage_a<T, Txc>(g0, bk, 34, detail_xck_mgga_lapl_ub_fg::c1_13, detail_xck_mgga_lapl_ub_fg::o1_13, detail_xck_mgga_lapl_ub_fg::f1_13, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_lapl_ub_fg::c1_14, detail_xck_mgga_lapl_ub_fg::o1_14, detail_xck_mgga_lapl_ub_fg::f1_14, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)1*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 18, detail_xck_mgga_lapl_ub_fg::c1_15, detail_xck_mgga_lapl_ub_fg::o1_15, detail_xck_mgga_lapl_ub_fg::f1_15, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)2*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_lapl_ub_fg::c1_16, detail_xck_mgga_lapl_ub_fg::o1_16, detail_xck_mgga_lapl_ub_fg::f1_16, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)3*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_lapl_ub_fg::c1_17, detail_xck_mgga_lapl_ub_fg::o1_17, detail_xck_mgga_lapl_ub_fg::f1_17, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)7*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_lapl_ub_fg::c1_18, detail_xck_mgga_lapl_ub_fg::o1_18, detail_xck_mgga_lapl_ub_fg::f1_18, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, X3, bk, W, 0);
        gemm_nt(nbf, bk, chi + (int64_t)2*nbf*npts + g0, npts, Wc, bk, out + (int64_t)1*nbf*nbf);
        stage_a<T, Txc>(g0, bk, 33, detail_xck_mgga_lapl_ub_fg::c1_19, detail_xck_mgga_lapl_ub_fg::o1_19, detail_xck_mgga_lapl_ub_fg::f1_19, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_lapl_ub_fg::c1_20, detail_xck_mgga_lapl_ub_fg::o1_20, detail_xck_mgga_lapl_ub_fg::f1_20, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)2*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 16, detail_xck_mgga_lapl_ub_fg::c1_21, detail_xck_mgga_lapl_ub_fg::o1_21, detail_xck_mgga_lapl_ub_fg::f1_21, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)3*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_lapl_ub_fg::c1_22, detail_xck_mgga_lapl_ub_fg::o1_22, detail_xck_mgga_lapl_ub_fg::f1_22, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)8*nbf*npts + g0, npts, W, 0);
        gemm_nt(nbf, bk, chi + (int64_t)3*nbf*npts + g0, npts, Wc, bk, out + (int64_t)1*nbf*nbf);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_lapl_ub_fg::c1_23, detail_xck_mgga_lapl_ub_fg::o1_23, detail_xck_mgga_lapl_ub_fg::f1_23, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        gemm_nt(nbf, bk, X1, bk, Wc, bk, out + (int64_t)1*nbf*nbf);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_lapl_ub_fg::c1_24, detail_xck_mgga_lapl_ub_fg::o1_24, detail_xck_mgga_lapl_ub_fg::f1_24, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_lapl_ub_fg::c1_25, detail_xck_mgga_lapl_ub_fg::o1_25, detail_xck_mgga_lapl_ub_fg::f1_25, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)1*nbf*npts + g0, npts, W, 0);
        gemm_nt(nbf, bk, chi + (int64_t)5*nbf*npts + g0, npts, Wc, bk, out + (int64_t)1*nbf*nbf);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_lapl_ub_fg::c1_26, detail_xck_mgga_lapl_ub_fg::o1_26, detail_xck_mgga_lapl_ub_fg::f1_26, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_lapl_ub_fg::c1_27, detail_xck_mgga_lapl_ub_fg::o1_27, detail_xck_mgga_lapl_ub_fg::f1_27, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)2*nbf*npts + g0, npts, W, 0);
        gemm_nt(nbf, bk, chi + (int64_t)7*nbf*npts + g0, npts, Wc, bk, out + (int64_t)1*nbf*nbf);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_lapl_ub_fg::c1_28, detail_xck_mgga_lapl_ub_fg::o1_28, detail_xck_mgga_lapl_ub_fg::f1_28, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_lapl_ub_fg::c1_29, detail_xck_mgga_lapl_ub_fg::o1_29, detail_xck_mgga_lapl_ub_fg::f1_29, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)3*nbf*npts + g0, npts, W, 0);
        gemm_nt(nbf, bk, chi + (int64_t)8*nbf*npts + g0, npts, Wc, bk, out + (int64_t)1*nbf*nbf);
        stage_a<T, Txc>(g0, bk, 16, detail_xck_mgga_lapl_ub_fg::c1_30, detail_xck_mgga_lapl_ub_fg::o1_30, detail_xck_mgga_lapl_ub_fg::f1_30, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_lapl_ub_fg::c1_31, detail_xck_mgga_lapl_ub_fg::o1_31, detail_xck_mgga_lapl_ub_fg::f1_31, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)2*nbf*npts + g0, npts, W, 0);
        gemm_nt(nbf, bk, X3, bk, Wc, bk, out + (int64_t)1*nbf*nbf);
        stage_a<T, Txc>(g0, bk, 16, detail_xck_mgga_lapl_ub_fg::c2_0, detail_xck_mgga_lapl_ub_fg::o2_0, detail_xck_mgga_lapl_ub_fg::f2_0, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 33, detail_xck_mgga_lapl_ub_fg::c2_1, detail_xck_mgga_lapl_ub_fg::o2_1, detail_xck_mgga_lapl_ub_fg::f2_1, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)1*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 33, detail_xck_mgga_lapl_ub_fg::c2_2, detail_xck_mgga_lapl_ub_fg::o2_2, detail_xck_mgga_lapl_ub_fg::f2_2, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)2*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 34, detail_xck_mgga_lapl_ub_fg::c2_3, detail_xck_mgga_lapl_ub_fg::o2_3, detail_xck_mgga_lapl_ub_fg::f2_3, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)3*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_lapl_ub_fg::c2_4, detail_xck_mgga_lapl_ub_fg::o2_4, detail_xck_mgga_lapl_ub_fg::f2_4, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, X2, bk, W, 0);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_lapl_ub_fg::c2_5, detail_xck_mgga_lapl_ub_fg::o2_5, detail_xck_mgga_lapl_ub_fg::f2_5, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)6*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_lapl_ub_fg::c2_6, detail_xck_mgga_lapl_ub_fg::o2_6, detail_xck_mgga_lapl_ub_fg::f2_6, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)8*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_lapl_ub_fg::c2_7, detail_xck_mgga_lapl_ub_fg::o2_7, detail_xck_mgga_lapl_ub_fg::f2_7, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)9*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 16, detail_xck_mgga_lapl_ub_fg::c2_8, detail_xck_mgga_lapl_ub_fg::o2_8, detail_xck_mgga_lapl_ub_fg::f2_8, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, X3, bk, W, 0);
        gemm_nt(nbf, bk, chi + (int64_t)0*nbf*npts + g0, npts, Wc, bk, out + (int64_t)2*nbf*nbf);
        stage_a<T, Txc>(g0, bk, 33, detail_xck_mgga_lapl_ub_fg::c2_9, detail_xck_mgga_lapl_ub_fg::o2_9, detail_xck_mgga_lapl_ub_fg::f2_9, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 16, detail_xck_mgga_lapl_ub_fg::c2_10, detail_xck_mgga_lapl_ub_fg::o2_10, detail_xck_mgga_lapl_ub_fg::f2_10, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)1*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_lapl_ub_fg::c2_11, detail_xck_mgga_lapl_ub_fg::o2_11, detail_xck_mgga_lapl_ub_fg::f2_11, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)3*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_lapl_ub_fg::c2_12, detail_xck_mgga_lapl_ub_fg::o2_12, detail_xck_mgga_lapl_ub_fg::f2_12, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)6*nbf*npts + g0, npts, W, 0);
        gemm_nt(nbf, bk, chi + (int64_t)1*nbf*npts + g0, npts, Wc, bk, out + (int64_t)2*nbf*nbf);
        stage_a<T, Txc>(g0, bk, 33, detail_xck_mgga_lapl_ub_fg::c2_13, detail_xck_mgga_lapl_ub_fg::o2_13, detail_xck_mgga_lapl_ub_fg::f2_13, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 16, detail_xck_mgga_lapl_ub_fg::c2_14, detail_xck_mgga_lapl_ub_fg::o2_14, detail_xck_mgga_lapl_ub_fg::f2_14, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)2*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_lapl_ub_fg::c2_15, detail_xck_mgga_lapl_ub_fg::o2_15, detail_xck_mgga_lapl_ub_fg::f2_15, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)3*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_lapl_ub_fg::c2_16, detail_xck_mgga_lapl_ub_fg::o2_16, detail_xck_mgga_lapl_ub_fg::f2_16, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)8*nbf*npts + g0, npts, W, 0);
        gemm_nt(nbf, bk, chi + (int64_t)2*nbf*npts + g0, npts, Wc, bk, out + (int64_t)2*nbf*nbf);
        stage_a<T, Txc>(g0, bk, 34, detail_xck_mgga_lapl_ub_fg::c2_17, detail_xck_mgga_lapl_ub_fg::o2_17, detail_xck_mgga_lapl_ub_fg::f2_17, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_lapl_ub_fg::c2_18, detail_xck_mgga_lapl_ub_fg::o2_18, detail_xck_mgga_lapl_ub_fg::f2_18, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)1*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_lapl_ub_fg::c2_19, detail_xck_mgga_lapl_ub_fg::o2_19, detail_xck_mgga_lapl_ub_fg::f2_19, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)2*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 18, detail_xck_mgga_lapl_ub_fg::c2_20, detail_xck_mgga_lapl_ub_fg::o2_20, detail_xck_mgga_lapl_ub_fg::f2_20, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)3*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_lapl_ub_fg::c2_21, detail_xck_mgga_lapl_ub_fg::o2_21, detail_xck_mgga_lapl_ub_fg::f2_21, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)9*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_lapl_ub_fg::c2_22, detail_xck_mgga_lapl_ub_fg::o2_22, detail_xck_mgga_lapl_ub_fg::f2_22, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, X3, bk, W, 0);
        gemm_nt(nbf, bk, chi + (int64_t)3*nbf*npts + g0, npts, Wc, bk, out + (int64_t)2*nbf*nbf);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_lapl_ub_fg::c2_23, detail_xck_mgga_lapl_ub_fg::o2_23, detail_xck_mgga_lapl_ub_fg::f2_23, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        gemm_nt(nbf, bk, X2, bk, Wc, bk, out + (int64_t)2*nbf*nbf);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_lapl_ub_fg::c2_24, detail_xck_mgga_lapl_ub_fg::o2_24, detail_xck_mgga_lapl_ub_fg::f2_24, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_lapl_ub_fg::c2_25, detail_xck_mgga_lapl_ub_fg::o2_25, detail_xck_mgga_lapl_ub_fg::f2_25, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)1*nbf*npts + g0, npts, W, 0);
        gemm_nt(nbf, bk, chi + (int64_t)6*nbf*npts + g0, npts, Wc, bk, out + (int64_t)2*nbf*nbf);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_lapl_ub_fg::c2_26, detail_xck_mgga_lapl_ub_fg::o2_26, detail_xck_mgga_lapl_ub_fg::f2_26, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_lapl_ub_fg::c2_27, detail_xck_mgga_lapl_ub_fg::o2_27, detail_xck_mgga_lapl_ub_fg::f2_27, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)2*nbf*npts + g0, npts, W, 0);
        gemm_nt(nbf, bk, chi + (int64_t)8*nbf*npts + g0, npts, Wc, bk, out + (int64_t)2*nbf*nbf);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_lapl_ub_fg::c2_28, detail_xck_mgga_lapl_ub_fg::o2_28, detail_xck_mgga_lapl_ub_fg::f2_28, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_lapl_ub_fg::c2_29, detail_xck_mgga_lapl_ub_fg::o2_29, detail_xck_mgga_lapl_ub_fg::f2_29, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)3*nbf*npts + g0, npts, W, 0);
        gemm_nt(nbf, bk, chi + (int64_t)9*nbf*npts + g0, npts, Wc, bk, out + (int64_t)2*nbf*nbf);
        stage_a<T, Txc>(g0, bk, 16, detail_xck_mgga_lapl_ub_fg::c2_30, detail_xck_mgga_lapl_ub_fg::o2_30, detail_xck_mgga_lapl_ub_fg::f2_30, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_lapl_ub_fg::c2_31, detail_xck_mgga_lapl_ub_fg::o2_31, detail_xck_mgga_lapl_ub_fg::f2_31, detail_xck_mgga_lapl_ub_fg::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)3*nbf*npts + g0, npts, W, 0);
        gemm_nt(nbf, bk, X3, bk, Wc, bk, out + (int64_t)2*nbf*nbf);
    }
    if (own) delete[] c;
    return 0;
}

} // namespace xckernel
