/* generated by xckernel; do not edit. */
#pragma once
#include <cstdint>
#include <new>
#include "xckernel/evaluator.hpp"

namespace xckernel {
namespace detail_xck_mgga_tau_r_gg {
static constexpr double c0_0[] = {
    1.0,1.0,2.0,2.0,2.0
};
static constexpr int32_t o0_0[] = {
    0,3,6,10,14,18
};
static constexpr uint16_t f0_0[] = {
    1,13,0,10,15,0,1,4,14,0,2,5,14,0,3,6,14,0
};
static constexpr double c1_0[] = {
    1.0,1.0,2.0,2.0,2.0
};
static constexpr int32_t o1_0[] = {
    0,3,6,10,14,18
};
static constexpr uint16_t f1_0[] = {
    2,13,0,11,15,0,1,5,14,0,2,7,14,0,3,8,14,0
};
static constexpr double c2_0[] = {
    1.0,1.0,2.0,2.0,2.0
};
static constexpr int32_t o2_0[] = {
    0,3,6,10,14,18
};
static constexpr uint16_t f2_0[] = {
    3,13,0,12,15,0,1,6,14,0,2,8,14,0,3,9,14,0
};
static constexpr int64_t NFLD = 13;
} // namespace detail_xck_mgga_tau_r_gg

/* Scratch (elements of T) the kernel needs: pass at least this
 * much as `work`, or nullptr to allocate it internally. */
inline int64_t xck_mgga_tau_r_gg_work(int64_t npts, int64_t nbf) {
    const int64_t blk = npts < grid_block ? npts : grid_block;
    return blk * (1 + nbf * 0) + 0 * npts + 1;
}

/* fields: the per-point tower operands (type T), in the order
 * of xck_mgga_tau_r_gg_scal_names; xc: the functional-derivative arrays
 * (type Txc; Libxc computes in double whatever T is). */
template <typename T, typename Txc = T>
int xck_mgga_tau_r_gg_t(int64_t npts,
        const T* const* fields,
        const Txc* const* xc,
        T* out,
        T* work = nullptr) {
    const int64_t blk = npts < grid_block ? npts : grid_block;
    T* c = work;
    bool own = false;
    if (!c) {
        c = new (std::nothrow) T[xck_mgga_tau_r_gg_work(npts, 0)];
        own = true;
    }
    if (!c) return 1;
    const T* fi[13] = {fields[0], fields[1], fields[2], fields[3], fields[4], fields[5], fields[6], fields[7], fields[8], fields[9], fields[10], fields[11], fields[12]};
    for (int64_t g0 = 0; g0 < npts; g0 += blk) {
        const int64_t bk = npts - g0 < blk ? npts - g0 : blk;
        stage_a<T, Txc>(g0, bk, 5, detail_xck_mgga_tau_r_gg::c0_0, detail_xck_mgga_tau_r_gg::o0_0, detail_xck_mgga_tau_r_gg::f0_0, detail_xck_mgga_tau_r_gg::NFLD, fi, xc, c);
        for (int64_t g = 0; g < bk; ++g) out[(int64_t)0*npts + g0 + g] += c[g];
        stage_a<T, Txc>(g0, bk, 5, detail_xck_mgga_tau_r_gg::c1_0, detail_xck_mgga_tau_r_gg::o1_0, detail_xck_mgga_tau_r_gg::f1_0, detail_xck_mgga_tau_r_gg::NFLD, fi, xc, c);
        for (int64_t g = 0; g < bk; ++g) out[(int64_t)1*npts + g0 + g] += c[g];
        stage_a<T, Txc>(g0, bk, 5, detail_xck_mgga_tau_r_gg::c2_0, detail_xck_mgga_tau_r_gg::o2_0, detail_xck_mgga_tau_r_gg::f2_0, detail_xck_mgga_tau_r_gg::NFLD, fi, xc, c);
        for (int64_t g = 0; g < bk; ++g) out[(int64_t)2*npts + g0 + g] += c[g];
    }
    if (own) delete[] c;
    return 0;
}

} // namespace xckernel
