/* generated by xckernel; do not edit. */
#pragma once
#include <cstdint>
#include <new>
#include "xckernel/evaluator.hpp"

namespace xckernel {
namespace detail_xck_cmgga_tau_u_gg {
static constexpr double c0_0[] = {
    1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,0.5,0.5,0.5,0.5,0.5,0.5,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
};
static constexpr int32_t o0_0[] = {
    0,3,6,9,12,16,20,24,28,32,36,40,44,48,52,56,60,67,74,81,88,95,102,107,112,117,122,127,132
};
static constexpr uint16_t f0_0[] = {
    1,51,0,4,52,0,25,56,0,28,57,0,1,19,54,0,2,20,54,0,3,21,54,0,4,13,54,0,5,14,54,0,6,15,54,0,1,13,53,0,2,14,53,0,3,15,53,0,4,19,55,0,5,20,55,0,6,21,55,0,1,49,49,7,7,56,0,1,49,49,8,8,56,0,1,49,49,9,9,56,0,4,50,50,10,10,57,0,4,50,50,11,11,57,0,4,50,50,12,12,57,0,49,7,31,56,0,49,8,34,56,0,49,9,37,56,0,50,10,40,57,0,50,11,43,57,0,50,12,46,57,0
};
static constexpr double c1_0[] = {
    1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,0.5,0.5,0.5,0.5,0.5,0.5,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
};
static constexpr int32_t o1_0[] = {
    0,3,6,9,12,16,20,24,28,32,36,40,44,48,52,56,60,67,74,81,88,95,102,107,112,117,122,127,132
};
static constexpr uint16_t f1_0[] = {
    2,51,0,5,52,0,26,56,0,29,57,0,1,20,54,0,2,22,54,0,3,23,54,0,4,14,54,0,5,16,54,0,6,17,54,0,1,14,53,0,2,16,53,0,3,17,53,0,4,20,55,0,5,22,55,0,6,23,55,0,2,49,49,7,7,56,0,2,49,49,8,8,56,0,2,49,49,9,9,56,0,5,50,50,10,10,57,0,5,50,50,11,11,57,0,5,50,50,12,12,57,0,49,7,32,56,0,49,8,35,56,0,49,9,38,56,0,50,10,41,57,0,50,11,44,57,0,50,12,47,57,0
};
static constexpr double c2_0[] = {
    1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,0.5,0.5,0.5,0.5,0.5,0.5,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
};
static constexpr int32_t o2_0[] = {
    0,3,6,9,12,16,20,24,28,32,36,40,44,48,52,56,60,67,74,81,88,95,102,107,112,117,122,127,132
};
static constexpr uint16_t f2_0[] = {
    3,51,0,6,52,0,27,56,0,30,57,0,1,21,54,0,2,23,54,0,3,24,54,0,4,15,54,0,5,17,54,0,6,18,54,0,1,15,53,0,2,17,53,0,3,18,53,0,4,21,55,0,5,23,55,0,6,24,55,0,3,49,49,7,7,56,0,3,49,49,8,8,56,0,3,49,49,9,9,56,0,6,50,50,10,10,57,0,6,50,50,11,11,57,0,6,50,50,12,12,57,0,49,7,33,56,0,49,8,36,56,0,49,9,39,56,0,50,10,42,57,0,50,11,45,57,0,50,12,48,57,0
};
static constexpr int64_t NFLD = 51;
} // namespace detail_xck_cmgga_tau_u_gg

/* Scratch (elements of T) the kernel needs: pass at least this
 * much as `work`, or nullptr to allocate it internally. */
inline int64_t xck_cmgga_tau_u_gg_work(int64_t npts, int64_t nbf) {
    const int64_t blk = npts < grid_block ? npts : grid_block;
    return blk * (1 + nbf * 0) + 0 * npts + 1;
}

/* fields: the per-point tower operands (type T), in the order
 * of xck_cmgga_tau_u_gg_scal_names; xc: the functional-derivative arrays
 * (type Txc; Libxc computes in double whatever T is). */
template <typename T, typename Txc = T>
int xck_cmgga_tau_u_gg_t(int64_t npts,
        const T* const* fields,
        const Txc* const* xc,
        T* out,
        T* work = nullptr) {
    const int64_t blk = npts < grid_block ? npts : grid_block;
    T* c = work;
    bool own = false;
    if (!c) {
        c = new (std::nothrow) T[xck_cmgga_tau_u_gg_work(npts, 0)];
        own = true;
    }
    if (!c) return 1;
    const T* fi[51] = {fields[0], fields[1], fields[2], fields[3], fields[4], fields[5], fields[6], fields[7], fields[8], fields[9], fields[10], fields[11], fields[12], fields[13], fields[14], fields[15], fields[16], fields[17], fields[18], fields[19], fields[20], fields[21], fields[22], fields[23], fields[24], fields[25], fields[26], fields[27], fields[28], fields[29], fields[30], fields[31], fields[32], fields[33], fields[34], fields[35], fields[36], fields[37], fields[38], fields[39], fields[40], fields[41], fields[42], fields[43], fields[44], fields[45], fields[46], fields[47], fields[48], fields[49], fields[50]};
    for (int64_t g0 = 0; g0 < npts; g0 += blk) {
        const int64_t bk = npts - g0 < blk ? npts - g0 : blk;
        stage_a<T, Txc>(g0, bk, 28, detail_xck_cmgga_tau_u_gg::c0_0, detail_xck_cmgga_tau_u_gg::o0_0, detail_xck_cmgga_tau_u_gg::f0_0, detail_xck_cmgga_tau_u_gg::NFLD, fi, xc, c);
        for (int64_t g = 0; g < bk; ++g) out[(int64_t)0*npts + g0 + g] += c[g];
        stage_a<T, Txc>(g0, bk, 28, detail_xck_cmgga_tau_u_gg::c1_0, detail_xck_cmgga_tau_u_gg::o1_0, detail_xck_cmgga_tau_u_gg::f1_0, detail_xck_cmgga_tau_u_gg::NFLD, fi, xc, c);
        for (int64_t g = 0; g < bk; ++g) out[(int64_t)1*npts + g0 + g] += c[g];
        stage_a<T, Txc>(g0, bk, 28, detail_xck_cmgga_tau_u_gg::c2_0, detail_xck_cmgga_tau_u_gg::o2_0, detail_xck_cmgga_tau_u_gg::f2_0, detail_xck_cmgga_tau_u_gg::NFLD, fi, xc, c);
        for (int64_t g = 0; g < bk; ++g) out[(int64_t)2*npts + g0 + g] += c[g];
    }
    if (own) delete[] c;
    return 0;
}

} // namespace xckernel
