/* generated by xckernel; do not edit. */
#pragma once
#include <cstdint>
#include <new>
#include "xckernel/evaluator.hpp"

namespace xckernel {
namespace detail_xck_cmgga_tau_ua_g1 {
static constexpr double c0_0[] = {
    -1.0,-0.5,-0.5,-0.5
};
static constexpr int32_t o0_0[] = {
    0,2,8,14,20
};
static constexpr uint16_t f0_0[] = {
    11,0,10,10,7,7,14,0,10,10,8,8,14,0,10,10,9,9,14,0
};
static constexpr double c0_1[] = {
    -1.0,-2.0,0.5
};
static constexpr int32_t o0_1[] = {
    0,3,6,10
};
static constexpr uint16_t f0_1[] = {
    4,13,0,1,12,0,10,7,14,0
};
static constexpr double c0_2[] = {
    -1.0,-2.0,0.5
};
static constexpr int32_t o0_2[] = {
    0,3,6,10
};
static constexpr uint16_t f0_2[] = {
    5,13,0,2,12,0,10,8,14,0
};
static constexpr double c0_3[] = {
    -1.0,-2.0,0.5
};
static constexpr int32_t o0_3[] = {
    0,3,6,10
};
static constexpr uint16_t f0_3[] = {
    6,13,0,3,12,0,10,9,14,0
};
static constexpr double c0_4[] = {
    -1.0,-0.5,-0.5,-0.5
};
static constexpr int32_t o0_4[] = {
    0,2,8,14,20
};
static constexpr uint16_t f0_4[] = {
    11,0,10,10,7,7,14,0,10,10,8,8,14,0,10,10,9,9,14,0
};
static constexpr double c0_5[] = {
    -1.0,-2.0,-0.5
};
static constexpr int32_t o0_5[] = {
    0,3,6,10
};
static constexpr uint16_t f0_5[] = {
    4,13,0,1,12,0,10,7,14,0
};
static constexpr double c0_6[] = {
    -1.0,-2.0,-0.5
};
static constexpr int32_t o0_6[] = {
    0,3,6,10
};
static constexpr uint16_t f0_6[] = {
    5,13,0,2,12,0,10,8,14,0
};
static constexpr double c0_7[] = {
    -1.0,-2.0,-0.5
};
static constexpr int32_t o0_7[] = {
    0,3,6,10
};
static constexpr uint16_t f0_7[] = {
    6,13,0,3,12,0,10,9,14,0
};
static constexpr double c0_8[] = {
    -1.0,-2.0,-0.5
};
static constexpr int32_t o0_8[] = {
    0,3,6,10
};
static constexpr uint16_t f0_8[] = {
    4,13,0,1,12,0,10,7,14,0
};
static constexpr double c0_9[] = {
    -0.5
};
static constexpr int32_t o0_9[] = {
    0,2
};
static constexpr uint16_t f0_9[] = {
    14,0
};
static constexpr double c0_10[] = {
    -1.0,-2.0,0.5
};
static constexpr int32_t o0_10[] = {
    0,3,6,10
};
static constexpr uint16_t f0_10[] = {
    4,13,0,1,12,0,10,7,14,0
};
static constexpr double c0_11[] = {
    -0.5
};
static constexpr int32_t o0_11[] = {
    0,2
};
static constexpr uint16_t f0_11[] = {
    14,0
};
static constexpr double c0_12[] = {
    -1.0,-2.0,-0.5
};
static constexpr int32_t o0_12[] = {
    0,3,6,10
};
static constexpr uint16_t f0_12[] = {
    5,13,0,2,12,0,10,8,14,0
};
static constexpr double c0_13[] = {
    -0.5
};
static constexpr int32_t o0_13[] = {
    0,2
};
static constexpr uint16_t f0_13[] = {
    14,0
};
static constexpr double c0_14[] = {
    -1.0,-2.0,0.5
};
static constexpr int32_t o0_14[] = {
    0,3,6,10
};
static constexpr uint16_t f0_14[] = {
    5,13,0,2,12,0,10,8,14,0
};
static constexpr double c0_15[] = {
    -0.5
};
static constexpr int32_t o0_15[] = {
    0,2
};
static constexpr uint16_t f0_15[] = {
    14,0
};
static constexpr double c0_16[] = {
    -1.0,-2.0,-0.5
};
static constexpr int32_t o0_16[] = {
    0,3,6,10
};
static constexpr uint16_t f0_16[] = {
    6,13,0,3,12,0,10,9,14,0
};
static constexpr double c0_17[] = {
    -0.5
};
static constexpr int32_t o0_17[] = {
    0,2
};
static constexpr uint16_t f0_17[] = {
    14,0
};
static constexpr double c0_18[] = {
    -1.0,-2.0,0.5
};
static constexpr int32_t o0_18[] = {
    0,3,6,10
};
static constexpr uint16_t f0_18[] = {
    6,13,0,3,12,0,10,9,14,0
};
static constexpr double c0_19[] = {
    -0.5
};
static constexpr int32_t o0_19[] = {
    0,2
};
static constexpr uint16_t f0_19[] = {
    14,0
};
static constexpr double c1_0[] = {
    -1.0,-0.5,-0.5,-0.5
};
static constexpr int32_t o1_0[] = {
    0,2,8,14,20
};
static constexpr uint16_t f1_0[] = {
    11,0,10,10,7,7,14,0,10,10,8,8,14,0,10,10,9,9,14,0
};
static constexpr double c1_1[] = {
    -1.0,-2.0,0.5
};
static constexpr int32_t o1_1[] = {
    0,3,6,10
};
static constexpr uint16_t f1_1[] = {
    4,13,0,1,12,0,10,7,14,0
};
static constexpr double c1_2[] = {
    -1.0,-2.0,0.5
};
static constexpr int32_t o1_2[] = {
    0,3,6,10
};
static constexpr uint16_t f1_2[] = {
    5,13,0,2,12,0,10,8,14,0
};
static constexpr double c1_3[] = {
    -1.0,-2.0,0.5
};
static constexpr int32_t o1_3[] = {
    0,3,6,10
};
static constexpr uint16_t f1_3[] = {
    6,13,0,3,12,0,10,9,14,0
};
static constexpr double c1_4[] = {
    -1.0,-0.5,-0.5,-0.5
};
static constexpr int32_t o1_4[] = {
    0,2,8,14,20
};
static constexpr uint16_t f1_4[] = {
    11,0,10,10,7,7,14,0,10,10,8,8,14,0,10,10,9,9,14,0
};
static constexpr double c1_5[] = {
    -1.0,-2.0,-0.5
};
static constexpr int32_t o1_5[] = {
    0,3,6,10
};
static constexpr uint16_t f1_5[] = {
    4,13,0,1,12,0,10,7,14,0
};
static constexpr double c1_6[] = {
    -1.0,-2.0,-0.5
};
static constexpr int32_t o1_6[] = {
    0,3,6,10
};
static constexpr uint16_t f1_6[] = {
    5,13,0,2,12,0,10,8,14,0
};
static constexpr double c1_7[] = {
    -1.0,-2.0,-0.5
};
static constexpr int32_t o1_7[] = {
    0,3,6,10
};
static constexpr uint16_t f1_7[] = {
    6,13,0,3,12,0,10,9,14,0
};
static constexpr double c1_8[] = {
    -1.0,-2.0,-0.5
};
static constexpr int32_t o1_8[] = {
    0,3,6,10
};
static constexpr uint16_t f1_8[] = {
    4,13,0,1,12,0,10,7,14,0
};
static constexpr double c1_9[] = {
    -0.5
};
static constexpr int32_t o1_9[] = {
    0,2
};
static constexpr uint16_t f1_9[] = {
    14,0
};
static constexpr double c1_10[] = {
    -1.0,-2.0,0.5
};
static constexpr int32_t o1_10[] = {
    0,3,6,10
};
static constexpr uint16_t f1_10[] = {
    4,13,0,1,12,0,10,7,14,0
};
static constexpr double c1_11[] = {
    -0.5
};
static constexpr int32_t o1_11[] = {
    0,2
};
static constexpr uint16_t f1_11[] = {
    14,0
};
static constexpr double c1_12[] = {
    -1.0,-2.0,-0.5
};
static constexpr int32_t o1_12[] = {
    0,3,6,10
};
static constexpr uint16_t f1_12[] = {
    5,13,0,2,12,0,10,8,14,0
};
static constexpr double c1_13[] = {
    -0.5
};
static constexpr int32_t o1_13[] = {
    0,2
};
static constexpr uint16_t f1_13[] = {
    14,0
};
static constexpr double c1_14[] = {
    -1.0,-2.0,0.5
};
static constexpr int32_t o1_14[] = {
    0,3,6,10
};
static constexpr uint16_t f1_14[] = {
    5,13,0,2,12,0,10,8,14,0
};
static constexpr double c1_15[] = {
    -0.5
};
static constexpr int32_t o1_15[] = {
    0,2
};
static constexpr uint16_t f1_15[] = {
    14,0
};
static constexpr double c1_16[] = {
    -1.0,-2.0,-0.5
};
static constexpr int32_t o1_16[] = {
    0,3,6,10
};
static constexpr uint16_t f1_16[] = {
    6,13,0,3,12,0,10,9,14,0
};
static constexpr double c1_17[] = {
    -0.5
};
static constexpr int32_t o1_17[] = {
    0,2
};
static constexpr uint16_t f1_17[] = {
    14,0
};
static constexpr double c1_18[] = {
    -1.0,-2.0,0.5
};
static constexpr int32_t o1_18[] = {
    0,3,6,10
};
static constexpr uint16_t f1_18[] = {
    6,13,0,3,12,0,10,9,14,0
};
static constexpr double c1_19[] = {
    -0.5
};
static constexpr int32_t o1_19[] = {
    0,2
};
static constexpr uint16_t f1_19[] = {
    14,0
};
static constexpr double c2_0[] = {
    -1.0,-0.5,-0.5,-0.5
};
static constexpr int32_t o2_0[] = {
    0,2,8,14,20
};
static constexpr uint16_t f2_0[] = {
    11,0,10,10,7,7,14,0,10,10,8,8,14,0,10,10,9,9,14,0
};
static constexpr double c2_1[] = {
    -1.0,-2.0,0.5
};
static constexpr int32_t o2_1[] = {
    0,3,6,10
};
static constexpr uint16_t f2_1[] = {
    4,13,0,1,12,0,10,7,14,0
};
static constexpr double c2_2[] = {
    -1.0,-2.0,0.5
};
static constexpr int32_t o2_2[] = {
    0,3,6,10
};
static constexpr uint16_t f2_2[] = {
    5,13,0,2,12,0,10,8,14,0
};
static constexpr double c2_3[] = {
    -1.0,-2.0,0.5
};
static constexpr int32_t o2_3[] = {
    0,3,6,10
};
static constexpr uint16_t f2_3[] = {
    6,13,0,3,12,0,10,9,14,0
};
static constexpr double c2_4[] = {
    -1.0,-0.5,-0.5,-0.5
};
static constexpr int32_t o2_4[] = {
    0,2,8,14,20
};
static constexpr uint16_t f2_4[] = {
    11,0,10,10,7,7,14,0,10,10,8,8,14,0,10,10,9,9,14,0
};
static constexpr double c2_5[] = {
    -1.0,-2.0,-0.5
};
static constexpr int32_t o2_5[] = {
    0,3,6,10
};
static constexpr uint16_t f2_5[] = {
    4,13,0,1,12,0,10,7,14,0
};
static constexpr double c2_6[] = {
    -1.0,-2.0,-0.5
};
static constexpr int32_t o2_6[] = {
    0,3,6,10
};
static constexpr uint16_t f2_6[] = {
    5,13,0,2,12,0,10,8,14,0
};
static constexpr double c2_7[] = {
    -1.0,-2.0,-0.5
};
static constexpr int32_t o2_7[] = {
    0,3,6,10
};
static constexpr uint16_t f2_7[] = {
    6,13,0,3,12,0,10,9,14,0
};
static constexpr double c2_8[] = {
    -1.0,-2.0,-0.5
};
static constexpr int32_t o2_8[] = {
    0,3,6,10
};
static constexpr uint16_t f2_8[] = {
    4,13,0,1,12,0,10,7,14,0
};
static constexpr double c2_9[] = {
    -0.5
};
static constexpr int32_t o2_9[] = {
    0,2
};
static constexpr uint16_t f2_9[] = {
    14,0
};
static constexpr double c2_10[] = {
    -1.0,-2.0,0.5
};
static constexpr int32_t o2_10[] = {
    0,3,6,10
};
static constexpr uint16_t f2_10[] = {
    4,13,0,1,12,0,10,7,14,0
};
static constexpr double c2_11[] = {
    -0.5
};
static constexpr int32_t o2_11[] = {
    0,2
};
static constexpr uint16_t f2_11[] = {
    14,0
};
static constexpr double c2_12[] = {
    -1.0,-2.0,-0.5
};
static constexpr int32_t o2_12[] = {
    0,3,6,10
};
static constexpr uint16_t f2_12[] = {
    5,13,0,2,12,0,10,8,14,0
};
static constexpr double c2_13[] = {
    -0.5
};
static constexpr int32_t o2_13[] = {
    0,2
};
static constexpr uint16_t f2_13[] = {
    14,0
};
static constexpr double c2_14[] = {
    -1.0,-2.0,0.5
};
static constexpr int32_t o2_14[] = {
    0,3,6,10
};
static constexpr uint16_t f2_14[] = {
    5,13,0,2,12,0,10,8,14,0
};
static constexpr double c2_15[] = {
    -0.5
};
static constexpr int32_t o2_15[] = {
    0,2
};
static constexpr uint16_t f2_15[] = {
    14,0
};
static constexpr double c2_16[] = {
    -1.0,-2.0,-0.5
};
static constexpr int32_t o2_16[] = {
    0,3,6,10
};
static constexpr uint16_t f2_16[] = {
    6,13,0,3,12,0,10,9,14,0
};
static constexpr double c2_17[] = {
    -0.5
};
static constexpr int32_t o2_17[] = {
    0,2
};
static constexpr uint16_t f2_17[] = {
    14,0
};
static constexpr double c2_18[] = {
    -1.0,-2.0,0.5
};
static constexpr int32_t o2_18[] = {
    0,3,6,10
};
static constexpr uint16_t f2_18[] = {
    6,13,0,3,12,0,10,9,14,0
};
static constexpr double c2_19[] = {
    -0.5
};
static constexpr int32_t o2_19[] = {
    0,2
};
static constexpr uint16_t f2_19[] = {
    14,0
};
static constexpr int64_t NFLD = 11;
} // namespace detail_xck_cmgga_tau_ua_g1

/* Scratch (elements of T) the kernel needs: pass at least this
 * much as `work`, or nullptr to allocate it internally. */
inline int64_t xck_cmgga_tau_ua_g1_work(int64_t npts, int64_t nbf) {
    const int64_t blk = npts < grid_block ? npts : grid_block;
    return blk * (1 + nbf * 1) + 0 * npts + 1;
}

/* fields: the per-point tower operands (type T), in the order
 * of xck_cmgga_tau_ua_g1_field_names; xc: the functional-derivative
 * arrays (type Txc; Libxc computes in double whatever T is),
 * in the order of xck_cmgga_tau_ua_g1_xc_names (both below). */
template <typename T, typename Txc = T>
int xck_cmgga_tau_ua_g1_t(int64_t npts,
        int64_t nbf,
        const T* chi,
        const T* Dchi,
        const T* DTchi,
        const T* const* fields,
        const Txc* const* xc,
        T* out,
        T* work = nullptr) {
    const int64_t blk = npts < grid_block ? npts : grid_block;
    T* c = work;
    bool own = false;
    if (!c) {
        c = new (std::nothrow) T[xck_cmgga_tau_ua_g1_work(npts, nbf)];
        own = true;
    }
    if (!c) return 1;
    T* W = c + blk;
    const T* Wc = W;
    const T* fi[11] = {fields[0], fields[1], fields[2], fields[3], fields[4], fields[5], fields[6], fields[7], fields[8], fields[9], fields[10]};
    for (int64_t g0 = 0; g0 < npts; g0 += blk) {
        const int64_t bk = npts - g0 < blk ? npts - g0 : blk;
        stage_a<T, Txc>(g0, bk, 4, detail_xck_cmgga_tau_ua_g1::c0_0, detail_xck_cmgga_tau_ua_g1::o0_0, detail_xck_cmgga_tau_ua_g1::f0_0, detail_xck_cmgga_tau_ua_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 3, detail_xck_cmgga_tau_ua_g1::c0_1, detail_xck_cmgga_tau_ua_g1::o0_1, detail_xck_cmgga_tau_ua_g1::f0_1, detail_xck_cmgga_tau_ua_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)1*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 3, detail_xck_cmgga_tau_ua_g1::c0_2, detail_xck_cmgga_tau_ua_g1::o0_2, detail_xck_cmgga_tau_ua_g1::f0_2, detail_xck_cmgga_tau_ua_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)2*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 3, detail_xck_cmgga_tau_ua_g1::c0_3, detail_xck_cmgga_tau_ua_g1::o0_3, detail_xck_cmgga_tau_ua_g1::f0_3, detail_xck_cmgga_tau_ua_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)3*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 4, detail_xck_cmgga_tau_ua_g1::c0_4, detail_xck_cmgga_tau_ua_g1::o0_4, detail_xck_cmgga_tau_ua_g1::f0_4, detail_xck_cmgga_tau_ua_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, DTchi + (int64_t)0*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 3, detail_xck_cmgga_tau_ua_g1::c0_5, detail_xck_cmgga_tau_ua_g1::o0_5, detail_xck_cmgga_tau_ua_g1::f0_5, detail_xck_cmgga_tau_ua_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, DTchi + (int64_t)1*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 3, detail_xck_cmgga_tau_ua_g1::c0_6, detail_xck_cmgga_tau_ua_g1::o0_6, detail_xck_cmgga_tau_ua_g1::f0_6, detail_xck_cmgga_tau_ua_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, DTchi + (int64_t)2*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 3, detail_xck_cmgga_tau_ua_g1::c0_7, detail_xck_cmgga_tau_ua_g1::o0_7, detail_xck_cmgga_tau_ua_g1::f0_7, detail_xck_cmgga_tau_ua_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, DTchi + (int64_t)3*nbf*npts + g0, npts, W, 0);
        rowdot(nbf, bk, chi + (int64_t)1*nbf*npts + g0, npts, Wc, bk, out + (int64_t)0*nbf);
        stage_a<T, Txc>(g0, bk, 3, detail_xck_cmgga_tau_ua_g1::c0_8, detail_xck_cmgga_tau_ua_g1::o0_8, detail_xck_cmgga_tau_ua_g1::f0_8, detail_xck_cmgga_tau_ua_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_cmgga_tau_ua_g1::c0_9, detail_xck_cmgga_tau_ua_g1::o0_9, detail_xck_cmgga_tau_ua_g1::f0_9, detail_xck_cmgga_tau_ua_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)1*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 3, detail_xck_cmgga_tau_ua_g1::c0_10, detail_xck_cmgga_tau_ua_g1::o0_10, detail_xck_cmgga_tau_ua_g1::f0_10, detail_xck_cmgga_tau_ua_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, DTchi + (int64_t)0*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_cmgga_tau_ua_g1::c0_11, detail_xck_cmgga_tau_ua_g1::o0_11, detail_xck_cmgga_tau_ua_g1::f0_11, detail_xck_cmgga_tau_ua_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, DTchi + (int64_t)1*nbf*npts + g0, npts, W, 0);
        rowdot(nbf, bk, chi + (int64_t)4*nbf*npts + g0, npts, Wc, bk, out + (int64_t)0*nbf);
        stage_a<T, Txc>(g0, bk, 3, detail_xck_cmgga_tau_ua_g1::c0_12, detail_xck_cmgga_tau_ua_g1::o0_12, detail_xck_cmgga_tau_ua_g1::f0_12, detail_xck_cmgga_tau_ua_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_cmgga_tau_ua_g1::c0_13, detail_xck_cmgga_tau_ua_g1::o0_13, detail_xck_cmgga_tau_ua_g1::f0_13, detail_xck_cmgga_tau_ua_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)2*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 3, detail_xck_cmgga_tau_ua_g1::c0_14, detail_xck_cmgga_tau_ua_g1::o0_14, detail_xck_cmgga_tau_ua_g1::f0_14, detail_xck_cmgga_tau_ua_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, DTchi + (int64_t)0*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_cmgga_tau_ua_g1::c0_15, detail_xck_cmgga_tau_ua_g1::o0_15, detail_xck_cmgga_tau_ua_g1::f0_15, detail_xck_cmgga_tau_ua_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, DTchi + (int64_t)2*nbf*npts + g0, npts, W, 0);
        rowdot(nbf, bk, chi + (int64_t)5*nbf*npts + g0, npts, Wc, bk, out + (int64_t)0*nbf);
        stage_a<T, Txc>(g0, bk, 3, detail_xck_cmgga_tau_ua_g1::c0_16, detail_xck_cmgga_tau_ua_g1::o0_16, detail_xck_cmgga_tau_ua_g1::f0_16, detail_xck_cmgga_tau_ua_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_cmgga_tau_ua_g1::c0_17, detail_xck_cmgga_tau_ua_g1::o0_17, detail_xck_cmgga_tau_ua_g1::f0_17, detail_xck_cmgga_tau_ua_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)3*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 3, detail_xck_cmgga_tau_ua_g1::c0_18, detail_xck_cmgga_tau_ua_g1::o0_18, detail_xck_cmgga_tau_ua_g1::f0_18, detail_xck_cmgga_tau_ua_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, DTchi + (int64_t)0*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_cmgga_tau_ua_g1::c0_19, detail_xck_cmgga_tau_ua_g1::o0_19, detail_xck_cmgga_tau_ua_g1::f0_19, detail_xck_cmgga_tau_ua_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, DTchi + (int64_t)3*nbf*npts + g0, npts, W, 0);
        rowdot(nbf, bk, chi + (int64_t)6*nbf*npts + g0, npts, Wc, bk, out + (int64_t)0*nbf);
        stage_a<T, Txc>(g0, bk, 4, detail_xck_cmgga_tau_ua_g1::c1_0, detail_xck_cmgga_tau_ua_g1::o1_0, detail_xck_cmgga_tau_ua_g1::f1_0, detail_xck_cmgga_tau_ua_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 3, detail_xck_cmgga_tau_ua_g1::c1_1, detail_xck_cmgga_tau_ua_g1::o1_1, detail_xck_cmgga_tau_ua_g1::f1_1, detail_xck_cmgga_tau_ua_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)1*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 3, detail_xck_cmgga_tau_ua_g1::c1_2, detail_xck_cmgga_tau_ua_g1::o1_2, detail_xck_cmgga_tau_ua_g1::f1_2, detail_xck_cmgga_tau_ua_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)2*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 3, detail_xck_cmgga_tau_ua_g1::c1_3, detail_xck_cmgga_tau_ua_g1::o1_3, detail_xck_cmgga_tau_ua_g1::f1_3, detail_xck_cmgga_tau_ua_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)3*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 4, detail_xck_cmgga_tau_ua_g1::c1_4, detail_xck_cmgga_tau_ua_g1::o1_4, detail_xck_cmgga_tau_ua_g1::f1_4, detail_xck_cmgga_tau_ua_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, DTchi + (int64_t)0*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 3, detail_xck_cmgga_tau_ua_g1::c1_5, detail_xck_cmgga_tau_ua_g1::o1_5, detail_xck_cmgga_tau_ua_g1::f1_5, detail_xck_cmgga_tau_ua_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, DTchi + (int64_t)1*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 3, detail_xck_cmgga_tau_ua_g1::c1_6, detail_xck_cmgga_tau_ua_g1::o1_6, detail_xck_cmgga_tau_ua_g1::f1_6, detail_xck_cmgga_tau_ua_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, DTchi + (int64_t)2*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 3, detail_xck_cmgga_tau_ua_g1::c1_7, detail_xck_cmgga_tau_ua_g1::o1_7, detail_xck_cmgga_tau_ua_g1::f1_7, detail_xck_cmgga_tau_ua_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, DTchi + (int64_t)3*nbf*npts + g0, npts, W, 0);
        rowdot(nbf, bk, chi + (int64_t)2*nbf*npts + g0, npts, Wc, bk, out + (int64_t)1*nbf);
        stage_a<T, Txc>(g0, bk, 3, detail_xck_cmgga_tau_ua_g1::c1_8, detail_xck_cmgga_tau_ua_g1::o1_8, detail_xck_cmgga_tau_ua_g1::f1_8, detail_xck_cmgga_tau_ua_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_cmgga_tau_ua_g1::c1_9, detail_xck_cmgga_tau_ua_g1::o1_9, detail_xck_cmgga_tau_ua_g1::f1_9, detail_xck_cmgga_tau_ua_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)1*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 3, detail_xck_cmgga_tau_ua_g1::c1_10, detail_xck_cmgga_tau_ua_g1::o1_10, detail_xck_cmgga_tau_ua_g1::f1_10, detail_xck_cmgga_tau_ua_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, DTchi + (int64_t)0*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_cmgga_tau_ua_g1::c1_11, detail_xck_cmgga_tau_ua_g1::o1_11, detail_xck_cmgga_tau_ua_g1::f1_11, detail_xck_cmgga_tau_ua_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, DTchi + (int64_t)1*nbf*npts + g0, npts, W, 0);
        rowdot(nbf, bk, chi + (int64_t)5*nbf*npts + g0, npts, Wc, bk, out + (int64_t)1*nbf);
        stage_a<T, Txc>(g0, bk, 3, detail_xck_cmgga_tau_ua_g1::c1_12, detail_xck_cmgga_tau_ua_g1::o1_12, detail_xck_cmgga_tau_ua_g1::f1_12, detail_xck_cmgga_tau_ua_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_cmgga_tau_ua_g1::c1_13, detail_xck_cmgga_tau_ua_g1::o1_13, detail_xck_cmgga_tau_ua_g1::f1_13, detail_xck_cmgga_tau_ua_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)2*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 3, detail_xck_cmgga_tau_ua_g1::c1_14, detail_xck_cmgga_tau_ua_g1::o1_14, detail_xck_cmgga_tau_ua_g1::f1_14, detail_xck_cmgga_tau_ua_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, DTchi + (int64_t)0*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_cmgga_tau_ua_g1::c1_15, detail_xck_cmgga_tau_ua_g1::o1_15, detail_xck_cmgga_tau_ua_g1::f1_15, detail_xck_cmgga_tau_ua_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, DTchi + (int64_t)2*nbf*npts + g0, npts, W, 0);
        rowdot(nbf, bk, chi + (int64_t)7*nbf*npts + g0, npts, Wc, bk, out + (int64_t)1*nbf);
        stage_a<T, Txc>(g0, bk, 3, detail_xck_cmgga_tau_ua_g1::c1_16, detail_xck_cmgga_tau_ua_g1::o1_16, detail_xck_cmgga_tau_ua_g1::f1_16, detail_xck_cmgga_tau_ua_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_cmgga_tau_ua_g1::c1_17, detail_xck_cmgga_tau_ua_g1::o1_17, detail_xck_cmgga_tau_ua_g1::f1_17, detail_xck_cmgga_tau_ua_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)3*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 3, detail_xck_cmgga_tau_ua_g1::c1_18, detail_xck_cmgga_tau_ua_g1::o1_18, detail_xck_cmgga_tau_ua_g1::f1_18, detail_xck_cmgga_tau_ua_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, DTchi + (int64_t)0*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_cmgga_tau_ua_g1::c1_19, detail_xck_cmgga_tau_ua_g1::o1_19, detail_xck_cmgga_tau_ua_g1::f1_19, detail_xck_cmgga_tau_ua_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, DTchi + (int64_t)3*nbf*npts + g0, npts, W, 0);
        rowdot(nbf, bk, chi + (int64_t)8*nbf*npts + g0, npts, Wc, bk, out + (int64_t)1*nbf);
        stage_a<T, Txc>(g0, bk, 4, detail_xck_cmgga_tau_ua_g1::c2_0, detail_xck_cmgga_tau_ua_g1::o2_0, detail_xck_cmgga_tau_ua_g1::f2_0, detail_xck_cmgga_tau_ua_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 3, detail_xck_cmgga_tau_ua_g1::c2_1, detail_xck_cmgga_tau_ua_g1::o2_1, detail_xck_cmgga_tau_ua_g1::f2_1, detail_xck_cmgga_tau_ua_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)1*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 3, detail_xck_cmgga_tau_ua_g1::c2_2, detail_xck_cmgga_tau_ua_g1::o2_2, detail_xck_cmgga_tau_ua_g1::f2_2, detail_xck_cmgga_tau_ua_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)2*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 3, detail_xck_cmgga_tau_ua_g1::c2_3, detail_xck_cmgga_tau_ua_g1::o2_3, detail_xck_cmgga_tau_ua_g1::f2_3, detail_xck_cmgga_tau_ua_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)3*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 4, detail_xck_cmgga_tau_ua_g1::c2_4, detail_xck_cmgga_tau_ua_g1::o2_4, detail_xck_cmgga_tau_ua_g1::f2_4, detail_xck_cmgga_tau_ua_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, DTchi + (int64_t)0*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 3, detail_xck_cmgga_tau_ua_g1::c2_5, detail_xck_cmgga_tau_ua_g1::o2_5, detail_xck_cmgga_tau_ua_g1::f2_5, detail_xck_cmgga_tau_ua_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, DTchi + (int64_t)1*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 3, detail_xck_cmgga_tau_ua_g1::c2_6, detail_xck_cmgga_tau_ua_g1::o2_6, detail_xck_cmgga_tau_ua_g1::f2_6, detail_xck_cmgga_tau_ua_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, DTchi + (int64_t)2*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 3, detail_xck_cmgga_tau_ua_g1::c2_7, detail_xck_cmgga_tau_ua_g1::o2_7, detail_xck_cmgga_tau_ua_g1::f2_7, detail_xck_cmgga_tau_ua_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, DTchi + (int64_t)3*nbf*npts + g0, npts, W, 0);
        rowdot(nbf, bk, chi + (int64_t)3*nbf*npts + g0, npts, Wc, bk, out + (int64_t)2*nbf);
        stage_a<T, Txc>(g0, bk, 3, detail_xck_cmgga_tau_ua_g1::c2_8, detail_xck_cmgga_tau_ua_g1::o2_8, detail_xck_cmgga_tau_ua_g1::f2_8, detail_xck_cmgga_tau_ua_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_cmgga_tau_ua_g1::c2_9, detail_xck_cmgga_tau_ua_g1::o2_9, detail_xck_cmgga_tau_ua_g1::f2_9, detail_xck_cmgga_tau_ua_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)1*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 3, detail_xck_cmgga_tau_ua_g1::c2_10, detail_xck_cmgga_tau_ua_g1::o2_10, detail_xck_cmgga_tau_ua_g1::f2_10, detail_xck_cmgga_tau_ua_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, DTchi + (int64_t)0*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_cmgga_tau_ua_g1::c2_11, detail_xck_cmgga_tau_ua_g1::o2_11, detail_xck_cmgga_tau_ua_g1::f2_11, detail_xck_cmgga_tau_ua_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, DTchi + (int64_t)1*nbf*npts + g0, npts, W, 0);
        rowdot(nbf, bk, chi + (int64_t)6*nbf*npts + g0, npts, Wc, bk, out + (int64_t)2*nbf);
        stage_a<T, Txc>(g0, bk, 3, detail_xck_cmgga_tau_ua_g1::c2_12, detail_xck_cmgga_tau_ua_g1::o2_12, detail_xck_cmgga_tau_ua_g1::f2_12, detail_xck_cmgga_tau_ua_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_cmgga_tau_ua_g1::c2_13, detail_xck_cmgga_tau_ua_g1::o2_13, detail_xck_cmgga_tau_ua_g1::f2_13, detail_xck_cmgga_tau_ua_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)2*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 3, detail_xck_cmgga_tau_ua_g1::c2_14, detail_xck_cmgga_tau_ua_g1::o2_14, detail_xck_cmgga_tau_ua_g1::f2_14, detail_xck_cmgga_tau_ua_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, DTchi + (int64_t)0*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_cmgga_tau_ua_g1::c2_15, detail_xck_cmgga_tau_ua_g1::o2_15, detail_xck_cmgga_tau_ua_g1::f2_15, detail_xck_cmgga_tau_ua_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, DTchi + (int64_t)2*nbf*npts + g0, npts, W, 0);
        rowdot(nbf, bk, chi + (int64_t)8*nbf*npts + g0, npts, Wc, bk, out + (int64_t)2*nbf);
        stage_a<T, Txc>(g0, bk, 3, detail_xck_cmgga_tau_ua_g1::c2_16, detail_xck_cmgga_tau_ua_g1::o2_16, detail_xck_cmgga_tau_ua_g1::f2_16, detail_xck_cmgga_tau_ua_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_cmgga_tau_ua_g1::c2_17, detail_xck_cmgga_tau_ua_g1::o2_17, detail_xck_cmgga_tau_ua_g1::f2_17, detail_xck_cmgga_tau_ua_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)3*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 3, detail_xck_cmgga_tau_ua_g1::c2_18, detail_xck_cmgga_tau_ua_g1::o2_18, detail_xck_cmgga_tau_ua_g1::f2_18, detail_xck_cmgga_tau_ua_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, DTchi + (int64_t)0*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_cmgga_tau_ua_g1::c2_19, detail_xck_cmgga_tau_ua_g1::o2_19, detail_xck_cmgga_tau_ua_g1::f2_19, detail_xck_cmgga_tau_ua_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, DTchi + (int64_t)3*nbf*npts + g0, npts, W, 0);
        rowdot(nbf, bk, chi + (int64_t)9*nbf*npts + g0, npts, Wc, bk, out + (int64_t)2*nbf);
    }
    if (own) delete[] c;
    return 0;
}


/* Operands of xck_cmgga_tau_ua_g1_t: `fields` in the order of
 * xck_cmgga_tau_ua_g1_field_names, `xc` in the order of xck_cmgga_tau_ua_g1_xc_names (the
 * C ABI's `scal` is the two concatenated, split at n_fields). The
 * structs name them; the overload taking them packs the arrays. */
inline constexpr int xck_cmgga_tau_ua_g1_n_fields = 11;
inline constexpr int xck_cmgga_tau_ua_g1_n_xc = 4;
inline constexpr const char* xck_cmgga_tau_ua_g1_field_names[] = {"w", "rho_a_x", "rho_a_y", "rho_a_z", "rho_b_x", "rho_b_y", "rho_b_z", "jpx_a", "jpy_a", "jpz_a", "inv_rho_a"};
inline constexpr const char* xck_cmgga_tau_ua_g1_xc_names[] = {"vrho_0", "vsigma_0", "vsigma_1", "vtau_0"};
template <typename T>
struct xck_cmgga_tau_ua_g1_fields {
    const T* w;
    const T* rho_a_x;
    const T* rho_a_y;
    const T* rho_a_z;
    const T* rho_b_x;
    const T* rho_b_y;
    const T* rho_b_z;
    const T* jpx_a;
    const T* jpy_a;
    const T* jpz_a;
    const T* inv_rho_a;
};
template <typename Txc>
struct xck_cmgga_tau_ua_g1_xc {
    const Txc* vrho_0;
    const Txc* vsigma_0;
    const Txc* vsigma_1;
    const Txc* vtau_0;
};

template <typename T, typename Txc = T>
int xck_cmgga_tau_ua_g1_t(int64_t npts,
        int64_t nbf,
        const T* chi,
        const T* Dchi,
        const T* DTchi,
        const xck_cmgga_tau_ua_g1_fields<T>& fields_,
        const xck_cmgga_tau_ua_g1_xc<Txc>& xc_,
        T* out,
        T* work = nullptr) {
    const T* f_[] = {fields_.w, fields_.rho_a_x, fields_.rho_a_y, fields_.rho_a_z, fields_.rho_b_x, fields_.rho_b_y, fields_.rho_b_z, fields_.jpx_a, fields_.jpy_a, fields_.jpz_a, fields_.inv_rho_a};
    const Txc* x_[] = {xc_.vrho_0, xc_.vsigma_0, xc_.vsigma_1, xc_.vtau_0};
    return xck_cmgga_tau_ua_g1_t<T, Txc>(npts, nbf, chi, Dchi, DTchi, f_, x_, out, work);
}

} // namespace xckernel
