/* generated by xckernel; do not edit. */
#pragma once
#include <cstdint>
#include <new>
#include "xckernel/evaluator.hpp"

namespace xckernel {
namespace detail_xck_mgga_u_gg {
static constexpr double c0_0[] = {
    1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0
};
static constexpr int32_t o0_0[] = {
    0,3,6,9,12,15,18,22,26,30,34,38,42,46,50,54,58,62,66
};
static constexpr uint16_t f0_0[] = {
    25,31,0,28,32,0,1,33,0,4,34,0,19,38,0,22,39,0,1,13,36,0,2,14,36,0,3,15,36,0,4,7,36,0,5,8,36,0,6,9,36,0,1,7,35,0,2,8,35,0,3,9,35,0,4,13,37,0,5,14,37,0,6,15,37,0
};
static constexpr double c1_0[] = {
    1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0
};
static constexpr int32_t o1_0[] = {
    0,3,6,9,12,15,18,22,26,30,34,38,42,46,50,54,58,62,66
};
static constexpr uint16_t f1_0[] = {
    26,31,0,29,32,0,2,33,0,5,34,0,20,38,0,23,39,0,1,14,36,0,2,16,36,0,3,17,36,0,4,8,36,0,5,10,36,0,6,11,36,0,1,8,35,0,2,10,35,0,3,11,35,0,4,14,37,0,5,16,37,0,6,17,37,0
};
static constexpr double c2_0[] = {
    1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0
};
static constexpr int32_t o2_0[] = {
    0,3,6,9,12,15,18,22,26,30,34,38,42,46,50,54,58,62,66
};
static constexpr uint16_t f2_0[] = {
    27,31,0,30,32,0,3,33,0,6,34,0,21,38,0,24,39,0,1,15,36,0,2,17,36,0,3,18,36,0,4,9,36,0,5,11,36,0,6,12,36,0,1,9,35,0,2,11,35,0,3,12,35,0,4,15,37,0,5,17,37,0,6,18,37,0
};
static constexpr int64_t NFLD = 31;
} // namespace detail_xck_mgga_u_gg

/* Scratch (elements of T) the kernel needs: pass at least this
 * much as `work`, or nullptr to allocate it internally. */
inline int64_t xck_mgga_u_gg_work(int64_t npts, int64_t nbf) {
    const int64_t blk = npts < grid_block ? npts : grid_block;
    return blk * (1 + nbf * 0) + 6 * npts + 1;
}

/* fields: the per-point tower operands (type T), in the order
 * of xck_mgga_u_gg_scal_names; xc: the functional-derivative arrays
 * (type Txc; Libxc computes in double whatever T is). */
template <typename T, typename Txc = T>
int xck_mgga_u_gg_t(int64_t npts,
        const T* const* fields,
        const Txc* const* xc,
        T* out,
        T* work = nullptr) {
    const int64_t blk = npts < grid_block ? npts : grid_block;
    T* c = work;
    bool own = false;
    if (!c) {
        c = new (std::nothrow) T[xck_mgga_u_gg_work(npts, 0)];
        own = true;
    }
    if (!c) return 1;
    T* S0 = c + blk + (int64_t)0*npts;
    {
        const T* s_[] = {fields[25], fields[26], fields[27]};
        static constexpr double w_[] = {1.0, 1.0, 1.0};
        combine<T>(npts, 1, 3, s_, w_, 0, S0);
    }
    T* S1 = c + blk + (int64_t)1*npts;
    {
        const T* s_[] = {fields[28], fields[29], fields[30]};
        static constexpr double w_[] = {1.0, 1.0, 1.0};
        combine<T>(npts, 1, 3, s_, w_, 0, S1);
    }
    T* S2 = c + blk + (int64_t)2*npts;
    {
        const T* s_[] = {fields[31], fields[32], fields[33]};
        static constexpr double w_[] = {1.0, 1.0, 1.0};
        combine<T>(npts, 1, 3, s_, w_, 0, S2);
    }
    T* S3 = c + blk + (int64_t)3*npts;
    {
        const T* s_[] = {fields[34], fields[35], fields[36]};
        static constexpr double w_[] = {1.0, 1.0, 1.0};
        combine<T>(npts, 1, 3, s_, w_, 0, S3);
    }
    T* S4 = c + blk + (int64_t)4*npts;
    {
        const T* s_[] = {fields[37], fields[38], fields[39]};
        static constexpr double w_[] = {1.0, 1.0, 1.0};
        combine<T>(npts, 1, 3, s_, w_, 0, S4);
    }
    T* S5 = c + blk + (int64_t)5*npts;
    {
        const T* s_[] = {fields[40], fields[41], fields[42]};
        static constexpr double w_[] = {1.0, 1.0, 1.0};
        combine<T>(npts, 1, 3, s_, w_, 0, S5);
    }
    const T* fi[31] = {fields[0], fields[1], fields[2], fields[3], fields[4], fields[5], fields[6], fields[7], fields[8], fields[9], fields[10], fields[11], fields[12], fields[13], fields[14], fields[15], fields[16], fields[17], fields[18], fields[19], fields[20], fields[21], fields[22], fields[23], fields[24], S0, S1, S2, S3, S4, S5};
    for (int64_t g0 = 0; g0 < npts; g0 += blk) {
        const int64_t bk = npts - g0 < blk ? npts - g0 : blk;
        stage_a<T, Txc>(g0, bk, 18, detail_xck_mgga_u_gg::c0_0, detail_xck_mgga_u_gg::o0_0, detail_xck_mgga_u_gg::f0_0, detail_xck_mgga_u_gg::NFLD, fi, xc, c);
        for (int64_t g = 0; g < bk; ++g) out[(int64_t)0*npts + g0 + g] += c[g];
        stage_a<T, Txc>(g0, bk, 18, detail_xck_mgga_u_gg::c1_0, detail_xck_mgga_u_gg::o1_0, detail_xck_mgga_u_gg::f1_0, detail_xck_mgga_u_gg::NFLD, fi, xc, c);
        for (int64_t g = 0; g < bk; ++g) out[(int64_t)1*npts + g0 + g] += c[g];
        stage_a<T, Txc>(g0, bk, 18, detail_xck_mgga_u_gg::c2_0, detail_xck_mgga_u_gg::o2_0, detail_xck_mgga_u_gg::f2_0, detail_xck_mgga_u_gg::NFLD, fi, xc, c);
        for (int64_t g = 0; g < bk; ++g) out[(int64_t)2*npts + g0 + g] += c[g];
    }
    if (own) delete[] c;
    return 0;
}

} // namespace xckernel
