/* generated by xckernel; do not edit. */
#pragma once
#include <cstdint>
#include <new>
#include "xckernel/evaluator.hpp"

namespace xckernel {
namespace detail_xck_mgga_u_gg {
static constexpr double c0_0[] = {
    1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0
};
static constexpr int32_t o0_0[] = {
    0,3,6,9,12,15,18,22,26,30,34,38,42,46,50,54,58,62,66
};
static constexpr uint16_t f0_0[] = {
    25,31,0,28,32,0,1,33,0,4,34,0,19,38,0,22,39,0,1,13,36,0,2,14,36,0,3,15,36,0,4,7,36,0,5,8,36,0,6,9,36,0,1,7,35,0,2,8,35,0,3,9,35,0,4,13,37,0,5,14,37,0,6,15,37,0
};
static constexpr double c1_0[] = {
    1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0
};
static constexpr int32_t o1_0[] = {
    0,3,6,9,12,15,18,22,26,30,34,38,42,46,50,54,58,62,66
};
static constexpr uint16_t f1_0[] = {
    26,31,0,29,32,0,2,33,0,5,34,0,20,38,0,23,39,0,1,14,36,0,2,16,36,0,3,17,36,0,4,8,36,0,5,10,36,0,6,11,36,0,1,8,35,0,2,10,35,0,3,11,35,0,4,14,37,0,5,16,37,0,6,17,37,0
};
static constexpr double c2_0[] = {
    1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0
};
static constexpr int32_t o2_0[] = {
    0,3,6,9,12,15,18,22,26,30,34,38,42,46,50,54,58,62,66
};
static constexpr uint16_t f2_0[] = {
    27,31,0,30,32,0,3,33,0,6,34,0,21,38,0,24,39,0,1,15,36,0,2,17,36,0,3,18,36,0,4,9,36,0,5,11,36,0,6,12,36,0,1,9,35,0,2,11,35,0,3,12,35,0,4,15,37,0,5,17,37,0,6,18,37,0
};
static constexpr int64_t NFLD = 31;
} // namespace detail_xck_mgga_u_gg

/* Scratch (elements of T) the kernel needs: pass at least this
 * much as `work`, or nullptr to allocate it internally. */
inline int64_t xck_mgga_u_gg_work(int64_t npts, int64_t nbf) {
    const int64_t blk = npts < grid_block ? npts : grid_block;
    return blk * (1 + nbf * 0) + 6 * npts + 1;
}

/* fields: the per-point tower operands (type T), in the order
 * of xck_mgga_u_gg_field_names; xc: the functional-derivative
 * arrays (type Txc; Libxc computes in double whatever T is),
 * in the order of xck_mgga_u_gg_xc_names (both below). */
template <typename T, typename Txc = T>
int xck_mgga_u_gg_t(int64_t npts,
        const T* const* fields,
        const Txc* const* xc,
        T* out,
        T* work = nullptr) {
    const int64_t blk = npts < grid_block ? npts : grid_block;
    T* c = work;
    bool own = false;
    if (!c) {
        c = new (std::nothrow) T[xck_mgga_u_gg_work(npts, 0)];
        own = true;
    }
    if (!c) return 1;
    T* S0 = c + blk + (int64_t)0*npts;
    {
        const T* s_[] = {fields[25], fields[26], fields[27]};
        static constexpr double w_[] = {1.0, 1.0, 1.0};
        combine<T>(npts, 1, 3, s_, w_, 0, S0);
    }
    T* S1 = c + blk + (int64_t)1*npts;
    {
        const T* s_[] = {fields[28], fields[29], fields[30]};
        static constexpr double w_[] = {1.0, 1.0, 1.0};
        combine<T>(npts, 1, 3, s_, w_, 0, S1);
    }
    T* S2 = c + blk + (int64_t)2*npts;
    {
        const T* s_[] = {fields[31], fields[32], fields[33]};
        static constexpr double w_[] = {1.0, 1.0, 1.0};
        combine<T>(npts, 1, 3, s_, w_, 0, S2);
    }
    T* S3 = c + blk + (int64_t)3*npts;
    {
        const T* s_[] = {fields[34], fields[35], fields[36]};
        static constexpr double w_[] = {1.0, 1.0, 1.0};
        combine<T>(npts, 1, 3, s_, w_, 0, S3);
    }
    T* S4 = c + blk + (int64_t)4*npts;
    {
        const T* s_[] = {fields[37], fields[38], fields[39]};
        static constexpr double w_[] = {1.0, 1.0, 1.0};
        combine<T>(npts, 1, 3, s_, w_, 0, S4);
    }
    T* S5 = c + blk + (int64_t)5*npts;
    {
        const T* s_[] = {fields[40], fields[41], fields[42]};
        static constexpr double w_[] = {1.0, 1.0, 1.0};
        combine<T>(npts, 1, 3, s_, w_, 0, S5);
    }
    const T* fi[31] = {fields[0], fields[1], fields[2], fields[3], fields[4], fields[5], fields[6], fields[7], fields[8], fields[9], fields[10], fields[11], fields[12], fields[13], fields[14], fields[15], fields[16], fields[17], fields[18], fields[19], fields[20], fields[21], fields[22], fields[23], fields[24], S0, S1, S2, S3, S4, S5};
    for (int64_t g0 = 0; g0 < npts; g0 += blk) {
        const int64_t bk = npts - g0 < blk ? npts - g0 : blk;
        stage_a<T, Txc>(g0, bk, 18, detail_xck_mgga_u_gg::c0_0, detail_xck_mgga_u_gg::o0_0, detail_xck_mgga_u_gg::f0_0, detail_xck_mgga_u_gg::NFLD, fi, xc, c);
        for (int64_t g = 0; g < bk; ++g) out[(int64_t)0*npts + g0 + g] += c[g];
        stage_a<T, Txc>(g0, bk, 18, detail_xck_mgga_u_gg::c1_0, detail_xck_mgga_u_gg::o1_0, detail_xck_mgga_u_gg::f1_0, detail_xck_mgga_u_gg::NFLD, fi, xc, c);
        for (int64_t g = 0; g < bk; ++g) out[(int64_t)1*npts + g0 + g] += c[g];
        stage_a<T, Txc>(g0, bk, 18, detail_xck_mgga_u_gg::c2_0, detail_xck_mgga_u_gg::o2_0, detail_xck_mgga_u_gg::f2_0, detail_xck_mgga_u_gg::NFLD, fi, xc, c);
        for (int64_t g = 0; g < bk; ++g) out[(int64_t)2*npts + g0 + g] += c[g];
    }
    if (own) delete[] c;
    return 0;
}


/* Operands of xck_mgga_u_gg_t: `fields` in the order of
 * xck_mgga_u_gg_field_names, `xc` in the order of xck_mgga_u_gg_xc_names (the
 * C ABI's `scal` is the two concatenated, split at n_fields). The
 * structs name them; the overload taking them packs the arrays. */
inline constexpr int xck_mgga_u_gg_n_fields = 43;
inline constexpr int xck_mgga_u_gg_n_xc = 9;
inline constexpr const char* xck_mgga_u_gg_field_names[] = {"w", "rho_a_x", "rho_a_y", "rho_a_z", "rho_b_x", "rho_b_y", "rho_b_z", "rho_a_xx", "rho_a_xy", "rho_a_xz", "rho_a_yy", "rho_a_yz", "rho_a_zz", "rho_b_xx", "rho_b_xy", "rho_b_xz", "rho_b_yy", "rho_b_yz", "rho_b_zz", "tau_a_x", "tau_a_y", "tau_a_z", "tau_b_x", "tau_b_y", "tau_b_z", "rho_a_xxx", "rho_a_xyy", "rho_a_xzz", "rho_a_xxy", "rho_a_yyy", "rho_a_yzz", "rho_a_xxz", "rho_a_yyz", "rho_a_zzz", "rho_b_xxx", "rho_b_xyy", "rho_b_xzz", "rho_b_xxy", "rho_b_yyy", "rho_b_yzz", "rho_b_xxz", "rho_b_yyz", "rho_b_zzz"};
inline constexpr const char* xck_mgga_u_gg_xc_names[] = {"vlapl_0", "vlapl_1", "vrho_0", "vrho_1", "vsigma_0", "vsigma_1", "vsigma_2", "vtau_0", "vtau_1"};
template <typename T>
struct xck_mgga_u_gg_fields {
    const T* w;
    const T* rho_a_x;
    const T* rho_a_y;
    const T* rho_a_z;
    const T* rho_b_x;
    const T* rho_b_y;
    const T* rho_b_z;
    const T* rho_a_xx;
    const T* rho_a_xy;
    const T* rho_a_xz;
    const T* rho_a_yy;
    const T* rho_a_yz;
    const T* rho_a_zz;
    const T* rho_b_xx;
    const T* rho_b_xy;
    const T* rho_b_xz;
    const T* rho_b_yy;
    const T* rho_b_yz;
    const T* rho_b_zz;
    const T* tau_a_x;
    const T* tau_a_y;
    const T* tau_a_z;
    const T* tau_b_x;
    const T* tau_b_y;
    const T* tau_b_z;
    const T* rho_a_xxx;
    const T* rho_a_xyy;
    const T* rho_a_xzz;
    const T* rho_a_xxy;
    const T* rho_a_yyy;
    const T* rho_a_yzz;
    const T* rho_a_xxz;
    const T* rho_a_yyz;
    const T* rho_a_zzz;
    const T* rho_b_xxx;
    const T* rho_b_xyy;
    const T* rho_b_xzz;
    const T* rho_b_xxy;
    const T* rho_b_yyy;
    const T* rho_b_yzz;
    const T* rho_b_xxz;
    const T* rho_b_yyz;
    const T* rho_b_zzz;
};
template <typename Txc>
struct xck_mgga_u_gg_xc {
    const Txc* vlapl_0;
    const Txc* vlapl_1;
    const Txc* vrho_0;
    const Txc* vrho_1;
    const Txc* vsigma_0;
    const Txc* vsigma_1;
    const Txc* vsigma_2;
    const Txc* vtau_0;
    const Txc* vtau_1;
};

template <typename T, typename Txc = T>
int xck_mgga_u_gg_t(int64_t npts,
        const xck_mgga_u_gg_fields<T>& fields_,
        const xck_mgga_u_gg_xc<Txc>& xc_,
        T* out,
        T* work = nullptr) {
    const T* f_[] = {fields_.w, fields_.rho_a_x, fields_.rho_a_y, fields_.rho_a_z, fields_.rho_b_x, fields_.rho_b_y, fields_.rho_b_z, fields_.rho_a_xx, fields_.rho_a_xy, fields_.rho_a_xz, fields_.rho_a_yy, fields_.rho_a_yz, fields_.rho_a_zz, fields_.rho_b_xx, fields_.rho_b_xy, fields_.rho_b_xz, fields_.rho_b_yy, fields_.rho_b_yz, fields_.rho_b_zz, fields_.tau_a_x, fields_.tau_a_y, fields_.tau_a_z, fields_.tau_b_x, fields_.tau_b_y, fields_.tau_b_z, fields_.rho_a_xxx, fields_.rho_a_xyy, fields_.rho_a_xzz, fields_.rho_a_xxy, fields_.rho_a_yyy, fields_.rho_a_yzz, fields_.rho_a_xxz, fields_.rho_a_yyz, fields_.rho_a_zzz, fields_.rho_b_xxx, fields_.rho_b_xyy, fields_.rho_b_xzz, fields_.rho_b_xxy, fields_.rho_b_yyy, fields_.rho_b_yzz, fields_.rho_b_xxz, fields_.rho_b_yyz, fields_.rho_b_zzz};
    const Txc* x_[] = {xc_.vlapl_0, xc_.vlapl_1, xc_.vrho_0, xc_.vrho_1, xc_.vsigma_0, xc_.vsigma_1, xc_.vsigma_2, xc_.vtau_0, xc_.vtau_1};
    return xck_mgga_u_gg_t<T, Txc>(npts, f_, x_, out, work);
}

} // namespace xckernel
