/* generated by xckernel; do not edit. */
#pragma once
#include <cstdint>
#include <new>
#include "xckernel/evaluator.hpp"

namespace xckernel {
namespace detail_xck_gga_st_o2_m {
static constexpr double c0_0[] = {
    1.0,-1.0,2.0,2.0,2.0,-2.0,-2.0,-2.0
};
static constexpr int32_t o0_0[] = {
    0,3,6,10,14,18,22,26,30
};
static constexpr uint16_t f0_0[] = {
    7,10,0,7,11,0,4,1,12,0,5,2,12,0,6,3,12,0,4,1,14,0,5,2,14,0,6,3,14,0
};
static constexpr double c0_1[] = {
    -1.0,1.0,-1.0,2.0,2.0,2.0,-2.0,-2.0,-2.0,2.0,2.0,-2.0,4.0,4.0,4.0,-4.0,-4.0,-4.0
};
static constexpr int32_t o0_1[] = {
    0,3,7,11,16,21,26,31,36,41,44,48,52,57,62,67,72,77,82
};
static constexpr uint16_t f0_1[] = {
    4,9,0,1,7,13,0,1,7,16,0,4,1,1,18,0,5,1,2,18,0,6,1,3,18,0,4,1,1,20,0,5,1,2,20,0,6,1,3,20,0,4,8,0,1,7,12,0,1,7,15,0,4,1,1,17,0,5,1,2,17,0,6,1,3,17,0,4,1,1,19,0,5,1,2,19,0,6,1,3,19,0
};
static constexpr double c0_2[] = {
    -1.0,1.0,-1.0,2.0,2.0,2.0,-2.0,-2.0,-2.0,2.0,2.0,-2.0,4.0,4.0,4.0,-4.0,-4.0,-4.0
};
static constexpr int32_t o0_2[] = {
    0,3,7,11,16,21,26,31,36,41,44,48,52,57,62,67,72,77,82
};
static constexpr uint16_t f0_2[] = {
    5,9,0,2,7,13,0,2,7,16,0,4,1,2,18,0,5,2,2,18,0,6,2,3,18,0,4,1,2,20,0,5,2,2,20,0,6,2,3,20,0,5,8,0,2,7,12,0,2,7,15,0,4,1,2,17,0,5,2,2,17,0,6,2,3,17,0,4,1,2,19,0,5,2,2,19,0,6,2,3,19,0
};
static constexpr double c0_3[] = {
    -1.0,1.0,-1.0,2.0,2.0,2.0,-2.0,-2.0,-2.0,2.0,2.0,-2.0,4.0,4.0,4.0,-4.0,-4.0,-4.0
};
static constexpr int32_t o0_3[] = {
    0,3,7,11,16,21,26,31,36,41,44,48,52,57,62,67,72,77,82
};
static constexpr uint16_t f0_3[] = {
    6,9,0,3,7,13,0,3,7,16,0,4,1,3,18,0,5,2,3,18,0,6,3,3,18,0,4,1,3,20,0,5,2,3,20,0,6,3,3,20,0,6,8,0,3,7,12,0,3,7,15,0,4,1,3,17,0,5,2,3,17,0,6,3,3,17,0,4,1,3,19,0,5,2,3,19,0,6,3,3,19,0
};
static constexpr double c0_4[] = {
    -1.0,1.0,-1.0,2.0,2.0,2.0,-2.0,-2.0,-2.0,2.0,2.0,-2.0,4.0,4.0,4.0,-4.0,-4.0,-4.0
};
static constexpr int32_t o0_4[] = {
    0,3,7,11,16,21,26,31,36,41,44,48,52,57,62,67,72,77,82
};
static constexpr uint16_t f0_4[] = {
    4,9,0,1,7,13,0,1,7,16,0,4,1,1,18,0,5,1,2,18,0,6,1,3,18,0,4,1,1,20,0,5,1,2,20,0,6,1,3,20,0,4,8,0,1,7,12,0,1,7,15,0,4,1,1,17,0,5,1,2,17,0,6,1,3,17,0,4,1,1,19,0,5,1,2,19,0,6,1,3,19,0
};
static constexpr double c0_5[] = {
    -1.0,1.0,-1.0,2.0,2.0,2.0,-2.0,-2.0,-2.0,2.0,2.0,-2.0,4.0,4.0,4.0,-4.0,-4.0,-4.0
};
static constexpr int32_t o0_5[] = {
    0,3,7,11,16,21,26,31,36,41,44,48,52,57,62,67,72,77,82
};
static constexpr uint16_t f0_5[] = {
    5,9,0,2,7,13,0,2,7,16,0,4,1,2,18,0,5,2,2,18,0,6,2,3,18,0,4,1,2,20,0,5,2,2,20,0,6,2,3,20,0,5,8,0,2,7,12,0,2,7,15,0,4,1,2,17,0,5,2,2,17,0,6,2,3,17,0,4,1,2,19,0,5,2,2,19,0,6,2,3,19,0
};
static constexpr double c0_6[] = {
    -1.0,1.0,-1.0,2.0,2.0,2.0,-2.0,-2.0,-2.0,2.0,2.0,-2.0,4.0,4.0,4.0,-4.0,-4.0,-4.0
};
static constexpr int32_t o0_6[] = {
    0,3,7,11,16,21,26,31,36,41,44,48,52,57,62,67,72,77,82
};
static constexpr uint16_t f0_6[] = {
    6,9,0,3,7,13,0,3,7,16,0,4,1,3,18,0,5,2,3,18,0,6,3,3,18,0,4,1,3,20,0,5,2,3,20,0,6,3,3,20,0,6,8,0,3,7,12,0,3,7,15,0,4,1,3,17,0,5,2,3,17,0,6,3,3,17,0,4,1,3,19,0,5,2,3,19,0,6,3,3,19,0
};
static constexpr int64_t NFLD = 8;
} // namespace detail_xck_gga_st_o2_m

/* Scratch (elements of T) the kernel needs: pass at least this
 * much as `work`, or nullptr to allocate it internally. */
inline int64_t xck_gga_st_o2_m_work(int64_t npts, int64_t nbf) {
    const int64_t blk = npts < grid_block ? npts : grid_block;
    return blk * (1 + nbf * 1) + 0 * npts + 1;
}

/* fields: the per-point tower operands (type T), in the order
 * of xck_gga_st_o2_m_field_names; xc: the functional-derivative
 * arrays (type Txc; Libxc computes in double whatever T is),
 * in the order of xck_gga_st_o2_m_xc_names (both below). */
template <typename T, typename Txc = T>
int xck_gga_st_o2_m_t(int64_t npts,
        int64_t nbf,
        const T* chi,
        const T* const* fields,
        const Txc* const* xc,
        T* out,
        T* work = nullptr) {
    const int64_t blk = npts < grid_block ? npts : grid_block;
    T* c = work;
    bool own = false;
    if (!c) {
        c = new (std::nothrow) T[xck_gga_st_o2_m_work(npts, nbf)];
        own = true;
    }
    if (!c) return 1;
    T* W = c + blk;
    const T* Wc = W;
    const T* fi[8] = {fields[0], fields[1], fields[2], fields[3], fields[4], fields[5], fields[6], fields[7]};
    for (int64_t g0 = 0; g0 < npts; g0 += blk) {
        const int64_t bk = npts - g0 < blk ? npts - g0 : blk;
        stage_a<T, Txc>(g0, bk, 8, detail_xck_gga_st_o2_m::c0_0, detail_xck_gga_st_o2_m::o0_0, detail_xck_gga_st_o2_m::f0_0, detail_xck_gga_st_o2_m::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 18, detail_xck_gga_st_o2_m::c0_1, detail_xck_gga_st_o2_m::o0_1, detail_xck_gga_st_o2_m::f0_1, detail_xck_gga_st_o2_m::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)1*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 18, detail_xck_gga_st_o2_m::c0_2, detail_xck_gga_st_o2_m::o0_2, detail_xck_gga_st_o2_m::f0_2, detail_xck_gga_st_o2_m::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)2*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 18, detail_xck_gga_st_o2_m::c0_3, detail_xck_gga_st_o2_m::o0_3, detail_xck_gga_st_o2_m::f0_3, detail_xck_gga_st_o2_m::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)3*nbf*npts + g0, npts, W, 0);
        gemm_nt(nbf, bk, chi + (int64_t)0*nbf*npts + g0, npts, Wc, bk, out + (int64_t)0*nbf*nbf);
        stage_a<T, Txc>(g0, bk, 18, detail_xck_gga_st_o2_m::c0_4, detail_xck_gga_st_o2_m::o0_4, detail_xck_gga_st_o2_m::f0_4, detail_xck_gga_st_o2_m::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        gemm_nt(nbf, bk, chi + (int64_t)1*nbf*npts + g0, npts, Wc, bk, out + (int64_t)0*nbf*nbf);
        stage_a<T, Txc>(g0, bk, 18, detail_xck_gga_st_o2_m::c0_5, detail_xck_gga_st_o2_m::o0_5, detail_xck_gga_st_o2_m::f0_5, detail_xck_gga_st_o2_m::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        gemm_nt(nbf, bk, chi + (int64_t)2*nbf*npts + g0, npts, Wc, bk, out + (int64_t)0*nbf*nbf);
        stage_a<T, Txc>(g0, bk, 18, detail_xck_gga_st_o2_m::c0_6, detail_xck_gga_st_o2_m::o0_6, detail_xck_gga_st_o2_m::f0_6, detail_xck_gga_st_o2_m::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        gemm_nt(nbf, bk, chi + (int64_t)3*nbf*npts + g0, npts, Wc, bk, out + (int64_t)0*nbf*nbf);
    }
    if (own) delete[] c;
    return 0;
}


/* Operands of xck_gga_st_o2_m_t: `fields` in the order of
 * xck_gga_st_o2_m_field_names, `xc` in the order of xck_gga_st_o2_m_xc_names (the
 * C ABI's `scal` is the two concatenated, split at n_fields). The
 * structs name them; the overload taking them packs the arrays. */
inline constexpr int xck_gga_st_o2_m_n_fields = 8;
inline constexpr int xck_gga_st_o2_m_n_xc = 13;
inline constexpr const char* xck_gga_st_o2_m_field_names[] = {"w", "rho_a_x", "rho_a_y", "rho_a_z", "rho_a_p1_x", "rho_a_p1_y", "rho_a_p1_z", "rho_a_p1"};
inline constexpr const char* xck_gga_st_o2_m_xc_names[] = {"vsigma_0", "vsigma_1", "v2rho2_0", "v2rho2_1", "v2rhosigma_0", "v2rhosigma_1", "v2rhosigma_2", "v2rhosigma_3", "v2rhosigma_4", "v2sigma2_0", "v2sigma2_1", "v2sigma2_2", "v2sigma2_4"};
template <typename T>
struct xck_gga_st_o2_m_fields {
    const T* w;
    const T* rho_a_x;
    const T* rho_a_y;
    const T* rho_a_z;
    const T* rho_a_p1_x;
    const T* rho_a_p1_y;
    const T* rho_a_p1_z;
    const T* rho_a_p1;
};
template <typename Txc>
struct xck_gga_st_o2_m_xc {
    const Txc* vsigma_0;
    const Txc* vsigma_1;
    const Txc* v2rho2_0;
    const Txc* v2rho2_1;
    const Txc* v2rhosigma_0;
    const Txc* v2rhosigma_1;
    const Txc* v2rhosigma_2;
    const Txc* v2rhosigma_3;
    const Txc* v2rhosigma_4;
    const Txc* v2sigma2_0;
    const Txc* v2sigma2_1;
    const Txc* v2sigma2_2;
    const Txc* v2sigma2_4;
};

template <typename T, typename Txc = T>
int xck_gga_st_o2_m_t(int64_t npts,
        int64_t nbf,
        const T* chi,
        const xck_gga_st_o2_m_fields<T>& fields_,
        const xck_gga_st_o2_m_xc<Txc>& xc_,
        T* out,
        T* work = nullptr) {
    const T* f_[] = {fields_.w, fields_.rho_a_x, fields_.rho_a_y, fields_.rho_a_z, fields_.rho_a_p1_x, fields_.rho_a_p1_y, fields_.rho_a_p1_z, fields_.rho_a_p1};
    const Txc* x_[] = {xc_.vsigma_0, xc_.vsigma_1, xc_.v2rho2_0, xc_.v2rho2_1, xc_.v2rhosigma_0, xc_.v2rhosigma_1, xc_.v2rhosigma_2, xc_.v2rhosigma_3, xc_.v2rhosigma_4, xc_.v2sigma2_0, xc_.v2sigma2_1, xc_.v2sigma2_2, xc_.v2sigma2_4};
    return xck_gga_st_o2_m_t<T, Txc>(npts, nbf, chi, f_, x_, out, work);
}

} // namespace xckernel
