/* generated by xckernel; do not edit. */
#pragma once
#include <cstdint>
#include <new>
#include "xckernel/evaluator.hpp"

namespace xckernel {
namespace detail_xck_lda_r_o1 {
static constexpr double c0[] = {
    1.0
};
static constexpr int32_t o0[] = {
    0,2
};
static constexpr uint16_t f0[] = {
    1,0
};
static constexpr int64_t NFLD = 1;
} // namespace detail_xck_lda_r_o1

/* fields: host-computed per-point operands (type T); xc: the
 * functional-derivative arrays (type Txc; Libxc computes in double
 * regardless of T). work: caller scratch of
 * xckernel::work_size(npts, nbf) elements or nullptr
 * (heap-allocated internally; pass a buffer in device code). */
template <typename T, typename Txc = T>
int xck_lda_r_o1_t(int64_t npts, int64_t nbf,
             const T* chi, const T* dchi, const T* lapl_chi,
             const T* hess_chi,
             const T* const* fields, const Txc* const* xc,
             T* out, T* work = nullptr) {
    const int64_t blk = npts < grid_block ? npts : grid_block;
    T* c = work;
    bool own = false;
    if (!c) {
        c = new (std::nothrow) T[work_size(npts, nbf)];
        own = true;
    }
    if (!c) return 1;
    T* W = c + blk;
    const T* Wc = W;
    for (int64_t g0 = 0; g0 < npts; g0 += blk) {
        const int64_t bk = npts - g0 < blk ? npts - g0 : blk;
        stage_a<T, Txc>(g0, bk, 1, detail_xck_lda_r_o1::c0, detail_xck_lda_r_o1::o0, detail_xck_lda_r_o1::f0, detail_xck_lda_r_o1::NFLD, fields, xc, c);
        accumulate<T>(bk, nbf, c, chi + g0, npts, W, 1);
        gemm_nt(nbf, bk, chi + g0, npts, Wc, bk, out);
    }
    if (own) delete[] c;
    return 0;
}

} // namespace xckernel
