/* generated by xckernel; do not edit. */
#pragma once
#include <cstdint>
#include <new>
#include "xckernel/evaluator.hpp"

namespace xckernel {
namespace detail_xck_cmgga_tau_r_o2 {
static constexpr double c0_0[] = {
    1.0,1.0,2.0,2.0,2.0,1.0,1.0,1.0,-1.0,-1.0,-1.0,-1.0,1.0,0.5,1.0,1.0,1.0,0.25,0.5,0.5,-0.5,-0.5,-0.5,-1.0,1.0,0.5,1.0,1.0,1.0,0.25,0.5,-0.5,-0.5,-0.5,-1.0,1.0,0.5,1.0,1.0,1.0,0.25,-0.5,-0.5,-0.5
};
static constexpr int32_t o0_0[] = {
    0,3,6,10,14,18,25,32,39,44,49,54,62,68,75,83,91,99,110,121,132,141,150,159,167,173,180,188,196,204,215,226,235,244,253,261,267,274,282,290,298,309,318,327,336
};
static constexpr uint16_t f0_0[] = {
    14,16,0,15,22,0,8,1,21,0,9,2,21,0,10,3,21,0,7,7,4,4,14,22,0,7,7,5,5,14,22,0,7,7,6,6,14,22,0,7,11,4,22,0,7,12,5,22,0,7,13,6,22,0,7,7,7,4,4,14,20,0,7,7,11,4,20,0,7,7,4,4,15,18,0,8,1,7,7,4,4,23,0,9,2,7,7,4,4,23,0,10,3,7,7,4,4,23,0,7,7,7,7,4,4,4,4,14,18,0,7,7,7,7,4,4,5,5,14,18,0,7,7,7,7,4,4,6,6,14,18,0,7,7,7,11,4,4,4,18,0,7,7,7,12,4,4,5,18,0,7,7,7,13,4,4,6,18,0,7,7,7,5,5,14,20,0,7,7,12,5,20,0,7,7,5,5,15,18,0,8,1,7,7,5,5,23,0,9,2,7,7,5,5,23,0,10,3,7,7,5,5,23,0,7,7,7,7,5,5,5,5,14,18,0,7,7,7,7,5,5,6,6,14,18,0,7,7,7,11,4,5,5,18,0,7,7,7,12,5,5,5,18,0,7,7,7,13,5,5,6,18,0,7,7,7,6,6,14,20,0,7,7,13,6,20,0,7,7,6,6,15,18,0,8,1,7,7,6,6,23,0,9,2,7,7,6,6,23,0,10,3,7,7,6,6,23,0,7,7,7,7,6,6,6,6,14,18,0,7,7,7,11,4,6,6,18,0,7,7,7,12,5,6,6,18,0,7,7,7,13,6,6,6,18,0
};
static constexpr double c0_1[] = {
    2.0,2.0,2.0,4.0,4.0,4.0,1.0,1.0,1.0,-2.0,-2.0,-2.0,0.5,-0.5,-0.5,-0.5,-1.0,-1.0,-1.0,-0.25,-0.25,-0.25,0.5,0.5,0.5
};
static constexpr int32_t o0_1[] = {
    0,3,7,11,16,21,26,34,42,50,56,62,68,74,78,83,88,94,100,106,115,124,133,140,147,154
};
static constexpr uint16_t f0_1[] = {
    8,19,0,1,14,21,0,1,15,23,0,8,1,1,17,0,9,1,2,17,0,10,1,3,17,0,1,7,7,4,4,14,23,0,1,7,7,5,5,14,23,0,1,7,7,6,6,14,23,0,1,7,11,4,23,0,1,7,12,5,23,0,1,7,13,6,23,0,7,7,4,14,20,0,7,11,20,0,7,4,14,22,0,7,4,15,18,0,8,1,7,4,23,0,9,2,7,4,23,0,10,3,7,4,23,0,7,7,7,4,4,4,14,18,0,7,7,7,4,5,5,14,18,0,7,7,7,4,6,6,14,18,0,7,7,11,4,4,18,0,7,7,12,4,5,18,0,7,7,13,4,6,18,0
};
static constexpr double c0_2[] = {
    2.0,2.0,2.0,4.0,4.0,4.0,1.0,1.0,1.0,-2.0,-2.0,-2.0,0.5,-0.5,-0.5,-0.5,-1.0,-1.0,-1.0,-0.25,-0.25,-0.25,0.5,0.5,0.5
};
static constexpr int32_t o0_2[] = {
    0,3,7,11,16,21,26,34,42,50,56,62,68,74,78,83,88,94,100,106,115,124,133,140,147,154
};
static constexpr uint16_t f0_2[] = {
    9,19,0,2,14,21,0,2,15,23,0,8,1,2,17,0,9,2,2,17,0,10,2,3,17,0,2,7,7,4,4,14,23,0,2,7,7,5,5,14,23,0,2,7,7,6,6,14,23,0,2,7,11,4,23,0,2,7,12,5,23,0,2,7,13,6,23,0,7,7,5,14,20,0,7,12,20,0,7,5,14,22,0,7,5,15,18,0,8,1,7,5,23,0,9,2,7,5,23,0,10,3,7,5,23,0,7,7,7,4,4,5,14,18,0,7,7,7,5,5,5,14,18,0,7,7,7,5,6,6,14,18,0,7,7,11,4,5,18,0,7,7,12,5,5,18,0,7,7,13,5,6,18,0
};
static constexpr double c0_3[] = {
    2.0,2.0,2.0,4.0,4.0,4.0,1.0,1.0,1.0,-2.0,-2.0,-2.0,0.5,-0.5,-0.5,-0.5,-1.0,-1.0,-1.0,-0.25,-0.25,-0.25,0.5,0.5,0.5
};
static constexpr int32_t o0_3[] = {
    0,3,7,11,16,21,26,34,42,50,56,62,68,74,78,83,88,94,100,106,115,124,133,140,147,154
};
static constexpr uint16_t f0_3[] = {
    10,19,0,3,14,21,0,3,15,23,0,8,1,3,17,0,9,2,3,17,0,10,3,3,17,0,3,7,7,4,4,14,23,0,3,7,7,5,5,14,23,0,3,7,7,6,6,14,23,0,3,7,11,4,23,0,3,7,12,5,23,0,3,7,13,6,23,0,7,7,6,14,20,0,7,13,20,0,7,6,14,22,0,7,6,15,18,0,8,1,7,6,23,0,9,2,7,6,23,0,10,3,7,6,23,0,7,7,7,4,4,6,14,18,0,7,7,7,5,5,6,14,18,0,7,7,7,6,6,6,14,18,0,7,7,11,4,6,18,0,7,7,12,5,6,18,0,7,7,13,6,6,18,0
};
static constexpr double c0_4[] = {
    2.0,2.0,2.0,4.0,4.0,4.0,1.0,1.0,1.0,-2.0,-2.0,-2.0,-0.5,0.5,0.5,0.5,1.0,1.0,1.0,0.25,0.25,0.25,-0.5,-0.5,-0.5
};
static constexpr int32_t o0_4[] = {
    0,3,7,11,16,21,26,34,42,50,56,62,68,74,78,83,88,94,100,106,115,124,133,140,147,154
};
static constexpr uint16_t f0_4[] = {
    8,19,0,1,14,21,0,1,15,23,0,8,1,1,17,0,9,1,2,17,0,10,1,3,17,0,1,7,7,4,4,14,23,0,1,7,7,5,5,14,23,0,1,7,7,6,6,14,23,0,1,7,11,4,23,0,1,7,12,5,23,0,1,7,13,6,23,0,7,7,4,14,20,0,7,11,20,0,7,4,14,22,0,7,4,15,18,0,8,1,7,4,23,0,9,2,7,4,23,0,10,3,7,4,23,0,7,7,7,4,4,4,14,18,0,7,7,7,4,5,5,14,18,0,7,7,7,4,6,6,14,18,0,7,7,11,4,4,18,0,7,7,12,4,5,18,0,7,7,13,4,6,18,0
};
static constexpr double c0_5[] = {
    0.5,0.5,1.0,1.0,1.0,0.25,0.25,0.25,-0.5,-0.5,-0.5
};
static constexpr int32_t o0_5[] = {
    0,3,6,10,14,18,25,32,39,44,49,54
};
static constexpr uint16_t f0_5[] = {
    14,22,0,15,18,0,8,1,23,0,9,2,23,0,10,3,23,0,7,7,4,4,14,18,0,7,7,5,5,14,18,0,7,7,6,6,14,18,0,7,11,4,18,0,7,12,5,18,0,7,13,6,18,0
};
static constexpr double c0_6[] = {
    2.0,2.0,2.0,4.0,4.0,4.0,1.0,1.0,1.0,-2.0,-2.0,-2.0,-0.5,0.5,0.5,0.5,1.0,1.0,1.0,0.25,0.25,0.25,-0.5,-0.5,-0.5
};
static constexpr int32_t o0_6[] = {
    0,3,7,11,16,21,26,34,42,50,56,62,68,74,78,83,88,94,100,106,115,124,133,140,147,154
};
static constexpr uint16_t f0_6[] = {
    9,19,0,2,14,21,0,2,15,23,0,8,1,2,17,0,9,2,2,17,0,10,2,3,17,0,2,7,7,4,4,14,23,0,2,7,7,5,5,14,23,0,2,7,7,6,6,14,23,0,2,7,11,4,23,0,2,7,12,5,23,0,2,7,13,6,23,0,7,7,5,14,20,0,7,12,20,0,7,5,14,22,0,7,5,15,18,0,8,1,7,5,23,0,9,2,7,5,23,0,10,3,7,5,23,0,7,7,7,4,4,5,14,18,0,7,7,7,5,5,5,14,18,0,7,7,7,5,6,6,14,18,0,7,7,11,4,5,18,0,7,7,12,5,5,18,0,7,7,13,5,6,18,0
};
static constexpr double c0_7[] = {
    0.5,0.5,1.0,1.0,1.0,0.25,0.25,0.25,-0.5,-0.5,-0.5
};
static constexpr int32_t o0_7[] = {
    0,3,6,10,14,18,25,32,39,44,49,54
};
static constexpr uint16_t f0_7[] = {
    14,22,0,15,18,0,8,1,23,0,9,2,23,0,10,3,23,0,7,7,4,4,14,18,0,7,7,5,5,14,18,0,7,7,6,6,14,18,0,7,11,4,18,0,7,12,5,18,0,7,13,6,18,0
};
static constexpr double c0_8[] = {
    2.0,2.0,2.0,4.0,4.0,4.0,1.0,1.0,1.0,-2.0,-2.0,-2.0,-0.5,0.5,0.5,0.5,1.0,1.0,1.0,0.25,0.25,0.25,-0.5,-0.5,-0.5
};
static constexpr int32_t o0_8[] = {
    0,3,7,11,16,21,26,34,42,50,56,62,68,74,78,83,88,94,100,106,115,124,133,140,147,154
};
static constexpr uint16_t f0_8[] = {
    10,19,0,3,14,21,0,3,15,23,0,8,1,3,17,0,9,2,3,17,0,10,3,3,17,0,3,7,7,4,4,14,23,0,3,7,7,5,5,14,23,0,3,7,7,6,6,14,23,0,3,7,11,4,23,0,3,7,12,5,23,0,3,7,13,6,23,0,7,7,6,14,20,0,7,13,20,0,7,6,14,22,0,7,6,15,18,0,8,1,7,6,23,0,9,2,7,6,23,0,10,3,7,6,23,0,7,7,7,4,4,6,14,18,0,7,7,7,5,5,6,14,18,0,7,7,7,6,6,6,14,18,0,7,7,11,4,6,18,0,7,7,12,5,6,18,0,7,7,13,6,6,18,0
};
static constexpr double c0_9[] = {
    0.5,0.5,1.0,1.0,1.0,0.25,0.25,0.25,-0.5,-0.5,-0.5
};
static constexpr int32_t o0_9[] = {
    0,3,6,10,14,18,25,32,39,44,49,54
};
static constexpr uint16_t f0_9[] = {
    14,22,0,15,18,0,8,1,23,0,9,2,23,0,10,3,23,0,7,7,4,4,14,18,0,7,7,5,5,14,18,0,7,7,6,6,14,18,0,7,11,4,18,0,7,12,5,18,0,7,13,6,18,0
};
static constexpr int64_t NFLD = 16;
} // namespace detail_xck_cmgga_tau_r_o2

/* Scratch (elements of T) the kernel needs: pass at least this
 * much as `work`, or nullptr to allocate it internally. */
inline int64_t xck_cmgga_tau_r_o2_work(int64_t npts, int64_t nbf) {
    const int64_t blk = npts < grid_block ? npts : grid_block;
    return blk * (1 + nbf * 1) + 0 * npts + 1;
}

/* fields: the per-point tower operands (type T), in the order
 * of xck_cmgga_tau_r_o2_field_names; xc: the functional-derivative
 * arrays (type Txc; Libxc computes in double whatever T is),
 * in the order of xck_cmgga_tau_r_o2_xc_names (both below). */
template <typename T, typename Txc = T>
int xck_cmgga_tau_r_o2_t(int64_t npts,
        int64_t nbf,
        const T* chi,
        const T* const* fields,
        const Txc* const* xc,
        T* out,
        T* work = nullptr) {
    const int64_t blk = npts < grid_block ? npts : grid_block;
    T* c = work;
    bool own = false;
    if (!c) {
        c = new (std::nothrow) T[xck_cmgga_tau_r_o2_work(npts, nbf)];
        own = true;
    }
    if (!c) return 1;
    T* W = c + blk;
    const T* Wc = W;
    const T* fi[16] = {fields[0], fields[1], fields[2], fields[3], fields[4], fields[5], fields[6], fields[7], fields[8], fields[9], fields[10], fields[11], fields[12], fields[13], fields[14], fields[15]};
    for (int64_t g0 = 0; g0 < npts; g0 += blk) {
        const int64_t bk = npts - g0 < blk ? npts - g0 : blk;
        stage_a<T, Txc>(g0, bk, 44, detail_xck_cmgga_tau_r_o2::c0_0, detail_xck_cmgga_tau_r_o2::o0_0, detail_xck_cmgga_tau_r_o2::f0_0, detail_xck_cmgga_tau_r_o2::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 25, detail_xck_cmgga_tau_r_o2::c0_1, detail_xck_cmgga_tau_r_o2::o0_1, detail_xck_cmgga_tau_r_o2::f0_1, detail_xck_cmgga_tau_r_o2::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)1*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 25, detail_xck_cmgga_tau_r_o2::c0_2, detail_xck_cmgga_tau_r_o2::o0_2, detail_xck_cmgga_tau_r_o2::f0_2, detail_xck_cmgga_tau_r_o2::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)2*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 25, detail_xck_cmgga_tau_r_o2::c0_3, detail_xck_cmgga_tau_r_o2::o0_3, detail_xck_cmgga_tau_r_o2::f0_3, detail_xck_cmgga_tau_r_o2::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)3*nbf*npts + g0, npts, W, 0);
        gemm_nt(nbf, bk, chi + (int64_t)0*nbf*npts + g0, npts, Wc, bk, out + (int64_t)0*nbf*nbf);
        stage_a<T, Txc>(g0, bk, 25, detail_xck_cmgga_tau_r_o2::c0_4, detail_xck_cmgga_tau_r_o2::o0_4, detail_xck_cmgga_tau_r_o2::f0_4, detail_xck_cmgga_tau_r_o2::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 11, detail_xck_cmgga_tau_r_o2::c0_5, detail_xck_cmgga_tau_r_o2::o0_5, detail_xck_cmgga_tau_r_o2::f0_5, detail_xck_cmgga_tau_r_o2::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)1*nbf*npts + g0, npts, W, 0);
        gemm_nt(nbf, bk, chi + (int64_t)1*nbf*npts + g0, npts, Wc, bk, out + (int64_t)0*nbf*nbf);
        stage_a<T, Txc>(g0, bk, 25, detail_xck_cmgga_tau_r_o2::c0_6, detail_xck_cmgga_tau_r_o2::o0_6, detail_xck_cmgga_tau_r_o2::f0_6, detail_xck_cmgga_tau_r_o2::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 11, detail_xck_cmgga_tau_r_o2::c0_7, detail_xck_cmgga_tau_r_o2::o0_7, detail_xck_cmgga_tau_r_o2::f0_7, detail_xck_cmgga_tau_r_o2::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)2*nbf*npts + g0, npts, W, 0);
        gemm_nt(nbf, bk, chi + (int64_t)2*nbf*npts + g0, npts, Wc, bk, out + (int64_t)0*nbf*nbf);
        stage_a<T, Txc>(g0, bk, 25, detail_xck_cmgga_tau_r_o2::c0_8, detail_xck_cmgga_tau_r_o2::o0_8, detail_xck_cmgga_tau_r_o2::f0_8, detail_xck_cmgga_tau_r_o2::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 11, detail_xck_cmgga_tau_r_o2::c0_9, detail_xck_cmgga_tau_r_o2::o0_9, detail_xck_cmgga_tau_r_o2::f0_9, detail_xck_cmgga_tau_r_o2::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, chi + (int64_t)3*nbf*npts + g0, npts, W, 0);
        gemm_nt(nbf, bk, chi + (int64_t)3*nbf*npts + g0, npts, Wc, bk, out + (int64_t)0*nbf*nbf);
    }
    if (own) delete[] c;
    return 0;
}


/* Operands of xck_cmgga_tau_r_o2_t: `fields` in the order of
 * xck_cmgga_tau_r_o2_field_names, `xc` in the order of xck_cmgga_tau_r_o2_xc_names (the
 * C ABI's `scal` is the two concatenated, split at n_fields). The
 * structs name them; the overload taking them packs the arrays. */
inline constexpr int xck_cmgga_tau_r_o2_n_fields = 16;
inline constexpr int xck_cmgga_tau_r_o2_n_xc = 8;
inline constexpr const char* xck_cmgga_tau_r_o2_field_names[] = {"w", "rho_x", "rho_y", "rho_z", "jpx", "jpy", "jpz", "inv_rho", "rho_p1_x", "rho_p1_y", "rho_p1_z", "jpx_p1", "jpy_p1", "jpz_p1", "rho_p1", "tau_p1"};
inline constexpr const char* xck_cmgga_tau_r_o2_xc_names[] = {"v2rho2", "v2sigma2", "v2tau2", "vsigma", "vtau", "v2rhosigma", "v2rhotau", "v2sigmatau"};
template <typename T>
struct xck_cmgga_tau_r_o2_fields {
    const T* w;
    const T* rho_x;
    const T* rho_y;
    const T* rho_z;
    const T* jpx;
    const T* jpy;
    const T* jpz;
    const T* inv_rho;
    const T* rho_p1_x;
    const T* rho_p1_y;
    const T* rho_p1_z;
    const T* jpx_p1;
    const T* jpy_p1;
    const T* jpz_p1;
    const T* rho_p1;
    const T* tau_p1;
};
template <typename Txc>
struct xck_cmgga_tau_r_o2_xc {
    const Txc* v2rho2;
    const Txc* v2sigma2;
    const Txc* v2tau2;
    const Txc* vsigma;
    const Txc* vtau;
    const Txc* v2rhosigma;
    const Txc* v2rhotau;
    const Txc* v2sigmatau;
};

template <typename T, typename Txc = T>
int xck_cmgga_tau_r_o2_t(int64_t npts,
        int64_t nbf,
        const T* chi,
        const xck_cmgga_tau_r_o2_fields<T>& fields_,
        const xck_cmgga_tau_r_o2_xc<Txc>& xc_,
        T* out,
        T* work = nullptr) {
    const T* f_[] = {fields_.w, fields_.rho_x, fields_.rho_y, fields_.rho_z, fields_.jpx, fields_.jpy, fields_.jpz, fields_.inv_rho, fields_.rho_p1_x, fields_.rho_p1_y, fields_.rho_p1_z, fields_.jpx_p1, fields_.jpy_p1, fields_.jpz_p1, fields_.rho_p1, fields_.tau_p1};
    const Txc* x_[] = {xc_.v2rho2, xc_.v2sigma2, xc_.v2tau2, xc_.vsigma, xc_.vtau, xc_.v2rhosigma, xc_.v2rhotau, xc_.v2sigmatau};
    return xck_cmgga_tau_r_o2_t<T, Txc>(npts, nbf, chi, f_, x_, out, work);
}

} // namespace xckernel
