/* generated by xckernel; do not edit. */
#pragma once
#include <cstdint>
#include <new>
#include "xckernel/evaluator.hpp"

namespace xckernel {
namespace detail_xck_mgga_ub_g1 {
static constexpr double c0_0[] = {
    -2.0
};
static constexpr int32_t o0_0[] = {
    0,2
};
static constexpr uint16_t f0_0[] = {
    8,0
};
static constexpr double c0_1[] = {
    -4.0,-2.0
};
static constexpr int32_t o0_1[] = {
    0,3,6
};
static constexpr uint16_t f0_1[] = {
    4,10,0,1,9,0
};
static constexpr double c0_2[] = {
    -4.0,-2.0
};
static constexpr int32_t o0_2[] = {
    0,3,6
};
static constexpr uint16_t f0_2[] = {
    5,10,0,2,9,0
};
static constexpr double c0_3[] = {
    -4.0,-2.0
};
static constexpr int32_t o0_3[] = {
    0,3,6
};
static constexpr uint16_t f0_3[] = {
    6,10,0,3,9,0
};
static constexpr double c0_4[] = {
    -2.0
};
static constexpr int32_t o0_4[] = {
    0,2
};
static constexpr uint16_t f0_4[] = {
    7,0
};
static constexpr double c0_5[] = {
    -2.0
};
static constexpr int32_t o0_5[] = {
    0,2
};
static constexpr uint16_t f0_5[] = {
    7,0
};
static constexpr double c0_6[] = {
    -4.0,-2.0
};
static constexpr int32_t o0_6[] = {
    0,3,6
};
static constexpr uint16_t f0_6[] = {
    4,10,0,1,9,0
};
static constexpr double c0_7[] = {
    -1.0,-4.0
};
static constexpr int32_t o0_7[] = {
    0,2,4
};
static constexpr uint16_t f0_7[] = {
    11,0,7,0
};
static constexpr double c0_8[] = {
    -4.0,-2.0
};
static constexpr int32_t o0_8[] = {
    0,3,6
};
static constexpr uint16_t f0_8[] = {
    5,10,0,2,9,0
};
static constexpr double c0_9[] = {
    -1.0,-4.0
};
static constexpr int32_t o0_9[] = {
    0,2,4
};
static constexpr uint16_t f0_9[] = {
    11,0,7,0
};
static constexpr double c0_10[] = {
    -4.0,-2.0
};
static constexpr int32_t o0_10[] = {
    0,3,6
};
static constexpr uint16_t f0_10[] = {
    6,10,0,3,9,0
};
static constexpr double c0_11[] = {
    -1.0,-4.0
};
static constexpr int32_t o0_11[] = {
    0,2,4
};
static constexpr uint16_t f0_11[] = {
    11,0,7,0
};
static constexpr double c1_0[] = {
    -2.0
};
static constexpr int32_t o1_0[] = {
    0,2
};
static constexpr uint16_t f1_0[] = {
    8,0
};
static constexpr double c1_1[] = {
    -4.0,-2.0
};
static constexpr int32_t o1_1[] = {
    0,3,6
};
static constexpr uint16_t f1_1[] = {
    4,10,0,1,9,0
};
static constexpr double c1_2[] = {
    -4.0,-2.0
};
static constexpr int32_t o1_2[] = {
    0,3,6
};
static constexpr uint16_t f1_2[] = {
    5,10,0,2,9,0
};
static constexpr double c1_3[] = {
    -4.0,-2.0
};
static constexpr int32_t o1_3[] = {
    0,3,6
};
static constexpr uint16_t f1_3[] = {
    6,10,0,3,9,0
};
static constexpr double c1_4[] = {
    -2.0
};
static constexpr int32_t o1_4[] = {
    0,2
};
static constexpr uint16_t f1_4[] = {
    7,0
};
static constexpr double c1_5[] = {
    -2.0
};
static constexpr int32_t o1_5[] = {
    0,2
};
static constexpr uint16_t f1_5[] = {
    7,0
};
static constexpr double c1_6[] = {
    -4.0,-2.0
};
static constexpr int32_t o1_6[] = {
    0,3,6
};
static constexpr uint16_t f1_6[] = {
    4,10,0,1,9,0
};
static constexpr double c1_7[] = {
    -1.0,-4.0
};
static constexpr int32_t o1_7[] = {
    0,2,4
};
static constexpr uint16_t f1_7[] = {
    11,0,7,0
};
static constexpr double c1_8[] = {
    -4.0,-2.0
};
static constexpr int32_t o1_8[] = {
    0,3,6
};
static constexpr uint16_t f1_8[] = {
    5,10,0,2,9,0
};
static constexpr double c1_9[] = {
    -1.0,-4.0
};
static constexpr int32_t o1_9[] = {
    0,2,4
};
static constexpr uint16_t f1_9[] = {
    11,0,7,0
};
static constexpr double c1_10[] = {
    -4.0,-2.0
};
static constexpr int32_t o1_10[] = {
    0,3,6
};
static constexpr uint16_t f1_10[] = {
    6,10,0,3,9,0
};
static constexpr double c1_11[] = {
    -1.0,-4.0
};
static constexpr int32_t o1_11[] = {
    0,2,4
};
static constexpr uint16_t f1_11[] = {
    11,0,7,0
};
static constexpr double c2_0[] = {
    -2.0
};
static constexpr int32_t o2_0[] = {
    0,2
};
static constexpr uint16_t f2_0[] = {
    8,0
};
static constexpr double c2_1[] = {
    -4.0,-2.0
};
static constexpr int32_t o2_1[] = {
    0,3,6
};
static constexpr uint16_t f2_1[] = {
    4,10,0,1,9,0
};
static constexpr double c2_2[] = {
    -4.0,-2.0
};
static constexpr int32_t o2_2[] = {
    0,3,6
};
static constexpr uint16_t f2_2[] = {
    5,10,0,2,9,0
};
static constexpr double c2_3[] = {
    -4.0,-2.0
};
static constexpr int32_t o2_3[] = {
    0,3,6
};
static constexpr uint16_t f2_3[] = {
    6,10,0,3,9,0
};
static constexpr double c2_4[] = {
    -2.0
};
static constexpr int32_t o2_4[] = {
    0,2
};
static constexpr uint16_t f2_4[] = {
    7,0
};
static constexpr double c2_5[] = {
    -2.0
};
static constexpr int32_t o2_5[] = {
    0,2
};
static constexpr uint16_t f2_5[] = {
    7,0
};
static constexpr double c2_6[] = {
    -4.0,-2.0
};
static constexpr int32_t o2_6[] = {
    0,3,6
};
static constexpr uint16_t f2_6[] = {
    4,10,0,1,9,0
};
static constexpr double c2_7[] = {
    -1.0,-4.0
};
static constexpr int32_t o2_7[] = {
    0,2,4
};
static constexpr uint16_t f2_7[] = {
    11,0,7,0
};
static constexpr double c2_8[] = {
    -4.0,-2.0
};
static constexpr int32_t o2_8[] = {
    0,3,6
};
static constexpr uint16_t f2_8[] = {
    5,10,0,2,9,0
};
static constexpr double c2_9[] = {
    -1.0,-4.0
};
static constexpr int32_t o2_9[] = {
    0,2,4
};
static constexpr uint16_t f2_9[] = {
    11,0,7,0
};
static constexpr double c2_10[] = {
    -4.0,-2.0
};
static constexpr int32_t o2_10[] = {
    0,3,6
};
static constexpr uint16_t f2_10[] = {
    6,10,0,3,9,0
};
static constexpr double c2_11[] = {
    -1.0,-4.0
};
static constexpr int32_t o2_11[] = {
    0,2,4
};
static constexpr uint16_t f2_11[] = {
    11,0,7,0
};
static constexpr int64_t NFLD = 7;
} // namespace detail_xck_mgga_ub_g1

/* Scratch (elements of T) the kernel needs: pass at least this
 * much as `work`, or nullptr to allocate it internally. */
inline int64_t xck_mgga_ub_g1_work(int64_t npts, int64_t nbf) {
    const int64_t blk = npts < grid_block ? npts : grid_block;
    return blk * (1 + nbf * 5) + 0 * npts + 1;
}

/* fields: the per-point tower operands (type T), in the order
 * of xck_mgga_ub_g1_scal_names; xc: the functional-derivative arrays
 * (type Txc; Libxc computes in double whatever T is). */
template <typename T, typename Txc = T>
int xck_mgga_ub_g1_t(int64_t npts,
        int64_t nbf,
        const T* chi,
        const T* Dchi,
        const T* const* fields,
        const Txc* const* xc,
        T* out,
        T* work = nullptr) {
    const int64_t blk = npts < grid_block ? npts : grid_block;
    T* c = work;
    bool own = false;
    if (!c) {
        c = new (std::nothrow) T[xck_mgga_ub_g1_work(npts, nbf)];
        own = true;
    }
    if (!c) return 1;
    T* W = c + blk;
    const T* Wc = W;
    T* X0 = W + (int64_t)1*nbf*blk;
    T* X1 = W + (int64_t)2*nbf*blk;
    T* X2 = W + (int64_t)3*nbf*blk;
    T* X3 = W + (int64_t)4*nbf*blk;
    const T* fi[7] = {fields[0], fields[1], fields[2], fields[3], fields[4], fields[5], fields[6]};
    for (int64_t g0 = 0; g0 < npts; g0 += blk) {
        const int64_t bk = npts - g0 < blk ? npts - g0 : blk;
        {
            const T* s_[] = {Dchi + (int64_t)4*nbf*npts + g0, Dchi + (int64_t)7*nbf*npts + g0, Dchi + (int64_t)9*nbf*npts + g0};
            static constexpr double w_[] = {1.0, 1.0, 1.0};
            combine<T>(bk, nbf, 3, s_, w_, npts, X0);
        }
        {
            const T* s_[] = {chi + (int64_t)10*nbf*npts + g0, chi + (int64_t)13*nbf*npts + g0, chi + (int64_t)15*nbf*npts + g0};
            static constexpr double w_[] = {1.0, 1.0, 1.0};
            combine<T>(bk, nbf, 3, s_, w_, npts, X1);
        }
        {
            const T* s_[] = {chi + (int64_t)11*nbf*npts + g0, chi + (int64_t)16*nbf*npts + g0, chi + (int64_t)18*nbf*npts + g0};
            static constexpr double w_[] = {1.0, 1.0, 1.0};
            combine<T>(bk, nbf, 3, s_, w_, npts, X2);
        }
        {
            const T* s_[] = {chi + (int64_t)12*nbf*npts + g0, chi + (int64_t)17*nbf*npts + g0, chi + (int64_t)19*nbf*npts + g0};
            static constexpr double w_[] = {1.0, 1.0, 1.0};
            combine<T>(bk, nbf, 3, s_, w_, npts, X3);
        }
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_ub_g1::c0_0, detail_xck_mgga_ub_g1::o0_0, detail_xck_mgga_ub_g1::f0_0, detail_xck_mgga_ub_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_ub_g1::c0_1, detail_xck_mgga_ub_g1::o0_1, detail_xck_mgga_ub_g1::f0_1, detail_xck_mgga_ub_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)1*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_ub_g1::c0_2, detail_xck_mgga_ub_g1::o0_2, detail_xck_mgga_ub_g1::f0_2, detail_xck_mgga_ub_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)2*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_ub_g1::c0_3, detail_xck_mgga_ub_g1::o0_3, detail_xck_mgga_ub_g1::f0_3, detail_xck_mgga_ub_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)3*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_ub_g1::c0_4, detail_xck_mgga_ub_g1::o0_4, detail_xck_mgga_ub_g1::f0_4, detail_xck_mgga_ub_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, X0, bk, W, 0);
        rowdot(nbf, bk, chi + (int64_t)1*nbf*npts + g0, npts, Wc, bk, out + (int64_t)0*nbf);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_ub_g1::c0_5, detail_xck_mgga_ub_g1::o0_5, detail_xck_mgga_ub_g1::f0_5, detail_xck_mgga_ub_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        rowdot(nbf, bk, X1, bk, Wc, bk, out + (int64_t)0*nbf);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_ub_g1::c0_6, detail_xck_mgga_ub_g1::o0_6, detail_xck_mgga_ub_g1::f0_6, detail_xck_mgga_ub_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_ub_g1::c0_7, detail_xck_mgga_ub_g1::o0_7, detail_xck_mgga_ub_g1::f0_7, detail_xck_mgga_ub_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)1*nbf*npts + g0, npts, W, 0);
        rowdot(nbf, bk, chi + (int64_t)4*nbf*npts + g0, npts, Wc, bk, out + (int64_t)0*nbf);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_ub_g1::c0_8, detail_xck_mgga_ub_g1::o0_8, detail_xck_mgga_ub_g1::f0_8, detail_xck_mgga_ub_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_ub_g1::c0_9, detail_xck_mgga_ub_g1::o0_9, detail_xck_mgga_ub_g1::f0_9, detail_xck_mgga_ub_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)2*nbf*npts + g0, npts, W, 0);
        rowdot(nbf, bk, chi + (int64_t)5*nbf*npts + g0, npts, Wc, bk, out + (int64_t)0*nbf);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_ub_g1::c0_10, detail_xck_mgga_ub_g1::o0_10, detail_xck_mgga_ub_g1::f0_10, detail_xck_mgga_ub_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_ub_g1::c0_11, detail_xck_mgga_ub_g1::o0_11, detail_xck_mgga_ub_g1::f0_11, detail_xck_mgga_ub_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)3*nbf*npts + g0, npts, W, 0);
        rowdot(nbf, bk, chi + (int64_t)6*nbf*npts + g0, npts, Wc, bk, out + (int64_t)0*nbf);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_ub_g1::c1_0, detail_xck_mgga_ub_g1::o1_0, detail_xck_mgga_ub_g1::f1_0, detail_xck_mgga_ub_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_ub_g1::c1_1, detail_xck_mgga_ub_g1::o1_1, detail_xck_mgga_ub_g1::f1_1, detail_xck_mgga_ub_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)1*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_ub_g1::c1_2, detail_xck_mgga_ub_g1::o1_2, detail_xck_mgga_ub_g1::f1_2, detail_xck_mgga_ub_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)2*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_ub_g1::c1_3, detail_xck_mgga_ub_g1::o1_3, detail_xck_mgga_ub_g1::f1_3, detail_xck_mgga_ub_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)3*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_ub_g1::c1_4, detail_xck_mgga_ub_g1::o1_4, detail_xck_mgga_ub_g1::f1_4, detail_xck_mgga_ub_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, X0, bk, W, 0);
        rowdot(nbf, bk, chi + (int64_t)2*nbf*npts + g0, npts, Wc, bk, out + (int64_t)1*nbf);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_ub_g1::c1_5, detail_xck_mgga_ub_g1::o1_5, detail_xck_mgga_ub_g1::f1_5, detail_xck_mgga_ub_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        rowdot(nbf, bk, X2, bk, Wc, bk, out + (int64_t)1*nbf);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_ub_g1::c1_6, detail_xck_mgga_ub_g1::o1_6, detail_xck_mgga_ub_g1::f1_6, detail_xck_mgga_ub_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_ub_g1::c1_7, detail_xck_mgga_ub_g1::o1_7, detail_xck_mgga_ub_g1::f1_7, detail_xck_mgga_ub_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)1*nbf*npts + g0, npts, W, 0);
        rowdot(nbf, bk, chi + (int64_t)5*nbf*npts + g0, npts, Wc, bk, out + (int64_t)1*nbf);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_ub_g1::c1_8, detail_xck_mgga_ub_g1::o1_8, detail_xck_mgga_ub_g1::f1_8, detail_xck_mgga_ub_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_ub_g1::c1_9, detail_xck_mgga_ub_g1::o1_9, detail_xck_mgga_ub_g1::f1_9, detail_xck_mgga_ub_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)2*nbf*npts + g0, npts, W, 0);
        rowdot(nbf, bk, chi + (int64_t)7*nbf*npts + g0, npts, Wc, bk, out + (int64_t)1*nbf);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_ub_g1::c1_10, detail_xck_mgga_ub_g1::o1_10, detail_xck_mgga_ub_g1::f1_10, detail_xck_mgga_ub_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_ub_g1::c1_11, detail_xck_mgga_ub_g1::o1_11, detail_xck_mgga_ub_g1::f1_11, detail_xck_mgga_ub_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)3*nbf*npts + g0, npts, W, 0);
        rowdot(nbf, bk, chi + (int64_t)8*nbf*npts + g0, npts, Wc, bk, out + (int64_t)1*nbf);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_ub_g1::c2_0, detail_xck_mgga_ub_g1::o2_0, detail_xck_mgga_ub_g1::f2_0, detail_xck_mgga_ub_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_ub_g1::c2_1, detail_xck_mgga_ub_g1::o2_1, detail_xck_mgga_ub_g1::f2_1, detail_xck_mgga_ub_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)1*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_ub_g1::c2_2, detail_xck_mgga_ub_g1::o2_2, detail_xck_mgga_ub_g1::f2_2, detail_xck_mgga_ub_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)2*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_ub_g1::c2_3, detail_xck_mgga_ub_g1::o2_3, detail_xck_mgga_ub_g1::f2_3, detail_xck_mgga_ub_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)3*nbf*npts + g0, npts, W, 0);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_ub_g1::c2_4, detail_xck_mgga_ub_g1::o2_4, detail_xck_mgga_ub_g1::f2_4, detail_xck_mgga_ub_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, X0, bk, W, 0);
        rowdot(nbf, bk, chi + (int64_t)3*nbf*npts + g0, npts, Wc, bk, out + (int64_t)2*nbf);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_ub_g1::c2_5, detail_xck_mgga_ub_g1::o2_5, detail_xck_mgga_ub_g1::f2_5, detail_xck_mgga_ub_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        rowdot(nbf, bk, X3, bk, Wc, bk, out + (int64_t)2*nbf);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_ub_g1::c2_6, detail_xck_mgga_ub_g1::o2_6, detail_xck_mgga_ub_g1::f2_6, detail_xck_mgga_ub_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_ub_g1::c2_7, detail_xck_mgga_ub_g1::o2_7, detail_xck_mgga_ub_g1::f2_7, detail_xck_mgga_ub_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)1*nbf*npts + g0, npts, W, 0);
        rowdot(nbf, bk, chi + (int64_t)6*nbf*npts + g0, npts, Wc, bk, out + (int64_t)2*nbf);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_ub_g1::c2_8, detail_xck_mgga_ub_g1::o2_8, detail_xck_mgga_ub_g1::f2_8, detail_xck_mgga_ub_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_ub_g1::c2_9, detail_xck_mgga_ub_g1::o2_9, detail_xck_mgga_ub_g1::f2_9, detail_xck_mgga_ub_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)2*nbf*npts + g0, npts, W, 0);
        rowdot(nbf, bk, chi + (int64_t)8*nbf*npts + g0, npts, Wc, bk, out + (int64_t)2*nbf);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_ub_g1::c2_10, detail_xck_mgga_ub_g1::o2_10, detail_xck_mgga_ub_g1::f2_10, detail_xck_mgga_ub_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_ub_g1::c2_11, detail_xck_mgga_ub_g1::o2_11, detail_xck_mgga_ub_g1::f2_11, detail_xck_mgga_ub_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)3*nbf*npts + g0, npts, W, 0);
        rowdot(nbf, bk, chi + (int64_t)9*nbf*npts + g0, npts, Wc, bk, out + (int64_t)2*nbf);
    }
    if (own) delete[] c;
    return 0;
}

} // namespace xckernel
