/* generated by xckernel; do not edit. */
#pragma once
#include <cstdint>
#include <new>
#include "xckernel/evaluator.hpp"

namespace xckernel {
namespace detail_xck_mgga_r_o2_batch {
static constexpr double c0_4[] = {
    2.0
};
static constexpr int32_t o0_4[] = {
    0,3
};
static constexpr uint16_t f0_4[] = {
    1,11,0
};
static constexpr double c0_5[] = {
    2.0
};
static constexpr int32_t o0_5[] = {
    0,3
};
static constexpr uint16_t f0_5[] = {
    2,11,0
};
static constexpr double c0_6[] = {
    2.0
};
static constexpr int32_t o0_6[] = {
    0,3
};
static constexpr uint16_t f0_6[] = {
    3,11,0
};
static constexpr double c0_7[] = {
    1.0
};
static constexpr int32_t o0_7[] = {
    0,2
};
static constexpr uint16_t f0_7[] = {
    10,0
};
static constexpr double c0_8[] = {
    1.0
};
static constexpr int32_t o0_8[] = {
    0,2
};
static constexpr uint16_t f0_8[] = {
    10,0
};
static constexpr double c0_9[] = {
    1.0
};
static constexpr int32_t o0_9[] = {
    0,2
};
static constexpr uint16_t f0_9[] = {
    10,0
};
static constexpr double c0_10[] = {
    1.0
};
static constexpr int32_t o0_10[] = {
    0,2
};
static constexpr uint16_t f0_10[] = {
    5,0
};
static constexpr double c0_11[] = {
    1.0
};
static constexpr int32_t o0_11[] = {
    0,2
};
static constexpr uint16_t f0_11[] = {
    12,0
};
static constexpr double c1_4[] = {
    2.0,4.0
};
static constexpr int32_t o1_4[] = {
    0,2,6
};
static constexpr uint16_t f1_4[] = {
    8,0,1,1,6,0
};
static constexpr double c1_5[] = {
    4.0
};
static constexpr int32_t o1_5[] = {
    0,4
};
static constexpr uint16_t f1_5[] = {
    1,2,6,0
};
static constexpr double c1_6[] = {
    4.0
};
static constexpr int32_t o1_6[] = {
    0,4
};
static constexpr uint16_t f1_6[] = {
    1,3,6,0
};
static constexpr double c1_7[] = {
    2.0
};
static constexpr int32_t o1_7[] = {
    0,3
};
static constexpr uint16_t f1_7[] = {
    1,13,0
};
static constexpr double c1_8[] = {
    2.0
};
static constexpr int32_t o1_8[] = {
    0,3
};
static constexpr uint16_t f1_8[] = {
    1,13,0
};
static constexpr double c1_9[] = {
    2.0
};
static constexpr int32_t o1_9[] = {
    0,3
};
static constexpr uint16_t f1_9[] = {
    1,13,0
};
static constexpr double c1_10[] = {
    2.0
};
static constexpr int32_t o1_10[] = {
    0,3
};
static constexpr uint16_t f1_10[] = {
    1,11,0
};
static constexpr double c1_11[] = {
    2.0
};
static constexpr int32_t o1_11[] = {
    0,3
};
static constexpr uint16_t f1_11[] = {
    1,14,0
};
static constexpr double c2_4[] = {
    4.0
};
static constexpr int32_t o2_4[] = {
    0,4
};
static constexpr uint16_t f2_4[] = {
    1,2,6,0
};
static constexpr double c2_5[] = {
    2.0,4.0
};
static constexpr int32_t o2_5[] = {
    0,2,6
};
static constexpr uint16_t f2_5[] = {
    8,0,2,2,6,0
};
static constexpr double c2_6[] = {
    4.0
};
static constexpr int32_t o2_6[] = {
    0,4
};
static constexpr uint16_t f2_6[] = {
    2,3,6,0
};
static constexpr double c2_7[] = {
    2.0
};
static constexpr int32_t o2_7[] = {
    0,3
};
static constexpr uint16_t f2_7[] = {
    2,13,0
};
static constexpr double c2_8[] = {
    2.0
};
static constexpr int32_t o2_8[] = {
    0,3
};
static constexpr uint16_t f2_8[] = {
    2,13,0
};
static constexpr double c2_9[] = {
    2.0
};
static constexpr int32_t o2_9[] = {
    0,3
};
static constexpr uint16_t f2_9[] = {
    2,13,0
};
static constexpr double c2_10[] = {
    2.0
};
static constexpr int32_t o2_10[] = {
    0,3
};
static constexpr uint16_t f2_10[] = {
    2,11,0
};
static constexpr double c2_11[] = {
    2.0
};
static constexpr int32_t o2_11[] = {
    0,3
};
static constexpr uint16_t f2_11[] = {
    2,14,0
};
static constexpr double c3_4[] = {
    4.0
};
static constexpr int32_t o3_4[] = {
    0,4
};
static constexpr uint16_t f3_4[] = {
    1,3,6,0
};
static constexpr double c3_5[] = {
    4.0
};
static constexpr int32_t o3_5[] = {
    0,4
};
static constexpr uint16_t f3_5[] = {
    2,3,6,0
};
static constexpr double c3_6[] = {
    2.0,4.0
};
static constexpr int32_t o3_6[] = {
    0,2,6
};
static constexpr uint16_t f3_6[] = {
    8,0,3,3,6,0
};
static constexpr double c3_7[] = {
    2.0
};
static constexpr int32_t o3_7[] = {
    0,3
};
static constexpr uint16_t f3_7[] = {
    3,13,0
};
static constexpr double c3_8[] = {
    2.0
};
static constexpr int32_t o3_8[] = {
    0,3
};
static constexpr uint16_t f3_8[] = {
    3,13,0
};
static constexpr double c3_9[] = {
    2.0
};
static constexpr int32_t o3_9[] = {
    0,3
};
static constexpr uint16_t f3_9[] = {
    3,13,0
};
static constexpr double c3_10[] = {
    2.0
};
static constexpr int32_t o3_10[] = {
    0,3
};
static constexpr uint16_t f3_10[] = {
    3,11,0
};
static constexpr double c3_11[] = {
    2.0
};
static constexpr int32_t o3_11[] = {
    0,3
};
static constexpr uint16_t f3_11[] = {
    3,14,0
};
static constexpr double c4_4[] = {
    2.0
};
static constexpr int32_t o4_4[] = {
    0,3
};
static constexpr uint16_t f4_4[] = {
    1,13,0
};
static constexpr double c4_5[] = {
    2.0
};
static constexpr int32_t o4_5[] = {
    0,3
};
static constexpr uint16_t f4_5[] = {
    2,13,0
};
static constexpr double c4_6[] = {
    2.0
};
static constexpr int32_t o4_6[] = {
    0,3
};
static constexpr uint16_t f4_6[] = {
    3,13,0
};
static constexpr double c4_7[] = {
    1.0
};
static constexpr int32_t o4_7[] = {
    0,2
};
static constexpr uint16_t f4_7[] = {
    4,0
};
static constexpr double c4_8[] = {
    1.0
};
static constexpr int32_t o4_8[] = {
    0,2
};
static constexpr uint16_t f4_8[] = {
    4,0
};
static constexpr double c4_9[] = {
    1.0
};
static constexpr int32_t o4_9[] = {
    0,2
};
static constexpr uint16_t f4_9[] = {
    4,0
};
static constexpr double c4_10[] = {
    1.0
};
static constexpr int32_t o4_10[] = {
    0,2
};
static constexpr uint16_t f4_10[] = {
    10,0
};
static constexpr double c4_11[] = {
    1.0
};
static constexpr int32_t o4_11[] = {
    0,2
};
static constexpr uint16_t f4_11[] = {
    9,0
};
static constexpr double c5_4[] = {
    2.0,4.0
};
static constexpr int32_t o5_4[] = {
    0,2,6
};
static constexpr uint16_t f5_4[] = {
    8,0,1,1,6,0
};
static constexpr double c5_5[] = {
    4.0
};
static constexpr int32_t o5_5[] = {
    0,4
};
static constexpr uint16_t f5_5[] = {
    1,2,6,0
};
static constexpr double c5_6[] = {
    4.0
};
static constexpr int32_t o5_6[] = {
    0,4
};
static constexpr uint16_t f5_6[] = {
    1,3,6,0
};
static constexpr double c5_7[] = {
    2.0
};
static constexpr int32_t o5_7[] = {
    0,3
};
static constexpr uint16_t f5_7[] = {
    1,13,0
};
static constexpr double c5_8[] = {
    2.0
};
static constexpr int32_t o5_8[] = {
    0,3
};
static constexpr uint16_t f5_8[] = {
    1,13,0
};
static constexpr double c5_9[] = {
    2.0
};
static constexpr int32_t o5_9[] = {
    0,3
};
static constexpr uint16_t f5_9[] = {
    1,13,0
};
static constexpr double c5_10[] = {
    2.0
};
static constexpr int32_t o5_10[] = {
    0,3
};
static constexpr uint16_t f5_10[] = {
    1,11,0
};
static constexpr double c5_11[] = {
    2.0
};
static constexpr int32_t o5_11[] = {
    0,3
};
static constexpr uint16_t f5_11[] = {
    1,14,0
};
static constexpr double c6_4[] = {
    1.0,4.0
};
static constexpr int32_t o6_4[] = {
    0,3,6
};
static constexpr uint16_t f6_4[] = {
    1,14,0,1,13,0
};
static constexpr double c6_5[] = {
    1.0,4.0
};
static constexpr int32_t o6_5[] = {
    0,3,6
};
static constexpr uint16_t f6_5[] = {
    2,14,0,2,13,0
};
static constexpr double c6_6[] = {
    1.0,4.0
};
static constexpr int32_t o6_6[] = {
    0,3,6
};
static constexpr uint16_t f6_6[] = {
    3,14,0,3,13,0
};
static constexpr double c6_7[] = {
    0.5,2.0
};
static constexpr int32_t o6_7[] = {
    0,2,4
};
static constexpr uint16_t f6_7[] = {
    9,0,4,0
};
static constexpr double c6_8[] = {
    0.5,2.0
};
static constexpr int32_t o6_8[] = {
    0,2,4
};
static constexpr uint16_t f6_8[] = {
    9,0,4,0
};
static constexpr double c6_9[] = {
    0.5,2.0
};
static constexpr int32_t o6_9[] = {
    0,2,4
};
static constexpr uint16_t f6_9[] = {
    9,0,4,0
};
static constexpr double c6_10[] = {
    0.5,2.0
};
static constexpr int32_t o6_10[] = {
    0,2,4
};
static constexpr uint16_t f6_10[] = {
    12,0,10,0
};
static constexpr double c6_11[] = {
    0.5,2.0
};
static constexpr int32_t o6_11[] = {
    0,2,4
};
static constexpr uint16_t f6_11[] = {
    7,0,9,0
};
static constexpr double c7_4[] = {
    4.0
};
static constexpr int32_t o7_4[] = {
    0,4
};
static constexpr uint16_t f7_4[] = {
    1,2,6,0
};
static constexpr double c7_5[] = {
    2.0,4.0
};
static constexpr int32_t o7_5[] = {
    0,2,6
};
static constexpr uint16_t f7_5[] = {
    8,0,2,2,6,0
};
static constexpr double c7_6[] = {
    4.0
};
static constexpr int32_t o7_6[] = {
    0,4
};
static constexpr uint16_t f7_6[] = {
    2,3,6,0
};
static constexpr double c7_7[] = {
    2.0
};
static constexpr int32_t o7_7[] = {
    0,3
};
static constexpr uint16_t f7_7[] = {
    2,13,0
};
static constexpr double c7_8[] = {
    2.0
};
static constexpr int32_t o7_8[] = {
    0,3
};
static constexpr uint16_t f7_8[] = {
    2,13,0
};
static constexpr double c7_9[] = {
    2.0
};
static constexpr int32_t o7_9[] = {
    0,3
};
static constexpr uint16_t f7_9[] = {
    2,13,0
};
static constexpr double c7_10[] = {
    2.0
};
static constexpr int32_t o7_10[] = {
    0,3
};
static constexpr uint16_t f7_10[] = {
    2,11,0
};
static constexpr double c7_11[] = {
    2.0
};
static constexpr int32_t o7_11[] = {
    0,3
};
static constexpr uint16_t f7_11[] = {
    2,14,0
};
static constexpr double c8_4[] = {
    1.0,4.0
};
static constexpr int32_t o8_4[] = {
    0,3,6
};
static constexpr uint16_t f8_4[] = {
    1,14,0,1,13,0
};
static constexpr double c8_5[] = {
    1.0,4.0
};
static constexpr int32_t o8_5[] = {
    0,3,6
};
static constexpr uint16_t f8_5[] = {
    2,14,0,2,13,0
};
static constexpr double c8_6[] = {
    1.0,4.0
};
static constexpr int32_t o8_6[] = {
    0,3,6
};
static constexpr uint16_t f8_6[] = {
    3,14,0,3,13,0
};
static constexpr double c8_7[] = {
    0.5,2.0
};
static constexpr int32_t o8_7[] = {
    0,2,4
};
static constexpr uint16_t f8_7[] = {
    9,0,4,0
};
static constexpr double c8_8[] = {
    0.5,2.0
};
static constexpr int32_t o8_8[] = {
    0,2,4
};
static constexpr uint16_t f8_8[] = {
    9,0,4,0
};
static constexpr double c8_9[] = {
    0.5,2.0
};
static constexpr int32_t o8_9[] = {
    0,2,4
};
static constexpr uint16_t f8_9[] = {
    9,0,4,0
};
static constexpr double c8_10[] = {
    0.5,2.0
};
static constexpr int32_t o8_10[] = {
    0,2,4
};
static constexpr uint16_t f8_10[] = {
    12,0,10,0
};
static constexpr double c8_11[] = {
    0.5,2.0
};
static constexpr int32_t o8_11[] = {
    0,2,4
};
static constexpr uint16_t f8_11[] = {
    7,0,9,0
};
static constexpr double c9_4[] = {
    4.0
};
static constexpr int32_t o9_4[] = {
    0,4
};
static constexpr uint16_t f9_4[] = {
    1,3,6,0
};
static constexpr double c9_5[] = {
    4.0
};
static constexpr int32_t o9_5[] = {
    0,4
};
static constexpr uint16_t f9_5[] = {
    2,3,6,0
};
static constexpr double c9_6[] = {
    2.0,4.0
};
static constexpr int32_t o9_6[] = {
    0,2,6
};
static constexpr uint16_t f9_6[] = {
    8,0,3,3,6,0
};
static constexpr double c9_7[] = {
    2.0
};
static constexpr int32_t o9_7[] = {
    0,3
};
static constexpr uint16_t f9_7[] = {
    3,13,0
};
static constexpr double c9_8[] = {
    2.0
};
static constexpr int32_t o9_8[] = {
    0,3
};
static constexpr uint16_t f9_8[] = {
    3,13,0
};
static constexpr double c9_9[] = {
    2.0
};
static constexpr int32_t o9_9[] = {
    0,3
};
static constexpr uint16_t f9_9[] = {
    3,13,0
};
static constexpr double c9_10[] = {
    2.0
};
static constexpr int32_t o9_10[] = {
    0,3
};
static constexpr uint16_t f9_10[] = {
    3,11,0
};
static constexpr double c9_11[] = {
    2.0
};
static constexpr int32_t o9_11[] = {
    0,3
};
static constexpr uint16_t f9_11[] = {
    3,14,0
};
static constexpr double c10_4[] = {
    1.0,4.0
};
static constexpr int32_t o10_4[] = {
    0,3,6
};
static constexpr uint16_t f10_4[] = {
    1,14,0,1,13,0
};
static constexpr double c10_5[] = {
    1.0,4.0
};
static constexpr int32_t o10_5[] = {
    0,3,6
};
static constexpr uint16_t f10_5[] = {
    2,14,0,2,13,0
};
static constexpr double c10_6[] = {
    1.0,4.0
};
static constexpr int32_t o10_6[] = {
    0,3,6
};
static constexpr uint16_t f10_6[] = {
    3,14,0,3,13,0
};
static constexpr double c10_7[] = {
    0.5,2.0
};
static constexpr int32_t o10_7[] = {
    0,2,4
};
static constexpr uint16_t f10_7[] = {
    9,0,4,0
};
static constexpr double c10_8[] = {
    0.5,2.0
};
static constexpr int32_t o10_8[] = {
    0,2,4
};
static constexpr uint16_t f10_8[] = {
    9,0,4,0
};
static constexpr double c10_9[] = {
    0.5,2.0
};
static constexpr int32_t o10_9[] = {
    0,2,4
};
static constexpr uint16_t f10_9[] = {
    9,0,4,0
};
static constexpr double c10_10[] = {
    0.5,2.0
};
static constexpr int32_t o10_10[] = {
    0,2,4
};
static constexpr uint16_t f10_10[] = {
    12,0,10,0
};
static constexpr double c10_11[] = {
    0.5,2.0
};
static constexpr int32_t o10_11[] = {
    0,2,4
};
static constexpr uint16_t f10_11[] = {
    7,0,9,0
};
static constexpr double c11_4[] = {
    2.0
};
static constexpr int32_t o11_4[] = {
    0,3
};
static constexpr uint16_t f11_4[] = {
    1,13,0
};
static constexpr double c11_5[] = {
    2.0
};
static constexpr int32_t o11_5[] = {
    0,3
};
static constexpr uint16_t f11_5[] = {
    2,13,0
};
static constexpr double c11_6[] = {
    2.0
};
static constexpr int32_t o11_6[] = {
    0,3
};
static constexpr uint16_t f11_6[] = {
    3,13,0
};
static constexpr double c11_7[] = {
    1.0
};
static constexpr int32_t o11_7[] = {
    0,2
};
static constexpr uint16_t f11_7[] = {
    4,0
};
static constexpr double c11_8[] = {
    1.0
};
static constexpr int32_t o11_8[] = {
    0,2
};
static constexpr uint16_t f11_8[] = {
    4,0
};
static constexpr double c11_9[] = {
    1.0
};
static constexpr int32_t o11_9[] = {
    0,2
};
static constexpr uint16_t f11_9[] = {
    4,0
};
static constexpr double c11_10[] = {
    1.0
};
static constexpr int32_t o11_10[] = {
    0,2
};
static constexpr uint16_t f11_10[] = {
    10,0
};
static constexpr double c11_11[] = {
    1.0
};
static constexpr int32_t o11_11[] = {
    0,2
};
static constexpr uint16_t f11_11[] = {
    9,0
};
static constexpr int64_t NFLD = 4;
} // namespace detail_xck_mgga_r_o2_batch

/* Scratch (elements of T) the kernel needs for nx perturbations. */
inline int64_t xck_mgga_r_o2_batch_work(int64_t npts, int64_t nbf, int64_t nx) {
    const int64_t blk = npts < grid_block ? npts : grid_block;
    const int64_t nxc = nx < 8 ? nx : 8;
    return blk * (97 + nbf * (nxc + 1)) + 0 * npts + 1;
}

/* fields: the per-point tower operands in the order of
 * xck_mgga_r_o2_batch_field_names, perturbed ones (_p1) (nx, npts); xc in
 * the order of xck_mgga_r_o2_batch_xc_names (both below). */
template <typename T, typename Txc = T>
int xck_mgga_r_o2_batch_t(int64_t npts, int64_t nbf, int64_t nx,
        const T* chi, const T* const* fields,
        const Txc* const* xc, T* out, T* work = nullptr) {
    const int64_t blk = npts < grid_block ? npts : grid_block;
    const int64_t nxc = nx < 8 ? nx : 8;
    T* c = work;
    bool own = false;
    if (!c) {
        c = new (std::nothrow) T[xck_mgga_r_o2_batch_work(npts, nbf, nx)];
        own = true;
    }
    if (!c) return 1;
    T* A = c + blk;
    T* W = A + (int64_t)96*blk;
    T* X0 = W + nxc*nbf*blk + (int64_t)0*nbf*blk;
    T* Sb = c + blk * (97 + nbf * (nxc + 1));
    const T* fi[4] = {fields[0], fields[1], fields[2], fields[3]};
    for (int64_t g0 = 0; g0 < npts; g0 += blk) {
        const int64_t bk = npts - g0 < blk ? npts - g0 : blk;
        {
            const T* s_[] = {chi + (int64_t)4*nbf*npts + g0, chi + (int64_t)7*nbf*npts + g0, chi + (int64_t)9*nbf*npts + g0};
            static constexpr double w_[] = {1.0, 1.0, 1.0};
            combine<T>(bk, nbf, 3, s_, w_, npts, X0);
        }
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_r_o2_batch::c0_4, detail_xck_mgga_r_o2_batch::o0_4, detail_xck_mgga_r_o2_batch::f0_4, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)0*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_r_o2_batch::c0_5, detail_xck_mgga_r_o2_batch::o0_5, detail_xck_mgga_r_o2_batch::f0_5, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)1*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_r_o2_batch::c0_6, detail_xck_mgga_r_o2_batch::o0_6, detail_xck_mgga_r_o2_batch::f0_6, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)2*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_r_o2_batch::c0_7, detail_xck_mgga_r_o2_batch::o0_7, detail_xck_mgga_r_o2_batch::f0_7, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)3*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_r_o2_batch::c0_8, detail_xck_mgga_r_o2_batch::o0_8, detail_xck_mgga_r_o2_batch::f0_8, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)4*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_r_o2_batch::c0_9, detail_xck_mgga_r_o2_batch::o0_9, detail_xck_mgga_r_o2_batch::f0_9, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)5*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_r_o2_batch::c0_10, detail_xck_mgga_r_o2_batch::o0_10, detail_xck_mgga_r_o2_batch::f0_10, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)6*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_r_o2_batch::c0_11, detail_xck_mgga_r_o2_batch::o0_11, detail_xck_mgga_r_o2_batch::f0_11, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)7*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_r_o2_batch::c1_4, detail_xck_mgga_r_o2_batch::o1_4, detail_xck_mgga_r_o2_batch::f1_4, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)8*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_r_o2_batch::c1_5, detail_xck_mgga_r_o2_batch::o1_5, detail_xck_mgga_r_o2_batch::f1_5, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)9*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_r_o2_batch::c1_6, detail_xck_mgga_r_o2_batch::o1_6, detail_xck_mgga_r_o2_batch::f1_6, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)10*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_r_o2_batch::c1_7, detail_xck_mgga_r_o2_batch::o1_7, detail_xck_mgga_r_o2_batch::f1_7, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)11*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_r_o2_batch::c1_8, detail_xck_mgga_r_o2_batch::o1_8, detail_xck_mgga_r_o2_batch::f1_8, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)12*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_r_o2_batch::c1_9, detail_xck_mgga_r_o2_batch::o1_9, detail_xck_mgga_r_o2_batch::f1_9, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)13*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_r_o2_batch::c1_10, detail_xck_mgga_r_o2_batch::o1_10, detail_xck_mgga_r_o2_batch::f1_10, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)14*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_r_o2_batch::c1_11, detail_xck_mgga_r_o2_batch::o1_11, detail_xck_mgga_r_o2_batch::f1_11, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)15*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_r_o2_batch::c2_4, detail_xck_mgga_r_o2_batch::o2_4, detail_xck_mgga_r_o2_batch::f2_4, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)16*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_r_o2_batch::c2_5, detail_xck_mgga_r_o2_batch::o2_5, detail_xck_mgga_r_o2_batch::f2_5, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)17*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_r_o2_batch::c2_6, detail_xck_mgga_r_o2_batch::o2_6, detail_xck_mgga_r_o2_batch::f2_6, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)18*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_r_o2_batch::c2_7, detail_xck_mgga_r_o2_batch::o2_7, detail_xck_mgga_r_o2_batch::f2_7, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)19*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_r_o2_batch::c2_8, detail_xck_mgga_r_o2_batch::o2_8, detail_xck_mgga_r_o2_batch::f2_8, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)20*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_r_o2_batch::c2_9, detail_xck_mgga_r_o2_batch::o2_9, detail_xck_mgga_r_o2_batch::f2_9, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)21*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_r_o2_batch::c2_10, detail_xck_mgga_r_o2_batch::o2_10, detail_xck_mgga_r_o2_batch::f2_10, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)22*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_r_o2_batch::c2_11, detail_xck_mgga_r_o2_batch::o2_11, detail_xck_mgga_r_o2_batch::f2_11, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)23*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_r_o2_batch::c3_4, detail_xck_mgga_r_o2_batch::o3_4, detail_xck_mgga_r_o2_batch::f3_4, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)24*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_r_o2_batch::c3_5, detail_xck_mgga_r_o2_batch::o3_5, detail_xck_mgga_r_o2_batch::f3_5, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)25*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_r_o2_batch::c3_6, detail_xck_mgga_r_o2_batch::o3_6, detail_xck_mgga_r_o2_batch::f3_6, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)26*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_r_o2_batch::c3_7, detail_xck_mgga_r_o2_batch::o3_7, detail_xck_mgga_r_o2_batch::f3_7, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)27*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_r_o2_batch::c3_8, detail_xck_mgga_r_o2_batch::o3_8, detail_xck_mgga_r_o2_batch::f3_8, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)28*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_r_o2_batch::c3_9, detail_xck_mgga_r_o2_batch::o3_9, detail_xck_mgga_r_o2_batch::f3_9, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)29*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_r_o2_batch::c3_10, detail_xck_mgga_r_o2_batch::o3_10, detail_xck_mgga_r_o2_batch::f3_10, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)30*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_r_o2_batch::c3_11, detail_xck_mgga_r_o2_batch::o3_11, detail_xck_mgga_r_o2_batch::f3_11, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)31*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_r_o2_batch::c4_4, detail_xck_mgga_r_o2_batch::o4_4, detail_xck_mgga_r_o2_batch::f4_4, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)32*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_r_o2_batch::c4_5, detail_xck_mgga_r_o2_batch::o4_5, detail_xck_mgga_r_o2_batch::f4_5, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)33*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_r_o2_batch::c4_6, detail_xck_mgga_r_o2_batch::o4_6, detail_xck_mgga_r_o2_batch::f4_6, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)34*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_r_o2_batch::c4_7, detail_xck_mgga_r_o2_batch::o4_7, detail_xck_mgga_r_o2_batch::f4_7, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)35*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_r_o2_batch::c4_8, detail_xck_mgga_r_o2_batch::o4_8, detail_xck_mgga_r_o2_batch::f4_8, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)36*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_r_o2_batch::c4_9, detail_xck_mgga_r_o2_batch::o4_9, detail_xck_mgga_r_o2_batch::f4_9, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)37*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_r_o2_batch::c4_10, detail_xck_mgga_r_o2_batch::o4_10, detail_xck_mgga_r_o2_batch::f4_10, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)38*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_r_o2_batch::c4_11, detail_xck_mgga_r_o2_batch::o4_11, detail_xck_mgga_r_o2_batch::f4_11, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)39*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_r_o2_batch::c5_4, detail_xck_mgga_r_o2_batch::o5_4, detail_xck_mgga_r_o2_batch::f5_4, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)40*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_r_o2_batch::c5_5, detail_xck_mgga_r_o2_batch::o5_5, detail_xck_mgga_r_o2_batch::f5_5, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)41*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_r_o2_batch::c5_6, detail_xck_mgga_r_o2_batch::o5_6, detail_xck_mgga_r_o2_batch::f5_6, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)42*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_r_o2_batch::c5_7, detail_xck_mgga_r_o2_batch::o5_7, detail_xck_mgga_r_o2_batch::f5_7, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)43*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_r_o2_batch::c5_8, detail_xck_mgga_r_o2_batch::o5_8, detail_xck_mgga_r_o2_batch::f5_8, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)44*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_r_o2_batch::c5_9, detail_xck_mgga_r_o2_batch::o5_9, detail_xck_mgga_r_o2_batch::f5_9, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)45*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_r_o2_batch::c5_10, detail_xck_mgga_r_o2_batch::o5_10, detail_xck_mgga_r_o2_batch::f5_10, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)46*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_r_o2_batch::c5_11, detail_xck_mgga_r_o2_batch::o5_11, detail_xck_mgga_r_o2_batch::f5_11, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)47*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_r_o2_batch::c6_4, detail_xck_mgga_r_o2_batch::o6_4, detail_xck_mgga_r_o2_batch::f6_4, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)48*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_r_o2_batch::c6_5, detail_xck_mgga_r_o2_batch::o6_5, detail_xck_mgga_r_o2_batch::f6_5, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)49*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_r_o2_batch::c6_6, detail_xck_mgga_r_o2_batch::o6_6, detail_xck_mgga_r_o2_batch::f6_6, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)50*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_r_o2_batch::c6_7, detail_xck_mgga_r_o2_batch::o6_7, detail_xck_mgga_r_o2_batch::f6_7, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)51*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_r_o2_batch::c6_8, detail_xck_mgga_r_o2_batch::o6_8, detail_xck_mgga_r_o2_batch::f6_8, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)52*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_r_o2_batch::c6_9, detail_xck_mgga_r_o2_batch::o6_9, detail_xck_mgga_r_o2_batch::f6_9, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)53*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_r_o2_batch::c6_10, detail_xck_mgga_r_o2_batch::o6_10, detail_xck_mgga_r_o2_batch::f6_10, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)54*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_r_o2_batch::c6_11, detail_xck_mgga_r_o2_batch::o6_11, detail_xck_mgga_r_o2_batch::f6_11, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)55*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_r_o2_batch::c7_4, detail_xck_mgga_r_o2_batch::o7_4, detail_xck_mgga_r_o2_batch::f7_4, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)56*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_r_o2_batch::c7_5, detail_xck_mgga_r_o2_batch::o7_5, detail_xck_mgga_r_o2_batch::f7_5, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)57*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_r_o2_batch::c7_6, detail_xck_mgga_r_o2_batch::o7_6, detail_xck_mgga_r_o2_batch::f7_6, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)58*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_r_o2_batch::c7_7, detail_xck_mgga_r_o2_batch::o7_7, detail_xck_mgga_r_o2_batch::f7_7, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)59*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_r_o2_batch::c7_8, detail_xck_mgga_r_o2_batch::o7_8, detail_xck_mgga_r_o2_batch::f7_8, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)60*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_r_o2_batch::c7_9, detail_xck_mgga_r_o2_batch::o7_9, detail_xck_mgga_r_o2_batch::f7_9, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)61*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_r_o2_batch::c7_10, detail_xck_mgga_r_o2_batch::o7_10, detail_xck_mgga_r_o2_batch::f7_10, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)62*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_r_o2_batch::c7_11, detail_xck_mgga_r_o2_batch::o7_11, detail_xck_mgga_r_o2_batch::f7_11, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)63*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_r_o2_batch::c8_4, detail_xck_mgga_r_o2_batch::o8_4, detail_xck_mgga_r_o2_batch::f8_4, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)64*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_r_o2_batch::c8_5, detail_xck_mgga_r_o2_batch::o8_5, detail_xck_mgga_r_o2_batch::f8_5, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)65*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_r_o2_batch::c8_6, detail_xck_mgga_r_o2_batch::o8_6, detail_xck_mgga_r_o2_batch::f8_6, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)66*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_r_o2_batch::c8_7, detail_xck_mgga_r_o2_batch::o8_7, detail_xck_mgga_r_o2_batch::f8_7, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)67*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_r_o2_batch::c8_8, detail_xck_mgga_r_o2_batch::o8_8, detail_xck_mgga_r_o2_batch::f8_8, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)68*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_r_o2_batch::c8_9, detail_xck_mgga_r_o2_batch::o8_9, detail_xck_mgga_r_o2_batch::f8_9, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)69*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_r_o2_batch::c8_10, detail_xck_mgga_r_o2_batch::o8_10, detail_xck_mgga_r_o2_batch::f8_10, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)70*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_r_o2_batch::c8_11, detail_xck_mgga_r_o2_batch::o8_11, detail_xck_mgga_r_o2_batch::f8_11, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)71*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_r_o2_batch::c9_4, detail_xck_mgga_r_o2_batch::o9_4, detail_xck_mgga_r_o2_batch::f9_4, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)72*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_r_o2_batch::c9_5, detail_xck_mgga_r_o2_batch::o9_5, detail_xck_mgga_r_o2_batch::f9_5, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)73*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_r_o2_batch::c9_6, detail_xck_mgga_r_o2_batch::o9_6, detail_xck_mgga_r_o2_batch::f9_6, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)74*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_r_o2_batch::c9_7, detail_xck_mgga_r_o2_batch::o9_7, detail_xck_mgga_r_o2_batch::f9_7, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)75*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_r_o2_batch::c9_8, detail_xck_mgga_r_o2_batch::o9_8, detail_xck_mgga_r_o2_batch::f9_8, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)76*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_r_o2_batch::c9_9, detail_xck_mgga_r_o2_batch::o9_9, detail_xck_mgga_r_o2_batch::f9_9, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)77*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_r_o2_batch::c9_10, detail_xck_mgga_r_o2_batch::o9_10, detail_xck_mgga_r_o2_batch::f9_10, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)78*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_r_o2_batch::c9_11, detail_xck_mgga_r_o2_batch::o9_11, detail_xck_mgga_r_o2_batch::f9_11, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)79*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_r_o2_batch::c10_4, detail_xck_mgga_r_o2_batch::o10_4, detail_xck_mgga_r_o2_batch::f10_4, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)80*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_r_o2_batch::c10_5, detail_xck_mgga_r_o2_batch::o10_5, detail_xck_mgga_r_o2_batch::f10_5, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)81*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_r_o2_batch::c10_6, detail_xck_mgga_r_o2_batch::o10_6, detail_xck_mgga_r_o2_batch::f10_6, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)82*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_r_o2_batch::c10_7, detail_xck_mgga_r_o2_batch::o10_7, detail_xck_mgga_r_o2_batch::f10_7, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)83*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_r_o2_batch::c10_8, detail_xck_mgga_r_o2_batch::o10_8, detail_xck_mgga_r_o2_batch::f10_8, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)84*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_r_o2_batch::c10_9, detail_xck_mgga_r_o2_batch::o10_9, detail_xck_mgga_r_o2_batch::f10_9, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)85*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_r_o2_batch::c10_10, detail_xck_mgga_r_o2_batch::o10_10, detail_xck_mgga_r_o2_batch::f10_10, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)86*blk);
        stage_a<T, Txc>(g0, bk, 2, detail_xck_mgga_r_o2_batch::c10_11, detail_xck_mgga_r_o2_batch::o10_11, detail_xck_mgga_r_o2_batch::f10_11, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)87*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_r_o2_batch::c11_4, detail_xck_mgga_r_o2_batch::o11_4, detail_xck_mgga_r_o2_batch::f11_4, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)88*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_r_o2_batch::c11_5, detail_xck_mgga_r_o2_batch::o11_5, detail_xck_mgga_r_o2_batch::f11_5, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)89*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_r_o2_batch::c11_6, detail_xck_mgga_r_o2_batch::o11_6, detail_xck_mgga_r_o2_batch::f11_6, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)90*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_r_o2_batch::c11_7, detail_xck_mgga_r_o2_batch::o11_7, detail_xck_mgga_r_o2_batch::f11_7, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)91*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_r_o2_batch::c11_8, detail_xck_mgga_r_o2_batch::o11_8, detail_xck_mgga_r_o2_batch::f11_8, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)92*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_r_o2_batch::c11_9, detail_xck_mgga_r_o2_batch::o11_9, detail_xck_mgga_r_o2_batch::f11_9, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)93*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_r_o2_batch::c11_10, detail_xck_mgga_r_o2_batch::o11_10, detail_xck_mgga_r_o2_batch::f11_10, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)94*blk);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_mgga_r_o2_batch::c11_11, detail_xck_mgga_r_o2_batch::o11_11, detail_xck_mgga_r_o2_batch::f11_11, detail_xck_mgga_r_o2_batch::NFLD, fi, xc, A + (int64_t)95*blk);
        for (int64_t x0 = 0; x0 < nx; x0 += nxc) {
            const int64_t nxb = nx - x0 < nxc ? nx - x0 : nxc;
            for (int64_t x = 0; x < nxb; ++x) {
                {
                    const T* A_[] = {A + (int64_t)0*blk, A + (int64_t)1*blk, A + (int64_t)2*blk, A + (int64_t)3*blk, A + (int64_t)4*blk, A + (int64_t)5*blk, A + (int64_t)6*blk, A + (int64_t)7*blk};
                    const T* P_[] = {fields[4] + (x0 + x)*npts + g0, fields[5] + (x0 + x)*npts + g0, fields[6] + (x0 + x)*npts + g0, fields[7] + (x0 + x)*npts + g0, fields[8] + (x0 + x)*npts + g0, fields[9] + (x0 + x)*npts + g0, fields[10] + (x0 + x)*npts + g0, fields[11] + (x0 + x)*npts + g0};
                    lincomb<T>(bk, 8, A_, P_, c);
                }
                accumulate<T>(bk, nbf, c, chi + (int64_t)0*nbf*npts + g0, npts, W + x*nbf*bk, 1);
                {
                    const T* A_[] = {A + (int64_t)40*blk, A + (int64_t)41*blk, A + (int64_t)42*blk, A + (int64_t)43*blk, A + (int64_t)44*blk, A + (int64_t)45*blk, A + (int64_t)46*blk, A + (int64_t)47*blk};
                    const T* P_[] = {fields[4] + (x0 + x)*npts + g0, fields[5] + (x0 + x)*npts + g0, fields[6] + (x0 + x)*npts + g0, fields[7] + (x0 + x)*npts + g0, fields[8] + (x0 + x)*npts + g0, fields[9] + (x0 + x)*npts + g0, fields[10] + (x0 + x)*npts + g0, fields[11] + (x0 + x)*npts + g0};
                    lincomb<T>(bk, 8, A_, P_, c);
                }
                accumulate<T>(bk, nbf, c, chi + (int64_t)1*nbf*npts + g0, npts, W + x*nbf*bk, 0);
                {
                    const T* A_[] = {A + (int64_t)56*blk, A + (int64_t)57*blk, A + (int64_t)58*blk, A + (int64_t)59*blk, A + (int64_t)60*blk, A + (int64_t)61*blk, A + (int64_t)62*blk, A + (int64_t)63*blk};
                    const T* P_[] = {fields[4] + (x0 + x)*npts + g0, fields[5] + (x0 + x)*npts + g0, fields[6] + (x0 + x)*npts + g0, fields[7] + (x0 + x)*npts + g0, fields[8] + (x0 + x)*npts + g0, fields[9] + (x0 + x)*npts + g0, fields[10] + (x0 + x)*npts + g0, fields[11] + (x0 + x)*npts + g0};
                    lincomb<T>(bk, 8, A_, P_, c);
                }
                accumulate<T>(bk, nbf, c, chi + (int64_t)2*nbf*npts + g0, npts, W + x*nbf*bk, 0);
                {
                    const T* A_[] = {A + (int64_t)72*blk, A + (int64_t)73*blk, A + (int64_t)74*blk, A + (int64_t)75*blk, A + (int64_t)76*blk, A + (int64_t)77*blk, A + (int64_t)78*blk, A + (int64_t)79*blk};
                    const T* P_[] = {fields[4] + (x0 + x)*npts + g0, fields[5] + (x0 + x)*npts + g0, fields[6] + (x0 + x)*npts + g0, fields[7] + (x0 + x)*npts + g0, fields[8] + (x0 + x)*npts + g0, fields[9] + (x0 + x)*npts + g0, fields[10] + (x0 + x)*npts + g0, fields[11] + (x0 + x)*npts + g0};
                    lincomb<T>(bk, 8, A_, P_, c);
                }
                accumulate<T>(bk, nbf, c, chi + (int64_t)3*nbf*npts + g0, npts, W + x*nbf*bk, 0);
                {
                    const T* A_[] = {A + (int64_t)88*blk, A + (int64_t)89*blk, A + (int64_t)90*blk, A + (int64_t)91*blk, A + (int64_t)92*blk, A + (int64_t)93*blk, A + (int64_t)94*blk, A + (int64_t)95*blk};
                    const T* P_[] = {fields[4] + (x0 + x)*npts + g0, fields[5] + (x0 + x)*npts + g0, fields[6] + (x0 + x)*npts + g0, fields[7] + (x0 + x)*npts + g0, fields[8] + (x0 + x)*npts + g0, fields[9] + (x0 + x)*npts + g0, fields[10] + (x0 + x)*npts + g0, fields[11] + (x0 + x)*npts + g0};
                    lincomb<T>(bk, 8, A_, P_, c);
                }
                accumulate<T>(bk, nbf, c, X0, bk, W + x*nbf*bk, 0);
            }
            gemm_rect(nxb*nbf, nbf, bk, static_cast<const T*>(W), bk, chi + (int64_t)0*nbf*npts + g0, npts, out + x0*nbf*nbf, nbf);
            for (int64_t x = 0; x < nxb; ++x) {
                {
                    const T* A_[] = {A + (int64_t)8*blk, A + (int64_t)9*blk, A + (int64_t)10*blk, A + (int64_t)11*blk, A + (int64_t)12*blk, A + (int64_t)13*blk, A + (int64_t)14*blk, A + (int64_t)15*blk};
                    const T* P_[] = {fields[4] + (x0 + x)*npts + g0, fields[5] + (x0 + x)*npts + g0, fields[6] + (x0 + x)*npts + g0, fields[7] + (x0 + x)*npts + g0, fields[8] + (x0 + x)*npts + g0, fields[9] + (x0 + x)*npts + g0, fields[10] + (x0 + x)*npts + g0, fields[11] + (x0 + x)*npts + g0};
                    lincomb<T>(bk, 8, A_, P_, c);
                }
                accumulate<T>(bk, nbf, c, chi + (int64_t)0*nbf*npts + g0, npts, W + x*nbf*bk, 1);
                {
                    const T* A_[] = {A + (int64_t)48*blk, A + (int64_t)49*blk, A + (int64_t)50*blk, A + (int64_t)51*blk, A + (int64_t)52*blk, A + (int64_t)53*blk, A + (int64_t)54*blk, A + (int64_t)55*blk};
                    const T* P_[] = {fields[4] + (x0 + x)*npts + g0, fields[5] + (x0 + x)*npts + g0, fields[6] + (x0 + x)*npts + g0, fields[7] + (x0 + x)*npts + g0, fields[8] + (x0 + x)*npts + g0, fields[9] + (x0 + x)*npts + g0, fields[10] + (x0 + x)*npts + g0, fields[11] + (x0 + x)*npts + g0};
                    lincomb<T>(bk, 8, A_, P_, c);
                }
                accumulate<T>(bk, nbf, c, chi + (int64_t)1*nbf*npts + g0, npts, W + x*nbf*bk, 0);
            }
            gemm_rect(nxb*nbf, nbf, bk, static_cast<const T*>(W), bk, chi + (int64_t)1*nbf*npts + g0, npts, out + x0*nbf*nbf, nbf);
            for (int64_t x = 0; x < nxb; ++x) {
                {
                    const T* A_[] = {A + (int64_t)16*blk, A + (int64_t)17*blk, A + (int64_t)18*blk, A + (int64_t)19*blk, A + (int64_t)20*blk, A + (int64_t)21*blk, A + (int64_t)22*blk, A + (int64_t)23*blk};
                    const T* P_[] = {fields[4] + (x0 + x)*npts + g0, fields[5] + (x0 + x)*npts + g0, fields[6] + (x0 + x)*npts + g0, fields[7] + (x0 + x)*npts + g0, fields[8] + (x0 + x)*npts + g0, fields[9] + (x0 + x)*npts + g0, fields[10] + (x0 + x)*npts + g0, fields[11] + (x0 + x)*npts + g0};
                    lincomb<T>(bk, 8, A_, P_, c);
                }
                accumulate<T>(bk, nbf, c, chi + (int64_t)0*nbf*npts + g0, npts, W + x*nbf*bk, 1);
                {
                    const T* A_[] = {A + (int64_t)64*blk, A + (int64_t)65*blk, A + (int64_t)66*blk, A + (int64_t)67*blk, A + (int64_t)68*blk, A + (int64_t)69*blk, A + (int64_t)70*blk, A + (int64_t)71*blk};
                    const T* P_[] = {fields[4] + (x0 + x)*npts + g0, fields[5] + (x0 + x)*npts + g0, fields[6] + (x0 + x)*npts + g0, fields[7] + (x0 + x)*npts + g0, fields[8] + (x0 + x)*npts + g0, fields[9] + (x0 + x)*npts + g0, fields[10] + (x0 + x)*npts + g0, fields[11] + (x0 + x)*npts + g0};
                    lincomb<T>(bk, 8, A_, P_, c);
                }
                accumulate<T>(bk, nbf, c, chi + (int64_t)2*nbf*npts + g0, npts, W + x*nbf*bk, 0);
            }
            gemm_rect(nxb*nbf, nbf, bk, static_cast<const T*>(W), bk, chi + (int64_t)2*nbf*npts + g0, npts, out + x0*nbf*nbf, nbf);
            for (int64_t x = 0; x < nxb; ++x) {
                {
                    const T* A_[] = {A + (int64_t)24*blk, A + (int64_t)25*blk, A + (int64_t)26*blk, A + (int64_t)27*blk, A + (int64_t)28*blk, A + (int64_t)29*blk, A + (int64_t)30*blk, A + (int64_t)31*blk};
                    const T* P_[] = {fields[4] + (x0 + x)*npts + g0, fields[5] + (x0 + x)*npts + g0, fields[6] + (x0 + x)*npts + g0, fields[7] + (x0 + x)*npts + g0, fields[8] + (x0 + x)*npts + g0, fields[9] + (x0 + x)*npts + g0, fields[10] + (x0 + x)*npts + g0, fields[11] + (x0 + x)*npts + g0};
                    lincomb<T>(bk, 8, A_, P_, c);
                }
                accumulate<T>(bk, nbf, c, chi + (int64_t)0*nbf*npts + g0, npts, W + x*nbf*bk, 1);
                {
                    const T* A_[] = {A + (int64_t)80*blk, A + (int64_t)81*blk, A + (int64_t)82*blk, A + (int64_t)83*blk, A + (int64_t)84*blk, A + (int64_t)85*blk, A + (int64_t)86*blk, A + (int64_t)87*blk};
                    const T* P_[] = {fields[4] + (x0 + x)*npts + g0, fields[5] + (x0 + x)*npts + g0, fields[6] + (x0 + x)*npts + g0, fields[7] + (x0 + x)*npts + g0, fields[8] + (x0 + x)*npts + g0, fields[9] + (x0 + x)*npts + g0, fields[10] + (x0 + x)*npts + g0, fields[11] + (x0 + x)*npts + g0};
                    lincomb<T>(bk, 8, A_, P_, c);
                }
                accumulate<T>(bk, nbf, c, chi + (int64_t)3*nbf*npts + g0, npts, W + x*nbf*bk, 0);
            }
            gemm_rect(nxb*nbf, nbf, bk, static_cast<const T*>(W), bk, chi + (int64_t)3*nbf*npts + g0, npts, out + x0*nbf*nbf, nbf);
            for (int64_t x = 0; x < nxb; ++x) {
                {
                    const T* A_[] = {A + (int64_t)32*blk, A + (int64_t)33*blk, A + (int64_t)34*blk, A + (int64_t)35*blk, A + (int64_t)36*blk, A + (int64_t)37*blk, A + (int64_t)38*blk, A + (int64_t)39*blk};
                    const T* P_[] = {fields[4] + (x0 + x)*npts + g0, fields[5] + (x0 + x)*npts + g0, fields[6] + (x0 + x)*npts + g0, fields[7] + (x0 + x)*npts + g0, fields[8] + (x0 + x)*npts + g0, fields[9] + (x0 + x)*npts + g0, fields[10] + (x0 + x)*npts + g0, fields[11] + (x0 + x)*npts + g0};
                    lincomb<T>(bk, 8, A_, P_, c);
                }
                accumulate<T>(bk, nbf, c, chi + (int64_t)0*nbf*npts + g0, npts, W + x*nbf*bk, 1);
            }
            gemm_rect(nxb*nbf, nbf, bk, static_cast<const T*>(W), bk, X0, bk, out + x0*nbf*nbf, nbf);
        }
    }
    if (own) delete[] c;
    return 0;
}


/* Operands of xck_mgga_r_o2_batch_t: `fields` in the order of
 * xck_mgga_r_o2_batch_field_names, `xc` in the order of xck_mgga_r_o2_batch_xc_names (the
 * C ABI's `scal` is the two concatenated, split at n_fields). The
 * structs name them; the overload taking them packs the arrays. */
inline constexpr int xck_mgga_r_o2_batch_n_fields = 12;
inline constexpr int xck_mgga_r_o2_batch_n_xc = 11;
inline constexpr const char* xck_mgga_r_o2_batch_field_names[] = {"w", "rho_x", "rho_y", "rho_z", "rho_p1_x", "rho_p1_y", "rho_p1_z", "rho_p1_xx", "rho_p1_yy", "rho_p1_zz", "rho_p1", "tau_p1"};
inline constexpr const char* xck_mgga_r_o2_batch_xc_names[] = {"v2lapl2", "v2rho2", "v2sigma2", "v2tau2", "vsigma", "v2lapltau", "v2rholapl", "v2rhosigma", "v2rhotau", "v2sigmalapl", "v2sigmatau"};
template <typename T>
struct xck_mgga_r_o2_batch_fields {
    const T* w;
    const T* rho_x;
    const T* rho_y;
    const T* rho_z;
    const T* rho_p1_x;
    const T* rho_p1_y;
    const T* rho_p1_z;
    const T* rho_p1_xx;
    const T* rho_p1_yy;
    const T* rho_p1_zz;
    const T* rho_p1;
    const T* tau_p1;
};
template <typename Txc>
struct xck_mgga_r_o2_batch_xc {
    const Txc* v2lapl2;
    const Txc* v2rho2;
    const Txc* v2sigma2;
    const Txc* v2tau2;
    const Txc* vsigma;
    const Txc* v2lapltau;
    const Txc* v2rholapl;
    const Txc* v2rhosigma;
    const Txc* v2rhotau;
    const Txc* v2sigmalapl;
    const Txc* v2sigmatau;
};

template <typename T, typename Txc = T>
int xck_mgga_r_o2_batch_t(int64_t npts,
        int64_t nbf,
        int64_t nx,
        const T* chi,
        const xck_mgga_r_o2_batch_fields<T>& fields_,
        const xck_mgga_r_o2_batch_xc<Txc>& xc_,
        T* out,
        T* work = nullptr) {
    const T* f_[] = {fields_.w, fields_.rho_x, fields_.rho_y, fields_.rho_z, fields_.rho_p1_x, fields_.rho_p1_y, fields_.rho_p1_z, fields_.rho_p1_xx, fields_.rho_p1_yy, fields_.rho_p1_zz, fields_.rho_p1, fields_.tau_p1};
    const Txc* x_[] = {xc_.v2lapl2, xc_.v2rho2, xc_.v2sigma2, xc_.v2tau2, xc_.vsigma, xc_.v2lapltau, xc_.v2rholapl, xc_.v2rhosigma, xc_.v2rhotau, xc_.v2sigmalapl, xc_.v2sigmatau};
    return xck_mgga_r_o2_batch_t<T, Txc>(npts, nbf, nx, chi, f_, x_, out, work);
}

} // namespace xckernel
