/* generated by xckernel; do not edit. */
#pragma once
#include <cstdint>
#include <new>
#include "xckernel/evaluator.hpp"

namespace xckernel {
namespace detail_xck_lda_r_g1 {
static constexpr double c0_0[] = {
    -2.0
};
static constexpr int32_t o0_0[] = {
    0,2
};
static constexpr uint16_t f0_0[] = {
    1,0
};
static constexpr double c1_0[] = {
    -2.0
};
static constexpr int32_t o1_0[] = {
    0,2
};
static constexpr uint16_t f1_0[] = {
    1,0
};
static constexpr double c2_0[] = {
    -2.0
};
static constexpr int32_t o2_0[] = {
    0,2
};
static constexpr uint16_t f2_0[] = {
    1,0
};
static constexpr int64_t NFLD = 1;
} // namespace detail_xck_lda_r_g1

/* Scratch (elements of T) the kernel needs: pass at least this
 * much as `work`, or nullptr to allocate it internally. */
inline int64_t xck_lda_r_g1_work(int64_t npts, int64_t nbf) {
    const int64_t blk = npts < grid_block ? npts : grid_block;
    return blk * (1 + nbf * 1) + 0 * npts + 1;
}

/* fields: the per-point tower operands (type T), in the order
 * of xck_lda_r_g1_scal_names; xc: the functional-derivative arrays
 * (type Txc; Libxc computes in double whatever T is). */
template <typename T, typename Txc = T>
int xck_lda_r_g1_t(int64_t npts,
        int64_t nbf,
        const T* chi,
        const T* Dchi,
        const T* const* fields,
        const Txc* const* xc,
        T* out,
        T* work = nullptr) {
    const int64_t blk = npts < grid_block ? npts : grid_block;
    T* c = work;
    bool own = false;
    if (!c) {
        c = new (std::nothrow) T[xck_lda_r_g1_work(npts, nbf)];
        own = true;
    }
    if (!c) return 1;
    T* W = c + blk;
    const T* Wc = W;
    const T* fi[1] = {fields[0]};
    for (int64_t g0 = 0; g0 < npts; g0 += blk) {
        const int64_t bk = npts - g0 < blk ? npts - g0 : blk;
        stage_a<T, Txc>(g0, bk, 1, detail_xck_lda_r_g1::c0_0, detail_xck_lda_r_g1::o0_0, detail_xck_lda_r_g1::f0_0, detail_xck_lda_r_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        rowdot(nbf, bk, chi + (int64_t)1*nbf*npts + g0, npts, Wc, bk, out + (int64_t)0*nbf);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_lda_r_g1::c1_0, detail_xck_lda_r_g1::o1_0, detail_xck_lda_r_g1::f1_0, detail_xck_lda_r_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        rowdot(nbf, bk, chi + (int64_t)2*nbf*npts + g0, npts, Wc, bk, out + (int64_t)1*nbf);
        stage_a<T, Txc>(g0, bk, 1, detail_xck_lda_r_g1::c2_0, detail_xck_lda_r_g1::o2_0, detail_xck_lda_r_g1::f2_0, detail_xck_lda_r_g1::NFLD, fi, xc, c);
        accumulate<T>(bk, nbf, c, Dchi + (int64_t)0*nbf*npts + g0, npts, W, 1);
        rowdot(nbf, bk, chi + (int64_t)3*nbf*npts + g0, npts, Wc, bk, out + (int64_t)2*nbf);
    }
    if (own) delete[] c;
    return 0;
}

} // namespace xckernel
