/* generated by xckernel; do not edit. */
#include "xckernel/kernels/xck_mgga_lapl_r_o2.hpp"

extern "C" {

const char* xck_mgga_lapl_r_o2_scal_names[18] = {
    xckernel::xck_mgga_lapl_r_o2_field_names[0],
    xckernel::xck_mgga_lapl_r_o2_field_names[1],
    xckernel::xck_mgga_lapl_r_o2_field_names[2],
    xckernel::xck_mgga_lapl_r_o2_field_names[3],
    xckernel::xck_mgga_lapl_r_o2_field_names[4],
    xckernel::xck_mgga_lapl_r_o2_field_names[5],
    xckernel::xck_mgga_lapl_r_o2_field_names[6],
    xckernel::xck_mgga_lapl_r_o2_field_names[7],
    xckernel::xck_mgga_lapl_r_o2_field_names[8],
    xckernel::xck_mgga_lapl_r_o2_field_names[9],
    xckernel::xck_mgga_lapl_r_o2_field_names[10],
    xckernel::xck_mgga_lapl_r_o2_xc_names[0],
    xckernel::xck_mgga_lapl_r_o2_xc_names[1],
    xckernel::xck_mgga_lapl_r_o2_xc_names[2],
    xckernel::xck_mgga_lapl_r_o2_xc_names[3],
    xckernel::xck_mgga_lapl_r_o2_xc_names[4],
    xckernel::xck_mgga_lapl_r_o2_xc_names[5],
    xckernel::xck_mgga_lapl_r_o2_xc_names[6],
};
extern const int xck_mgga_lapl_r_o2_n_scal;
const int xck_mgga_lapl_r_o2_n_scal = xckernel::xck_mgga_lapl_r_o2_n_fields + xckernel::xck_mgga_lapl_r_o2_n_xc;
extern const int xck_mgga_lapl_r_o2_n_fields;
const int xck_mgga_lapl_r_o2_n_fields = xckernel::xck_mgga_lapl_r_o2_n_fields;
extern const char* const xck_mgga_lapl_r_o2_kind;
const char* const xck_mgga_lapl_r_o2_kind = "matrix";
extern const int xck_mgga_lapl_r_o2_out_rank;
const int xck_mgga_lapl_r_o2_out_rank = 2;
extern const char* const xck_mgga_lapl_r_o2_out_shape;
const char* const xck_mgga_lapl_r_o2_out_shape = "(nbf, nbf)";
extern const int xck_mgga_lapl_r_o2_chi_order;
const int xck_mgga_lapl_r_o2_chi_order = 2;

/* One homogeneous scal list (all double): the per-point tower
 * operands first, the functional-derivative arrays from
 * xck_mgga_lapl_r_o2_n_fields on. */
int xck_mgga_lapl_r_o2(int64_t npts,
    int64_t nbf,
    const double* chi,
    const double* const* scal,
    double* out) {
    return xckernel::xck_mgga_lapl_r_o2_t<double, double>(
        npts, nbf, chi,
        scal, scal + 11, out);
}

} // extern C
