/* generated by xckernel; do not edit. */
#include "xckernel/kernels/xck_mgga_r_g1.hpp"

extern "C" {

const char* xck_mgga_r_g1_scal_names[8] = {
    "w",
    "rho_x",
    "rho_y",
    "rho_z",
    "vlapl",
    "vrho",
    "vsigma",
    "vtau",
};
extern const int xck_mgga_r_g1_n_scal;
const int xck_mgga_r_g1_n_scal = 8;
extern const int xck_mgga_r_g1_n_fields;
const int xck_mgga_r_g1_n_fields = 4;
extern const int xck_mgga_r_g1_chi_order;
const int xck_mgga_r_g1_chi_order = 3;
extern const int xck_mgga_r_g1_Dchi_order;
const int xck_mgga_r_g1_Dchi_order = 2;

/* One homogeneous scal list (all double): the per-point tower
 * operands first, the functional-derivative arrays from
 * xck_mgga_r_g1_n_fields on. */
int xck_mgga_r_g1(int64_t npts,
    int64_t nbf,
    const double* chi,
    const double* Dchi,
    const double* const* scal,
    double* out) {
    return xckernel::xck_mgga_r_g1_t<double, double>(
        npts, nbf, chi, Dchi,
        scal, scal + 4, out);
}

} // extern C
