/* generated by xckernel; do not edit. */
#include "xckernel/kernels/xck_mgga_lapl_r_o1.hpp"

extern "C" {

const char* xck_mgga_lapl_r_o1_scal_names[7] = {
    xckernel::xck_mgga_lapl_r_o1_field_names[0],
    xckernel::xck_mgga_lapl_r_o1_field_names[1],
    xckernel::xck_mgga_lapl_r_o1_field_names[2],
    xckernel::xck_mgga_lapl_r_o1_field_names[3],
    xckernel::xck_mgga_lapl_r_o1_xc_names[0],
    xckernel::xck_mgga_lapl_r_o1_xc_names[1],
    xckernel::xck_mgga_lapl_r_o1_xc_names[2],
};
extern const int xck_mgga_lapl_r_o1_n_scal;
const int xck_mgga_lapl_r_o1_n_scal = xckernel::xck_mgga_lapl_r_o1_n_fields + xckernel::xck_mgga_lapl_r_o1_n_xc;
extern const int xck_mgga_lapl_r_o1_n_fields;
const int xck_mgga_lapl_r_o1_n_fields = xckernel::xck_mgga_lapl_r_o1_n_fields;
extern const char* const xck_mgga_lapl_r_o1_kind;
const char* const xck_mgga_lapl_r_o1_kind = "matrix";
extern const int xck_mgga_lapl_r_o1_out_rank;
const int xck_mgga_lapl_r_o1_out_rank = 2;
extern const char* const xck_mgga_lapl_r_o1_out_shape;
const char* const xck_mgga_lapl_r_o1_out_shape = "(nbf, nbf)";
extern const int xck_mgga_lapl_r_o1_chi_order;
const int xck_mgga_lapl_r_o1_chi_order = 2;

/* One homogeneous scal list (all double): the per-point tower
 * operands first, the functional-derivative arrays from
 * xck_mgga_lapl_r_o1_n_fields on. */
int xck_mgga_lapl_r_o1(int64_t npts,
    int64_t nbf,
    const double* chi,
    const double* const* scal,
    double* out) {
    return xckernel::xck_mgga_lapl_r_o1_t<double, double>(
        npts, nbf, chi,
        scal, scal + 4, out);
}

} // extern C
