/* generated by xckernel; do not edit. */
#include "xckernel/kernels/xck_mgga_tau_u_gg.hpp"

extern "C" {

const char* xck_mgga_tau_u_gg_scal_names[32] = {
    xckernel::xck_mgga_tau_u_gg_field_names[0],
    xckernel::xck_mgga_tau_u_gg_field_names[1],
    xckernel::xck_mgga_tau_u_gg_field_names[2],
    xckernel::xck_mgga_tau_u_gg_field_names[3],
    xckernel::xck_mgga_tau_u_gg_field_names[4],
    xckernel::xck_mgga_tau_u_gg_field_names[5],
    xckernel::xck_mgga_tau_u_gg_field_names[6],
    xckernel::xck_mgga_tau_u_gg_field_names[7],
    xckernel::xck_mgga_tau_u_gg_field_names[8],
    xckernel::xck_mgga_tau_u_gg_field_names[9],
    xckernel::xck_mgga_tau_u_gg_field_names[10],
    xckernel::xck_mgga_tau_u_gg_field_names[11],
    xckernel::xck_mgga_tau_u_gg_field_names[12],
    xckernel::xck_mgga_tau_u_gg_field_names[13],
    xckernel::xck_mgga_tau_u_gg_field_names[14],
    xckernel::xck_mgga_tau_u_gg_field_names[15],
    xckernel::xck_mgga_tau_u_gg_field_names[16],
    xckernel::xck_mgga_tau_u_gg_field_names[17],
    xckernel::xck_mgga_tau_u_gg_field_names[18],
    xckernel::xck_mgga_tau_u_gg_field_names[19],
    xckernel::xck_mgga_tau_u_gg_field_names[20],
    xckernel::xck_mgga_tau_u_gg_field_names[21],
    xckernel::xck_mgga_tau_u_gg_field_names[22],
    xckernel::xck_mgga_tau_u_gg_field_names[23],
    xckernel::xck_mgga_tau_u_gg_field_names[24],
    xckernel::xck_mgga_tau_u_gg_xc_names[0],
    xckernel::xck_mgga_tau_u_gg_xc_names[1],
    xckernel::xck_mgga_tau_u_gg_xc_names[2],
    xckernel::xck_mgga_tau_u_gg_xc_names[3],
    xckernel::xck_mgga_tau_u_gg_xc_names[4],
    xckernel::xck_mgga_tau_u_gg_xc_names[5],
    xckernel::xck_mgga_tau_u_gg_xc_names[6],
};
extern const int xck_mgga_tau_u_gg_n_scal;
const int xck_mgga_tau_u_gg_n_scal = xckernel::xck_mgga_tau_u_gg_n_fields + xckernel::xck_mgga_tau_u_gg_n_xc;
extern const int xck_mgga_tau_u_gg_n_fields;
const int xck_mgga_tau_u_gg_n_fields = xckernel::xck_mgga_tau_u_gg_n_fields;
extern const char* const xck_mgga_tau_u_gg_kind;
const char* const xck_mgga_tau_u_gg_kind = "gg";
extern const int xck_mgga_tau_u_gg_out_rank;
const int xck_mgga_tau_u_gg_out_rank = 2;
extern const char* const xck_mgga_tau_u_gg_out_shape;
const char* const xck_mgga_tau_u_gg_out_shape = "(3, ng)";

/* One homogeneous scal list (all double): the per-point tower
 * operands first, the functional-derivative arrays from
 * xck_mgga_tau_u_gg_n_fields on. */
int xck_mgga_tau_u_gg(int64_t npts,
    const double* const* scal,
    double* out) {
    return xckernel::xck_mgga_tau_u_gg_t<double, double>(
        npts,
        scal, scal + 25, out);
}

} // extern C
