/* generated by xckernel; do not edit. */
#include "xckernel/kernels/xck_cmgga_tau_ub_o2.hpp"

extern "C" {

const char* xck_cmgga_tau_ub_o2_scal_names[56] = {
    "w",
    "rho_a_x",
    "rho_a_y",
    "rho_a_z",
    "rho_b_x",
    "rho_b_y",
    "rho_b_z",
    "jpx_a",
    "jpy_a",
    "jpz_a",
    "jpx_b",
    "jpy_b",
    "jpz_b",
    "inv_rho_a",
    "inv_rho_b",
    "rho_a_p1_x",
    "rho_a_p1_y",
    "rho_a_p1_z",
    "rho_b_p1_x",
    "rho_b_p1_y",
    "rho_b_p1_z",
    "jpx_a_p1",
    "jpy_a_p1",
    "jpz_a_p1",
    "jpx_b_p1",
    "jpy_b_p1",
    "jpz_b_p1",
    "rho_a_p1",
    "rho_b_p1",
    "tau_a_p1",
    "tau_b_p1",
    "vsigma_1",
    "vsigma_2",
    "vtau_1",
    "v2rho2_1",
    "v2rho2_2",
    "v2rhosigma_1",
    "v2rhosigma_2",
    "v2rhosigma_3",
    "v2rhosigma_4",
    "v2rhosigma_5",
    "v2rhotau_1",
    "v2rhotau_2",
    "v2rhotau_3",
    "v2sigma2_1",
    "v2sigma2_2",
    "v2sigma2_3",
    "v2sigma2_4",
    "v2sigma2_5",
    "v2sigmatau_1",
    "v2sigmatau_2",
    "v2sigmatau_3",
    "v2sigmatau_4",
    "v2sigmatau_5",
    "v2tau2_1",
    "v2tau2_2",
};
extern const int xck_cmgga_tau_ub_o2_n_scal;
const int xck_cmgga_tau_ub_o2_n_scal = 56;
extern const int xck_cmgga_tau_ub_o2_n_fields;
const int xck_cmgga_tau_ub_o2_n_fields = 31;
extern const int xck_cmgga_tau_ub_o2_chi_order;
const int xck_cmgga_tau_ub_o2_chi_order = 1;

/* One homogeneous scal list (all double): the per-point tower
 * operands first, the functional-derivative arrays from
 * xck_cmgga_tau_ub_o2_n_fields on. */
int xck_cmgga_tau_ub_o2(int64_t npts,
    int64_t nbf,
    const double* chi,
    const double* const* scal,
    double* out) {
    return xckernel::xck_cmgga_tau_ub_o2_t<double, double>(
        npts, nbf, chi,
        scal, scal + 31, out);
}

} // extern C
