/* generated by xckernel; do not edit. */
#include "xckernel/kernels/xck_gga_ua_f1.hpp"

extern "C" {

const char* xck_gga_ua_f1_scal_names[22] = {
    "w",
    "rho_a_x",
    "rho_a_y",
    "rho_a_z",
    "rho_b_x",
    "rho_b_y",
    "rho_b_z",
    "vrho_0",
    "vsigma_0",
    "vsigma_1",
    "v2rho2_0",
    "v2rho2_1",
    "v2rhosigma_0",
    "v2rhosigma_1",
    "v2rhosigma_2",
    "v2rhosigma_3",
    "v2rhosigma_4",
    "v2sigma2_0",
    "v2sigma2_1",
    "v2sigma2_2",
    "v2sigma2_3",
    "v2sigma2_4",
};
extern const int xck_gga_ua_f1_n_scal;
const int xck_gga_ua_f1_n_scal = 22;
extern const int xck_gga_ua_f1_n_fields;
const int xck_gga_ua_f1_n_fields = 7;
extern const int xck_gga_ua_f1_chi_order;
const int xck_gga_ua_f1_chi_order = 2;
extern const int xck_gga_ua_f1_Dchi_a_order;
const int xck_gga_ua_f1_Dchi_a_order = 1;
extern const int xck_gga_ua_f1_Dchi_b_order;
const int xck_gga_ua_f1_Dchi_b_order = 1;

/* One homogeneous scal list (all double): the per-point tower
 * operands first, the functional-derivative arrays from
 * xck_gga_ua_f1_n_fields on. */
int xck_gga_ua_f1(int64_t npts,
    int64_t nbf,
    const double* chi,
    const double* Dchi_a,
    const double* Dchi_b,
    const int8_t* atom_mask,
    const double* const* scal,
    double* out) {
    return xckernel::xck_gga_ua_f1_t<double, double>(
        npts, nbf, chi, Dchi_a, Dchi_b, atom_mask,
        scal, scal + 7, out);
}

} // extern C
