/* generated by xckernel; do not edit. */
#include "xckernel/kernels/xck_cmgga_tau_u_gg.hpp"

extern "C" {

const char* xck_cmgga_tau_u_gg_scal_names[58] = {
    "w",
    "rho_a_x",
    "rho_a_y",
    "rho_a_z",
    "rho_b_x",
    "rho_b_y",
    "rho_b_z",
    "jpx_a",
    "jpy_a",
    "jpz_a",
    "jpx_b",
    "jpy_b",
    "jpz_b",
    "rho_a_xx",
    "rho_a_xy",
    "rho_a_xz",
    "rho_a_yy",
    "rho_a_yz",
    "rho_a_zz",
    "rho_b_xx",
    "rho_b_xy",
    "rho_b_xz",
    "rho_b_yy",
    "rho_b_yz",
    "rho_b_zz",
    "tau_a_x",
    "tau_a_y",
    "tau_a_z",
    "tau_b_x",
    "tau_b_y",
    "tau_b_z",
    "jpx_a_x",
    "jpx_a_y",
    "jpx_a_z",
    "jpy_a_x",
    "jpy_a_y",
    "jpy_a_z",
    "jpz_a_x",
    "jpz_a_y",
    "jpz_a_z",
    "jpx_b_x",
    "jpx_b_y",
    "jpx_b_z",
    "jpy_b_x",
    "jpy_b_y",
    "jpy_b_z",
    "jpz_b_x",
    "jpz_b_y",
    "jpz_b_z",
    "inv_rho_a",
    "inv_rho_b",
    "vrho_0",
    "vrho_1",
    "vsigma_0",
    "vsigma_1",
    "vsigma_2",
    "vtau_0",
    "vtau_1",
};
extern const int xck_cmgga_tau_u_gg_n_scal;
const int xck_cmgga_tau_u_gg_n_scal = 58;
extern const int xck_cmgga_tau_u_gg_n_fields;
const int xck_cmgga_tau_u_gg_n_fields = 51;

/* One homogeneous scal list (all double): the per-point tower
 * operands first, the functional-derivative arrays from
 * xck_cmgga_tau_u_gg_n_fields on. */
int xck_cmgga_tau_u_gg(int64_t npts,
    const double* const* scal,
    double* out) {
    return xckernel::xck_cmgga_tau_u_gg_t<double, double>(
        npts,
        scal, scal + 51, out);
}

} // extern C
