/* generated by xckernel; do not edit. */
#include "xckernel/kernels/xck_cmgga_tau_ua_o1.hpp"

extern "C" {

const char* xck_cmgga_tau_ua_o1_scal_names[15] = {
    "w",
    "rho_a_x",
    "rho_a_y",
    "rho_a_z",
    "rho_b_x",
    "rho_b_y",
    "rho_b_z",
    "jpx_a",
    "jpy_a",
    "jpz_a",
    "inv_rho_a",
    "vrho_0",
    "vsigma_0",
    "vsigma_1",
    "vtau_0",
};
extern const int xck_cmgga_tau_ua_o1_n_scal;
const int xck_cmgga_tau_ua_o1_n_scal = 15;
extern const int xck_cmgga_tau_ua_o1_n_fields;
const int xck_cmgga_tau_ua_o1_n_fields = 11;
extern const int xck_cmgga_tau_ua_o1_chi_order;
const int xck_cmgga_tau_ua_o1_chi_order = 1;

/* One homogeneous scal list (all double): the per-point tower
 * operands first, the functional-derivative arrays from
 * xck_cmgga_tau_ua_o1_n_fields on. */
int xck_cmgga_tau_ua_o1(int64_t npts,
    int64_t nbf,
    const double* chi,
    const double* const* scal,
    double* out) {
    return xckernel::xck_cmgga_tau_ua_o1_t<double, double>(
        npts, nbf, chi,
        scal, scal + 11, out);
}

} // extern C
