/* generated by xckernel; do not edit. */
#include "xckernel/kernels/xck_mgga_ua_fg.hpp"

extern "C" {

const char* xck_mgga_ua_fg_scal_names[83] = {
    "w",
    "rho_a_x",
    "rho_a_y",
    "rho_a_z",
    "rho_b_x",
    "rho_b_y",
    "rho_b_z",
    "rho_a_xx",
    "rho_a_xy",
    "rho_a_xz",
    "rho_a_yy",
    "rho_a_yz",
    "rho_a_zz",
    "rho_b_xx",
    "rho_b_xy",
    "rho_b_xz",
    "rho_b_yy",
    "rho_b_yz",
    "rho_b_zz",
    "tau_a_x",
    "tau_a_y",
    "tau_a_z",
    "tau_b_x",
    "tau_b_y",
    "tau_b_z",
    "rho_a_xxx",
    "rho_a_xyy",
    "rho_a_xzz",
    "rho_a_xxy",
    "rho_a_yyy",
    "rho_a_yzz",
    "rho_a_xxz",
    "rho_a_yyz",
    "rho_a_zzz",
    "rho_b_xxx",
    "rho_b_xyy",
    "rho_b_xzz",
    "rho_b_xxy",
    "rho_b_yyy",
    "rho_b_yzz",
    "rho_b_xxz",
    "rho_b_yyz",
    "rho_b_zzz",
    "vlapl_0",
    "vrho_0",
    "vsigma_0",
    "vsigma_1",
    "vtau_0",
    "v2lapl2_0",
    "v2lapl2_1",
    "v2lapltau_0",
    "v2lapltau_1",
    "v2lapltau_2",
    "v2rho2_0",
    "v2rho2_1",
    "v2rholapl_0",
    "v2rholapl_1",
    "v2rholapl_2",
    "v2rhosigma_0",
    "v2rhosigma_1",
    "v2rhosigma_2",
    "v2rhosigma_3",
    "v2rhosigma_4",
    "v2rhotau_0",
    "v2rhotau_1",
    "v2rhotau_2",
    "v2sigma2_0",
    "v2sigma2_1",
    "v2sigma2_2",
    "v2sigma2_3",
    "v2sigma2_4",
    "v2sigmalapl_0",
    "v2sigmalapl_1",
    "v2sigmalapl_2",
    "v2sigmalapl_3",
    "v2sigmalapl_4",
    "v2sigmatau_0",
    "v2sigmatau_1",
    "v2sigmatau_2",
    "v2sigmatau_3",
    "v2sigmatau_4",
    "v2tau2_0",
    "v2tau2_1",
};
extern const int xck_mgga_ua_fg_n_scal;
const int xck_mgga_ua_fg_n_scal = 83;
extern const int xck_mgga_ua_fg_n_fields;
const int xck_mgga_ua_fg_n_fields = 43;
extern const int xck_mgga_ua_fg_chi_order;
const int xck_mgga_ua_fg_chi_order = 3;

/* One homogeneous scal list (all double): the per-point tower
 * operands first, the functional-derivative arrays from
 * xck_mgga_ua_fg_n_fields on. */
int xck_mgga_ua_fg(int64_t npts,
    int64_t nbf,
    const double* chi,
    const double* const* scal,
    double* out) {
    return xckernel::xck_mgga_ua_fg_t<double, double>(
        npts, nbf, chi,
        scal, scal + 43, out);
}

} // extern C
