/* generated by xckernel; do not edit. */
#include "xckernel/kernels/xck_mgga_r_gg.hpp"

extern "C" {

const char* xck_mgga_r_gg_scal_names[26] = {
    "w",
    "rho_x",
    "rho_y",
    "rho_z",
    "rho_xx",
    "rho_xy",
    "rho_xz",
    "rho_yy",
    "rho_yz",
    "rho_zz",
    "tau_x",
    "tau_y",
    "tau_z",
    "rho_xxx",
    "rho_xyy",
    "rho_xzz",
    "rho_xxy",
    "rho_yyy",
    "rho_yzz",
    "rho_xxz",
    "rho_yyz",
    "rho_zzz",
    "vlapl",
    "vrho",
    "vsigma",
    "vtau",
};
extern const int xck_mgga_r_gg_n_scal;
const int xck_mgga_r_gg_n_scal = 26;
extern const int xck_mgga_r_gg_n_fields;
const int xck_mgga_r_gg_n_fields = 22;

/* One homogeneous scal list (all double): the per-point tower
 * operands first, the functional-derivative arrays from
 * xck_mgga_r_gg_n_fields on. */
int xck_mgga_r_gg(int64_t npts,
    const double* const* scal,
    double* out) {
    return xckernel::xck_mgga_r_gg_t<double, double>(
        npts,
        scal, scal + 22, out);
}

} // extern C
