/* generated by xckernel; do not edit. */
#include "xckernel/kernels/xck_mgga_u_gg.hpp"

extern "C" {

const char* xck_mgga_u_gg_scal_names[52] = {
    "w",
    "rho_a_x",
    "rho_a_y",
    "rho_a_z",
    "rho_b_x",
    "rho_b_y",
    "rho_b_z",
    "rho_a_xx",
    "rho_a_xy",
    "rho_a_xz",
    "rho_a_yy",
    "rho_a_yz",
    "rho_a_zz",
    "rho_b_xx",
    "rho_b_xy",
    "rho_b_xz",
    "rho_b_yy",
    "rho_b_yz",
    "rho_b_zz",
    "tau_a_x",
    "tau_a_y",
    "tau_a_z",
    "tau_b_x",
    "tau_b_y",
    "tau_b_z",
    "rho_a_xxx",
    "rho_a_xyy",
    "rho_a_xzz",
    "rho_a_xxy",
    "rho_a_yyy",
    "rho_a_yzz",
    "rho_a_xxz",
    "rho_a_yyz",
    "rho_a_zzz",
    "rho_b_xxx",
    "rho_b_xyy",
    "rho_b_xzz",
    "rho_b_xxy",
    "rho_b_yyy",
    "rho_b_yzz",
    "rho_b_xxz",
    "rho_b_yyz",
    "rho_b_zzz",
    "vlapl_0",
    "vlapl_1",
    "vrho_0",
    "vrho_1",
    "vsigma_0",
    "vsigma_1",
    "vsigma_2",
    "vtau_0",
    "vtau_1",
};
extern const int xck_mgga_u_gg_n_scal;
const int xck_mgga_u_gg_n_scal = 52;
extern const int xck_mgga_u_gg_n_fields;
const int xck_mgga_u_gg_n_fields = 43;

/* One homogeneous scal list (all double): the per-point tower
 * operands first, the functional-derivative arrays from
 * xck_mgga_u_gg_n_fields on. */
int xck_mgga_u_gg(int64_t npts,
    const double* const* scal,
    double* out) {
    return xckernel::xck_mgga_u_gg_t<double, double>(
        npts,
        scal, scal + 43, out);
}

} // extern C
