/* generated by xckernel; do not edit. */
#include "xckernel/kernels/xck_cmgga_tau_r_o2.hpp"

extern "C" {

const char* xck_cmgga_tau_r_o2_scal_names[24] = {
    "w",
    "rho_x",
    "rho_y",
    "rho_z",
    "jpx",
    "jpy",
    "jpz",
    "inv_rho",
    "rho_p1_x",
    "rho_p1_y",
    "rho_p1_z",
    "jpx_p1",
    "jpy_p1",
    "jpz_p1",
    "rho_p1",
    "tau_p1",
    "v2rho2",
    "v2sigma2",
    "v2tau2",
    "vsigma",
    "vtau",
    "v2rhosigma",
    "v2rhotau",
    "v2sigmatau",
};
extern const int xck_cmgga_tau_r_o2_n_scal;
const int xck_cmgga_tau_r_o2_n_scal = 24;
extern const int xck_cmgga_tau_r_o2_n_fields;
const int xck_cmgga_tau_r_o2_n_fields = 16;
extern const int xck_cmgga_tau_r_o2_chi_order;
const int xck_cmgga_tau_r_o2_chi_order = 1;

/* One homogeneous scal list (all double): the per-point tower
 * operands first, the functional-derivative arrays from
 * xck_cmgga_tau_r_o2_n_fields on. */
int xck_cmgga_tau_r_o2(int64_t npts,
    int64_t nbf,
    const double* chi,
    const double* const* scal,
    double* out) {
    return xckernel::xck_cmgga_tau_r_o2_t<double, double>(
        npts, nbf, chi,
        scal, scal + 16, out);
}

} // extern C
