/* generated by xckernel; do not edit. */
#include "xckernel/kernels/xck_mgga_r_o1_diag.hpp"

extern "C" {

const char* xck_mgga_r_o1_diag_scal_names[8] = {
    "w",
    "rho_x",
    "rho_y",
    "rho_z",
    "vlapl",
    "vrho",
    "vsigma",
    "vtau",
};
extern const int xck_mgga_r_o1_diag_n_scal;
const int xck_mgga_r_o1_diag_n_scal = 8;
extern const int xck_mgga_r_o1_diag_n_fields;
const int xck_mgga_r_o1_diag_n_fields = 4;
extern const int xck_mgga_r_o1_diag_chi_order;
const int xck_mgga_r_o1_diag_chi_order = 2;

/* One homogeneous scal list (all double): the per-point tower
 * operands first, the functional-derivative arrays from
 * xck_mgga_r_o1_diag_n_fields on. */
int xck_mgga_r_o1_diag(int64_t npts,
    int64_t nbf,
    const double* chi,
    const double* const* scal,
    double* out) {
    return xckernel::xck_mgga_r_o1_diag_t<double, double>(
        npts, nbf, chi,
        scal, scal + 4, out);
}

} // extern C
