/* generated by xckernel; do not edit. */
#include "xckernel/kernels/xck_lda_r_fg.hpp"

extern "C" {

const char* xck_lda_r_fg_scal_names[6] = {
    "w",
    "rho_x",
    "rho_y",
    "rho_z",
    "v2rho2",
    "vrho",
};
extern const int xck_lda_r_fg_n_scal;
const int xck_lda_r_fg_n_scal = 6;
extern const int xck_lda_r_fg_n_fields;
const int xck_lda_r_fg_n_fields = 4;
extern const int xck_lda_r_fg_chi_order;
const int xck_lda_r_fg_chi_order = 1;

/* One homogeneous scal list (all double): the per-point tower
 * operands first, the functional-derivative arrays from
 * xck_lda_r_fg_n_fields on. */
int xck_lda_r_fg(int64_t npts,
    int64_t nbf,
    const double* chi,
    const double* const* scal,
    double* out) {
    return xckernel::xck_lda_r_fg_t<double, double>(
        npts, nbf, chi,
        scal, scal + 4, out);
}

} // extern C
