/* generated by xckernel; do not edit. */
#include "xckernel/kernels/xck_mgga_tau_r_f1.hpp"

extern "C" {

const char* xck_mgga_tau_r_f1_scal_names[13] = {
    "w",
    "rho_x",
    "rho_y",
    "rho_z",
    "v2rho2",
    "v2sigma2",
    "v2tau2",
    "vrho",
    "vsigma",
    "vtau",
    "v2rhosigma",
    "v2rhotau",
    "v2sigmatau",
};
extern const int xck_mgga_tau_r_f1_n_scal;
const int xck_mgga_tau_r_f1_n_scal = 13;
extern const int xck_mgga_tau_r_f1_n_fields;
const int xck_mgga_tau_r_f1_n_fields = 4;
extern const int xck_mgga_tau_r_f1_chi_order;
const int xck_mgga_tau_r_f1_chi_order = 2;
extern const int xck_mgga_tau_r_f1_Dchi_order;
const int xck_mgga_tau_r_f1_Dchi_order = 1;

/* One homogeneous scal list (all double): the per-point tower
 * operands first, the functional-derivative arrays from
 * xck_mgga_tau_r_f1_n_fields on. */
int xck_mgga_tau_r_f1(int64_t npts,
    int64_t nbf,
    const double* chi,
    const double* Dchi,
    const int8_t* atom_mask,
    const double* const* scal,
    double* out) {
    return xckernel::xck_mgga_tau_r_f1_t<double, double>(
        npts, nbf, chi, Dchi, atom_mask,
        scal, scal + 4, out);
}

} // extern C
