/* generated by xckernel; do not edit. */
#include "xckernel/kernels/xck_gga_ub_g1.hpp"

extern "C" {

const char* xck_gga_ub_g1_scal_names[10] = {
    "w",
    "rho_a_x",
    "rho_a_y",
    "rho_a_z",
    "rho_b_x",
    "rho_b_y",
    "rho_b_z",
    "vrho_1",
    "vsigma_1",
    "vsigma_2",
};
extern const int xck_gga_ub_g1_n_scal;
const int xck_gga_ub_g1_n_scal = 10;
extern const int xck_gga_ub_g1_n_fields;
const int xck_gga_ub_g1_n_fields = 7;
extern const int xck_gga_ub_g1_chi_order;
const int xck_gga_ub_g1_chi_order = 2;
extern const int xck_gga_ub_g1_Dchi_order;
const int xck_gga_ub_g1_Dchi_order = 1;

/* One homogeneous scal list (all double): the per-point tower
 * operands first, the functional-derivative arrays from
 * xck_gga_ub_g1_n_fields on. */
int xck_gga_ub_g1(int64_t npts,
    int64_t nbf,
    const double* chi,
    const double* Dchi,
    const double* const* scal,
    double* out) {
    return xckernel::xck_gga_ub_g1_t<double, double>(
        npts, nbf, chi, Dchi,
        scal, scal + 7, out);
}

} // extern C
