/* generated by xckernel; do not edit. */
#include "xckernel/kernels/xck_lda_r_f1.hpp"

extern "C" {

const char* xck_lda_r_f1_scal_names[3] = {
    "w",
    "v2rho2",
    "vrho",
};
extern const int xck_lda_r_f1_n_scal;
const int xck_lda_r_f1_n_scal = 3;
extern const int xck_lda_r_f1_n_fields;
const int xck_lda_r_f1_n_fields = 1;
extern const int xck_lda_r_f1_chi_order;
const int xck_lda_r_f1_chi_order = 1;
extern const int xck_lda_r_f1_Dchi_order;
const int xck_lda_r_f1_Dchi_order = 0;

/* One homogeneous scal list (all double): the per-point tower
 * operands first, the functional-derivative arrays from
 * xck_lda_r_f1_n_fields on. */
int xck_lda_r_f1(int64_t npts,
    int64_t nbf,
    const double* chi,
    const double* Dchi,
    const int8_t* atom_mask,
    const double* const* scal,
    double* out) {
    return xckernel::xck_lda_r_f1_t<double, double>(
        npts, nbf, chi, Dchi, atom_mask,
        scal, scal + 1, out);
}

} // extern C
