/* generated by xckernel; do not edit. */
#include "xckernel/kernels/xck_lda_r_o2.hpp"

extern "C" {

const char* xck_lda_r_o2_scal_names[3] = {
    "w",
    "rho_p1",
    "v2rho2",
};
extern const int xck_lda_r_o2_n_scal;
const int xck_lda_r_o2_n_scal = 3;
extern const int xck_lda_r_o2_n_fields;
const int xck_lda_r_o2_n_fields = 2;

/* The C ABI keeps one homogeneous scal list (all double);
 * fields come first, functional-derivative arrays last, split at
 * xck_lda_r_o2_n_fields. */
int xck_lda_r_o2(int64_t npts, int64_t nbf,
           const double* chi, const double* dchi,
           const double* lapl_chi, const double* hess_chi,
           const double* const* scal, double* out) {
    return xckernel::xck_lda_r_o2_t<double, double>(
        npts, nbf, chi, dchi, lapl_chi, hess_chi,
        scal, scal + 2, out);
}

} // extern C
