/* generated by xckernel; do not edit. */
#include "xckernel/kernels/xck_mgga_tau_ua_o1.hpp"

extern "C" {

const char* xck_mgga_tau_ua_o1_scal_names[11] = {
    "w",
    "grad_rho_a_x",
    "grad_rho_a_y",
    "grad_rho_a_z",
    "grad_rho_b_x",
    "grad_rho_b_y",
    "grad_rho_b_z",
    "vrho_0",
    "vsigma_0",
    "vsigma_1",
    "vtau_0",
};
extern const int xck_mgga_tau_ua_o1_n_scal;
const int xck_mgga_tau_ua_o1_n_scal = 11;
extern const int xck_mgga_tau_ua_o1_n_fields;
const int xck_mgga_tau_ua_o1_n_fields = 7;

/* The C ABI keeps one homogeneous scal list (all double);
 * fields come first, functional-derivative arrays last, split at
 * xck_mgga_tau_ua_o1_n_fields. */
int xck_mgga_tau_ua_o1(int64_t npts, int64_t nbf,
           const double* chi, const double* dchi,
           const double* lapl_chi, const double* hess_chi,
           const double* const* scal, double* out) {
    return xckernel::xck_mgga_tau_ua_o1_t<double, double>(
        npts, nbf, chi, dchi, lapl_chi, hess_chi,
        scal, scal + 7, out);
}

} // extern C
